// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FUNCGET_IPC_H_
#define FLATBUFFERS_GENERATED_FUNCGET_IPC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "common_struct_generated.h"
#include "func_return_generated.h"

namespace IPC {

struct Request_Get_Core_Data;
struct Request_Get_Core_DataBuilder;
struct Request_Get_Core_DataT;

struct Response_Get_Core_Data;
struct Response_Get_Core_DataBuilder;
struct Response_Get_Core_DataT;

struct Request_Get_Core_DataT : public ::flatbuffers::NativeTable {
  typedef Request_Get_Core_Data TableType;
  int32_t option = 0;
  std::string name{};
};

struct Request_Get_Core_Data FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Request_Get_Core_DataT NativeTableType;
  typedef Request_Get_Core_DataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OPTION = 4,
    VT_NAME = 6
  };
  int32_t option() const {
    return GetField<int32_t>(VT_OPTION, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_OPTION, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
  Request_Get_Core_DataT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Request_Get_Core_DataT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Request_Get_Core_Data> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Request_Get_Core_DataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Request_Get_Core_DataBuilder {
  typedef Request_Get_Core_Data Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_option(int32_t option) {
    fbb_.AddElement<int32_t>(Request_Get_Core_Data::VT_OPTION, option, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Request_Get_Core_Data::VT_NAME, name);
  }
  explicit Request_Get_Core_DataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Request_Get_Core_Data> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Request_Get_Core_Data>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Request_Get_Core_Data> CreateRequest_Get_Core_Data(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t option = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  Request_Get_Core_DataBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_option(option);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Request_Get_Core_Data> CreateRequest_Get_Core_DataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t option = 0,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return IPC::CreateRequest_Get_Core_Data(
      _fbb,
      option,
      name__);
}

::flatbuffers::Offset<Request_Get_Core_Data> CreateRequest_Get_Core_Data(::flatbuffers::FlatBufferBuilder &_fbb, const Request_Get_Core_DataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct Response_Get_Core_DataT : public ::flatbuffers::NativeTable {
  typedef Response_Get_Core_Data TableType;
  int32_t valid = 0;
  std::unique_ptr<IPC::FloatArray32> payload{};
  Response_Get_Core_DataT() = default;
  Response_Get_Core_DataT(const Response_Get_Core_DataT &o);
  Response_Get_Core_DataT(Response_Get_Core_DataT&&) FLATBUFFERS_NOEXCEPT = default;
  Response_Get_Core_DataT &operator=(Response_Get_Core_DataT o) FLATBUFFERS_NOEXCEPT;
};

struct Response_Get_Core_Data FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Response_Get_Core_DataT NativeTableType;
  typedef Response_Get_Core_DataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALID = 4,
    VT_PAYLOAD = 6
  };
  int32_t valid() const {
    return GetField<int32_t>(VT_VALID, 0);
  }
  const IPC::FloatArray32 *payload() const {
    return GetStruct<const IPC::FloatArray32 *>(VT_PAYLOAD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VALID, 4) &&
           VerifyField<IPC::FloatArray32>(verifier, VT_PAYLOAD, 4) &&
           verifier.EndTable();
  }
  Response_Get_Core_DataT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(Response_Get_Core_DataT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Response_Get_Core_Data> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Response_Get_Core_DataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct Response_Get_Core_DataBuilder {
  typedef Response_Get_Core_Data Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_valid(int32_t valid) {
    fbb_.AddElement<int32_t>(Response_Get_Core_Data::VT_VALID, valid, 0);
  }
  void add_payload(const IPC::FloatArray32 *payload) {
    fbb_.AddStruct(Response_Get_Core_Data::VT_PAYLOAD, payload);
  }
  explicit Response_Get_Core_DataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Response_Get_Core_Data> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Response_Get_Core_Data>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Response_Get_Core_Data> CreateResponse_Get_Core_Data(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t valid = 0,
    const IPC::FloatArray32 *payload = nullptr) {
  Response_Get_Core_DataBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_valid(valid);
  return builder_.Finish();
}

::flatbuffers::Offset<Response_Get_Core_Data> CreateResponse_Get_Core_Data(::flatbuffers::FlatBufferBuilder &_fbb, const Response_Get_Core_DataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline Request_Get_Core_DataT *Request_Get_Core_Data::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Request_Get_Core_DataT>(new Request_Get_Core_DataT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Request_Get_Core_Data::UnPackTo(Request_Get_Core_DataT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = option(); _o->option = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
}

inline ::flatbuffers::Offset<Request_Get_Core_Data> Request_Get_Core_Data::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Request_Get_Core_DataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRequest_Get_Core_Data(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Request_Get_Core_Data> CreateRequest_Get_Core_Data(::flatbuffers::FlatBufferBuilder &_fbb, const Request_Get_Core_DataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Request_Get_Core_DataT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _option = _o->option;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  return IPC::CreateRequest_Get_Core_Data(
      _fbb,
      _option,
      _name);
}

inline Response_Get_Core_DataT::Response_Get_Core_DataT(const Response_Get_Core_DataT &o)
      : valid(o.valid),
        payload((o.payload) ? new IPC::FloatArray32(*o.payload) : nullptr) {
}

inline Response_Get_Core_DataT &Response_Get_Core_DataT::operator=(Response_Get_Core_DataT o) FLATBUFFERS_NOEXCEPT {
  std::swap(valid, o.valid);
  std::swap(payload, o.payload);
  return *this;
}

inline Response_Get_Core_DataT *Response_Get_Core_Data::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<Response_Get_Core_DataT>(new Response_Get_Core_DataT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Response_Get_Core_Data::UnPackTo(Response_Get_Core_DataT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = valid(); _o->valid = _e; }
  { auto _e = payload(); if (_e) _o->payload = std::unique_ptr<IPC::FloatArray32>(new IPC::FloatArray32(*_e)); }
}

inline ::flatbuffers::Offset<Response_Get_Core_Data> Response_Get_Core_Data::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const Response_Get_Core_DataT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateResponse_Get_Core_Data(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Response_Get_Core_Data> CreateResponse_Get_Core_Data(::flatbuffers::FlatBufferBuilder &_fbb, const Response_Get_Core_DataT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const Response_Get_Core_DataT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _valid = _o->valid;
  auto _payload = _o->payload ? _o->payload.get() : nullptr;
  return IPC::CreateResponse_Get_Core_Data(
      _fbb,
      _valid,
      _payload);
}

}  // namespace IPC

#endif  // FLATBUFFERS_GENERATED_FUNCGET_IPC_H_
