// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_STATEMESSAGE_IPC_H_
#define FLATBUFFERS_GENERATED_STATEMESSAGE_IPC_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace IPC {

struct State_Message;
struct State_MessageBuilder;
struct State_MessageT;

struct State_MessageT : public ::flatbuffers::NativeTable {
  typedef State_Message TableType;
  int32_t type = 0;
  int32_t code = 0;
  std::string sub_str{};
};

struct State_Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef State_MessageT NativeTableType;
  typedef State_MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_CODE = 6,
    VT_SUB_STR = 8
  };
  int32_t type() const {
    return GetField<int32_t>(VT_TYPE, 0);
  }
  int32_t code() const {
    return GetField<int32_t>(VT_CODE, 0);
  }
  const ::flatbuffers::String *sub_str() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SUB_STR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyField<int32_t>(verifier, VT_CODE, 4) &&
           VerifyOffset(verifier, VT_SUB_STR) &&
           verifier.VerifyString(sub_str()) &&
           verifier.EndTable();
  }
  State_MessageT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(State_MessageT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<State_Message> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const State_MessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct State_MessageBuilder {
  typedef State_Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(int32_t type) {
    fbb_.AddElement<int32_t>(State_Message::VT_TYPE, type, 0);
  }
  void add_code(int32_t code) {
    fbb_.AddElement<int32_t>(State_Message::VT_CODE, code, 0);
  }
  void add_sub_str(::flatbuffers::Offset<::flatbuffers::String> sub_str) {
    fbb_.AddOffset(State_Message::VT_SUB_STR, sub_str);
  }
  explicit State_MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<State_Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<State_Message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<State_Message> CreateState_Message(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t type = 0,
    int32_t code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sub_str = 0) {
  State_MessageBuilder builder_(_fbb);
  builder_.add_sub_str(sub_str);
  builder_.add_code(code);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<State_Message> CreateState_MessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t type = 0,
    int32_t code = 0,
    const char *sub_str = nullptr) {
  auto sub_str__ = sub_str ? _fbb.CreateString(sub_str) : 0;
  return IPC::CreateState_Message(
      _fbb,
      type,
      code,
      sub_str__);
}

::flatbuffers::Offset<State_Message> CreateState_Message(::flatbuffers::FlatBufferBuilder &_fbb, const State_MessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline State_MessageT *State_Message::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<State_MessageT>(new State_MessageT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void State_Message::UnPackTo(State_MessageT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = code(); _o->code = _e; }
  { auto _e = sub_str(); if (_e) _o->sub_str = _e->str(); }
}

inline ::flatbuffers::Offset<State_Message> State_Message::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const State_MessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateState_Message(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<State_Message> CreateState_Message(::flatbuffers::FlatBufferBuilder &_fbb, const State_MessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const State_MessageT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _code = _o->code;
  auto _sub_str = _o->sub_str.empty() ? 0 : _fbb.CreateString(_o->sub_str);
  return IPC::CreateState_Message(
      _fbb,
      _type,
      _code,
      _sub_str);
}

inline const IPC::State_Message *GetState_Message(const void *buf) {
  return ::flatbuffers::GetRoot<IPC::State_Message>(buf);
}

inline const IPC::State_Message *GetSizePrefixedState_Message(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<IPC::State_Message>(buf);
}

inline bool VerifyState_MessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<IPC::State_Message>(nullptr);
}

inline bool VerifySizePrefixedState_MessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<IPC::State_Message>(nullptr);
}

inline void FinishState_MessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<IPC::State_Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedState_MessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<IPC::State_Message> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<IPC::State_MessageT> UnPackState_Message(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<IPC::State_MessageT>(GetState_Message(buf)->UnPack(res));
}

inline std::unique_ptr<IPC::State_MessageT> UnPackSizePrefixedState_Message(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<IPC::State_MessageT>(GetSizePrefixedState_Message(buf)->UnPack(res));
}

}  // namespace IPC

#endif  // FLATBUFFERS_GENERATED_STATEMESSAGE_IPC_H_
