# automatically generated by the FlatBuffers compiler, do not modify

# namespace: example

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DemoExampleHello(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DemoExampleHello()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDemoExampleHello(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DemoExampleHello
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DemoExampleHello
    def SenderInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flat_buffers.message.MessageSenderInfo import MessageSenderInfo
            obj = MessageSenderInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DemoExampleHello
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DemoExampleHello
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DemoExampleHello
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def DemoExampleHelloStart(builder):
    builder.StartObject(4)

def Start(builder):
    DemoExampleHelloStart(builder)

def DemoExampleHelloAddSenderInfo(builder, senderInfo):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(senderInfo), 0)

def AddSenderInfo(builder, senderInfo):
    DemoExampleHelloAddSenderInfo(builder, senderInfo)

def DemoExampleHelloAddX(builder, x):
    builder.PrependFloat32Slot(1, x, 0.0)

def AddX(builder, x):
    DemoExampleHelloAddX(builder, x)

def DemoExampleHelloAddY(builder, y):
    builder.PrependFloat32Slot(2, y, 0.0)

def AddY(builder, y):
    DemoExampleHelloAddY(builder, y)

def DemoExampleHelloAddZ(builder, z):
    builder.PrependFloat32Slot(3, z, 0.0)

def AddZ(builder, z):
    DemoExampleHelloAddZ(builder, z)

def DemoExampleHelloEnd(builder):
    return builder.EndObject()

def End(builder):
    return DemoExampleHelloEnd(builder)

import flat_buffers.message.MessageSenderInfo
try:
    from typing import Optional
except:
    pass

class DemoExampleHelloT(object):

    # DemoExampleHelloT
    def __init__(self):
        self.senderInfo = None  # type: Optional[message.MessageSenderInfo.MessageSenderInfoT]
        self.x = 0.0  # type: float
        self.y = 0.0  # type: float
        self.z = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        demoExampleHello = DemoExampleHello()
        demoExampleHello.Init(buf, pos)
        return cls.InitFromObj(demoExampleHello)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, demoExampleHello):
        x = DemoExampleHelloT()
        x._UnPack(demoExampleHello)
        return x

    # DemoExampleHelloT
    def _UnPack(self, demoExampleHello):
        if demoExampleHello is None:
            return
        if demoExampleHello.SenderInfo() is not None:
            self.senderInfo = flat_buffers.message.MessageSenderInfo.MessageSenderInfoT.InitFromObj(demoExampleHello.SenderInfo())
        self.x = demoExampleHello.X()
        self.y = demoExampleHello.Y()
        self.z = demoExampleHello.Z()

    # DemoExampleHelloT
    def Pack(self, builder):
        if self.senderInfo is not None:
            senderInfo = self.senderInfo.Pack(builder)
        DemoExampleHelloStart(builder)
        if self.senderInfo is not None:
            DemoExampleHelloAddSenderInfo(builder, senderInfo)
        DemoExampleHelloAddX(builder, self.x)
        DemoExampleHelloAddY(builder, self.y)
        DemoExampleHelloAddZ(builder, self.z)
        demoExampleHello = DemoExampleHelloEnd(builder)
        return demoExampleHello
