from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MoveStatus_Node(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MoveStatus_Node: ...
  @classmethod
  def GetRootAsMoveStatus_Node(cls, buf: bytes, offset: int) -> MoveStatus_Node: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def NodeId(self) -> str | None: ...
  def Name(self) -> str | None: ...
  def State(self) -> str | None: ...
  def X(self) -> float: ...
  def Y(self) -> float: ...
  def Rz(self) -> float: ...
class MoveStatus_NodeT(object):
  nodeId: str | None
  name: str | None
  state: str | None
  x: float
  y: float
  rz: float
  def __init__(
    self,
    nodeId: str | None = ...,
    name: str | None = ...,
    state: str | None = ...,
    x: float = ...,
    y: float = ...,
    rz: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> MoveStatus_NodeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> MoveStatus_NodeT: ...
  @classmethod
  def InitFromObj(cls, moveStatusNode: MoveStatus_Node) -> MoveStatus_NodeT: ...
  def _UnPack(self, moveStatusNode: MoveStatus_Node) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def MoveStatus_NodeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MoveStatus_NodeAddNodeId(builder: flatbuffers.Builder, nodeId: uoffset) -> None: ...
def MoveStatus_NodeAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def MoveStatus_NodeAddState(builder: flatbuffers.Builder, state: uoffset) -> None: ...
def MoveStatus_NodeAddX(builder: flatbuffers.Builder, x: float) -> None: ...
def MoveStatus_NodeAddY(builder: flatbuffers.Builder, y: float) -> None: ...
def MoveStatus_NodeAddRz(builder: flatbuffers.Builder, rz: float) -> None: ...
def MoveStatus_NodeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

