# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class MoveStatus_Move_State(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MoveStatus_Move_State()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMoveStatus_Move_State(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MoveStatus_Move_State
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MoveStatus_Move_State
    def AutoMove(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MoveStatus_Move_State
    def DockMove(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MoveStatus_Move_State
    def JogMove(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MoveStatus_Move_State
    def Obs(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MoveStatus_Move_State
    def Path(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MoveStatus_Move_StateStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    MoveStatus_Move_StateStart(builder)

def MoveStatus_Move_StateAddAutoMove(builder: flatbuffers.Builder, autoMove: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(autoMove), 0)

def AddAutoMove(builder: flatbuffers.Builder, autoMove: int):
    MoveStatus_Move_StateAddAutoMove(builder, autoMove)

def MoveStatus_Move_StateAddDockMove(builder: flatbuffers.Builder, dockMove: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(dockMove), 0)

def AddDockMove(builder: flatbuffers.Builder, dockMove: int):
    MoveStatus_Move_StateAddDockMove(builder, dockMove)

def MoveStatus_Move_StateAddJogMove(builder: flatbuffers.Builder, jogMove: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(jogMove), 0)

def AddJogMove(builder: flatbuffers.Builder, jogMove: int):
    MoveStatus_Move_StateAddJogMove(builder, jogMove)

def MoveStatus_Move_StateAddObs(builder: flatbuffers.Builder, obs: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(obs), 0)

def AddObs(builder: flatbuffers.Builder, obs: int):
    MoveStatus_Move_StateAddObs(builder, obs)

def MoveStatus_Move_StateAddPath(builder: flatbuffers.Builder, path: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)

def AddPath(builder: flatbuffers.Builder, path: int):
    MoveStatus_Move_StateAddPath(builder, path)

def MoveStatus_Move_StateEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MoveStatus_Move_StateEnd(builder)


class MoveStatus_Move_StateT(object):

    # MoveStatus_Move_StateT
    def __init__(
        self,
        autoMove = None,
        dockMove = None,
        jogMove = None,
        obs = None,
        path = None,
    ):
        self.autoMove = autoMove  # type: Optional[str]
        self.dockMove = dockMove  # type: Optional[str]
        self.jogMove = jogMove  # type: Optional[str]
        self.obs = obs  # type: Optional[str]
        self.path = path  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        moveStatusMoveState = MoveStatus_Move_State()
        moveStatusMoveState.Init(buf, pos)
        return cls.InitFromObj(moveStatusMoveState)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, moveStatusMoveState):
        x = MoveStatus_Move_StateT()
        x._UnPack(moveStatusMoveState)
        return x

    # MoveStatus_Move_StateT
    def _UnPack(self, moveStatusMoveState):
        if moveStatusMoveState is None:
            return
        self.autoMove = moveStatusMoveState.AutoMove()
        self.dockMove = moveStatusMoveState.DockMove()
        self.jogMove = moveStatusMoveState.JogMove()
        self.obs = moveStatusMoveState.Obs()
        self.path = moveStatusMoveState.Path()

    # MoveStatus_Move_StateT
    def Pack(self, builder):
        if self.autoMove is not None:
            autoMove = builder.CreateString(self.autoMove)
        if self.dockMove is not None:
            dockMove = builder.CreateString(self.dockMove)
        if self.jogMove is not None:
            jogMove = builder.CreateString(self.jogMove)
        if self.obs is not None:
            obs = builder.CreateString(self.obs)
        if self.path is not None:
            path = builder.CreateString(self.path)
        MoveStatus_Move_StateStart(builder)
        if self.autoMove is not None:
            MoveStatus_Move_StateAddAutoMove(builder, autoMove)
        if self.dockMove is not None:
            MoveStatus_Move_StateAddDockMove(builder, dockMove)
        if self.jogMove is not None:
            MoveStatus_Move_StateAddJogMove(builder, jogMove)
        if self.obs is not None:
            MoveStatus_Move_StateAddObs(builder, obs)
        if self.path is not None:
            MoveStatus_Move_StateAddPath(builder, path)
        moveStatusMoveState = MoveStatus_Move_StateEnd(builder)
        return moveStatusMoveState
