# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class MoveStatus_Pose(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MoveStatus_Pose()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMoveStatus_Pose(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MoveStatus_Pose
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MoveStatus_Pose
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # MoveStatus_Pose
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # MoveStatus_Pose
    def Rz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def MoveStatus_PoseStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    MoveStatus_PoseStart(builder)

def MoveStatus_PoseAddX(builder: flatbuffers.Builder, x: float):
    builder.PrependFloat64Slot(0, x, 0.0)

def AddX(builder: flatbuffers.Builder, x: float):
    MoveStatus_PoseAddX(builder, x)

def MoveStatus_PoseAddY(builder: flatbuffers.Builder, y: float):
    builder.PrependFloat64Slot(1, y, 0.0)

def AddY(builder: flatbuffers.Builder, y: float):
    MoveStatus_PoseAddY(builder, y)

def MoveStatus_PoseAddRz(builder: flatbuffers.Builder, rz: float):
    builder.PrependFloat64Slot(2, rz, 0.0)

def AddRz(builder: flatbuffers.Builder, rz: float):
    MoveStatus_PoseAddRz(builder, rz)

def MoveStatus_PoseEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MoveStatus_PoseEnd(builder)


class MoveStatus_PoseT(object):

    # MoveStatus_PoseT
    def __init__(
        self,
        x = 0.0,
        y = 0.0,
        rz = 0.0,
    ):
        self.x = x  # type: float
        self.y = y  # type: float
        self.rz = rz  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        moveStatusPose = MoveStatus_Pose()
        moveStatusPose.Init(buf, pos)
        return cls.InitFromObj(moveStatusPose)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, moveStatusPose):
        x = MoveStatus_PoseT()
        x._UnPack(moveStatusPose)
        return x

    # MoveStatus_PoseT
    def _UnPack(self, moveStatusPose):
        if moveStatusPose is None:
            return
        self.x = moveStatusPose.X()
        self.y = moveStatusPose.Y()
        self.rz = moveStatusPose.Rz()

    # MoveStatus_PoseT
    def Pack(self, builder):
        MoveStatus_PoseStart(builder)
        MoveStatus_PoseAddX(builder, self.x)
        MoveStatus_PoseAddY(builder, self.y)
        MoveStatus_PoseAddRz(builder, self.rz)
        moveStatusPose = MoveStatus_PoseEnd(builder)
        return moveStatusPose
