from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MoveStatus_Vel(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MoveStatus_Vel: ...
  @classmethod
  def GetRootAsMoveStatus_Vel(cls, buf: bytes, offset: int) -> MoveStatus_Vel: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Vx(self) -> float: ...
  def Vy(self) -> float: ...
  def Wz(self) -> float: ...
class MoveStatus_VelT(object):
  vx: float
  vy: float
  wz: float
  def __init__(
    self,
    vx: float = ...,
    vy: float = ...,
    wz: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> MoveStatus_VelT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> MoveStatus_VelT: ...
  @classmethod
  def InitFromObj(cls, moveStatusVel: MoveStatus_Vel) -> MoveStatus_VelT: ...
  def _UnPack(self, moveStatusVel: MoveStatus_Vel) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def MoveStatus_VelStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MoveStatus_VelAddVx(builder: flatbuffers.Builder, vx: float) -> None: ...
def MoveStatus_VelAddVy(builder: flatbuffers.Builder, vy: float) -> None: ...
def MoveStatus_VelAddWz(builder: flatbuffers.Builder, wz: float) -> None: ...
def MoveStatus_VelEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

