from __future__ import annotations

from rb_flat_buffers.IPC.MoveStatus_Vel import MoveStatus_Vel, MoveStatus_VelT
from rb_flat_buffers.IPC.MoveStatus_Pose import MoveStatus_Pose, MoveStatus_PoseT
from rb_flat_buffers.IPC.MoveStatus_Node import MoveStatus_Node, MoveStatus_NodeT
from rb_flat_buffers.IPC.MoveStatus_Move_State import MoveStatus_Move_State, MoveStatus_Move_StateT
import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.SLAMNAV.MoveStatus_Move_State import MoveStatus_Move_State, MoveStatus_Move_StateT
from rb_flat_buffers.SLAMNAV.MoveStatus_Node import MoveStatus_Node, MoveStatus_NodeT
from rb_flat_buffers.SLAMNAV.MoveStatus_Pose import MoveStatus_Pose, MoveStatus_PoseT
from rb_flat_buffers.SLAMNAV.MoveStatus_Vel import MoveStatus_Vel, MoveStatus_VelT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MoveStatus(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MoveStatus: ...
  @classmethod
  def GetRootAsMoveStatus(cls, buf: bytes, offset: int) -> MoveStatus: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def MoveState(self) -> MoveStatus_Move_State | None: ...
  def Pose(self) -> MoveStatus_Pose | None: ...
  def Vel(self) -> MoveStatus_Vel | None: ...
  def GoalNode(self) -> MoveStatus_Node | None: ...
  def CurNode(self) -> MoveStatus_Node | None: ...
class MoveStatusT(object):
  moveState: MoveStatus_Move_StateT | None
  pose: MoveStatus_PoseT | None
  vel: MoveStatus_VelT | None
  goalNode: MoveStatus_NodeT | None
  curNode: MoveStatus_NodeT | None
  def __init__(
    self,
    moveState: 'MoveStatus_Move_StateT' | None = ...,
    pose: 'MoveStatus_PoseT' | None = ...,
    vel: 'MoveStatus_VelT' | None = ...,
    goalNode: 'MoveStatus_NodeT' | None = ...,
    curNode: 'MoveStatus_NodeT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> MoveStatusT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> MoveStatusT: ...
  @classmethod
  def InitFromObj(cls, moveStatus: MoveStatus) -> MoveStatusT: ...
  def _UnPack(self, moveStatus: MoveStatus) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def MoveStatusStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MoveStatusAddMoveState(builder: flatbuffers.Builder, moveState: uoffset) -> None: ...
def MoveStatusAddPose(builder: flatbuffers.Builder, pose: uoffset) -> None: ...
def MoveStatusAddVel(builder: flatbuffers.Builder, vel: uoffset) -> None: ...
def MoveStatusAddGoalNode(builder: flatbuffers.Builder, goalNode: uoffset) -> None: ...
def MoveStatusAddCurNode(builder: flatbuffers.Builder, curNode: uoffset) -> None: ...
def MoveStatusEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

