from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MoveStatus_Move_State(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MoveStatus_Move_State: ...
  @classmethod
  def GetRootAsMoveStatus_Move_State(cls, buf: bytes, offset: int) -> MoveStatus_Move_State: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def AutoMove(self) -> str | None: ...
  def DockMove(self) -> str | None: ...
  def JogMove(self) -> str | None: ...
  def Obs(self) -> str | None: ...
  def Path(self) -> str | None: ...
class MoveStatus_Move_StateT(object):
  autoMove: str | None
  dockMove: str | None
  jogMove: str | None
  obs: str | None
  path: str | None
  def __init__(
    self,
    autoMove: str | None = ...,
    dockMove: str | None = ...,
    jogMove: str | None = ...,
    obs: str | None = ...,
    path: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> MoveStatus_Move_StateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> MoveStatus_Move_StateT: ...
  @classmethod
  def InitFromObj(cls, moveStatusMoveState: MoveStatus_Move_State) -> MoveStatus_Move_StateT: ...
  def _UnPack(self, moveStatusMoveState: MoveStatus_Move_State) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def MoveStatus_Move_StateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MoveStatus_Move_StateAddAutoMove(builder: flatbuffers.Builder, autoMove: uoffset) -> None: ...
def MoveStatus_Move_StateAddDockMove(builder: flatbuffers.Builder, dockMove: uoffset) -> None: ...
def MoveStatus_Move_StateAddJogMove(builder: flatbuffers.Builder, jogMove: uoffset) -> None: ...
def MoveStatus_Move_StateAddObs(builder: flatbuffers.Builder, obs: uoffset) -> None: ...
def MoveStatus_Move_StateAddPath(builder: flatbuffers.Builder, path: uoffset) -> None: ...
def MoveStatus_Move_StateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

