from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MoveStatus_Pose(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MoveStatus_Pose: ...
  @classmethod
  def GetRootAsMoveStatus_Pose(cls, buf: bytes, offset: int) -> MoveStatus_Pose: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def X(self) -> float: ...
  def Y(self) -> float: ...
  def Rz(self) -> float: ...
class MoveStatus_PoseT(object):
  x: float
  y: float
  rz: float
  def __init__(
    self,
    x: float = ...,
    y: float = ...,
    rz: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> MoveStatus_PoseT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> MoveStatus_PoseT: ...
  @classmethod
  def InitFromObj(cls, moveStatusPose: MoveStatus_Pose) -> MoveStatus_PoseT: ...
  def _UnPack(self, moveStatusPose: MoveStatus_Pose) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def MoveStatus_PoseStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MoveStatus_PoseAddX(builder: flatbuffers.Builder, x: float) -> None: ...
def MoveStatus_PoseAddY(builder: flatbuffers.Builder, y: float) -> None: ...
def MoveStatus_PoseAddRz(builder: flatbuffers.Builder, rz: float) -> None: ...
def MoveStatus_PoseEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

