from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Node(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Node: ...
  @classmethod
  def GetRootAsNode(cls, buf: bytes, offset: int) -> Node: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Name(self) -> str | None: ...
  def Pose(self, i: int) -> typing.List[float]: ...
  def PoseAsNumpy(self) -> np.ndarray: ...
  def PoseLength(self) -> int: ...
  def PoseIsNone(self) -> bool: ...
  def Info(self) -> str | None: ...
  def Links(self, i: int) -> str: ...
  def LinksLength(self) -> int: ...
  def LinksIsNone(self) -> bool: ...
  def Type(self) -> str | None: ...
class NodeT(object):
  id: str | None
  name: str | None
  pose: typing.List[float]
  info: str | None
  links: typing.List[str]
  type: str | None
  def __init__(
    self,
    id: str | None = ...,
    name: str | None = ...,
    pose: typing.List[float] | None = ...,
    info: str | None = ...,
    links: typing.List[str] | None = ...,
    type: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> NodeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> NodeT: ...
  @classmethod
  def InitFromObj(cls, node: Node) -> NodeT: ...
  def _UnPack(self, node: Node) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def NodeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def NodeAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def NodeAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def NodeAddPose(builder: flatbuffers.Builder, pose: uoffset) -> None: ...
def NodeStartPoseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartPoseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def NodeAddInfo(builder: flatbuffers.Builder, info: uoffset) -> None: ...
def NodeAddLinks(builder: flatbuffers.Builder, links: uoffset) -> None: ...
def NodeStartLinksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartLinksVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def NodeAddType(builder: flatbuffers.Builder, type: uoffset) -> None: ...
def NodeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

