from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Path import Path
from rb_flat_buffers.SLAMNAV.PointArray import PointArray, PointArrayT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Path(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Path: ...
  @classmethod
  def GetRootAsPath(cls, buf: bytes, offset: int) -> Path: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Value(self, i: int) -> PointArray | None: ...
  def ValueLength(self) -> int: ...
  def ValueIsNone(self) -> bool: ...
class PathT(object):
  value: typing.List[PointArrayT]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> PathT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> PathT: ...
  @classmethod
  def InitFromObj(cls, path: Path) -> PathT: ...
  def _UnPack(self, path: Path) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def PathStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def PathAddValue(builder: flatbuffers.Builder, value: uoffset) -> None: ...
def PathStartValueVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartValueVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def PathEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

