from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.PointArray import PointArray

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class PointArray(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def Point(self, i: int) -> typing.List[float]: ...
  def PointAsNumpy(self) -> np.ndarray: ...
  def PointLength(self) -> int: ...
  def PointIsNone(self) -> bool: ...
class PointArrayT(object):
  point: typing.List[float]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> PointArrayT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> PointArrayT: ...
  @classmethod
  def InitFromObj(cls, pointArray: PointArray) -> PointArrayT: ...
  def _UnPack(self, pointArray: PointArray) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreatePointArray(builder: flatbuffers.Builder, point: float) -> uoffset: ...

