# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Localization_Start(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Localization_Start()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Localization_Start(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Localization_Start
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Localization_Start
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Request_Localization_StartStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    Request_Localization_StartStart(builder)

def Request_Localization_StartAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Request_Localization_StartAddId(builder, id)

def Request_Localization_StartEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Localization_StartEnd(builder)


class Request_Localization_StartT(object):

    # Request_Localization_StartT
    def __init__(self):
        self.id = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestLocalizationStart = Request_Localization_Start()
        requestLocalizationStart.Init(buf, pos)
        return cls.InitFromObj(requestLocalizationStart)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestLocalizationStart):
        x = Request_Localization_StartT()
        x._UnPack(requestLocalizationStart)
        return x

    # Request_Localization_StartT
    def _UnPack(self, requestLocalizationStart):
        if requestLocalizationStart is None:
            return
        self.id = requestLocalizationStart.Id()

    # Request_Localization_StartT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        Request_Localization_StartStart(builder)
        if self.id is not None:
            Request_Localization_StartAddId(builder, id)
        requestLocalizationStart = Request_Localization_StartEnd(builder)
        return requestLocalizationStart
