from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Safety_Field(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Safety_Field: ...
  @classmethod
  def GetRootAsRequest_Safety_Field(cls, buf: bytes, offset: int) -> Request_Safety_Field: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def SafetyField(self) -> int: ...
class Request_Safety_FieldT(object):
  id: str | None
  command: str | None
  safetyField: int
  def __init__(
    self,
    id: str | None = ...,
    command: str | None = ...,
    safetyField: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Safety_FieldT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Safety_FieldT: ...
  @classmethod
  def InitFromObj(cls, requestSafetyField: Request_Safety_Field) -> Request_Safety_FieldT: ...
  def _UnPack(self, requestSafetyField: Request_Safety_Field) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Safety_FieldStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Safety_FieldAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Safety_FieldAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Request_Safety_FieldAddSafetyField(builder: flatbuffers.Builder, safetyField: int) -> None: ...
def Request_Safety_FieldEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

