from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Get_Map_File import Request_Get_Map_File

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Get_Map_File(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Get_Map_File: ...
  @classmethod
  def GetRootAsRequest_Get_Map_File(cls, buf: bytes, offset: int) -> Request_Get_Map_File: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def FileName(self) -> str | None: ...
class Request_Get_Map_FileT(object):
  id: str | None
  mapName: str | None
  fileName: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Get_Map_FileT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Get_Map_FileT: ...
  @classmethod
  def InitFromObj(cls, requestGetMapFile: Request_Get_Map_File) -> Request_Get_Map_FileT: ...
  def _UnPack(self, requestGetMapFile: Request_Get_Map_File) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Get_Map_FileStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Get_Map_FileAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Get_Map_FileAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Request_Get_Map_FileAddFileName(builder: flatbuffers.Builder, fileName: uoffset) -> None: ...
def Request_Get_Map_FileEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

