from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Localization_RandomInit(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Localization_RandomInit: ...
  @classmethod
  def GetRootAsRequest_Localization_RandomInit(cls, buf: bytes, offset: int) -> Request_Localization_RandomInit: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def RandomSeed(self) -> str | None: ...
class Request_Localization_RandomInitT(object):
  id: str | None
  randomSeed: str | None
  def __init__(
    self,
    id: str | None = ...,
    randomSeed: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Localization_RandomInitT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Localization_RandomInitT: ...
  @classmethod
  def InitFromObj(cls, requestLocalizationRandomInit: Request_Localization_RandomInit) -> Request_Localization_RandomInitT: ...
  def _UnPack(self, requestLocalizationRandomInit: Request_Localization_RandomInit) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Localization_RandomInitStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Localization_RandomInitAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Localization_RandomInitAddRandomSeed(builder: flatbuffers.Builder, randomSeed: uoffset) -> None: ...
def Request_Localization_RandomInitEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

