from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Node import Node, NodeT
from rb_flat_buffers.SLAMNAV.Request_Set_Map_Topology import Request_Set_Map_Topology

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Set_Map_Topology(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Set_Map_Topology: ...
  @classmethod
  def GetRootAsRequest_Set_Map_Topology(cls, buf: bytes, offset: int) -> Request_Set_Map_Topology: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def Data(self, i: int) -> Node | None: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
class Request_Set_Map_TopologyT(object):
  id: str | None
  mapName: str | None
  data: typing.List[NodeT]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Set_Map_TopologyT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Set_Map_TopologyT: ...
  @classmethod
  def InitFromObj(cls, requestSetMapTopology: Request_Set_Map_Topology) -> Request_Set_Map_TopologyT: ...
  def _UnPack(self, requestSetMapTopology: Request_Set_Map_Topology) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Set_Map_TopologyStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Set_Map_TopologyAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Set_Map_TopologyAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Request_Set_Map_TopologyAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def Request_Set_Map_TopologyStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Request_Set_Map_TopologyEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

