from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Current_Version(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Current_Version: ...
  @classmethod
  def GetRootAsRequest_Current_Version(cls, buf: bytes, offset: int) -> Request_Current_Version: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Current_VersionT(object):
  id: str | None
  def __init__(
    self,
    id: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Current_VersionT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Current_VersionT: ...
  @classmethod
  def InitFromObj(cls, requestCurrentVersion: Request_Current_Version) -> Request_Current_VersionT: ...
  def _UnPack(self, requestCurrentVersion: Request_Current_Version) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Current_VersionStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Current_VersionAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Current_VersionEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

