from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Mapping(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Mapping: ...
  @classmethod
  def GetRootAsRequest_Mapping(cls, buf: bytes, offset: int) -> Request_Mapping: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def MapName(self) -> str | None: ...
class Request_MappingT(object):
  id: str | None
  command: str | None
  mapName: str | None
  def __init__(
    self,
    id: str | None = ...,
    command: str | None = ...,
    mapName: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_MappingT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_MappingT: ...
  @classmethod
  def InitFromObj(cls, requestMapping: Request_Mapping) -> Request_MappingT: ...
  def _UnPack(self, requestMapping: Request_Mapping) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_MappingStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_MappingAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_MappingAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Request_MappingAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Request_MappingEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

