from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Set_Pdu_Param import Request_Set_Pdu_Param
from rb_flat_buffers.SLAMNAV.Setting_Param import Setting_Param, Setting_ParamT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Set_Pdu_Param(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Set_Pdu_Param: ...
  @classmethod
  def GetRootAsRequest_Set_Pdu_Param(cls, buf: bytes, offset: int) -> Request_Set_Pdu_Param: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Params(self, i: int) -> Setting_Param | None: ...
  def ParamsLength(self) -> int: ...
  def ParamsIsNone(self) -> bool: ...
class Request_Set_Pdu_ParamT(object):
  id: str | None
  params: typing.List[Setting_ParamT]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Set_Pdu_ParamT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Set_Pdu_ParamT: ...
  @classmethod
  def InitFromObj(cls, requestSetPduParam: Request_Set_Pdu_Param) -> Request_Set_Pdu_ParamT: ...
  def _UnPack(self, requestSetPduParam: Request_Set_Pdu_Param) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Set_Pdu_ParamStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Set_Pdu_ParamAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Set_Pdu_ParamAddParams(builder: flatbuffers.Builder, params: uoffset) -> None: ...
def Request_Set_Pdu_ParamStartParamsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartParamsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Request_Set_Pdu_ParamEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

