from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Map_List import Request_Map_List

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Map_List(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Map_List: ...
  @classmethod
  def GetRootAsRequest_Map_List(cls, buf: bytes, offset: int) -> Request_Map_List: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Map_ListT(object):
  id: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Map_ListT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Map_ListT: ...
  @classmethod
  def InitFromObj(cls, requestMapList: Request_Map_List) -> Request_Map_ListT: ...
  def _UnPack(self, requestMapList: Request_Map_List) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Map_ListStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Map_ListAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Map_ListEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

