from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_Circular(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_Circular: ...
  @classmethod
  def GetRootAsRequest_Move_Circular(cls, buf: bytes, offset: int) -> Request_Move_Circular: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Target(self) -> float: ...
  def Speed(self) -> float: ...
  def Direction(self) -> str | None: ...
class Request_Move_CircularT(object):
  id: str | None
  target: float
  speed: float
  direction: str | None
  def __init__(
    self,
    id: str | None = ...,
    target: float = ...,
    speed: float = ...,
    direction: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_CircularT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_CircularT: ...
  @classmethod
  def InitFromObj(cls, requestMoveCircular: Request_Move_Circular) -> Request_Move_CircularT: ...
  def _UnPack(self, requestMoveCircular: Request_Move_Circular) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_CircularStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_CircularAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Move_CircularAddTarget(builder: flatbuffers.Builder, target: float) -> None: ...
def Request_Move_CircularAddSpeed(builder: flatbuffers.Builder, speed: float) -> None: ...
def Request_Move_CircularAddDirection(builder: flatbuffers.Builder, direction: uoffset) -> None: ...
def Request_Move_CircularEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

