# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from rb_flat_buffers.SLAMNAV.Sensor_Info import Sensor_Info, Sensor_InfoT
from typing import Optional
np = import_numpy()

class Request_Get_Sensor_Off(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Get_Sensor_Off()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Get_Sensor_Off(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Get_Sensor_Off
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Get_Sensor_Off
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Get_Sensor_Off
    def Index(self, j: int) -> Optional[Sensor_Info]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Sensor_Info()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Request_Get_Sensor_Off
    def IndexLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Request_Get_Sensor_Off
    def IndexIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def Request_Get_Sensor_OffStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    Request_Get_Sensor_OffStart(builder)

def Request_Get_Sensor_OffAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Request_Get_Sensor_OffAddId(builder, id)

def Request_Get_Sensor_OffAddIndex(builder: flatbuffers.Builder, index: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(index), 0)

def AddIndex(builder: flatbuffers.Builder, index: int):
    Request_Get_Sensor_OffAddIndex(builder, index)

def Request_Get_Sensor_OffStartIndexVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartIndexVector(builder, numElems: int) -> int:
    return Request_Get_Sensor_OffStartIndexVector(builder, numElems)

def Request_Get_Sensor_OffEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Get_Sensor_OffEnd(builder)

try:
    from typing import List
except:
    pass

class Request_Get_Sensor_OffT(object):

    # Request_Get_Sensor_OffT
    def __init__(
        self,
        id = None,
        index = None,
    ):
        self.id = id  # type: Optional[str]
        self.index = index  # type: Optional[List[Sensor_InfoT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestGetSensorOff = Request_Get_Sensor_Off()
        requestGetSensorOff.Init(buf, pos)
        return cls.InitFromObj(requestGetSensorOff)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestGetSensorOff):
        x = Request_Get_Sensor_OffT()
        x._UnPack(requestGetSensorOff)
        return x

    # Request_Get_Sensor_OffT
    def _UnPack(self, requestGetSensorOff):
        if requestGetSensorOff is None:
            return
        self.id = requestGetSensorOff.Id()
        if not requestGetSensorOff.IndexIsNone():
            self.index = []
            for i in range(requestGetSensorOff.IndexLength()):
                if requestGetSensorOff.Index(i) is None:
                    self.index.append(None)
                else:
                    sensor_Info_ = Sensor_InfoT.InitFromObj(requestGetSensorOff.Index(i))
                    self.index.append(sensor_Info_)

    # Request_Get_Sensor_OffT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.index is not None:
            indexlist = []
            for i in range(len(self.index)):
                indexlist.append(self.index[i].Pack(builder))
            Request_Get_Sensor_OffStartIndexVector(builder, len(self.index))
            for i in reversed(range(len(self.index))):
                builder.PrependUOffsetTRelative(indexlist[i])
            index = builder.EndVector()
        Request_Get_Sensor_OffStart(builder)
        if self.id is not None:
            Request_Get_Sensor_OffAddId(builder, id)
        if self.index is not None:
            Request_Get_Sensor_OffAddIndex(builder, index)
        requestGetSensorOff = Request_Get_Sensor_OffEnd(builder)
        return requestGetSensorOff
