# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Get_Sensor_Index(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Get_Sensor_Index()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Get_Sensor_Index(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Get_Sensor_Index
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Get_Sensor_Index
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Get_Sensor_Index
    def Target(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Request_Get_Sensor_IndexStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    Request_Get_Sensor_IndexStart(builder)

def Request_Get_Sensor_IndexAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Request_Get_Sensor_IndexAddId(builder, id)

def Request_Get_Sensor_IndexAddTarget(builder: flatbuffers.Builder, target: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(target), 0)

def AddTarget(builder: flatbuffers.Builder, target: int):
    Request_Get_Sensor_IndexAddTarget(builder, target)

def Request_Get_Sensor_IndexEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Get_Sensor_IndexEnd(builder)


class Request_Get_Sensor_IndexT(object):

    # Request_Get_Sensor_IndexT
    def __init__(
        self,
        id = None,
        target = None,
    ):
        self.id = id  # type: Optional[str]
        self.target = target  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestGetSensorIndex = Request_Get_Sensor_Index()
        requestGetSensorIndex.Init(buf, pos)
        return cls.InitFromObj(requestGetSensorIndex)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestGetSensorIndex):
        x = Request_Get_Sensor_IndexT()
        x._UnPack(requestGetSensorIndex)
        return x

    # Request_Get_Sensor_IndexT
    def _UnPack(self, requestGetSensorIndex):
        if requestGetSensorIndex is None:
            return
        self.id = requestGetSensorIndex.Id()
        self.target = requestGetSensorIndex.Target()

    # Request_Get_Sensor_IndexT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.target is not None:
            target = builder.CreateString(self.target)
        Request_Get_Sensor_IndexStart(builder)
        if self.id is not None:
            Request_Get_Sensor_IndexAddId(builder, id)
        if self.target is not None:
            Request_Get_Sensor_IndexAddTarget(builder, target)
        requestGetSensorIndex = Request_Get_Sensor_IndexEnd(builder)
        return requestGetSensorIndex
