from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Random_Sequence import Request_Random_Sequence

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Random_Sequence(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Random_Sequence: ...
  @classmethod
  def GetRootAsRequest_Random_Sequence(cls, buf: bytes, offset: int) -> Request_Random_Sequence: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Random_SequenceT(object):
  id: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Random_SequenceT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Random_SequenceT: ...
  @classmethod
  def InitFromObj(cls, requestRandomSequence: Request_Random_Sequence) -> Request_Random_SequenceT: ...
  def _UnPack(self, requestRandomSequence: Request_Random_Sequence) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Random_SequenceStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Random_SequenceAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Random_SequenceEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

