from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Version import Request_Version

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Version(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Version: ...
  @classmethod
  def GetRootAsRequest_Version(cls, buf: bytes, offset: int) -> Request_Version: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_VersionT(object):
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_VersionT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_VersionT: ...
  @classmethod
  def InitFromObj(cls, requestVersion: Request_Version) -> Request_VersionT: ...
  def _UnPack(self, requestVersion: Request_Version) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_VersionStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_VersionEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

