from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Move_Target import Request_Move_Target

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_Target(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_Target: ...
  @classmethod
  def GetRootAsRequest_Move_Target(cls, buf: bytes, offset: int) -> Request_Move_Target: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def GoalPose(self, i: int) -> typing.List[float]: ...
  def GoalPoseAsNumpy(self) -> np.ndarray: ...
  def GoalPoseLength(self) -> int: ...
  def GoalPoseIsNone(self) -> bool: ...
  def Method(self) -> str | None: ...
  def Preset(self) -> int: ...
class Request_Move_TargetT(object):
  id: str | None
  goalPose: typing.List[float]
  method: str | None
  preset: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_TargetT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_TargetT: ...
  @classmethod
  def InitFromObj(cls, requestMoveTarget: Request_Move_Target) -> Request_Move_TargetT: ...
  def _UnPack(self, requestMoveTarget: Request_Move_Target) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_TargetStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_TargetAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Move_TargetAddGoalPose(builder: flatbuffers.Builder, goalPose: uoffset) -> None: ...
def Request_Move_TargetStartGoalPoseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartGoalPoseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Request_Move_TargetAddMethod(builder: flatbuffers.Builder, method: uoffset) -> None: ...
def Request_Move_TargetAddPreset(builder: flatbuffers.Builder, preset: int) -> None: ...
def Request_Move_TargetEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

