from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Localization_AutoInit import Request_Localization_AutoInit

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Localization_AutoInit(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Localization_AutoInit: ...
  @classmethod
  def GetRootAsRequest_Localization_AutoInit(cls, buf: bytes, offset: int) -> Request_Localization_AutoInit: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Localization_AutoInitT(object):
  id: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Localization_AutoInitT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Localization_AutoInitT: ...
  @classmethod
  def InitFromObj(cls, requestLocalizationAutoInit: Request_Localization_AutoInit) -> Request_Localization_AutoInitT: ...
  def _UnPack(self, requestLocalizationAutoInit: Request_Localization_AutoInit) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Localization_AutoInitStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Localization_AutoInitAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Localization_AutoInitEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

