from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Localization_SemiAutoInit import Request_Localization_SemiAutoInit

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Localization_SemiAutoInit(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Localization_SemiAutoInit: ...
  @classmethod
  def GetRootAsRequest_Localization_SemiAutoInit(cls, buf: bytes, offset: int) -> Request_Localization_SemiAutoInit: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Localization_SemiAutoInitT(object):
  id: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Localization_SemiAutoInitT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Localization_SemiAutoInitT: ...
  @classmethod
  def InitFromObj(cls, requestLocalizationSemiAutoInit: Request_Localization_SemiAutoInit) -> Request_Localization_SemiAutoInitT: ...
  def _UnPack(self, requestLocalizationSemiAutoInit: Request_Localization_SemiAutoInit) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Localization_SemiAutoInitStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Localization_SemiAutoInitAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Localization_SemiAutoInitEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

