from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Get_Robot_Type import Request_Get_Robot_Type

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Get_Robot_Type(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Get_Robot_Type: ...
  @classmethod
  def GetRootAsRequest_Get_Robot_Type(cls, buf: bytes, offset: int) -> Request_Get_Robot_Type: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Get_Robot_TypeT(object):
  id: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Get_Robot_TypeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Get_Robot_TypeT: ...
  @classmethod
  def InitFromObj(cls, requestGetRobotType: Request_Get_Robot_Type) -> Request_Get_Robot_TypeT: ...
  def _UnPack(self, requestGetRobotType: Request_Get_Robot_Type) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Get_Robot_TypeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Get_Robot_TypeAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Get_Robot_TypeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

