# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Get_Robot_Type(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Get_Robot_Type()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Get_Robot_Type(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Get_Robot_Type
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Get_Robot_Type
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Request_Get_Robot_TypeStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    Request_Get_Robot_TypeStart(builder)

def Request_Get_Robot_TypeAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Request_Get_Robot_TypeAddId(builder, id)

def Request_Get_Robot_TypeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Get_Robot_TypeEnd(builder)


class Request_Get_Robot_TypeT(object):

    # Request_Get_Robot_TypeT
    def __init__(
        self,
        id = None,
    ):
        self.id = id  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestGetRobotType = Request_Get_Robot_Type()
        requestGetRobotType.Init(buf, pos)
        return cls.InitFromObj(requestGetRobotType)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestGetRobotType):
        x = Request_Get_Robot_TypeT()
        x._UnPack(requestGetRobotType)
        return x

    # Request_Get_Robot_TypeT
    def _UnPack(self, requestGetRobotType):
        if requestGetRobotType is None:
            return
        self.id = requestGetRobotType.Id()

    # Request_Get_Robot_TypeT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        Request_Get_Robot_TypeStart(builder)
        if self.id is not None:
            Request_Get_Robot_TypeAddId(builder, id)
        requestGetRobotType = Request_Get_Robot_TypeEnd(builder)
        return requestGetRobotType
