# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Move_Target(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Move_Target()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Move_Target(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Move_Target
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Move_Target
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Move_Target
    def GoalPose(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Request_Move_Target
    def GoalPoseAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # Request_Move_Target
    def GoalPoseLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Request_Move_Target
    def GoalPoseIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Request_Move_Target
    def Method(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Move_Target
    def Preset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Request_Move_TargetStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    Request_Move_TargetStart(builder)

def Request_Move_TargetAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Request_Move_TargetAddId(builder, id)

def Request_Move_TargetAddGoalPose(builder: flatbuffers.Builder, goalPose: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(goalPose), 0)

def AddGoalPose(builder: flatbuffers.Builder, goalPose: int):
    Request_Move_TargetAddGoalPose(builder, goalPose)

def Request_Move_TargetStartGoalPoseVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartGoalPoseVector(builder, numElems: int) -> int:
    return Request_Move_TargetStartGoalPoseVector(builder, numElems)

def Request_Move_TargetAddMethod(builder: flatbuffers.Builder, method: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(method), 0)

def AddMethod(builder: flatbuffers.Builder, method: int):
    Request_Move_TargetAddMethod(builder, method)

def Request_Move_TargetAddPreset(builder: flatbuffers.Builder, preset: int):
    builder.PrependInt32Slot(3, preset, 0)

def AddPreset(builder: flatbuffers.Builder, preset: int):
    Request_Move_TargetAddPreset(builder, preset)

def Request_Move_TargetEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Move_TargetEnd(builder)

try:
    from typing import List
except:
    pass

class Request_Move_TargetT(object):

    # Request_Move_TargetT
    def __init__(
        self,
        id = None,
        goalPose = None,
        method = None,
        preset = 0,
    ):
        self.id = id  # type: Optional[str]
        self.goalPose = goalPose  # type: Optional[List[float]]
        self.method = method  # type: Optional[str]
        self.preset = preset  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestMoveTarget = Request_Move_Target()
        requestMoveTarget.Init(buf, pos)
        return cls.InitFromObj(requestMoveTarget)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestMoveTarget):
        x = Request_Move_TargetT()
        x._UnPack(requestMoveTarget)
        return x

    # Request_Move_TargetT
    def _UnPack(self, requestMoveTarget):
        if requestMoveTarget is None:
            return
        self.id = requestMoveTarget.Id()
        if not requestMoveTarget.GoalPoseIsNone():
            if np is None:
                self.goalPose = []
                for i in range(requestMoveTarget.GoalPoseLength()):
                    self.goalPose.append(requestMoveTarget.GoalPose(i))
            else:
                self.goalPose = requestMoveTarget.GoalPoseAsNumpy()
        self.method = requestMoveTarget.Method()
        self.preset = requestMoveTarget.Preset()

    # Request_Move_TargetT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.goalPose is not None:
            if np is not None and type(self.goalPose) is np.ndarray:
                goalPose = builder.CreateNumpyVector(self.goalPose)
            else:
                Request_Move_TargetStartGoalPoseVector(builder, len(self.goalPose))
                for i in reversed(range(len(self.goalPose))):
                    builder.PrependFloat64(self.goalPose[i])
                goalPose = builder.EndVector()
        if self.method is not None:
            method = builder.CreateString(self.method)
        Request_Move_TargetStart(builder)
        if self.id is not None:
            Request_Move_TargetAddId(builder, id)
        if self.goalPose is not None:
            Request_Move_TargetAddGoalPose(builder, goalPose)
        if self.method is not None:
            Request_Move_TargetAddMethod(builder, method)
        Request_Move_TargetAddPreset(builder, self.preset)
        requestMoveTarget = Request_Move_TargetEnd(builder)
        return requestMoveTarget
