from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Move_Resume import Request_Move_Resume

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_Resume(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_Resume: ...
  @classmethod
  def GetRootAsRequest_Move_Resume(cls, buf: bytes, offset: int) -> Request_Move_Resume: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Move_ResumeT(object):
  id: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_ResumeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_ResumeT: ...
  @classmethod
  def InitFromObj(cls, requestMoveResume: Request_Move_Resume) -> Request_Move_ResumeT: ...
  def _UnPack(self, requestMoveResume: Request_Move_Resume) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_ResumeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_ResumeAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Move_ResumeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

