from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Get_Map_Topology(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Get_Map_Topology: ...
  @classmethod
  def GetRootAsRequest_Get_Map_Topology(cls, buf: bytes, offset: int) -> Request_Get_Map_Topology: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def FileName(self) -> str | None: ...
  def PageNo(self) -> int: ...
  def PageSize(self) -> int: ...
  def TotalPage(self) -> int: ...
  def NodeType(self) -> str | None: ...
  def SearchText(self) -> str | None: ...
  def SortOption(self) -> str | None: ...
  def SortDirection(self) -> str | None: ...
class Request_Get_Map_TopologyT(object):
  id: str | None
  mapName: str | None
  fileName: str | None
  pageNo: int
  pageSize: int
  totalPage: int
  nodeType: str | None
  searchText: str | None
  sortOption: str | None
  sortDirection: str | None
  def __init__(
    self,
    id: str | None = ...,
    mapName: str | None = ...,
    fileName: str | None = ...,
    pageNo: int = ...,
    pageSize: int = ...,
    totalPage: int = ...,
    nodeType: str | None = ...,
    searchText: str | None = ...,
    sortOption: str | None = ...,
    sortDirection: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Get_Map_TopologyT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Get_Map_TopologyT: ...
  @classmethod
  def InitFromObj(cls, requestGetMapTopology: Request_Get_Map_Topology) -> Request_Get_Map_TopologyT: ...
  def _UnPack(self, requestGetMapTopology: Request_Get_Map_Topology) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Get_Map_TopologyStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Get_Map_TopologyAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Get_Map_TopologyAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Request_Get_Map_TopologyAddFileName(builder: flatbuffers.Builder, fileName: uoffset) -> None: ...
def Request_Get_Map_TopologyAddPageNo(builder: flatbuffers.Builder, pageNo: int) -> None: ...
def Request_Get_Map_TopologyAddPageSize(builder: flatbuffers.Builder, pageSize: int) -> None: ...
def Request_Get_Map_TopologyAddTotalPage(builder: flatbuffers.Builder, totalPage: int) -> None: ...
def Request_Get_Map_TopologyAddNodeType(builder: flatbuffers.Builder, nodeType: uoffset) -> None: ...
def Request_Get_Map_TopologyAddSearchText(builder: flatbuffers.Builder, searchText: uoffset) -> None: ...
def Request_Get_Map_TopologyAddSortOption(builder: flatbuffers.Builder, sortOption: uoffset) -> None: ...
def Request_Get_Map_TopologyAddSortDirection(builder: flatbuffers.Builder, sortDirection: uoffset) -> None: ...
def Request_Get_Map_TopologyEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

