from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_Stop(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_Stop: ...
  @classmethod
  def GetRootAsRequest_Move_Stop(cls, buf: bytes, offset: int) -> Request_Move_Stop: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Move_StopT(object):
  id: str | None
  def __init__(
    self,
    id: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_StopT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_StopT: ...
  @classmethod
  def InitFromObj(cls, requestMoveStop: Request_Move_Stop) -> Request_Move_StopT: ...
  def _UnPack(self, requestMoveStop: Request_Move_Stop) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_StopStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_StopAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Move_StopEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

