from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Control_Motor import Request_Control_Motor

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Control_Motor(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Control_Motor: ...
  @classmethod
  def GetRootAsRequest_Control_Motor(cls, buf: bytes, offset: int) -> Request_Control_Motor: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Onoff(self) -> bool: ...
class Request_Control_MotorT(object):
  id: str | None
  onoff: bool
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Control_MotorT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Control_MotorT: ...
  @classmethod
  def InitFromObj(cls, requestControlMotor: Request_Control_Motor) -> Request_Control_MotorT: ...
  def _UnPack(self, requestControlMotor: Request_Control_Motor) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Control_MotorStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Control_MotorAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Control_MotorAddOnoff(builder: flatbuffers.Builder, onoff: bool) -> None: ...
def Request_Control_MotorEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

