# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Move_Pause(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Move_Pause()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Move_Pause(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Move_Pause
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Move_Pause
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Request_Move_PauseStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    Request_Move_PauseStart(builder)

def Request_Move_PauseAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Request_Move_PauseAddId(builder, id)

def Request_Move_PauseEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Move_PauseEnd(builder)


class Request_Move_PauseT(object):

    # Request_Move_PauseT
    def __init__(self):
        self.id = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestMovePause = Request_Move_Pause()
        requestMovePause.Init(buf, pos)
        return cls.InitFromObj(requestMovePause)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestMovePause):
        x = Request_Move_PauseT()
        x._UnPack(requestMovePause)
        return x

    # Request_Move_PauseT
    def _UnPack(self, requestMovePause):
        if requestMovePause is None:
            return
        self.id = requestMovePause.Id()

    # Request_Move_PauseT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        Request_Move_PauseStart(builder)
        if self.id is not None:
            Request_Move_PauseAddId(builder, id)
        requestMovePause = Request_Move_PauseEnd(builder)
        return requestMovePause
