from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Move_Goal import Request_Move_Goal

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_Goal(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_Goal: ...
  @classmethod
  def GetRootAsRequest_Move_Goal(cls, buf: bytes, offset: int) -> Request_Move_Goal: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def GoalId(self) -> str | None: ...
  def Method(self) -> str | None: ...
  def Preset(self) -> int: ...
class Request_Move_GoalT(object):
  id: str | None
  goalId: str | None
  method: str | None
  preset: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_GoalT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_GoalT: ...
  @classmethod
  def InitFromObj(cls, requestMoveGoal: Request_Move_Goal) -> Request_Move_GoalT: ...
  def _UnPack(self, requestMoveGoal: Request_Move_Goal) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_GoalStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_GoalAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Move_GoalAddGoalId(builder: flatbuffers.Builder, goalId: uoffset) -> None: ...
def Request_Move_GoalAddMethod(builder: flatbuffers.Builder, method: uoffset) -> None: ...
def Request_Move_GoalAddPreset(builder: flatbuffers.Builder, preset: int) -> None: ...
def Request_Move_GoalEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

