from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Mapping_Start import Request_Mapping_Start

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Mapping_Start(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Mapping_Start: ...
  @classmethod
  def GetRootAsRequest_Mapping_Start(cls, buf: bytes, offset: int) -> Request_Mapping_Start: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Mapping_StartT(object):
  id: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Mapping_StartT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Mapping_StartT: ...
  @classmethod
  def InitFromObj(cls, requestMappingStart: Request_Mapping_Start) -> Request_Mapping_StartT: ...
  def _UnPack(self, requestMappingStart: Request_Mapping_Start) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Mapping_StartStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Mapping_StartAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Mapping_StartEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

