from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Control_Frequency import Request_Control_Frequency

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Control_Frequency(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Control_Frequency: ...
  @classmethod
  def GetRootAsRequest_Control_Frequency(cls, buf: bytes, offset: int) -> Request_Control_Frequency: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Target(self) -> str | None: ...
  def Onoff(self) -> bool: ...
  def Frequency(self) -> int: ...
class Request_Control_FrequencyT(object):
  id: str | None
  target: str | None
  onoff: bool
  frequency: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Control_FrequencyT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Control_FrequencyT: ...
  @classmethod
  def InitFromObj(cls, requestControlFrequency: Request_Control_Frequency) -> Request_Control_FrequencyT: ...
  def _UnPack(self, requestControlFrequency: Request_Control_Frequency) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Control_FrequencyStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Control_FrequencyAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Control_FrequencyAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Request_Control_FrequencyAddOnoff(builder: flatbuffers.Builder, onoff: bool) -> None: ...
def Request_Control_FrequencyAddFrequency(builder: flatbuffers.Builder, frequency: int) -> None: ...
def Request_Control_FrequencyEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

