from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Localization(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Localization: ...
  @classmethod
  def GetRootAsRequest_Localization(cls, buf: bytes, offset: int) -> Request_Localization: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def X(self) -> float: ...
  def Y(self) -> float: ...
  def Z(self) -> float: ...
  def Rz(self) -> float: ...
class Request_LocalizationT(object):
  id: str | None
  command: str | None
  x: float
  y: float
  z: float
  rz: float
  def __init__(
    self,
    id: str | None = ...,
    command: str | None = ...,
    x: float = ...,
    y: float = ...,
    z: float = ...,
    rz: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_LocalizationT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_LocalizationT: ...
  @classmethod
  def InitFromObj(cls, requestLocalization: Request_Localization) -> Request_LocalizationT: ...
  def _UnPack(self, requestLocalization: Request_Localization) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_LocalizationStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_LocalizationAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_LocalizationAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Request_LocalizationAddX(builder: flatbuffers.Builder, x: float) -> None: ...
def Request_LocalizationAddY(builder: flatbuffers.Builder, y: float) -> None: ...
def Request_LocalizationAddZ(builder: flatbuffers.Builder, z: float) -> None: ...
def Request_LocalizationAddRz(builder: flatbuffers.Builder, rz: float) -> None: ...
def Request_LocalizationEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

