# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Set_Map_Cloud(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Set_Map_Cloud()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Set_Map_Cloud(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Set_Map_Cloud
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Set_Map_Cloud
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Set_Map_Cloud
    def MapName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Set_Map_Cloud
    def FileName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Set_Map_Cloud
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_Map_Cloud
    def Data(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Request_Set_Map_Cloud
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # Request_Set_Map_Cloud
    def DataLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Request_Set_Map_Cloud
    def DataIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def Request_Set_Map_CloudStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    Request_Set_Map_CloudStart(builder)

def Request_Set_Map_CloudAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Request_Set_Map_CloudAddId(builder, id)

def Request_Set_Map_CloudAddMapName(builder: flatbuffers.Builder, mapName: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(mapName), 0)

def AddMapName(builder: flatbuffers.Builder, mapName: int):
    Request_Set_Map_CloudAddMapName(builder, mapName)

def Request_Set_Map_CloudAddFileName(builder: flatbuffers.Builder, fileName: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fileName), 0)

def AddFileName(builder: flatbuffers.Builder, fileName: int):
    Request_Set_Map_CloudAddFileName(builder, fileName)

def Request_Set_Map_CloudAddSize(builder: flatbuffers.Builder, size: int):
    builder.PrependInt32Slot(3, size, 0)

def AddSize(builder: flatbuffers.Builder, size: int):
    Request_Set_Map_CloudAddSize(builder, size)

def Request_Set_Map_CloudAddData(builder: flatbuffers.Builder, data: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder: flatbuffers.Builder, data: int):
    Request_Set_Map_CloudAddData(builder, data)

def Request_Set_Map_CloudStartDataVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartDataVector(builder, numElems: int) -> int:
    return Request_Set_Map_CloudStartDataVector(builder, numElems)

def Request_Set_Map_CloudEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Set_Map_CloudEnd(builder)

try:
    from typing import List
except:
    pass

class Request_Set_Map_CloudT(object):

    # Request_Set_Map_CloudT
    def __init__(self):
        self.id = None  # type: str
        self.mapName = None  # type: str
        self.fileName = None  # type: str
        self.size = 0  # type: int
        self.data = None  # type: List[float]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestSetMapCloud = Request_Set_Map_Cloud()
        requestSetMapCloud.Init(buf, pos)
        return cls.InitFromObj(requestSetMapCloud)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestSetMapCloud):
        x = Request_Set_Map_CloudT()
        x._UnPack(requestSetMapCloud)
        return x

    # Request_Set_Map_CloudT
    def _UnPack(self, requestSetMapCloud):
        if requestSetMapCloud is None:
            return
        self.id = requestSetMapCloud.Id()
        self.mapName = requestSetMapCloud.MapName()
        self.fileName = requestSetMapCloud.FileName()
        self.size = requestSetMapCloud.Size()
        if not requestSetMapCloud.DataIsNone():
            if np is None:
                self.data = []
                for i in range(requestSetMapCloud.DataLength()):
                    self.data.append(requestSetMapCloud.Data(i))
            else:
                self.data = requestSetMapCloud.DataAsNumpy()

    # Request_Set_Map_CloudT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.mapName is not None:
            mapName = builder.CreateString(self.mapName)
        if self.fileName is not None:
            fileName = builder.CreateString(self.fileName)
        if self.data is not None:
            if np is not None and type(self.data) is np.ndarray:
                data = builder.CreateNumpyVector(self.data)
            else:
                Request_Set_Map_CloudStartDataVector(builder, len(self.data))
                for i in reversed(range(len(self.data))):
                    builder.PrependFloat64(self.data[i])
                data = builder.EndVector()
        Request_Set_Map_CloudStart(builder)
        if self.id is not None:
            Request_Set_Map_CloudAddId(builder, id)
        if self.mapName is not None:
            Request_Set_Map_CloudAddMapName(builder, mapName)
        if self.fileName is not None:
            Request_Set_Map_CloudAddFileName(builder, fileName)
        Request_Set_Map_CloudAddSize(builder, self.size)
        if self.data is not None:
            Request_Set_Map_CloudAddData(builder, data)
        requestSetMapCloud = Request_Set_Map_CloudEnd(builder)
        return requestSetMapCloud
