from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Map_Load(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Map_Load: ...
  @classmethod
  def GetRootAsRequest_Map_Load(cls, buf: bytes, offset: int) -> Request_Map_Load: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
class Request_Map_LoadT(object):
  id: str | None
  mapName: str | None
  def __init__(
    self,
    id: str | None = ...,
    mapName: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Map_LoadT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Map_LoadT: ...
  @classmethod
  def InitFromObj(cls, requestMapLoad: Request_Map_Load) -> Request_Map_LoadT: ...
  def _UnPack(self, requestMapLoad: Request_Map_Load) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Map_LoadStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Map_LoadAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Map_LoadAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Request_Map_LoadEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

