from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Localization_Start(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Localization_Start: ...
  @classmethod
  def GetRootAsRequest_Localization_Start(cls, buf: bytes, offset: int) -> Request_Localization_Start: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Localization_StartT(object):
  id: str | None
  def __init__(
    self,
    id: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Localization_StartT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Localization_StartT: ...
  @classmethod
  def InitFromObj(cls, requestLocalizationStart: Request_Localization_Start) -> Request_Localization_StartT: ...
  def _UnPack(self, requestLocalizationStart: Request_Localization_Start) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Localization_StartStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Localization_StartAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Localization_StartEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

