# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Localization(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Localization()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Localization(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Localization
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Localization
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Localization
    def Command(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Localization
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Localization
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Localization
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Localization
    def Rz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Request_LocalizationStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    Request_LocalizationStart(builder)

def Request_LocalizationAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Request_LocalizationAddId(builder, id)

def Request_LocalizationAddCommand(builder: flatbuffers.Builder, command: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(command), 0)

def AddCommand(builder: flatbuffers.Builder, command: int):
    Request_LocalizationAddCommand(builder, command)

def Request_LocalizationAddX(builder: flatbuffers.Builder, x: float):
    builder.PrependFloat32Slot(2, x, 0.0)

def AddX(builder: flatbuffers.Builder, x: float):
    Request_LocalizationAddX(builder, x)

def Request_LocalizationAddY(builder: flatbuffers.Builder, y: float):
    builder.PrependFloat32Slot(3, y, 0.0)

def AddY(builder: flatbuffers.Builder, y: float):
    Request_LocalizationAddY(builder, y)

def Request_LocalizationAddZ(builder: flatbuffers.Builder, z: float):
    builder.PrependFloat32Slot(4, z, 0.0)

def AddZ(builder: flatbuffers.Builder, z: float):
    Request_LocalizationAddZ(builder, z)

def Request_LocalizationAddRz(builder: flatbuffers.Builder, rz: float):
    builder.PrependFloat32Slot(5, rz, 0.0)

def AddRz(builder: flatbuffers.Builder, rz: float):
    Request_LocalizationAddRz(builder, rz)

def Request_LocalizationEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_LocalizationEnd(builder)


class Request_LocalizationT(object):

    # Request_LocalizationT
    def __init__(self):
        self.id = None  # type: str
        self.command = None  # type: str
        self.x = 0.0  # type: float
        self.y = 0.0  # type: float
        self.z = 0.0  # type: float
        self.rz = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestLocalization = Request_Localization()
        requestLocalization.Init(buf, pos)
        return cls.InitFromObj(requestLocalization)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestLocalization):
        x = Request_LocalizationT()
        x._UnPack(requestLocalization)
        return x

    # Request_LocalizationT
    def _UnPack(self, requestLocalization):
        if requestLocalization is None:
            return
        self.id = requestLocalization.Id()
        self.command = requestLocalization.Command()
        self.x = requestLocalization.X()
        self.y = requestLocalization.Y()
        self.z = requestLocalization.Z()
        self.rz = requestLocalization.Rz()

    # Request_LocalizationT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.command is not None:
            command = builder.CreateString(self.command)
        Request_LocalizationStart(builder)
        if self.id is not None:
            Request_LocalizationAddId(builder, id)
        if self.command is not None:
            Request_LocalizationAddCommand(builder, command)
        Request_LocalizationAddX(builder, self.x)
        Request_LocalizationAddY(builder, self.y)
        Request_LocalizationAddZ(builder, self.z)
        Request_LocalizationAddRz(builder, self.rz)
        requestLocalization = Request_LocalizationEnd(builder)
        return requestLocalization
