from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Control_LED(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Control_LED: ...
  @classmethod
  def GetRootAsRequest_Control_LED(cls, buf: bytes, offset: int) -> Request_Control_LED: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Onoff(self) -> bool: ...
  def Color(self) -> str | None: ...
class Request_Control_LEDT(object):
  id: str | None
  onoff: bool
  color: str | None
  def __init__(
    self,
    id: str | None = ...,
    onoff: bool = ...,
    color: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Control_LEDT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Control_LEDT: ...
  @classmethod
  def InitFromObj(cls, requestControlLed: Request_Control_LED) -> Request_Control_LEDT: ...
  def _UnPack(self, requestControlLed: Request_Control_LED) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Control_LEDStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Control_LEDAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Control_LEDAddOnoff(builder: flatbuffers.Builder, onoff: bool) -> None: ...
def Request_Control_LEDAddColor(builder: flatbuffers.Builder, color: uoffset) -> None: ...
def Request_Control_LEDEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

