from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Dock(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Dock: ...
  @classmethod
  def GetRootAsRequest_Dock(cls, buf: bytes, offset: int) -> Request_Dock: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
class Request_DockT(object):
  id: str | None
  command: str | None
  def __init__(
    self,
    id: str | None = ...,
    command: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_DockT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_DockT: ...
  @classmethod
  def InitFromObj(cls, requestDock: Request_Dock) -> Request_DockT: ...
  def _UnPack(self, requestDock: Request_Dock) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_DockStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_DockAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_DockAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Request_DockEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

