from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Localization_Stop(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Localization_Stop: ...
  @classmethod
  def GetRootAsRequest_Localization_Stop(cls, buf: bytes, offset: int) -> Request_Localization_Stop: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Localization_StopT(object):
  id: str | None
  def __init__(
    self,
    id: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Localization_StopT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Localization_StopT: ...
  @classmethod
  def InitFromObj(cls, requestLocalizationStop: Request_Localization_Stop) -> Request_Localization_StopT: ...
  def _UnPack(self, requestLocalizationStop: Request_Localization_Stop) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Localization_StopStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Localization_StopAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Localization_StopEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

