from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Map_File(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Map_File: ...
  @classmethod
  def GetRootAsRequest_Map_File(cls, buf: bytes, offset: int) -> Request_Map_File: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def FileName(self) -> str | None: ...
class Request_Map_FileT(object):
  id: str | None
  mapName: str | None
  fileName: str | None
  def __init__(
    self,
    id: str | None = ...,
    mapName: str | None = ...,
    fileName: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Map_FileT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Map_FileT: ...
  @classmethod
  def InitFromObj(cls, requestMapFile: Request_Map_File) -> Request_Map_FileT: ...
  def _UnPack(self, requestMapFile: Request_Map_File) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Map_FileStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Map_FileAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Map_FileAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Request_Map_FileAddFileName(builder: flatbuffers.Builder, fileName: uoffset) -> None: ...
def Request_Map_FileEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

