from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_Rotate(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_Rotate: ...
  @classmethod
  def GetRootAsRequest_Move_Rotate(cls, buf: bytes, offset: int) -> Request_Move_Rotate: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Target(self) -> float: ...
  def Speed(self) -> float: ...
class Request_Move_RotateT(object):
  id: str | None
  target: float
  speed: float
  def __init__(
    self,
    id: str | None = ...,
    target: float = ...,
    speed: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_RotateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_RotateT: ...
  @classmethod
  def InitFromObj(cls, requestMoveRotate: Request_Move_Rotate) -> Request_Move_RotateT: ...
  def _UnPack(self, requestMoveRotate: Request_Move_Rotate) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_RotateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_RotateAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Move_RotateAddTarget(builder: flatbuffers.Builder, target: float) -> None: ...
def Request_Move_RotateAddSpeed(builder: flatbuffers.Builder, speed: float) -> None: ...
def Request_Move_RotateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

