from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Move_XLinear import Request_Move_XLinear

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_XLinear(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_XLinear: ...
  @classmethod
  def GetRootAsRequest_Move_XLinear(cls, buf: bytes, offset: int) -> Request_Move_XLinear: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Target(self) -> float: ...
  def Speed(self) -> float: ...
class Request_Move_XLinearT(object):
  id: str | None
  target: float
  speed: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_XLinearT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_XLinearT: ...
  @classmethod
  def InitFromObj(cls, requestMoveXlinear: Request_Move_XLinear) -> Request_Move_XLinearT: ...
  def _UnPack(self, requestMoveXlinear: Request_Move_XLinear) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_XLinearStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_XLinearAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Move_XLinearAddTarget(builder: flatbuffers.Builder, target: float) -> None: ...
def Request_Move_XLinearAddSpeed(builder: flatbuffers.Builder, speed: float) -> None: ...
def Request_Move_XLinearEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

