# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from rb_flat_buffers.SLAMNAV.Setting_Param import Setting_Param, Setting_ParamT
from typing import Optional
np = import_numpy()

class Request_Set_Pdu_Param(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Set_Pdu_Param()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Set_Pdu_Param(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Set_Pdu_Param
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Set_Pdu_Param
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Set_Pdu_Param
    def Params(self, j: int) -> Optional[Setting_Param]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Setting_Param()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Request_Set_Pdu_Param
    def ParamsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Request_Set_Pdu_Param
    def ParamsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def Request_Set_Pdu_ParamStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    Request_Set_Pdu_ParamStart(builder)

def Request_Set_Pdu_ParamAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Request_Set_Pdu_ParamAddId(builder, id)

def Request_Set_Pdu_ParamAddParams(builder: flatbuffers.Builder, params: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(params), 0)

def AddParams(builder: flatbuffers.Builder, params: int):
    Request_Set_Pdu_ParamAddParams(builder, params)

def Request_Set_Pdu_ParamStartParamsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartParamsVector(builder, numElems: int) -> int:
    return Request_Set_Pdu_ParamStartParamsVector(builder, numElems)

def Request_Set_Pdu_ParamEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Set_Pdu_ParamEnd(builder)

try:
    from typing import List
except:
    pass

class Request_Set_Pdu_ParamT(object):

    # Request_Set_Pdu_ParamT
    def __init__(
        self,
        id = None,
        params = None,
    ):
        self.id = id  # type: Optional[str]
        self.params = params  # type: Optional[List[Setting_ParamT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestSetPduParam = Request_Set_Pdu_Param()
        requestSetPduParam.Init(buf, pos)
        return cls.InitFromObj(requestSetPduParam)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestSetPduParam):
        x = Request_Set_Pdu_ParamT()
        x._UnPack(requestSetPduParam)
        return x

    # Request_Set_Pdu_ParamT
    def _UnPack(self, requestSetPduParam):
        if requestSetPduParam is None:
            return
        self.id = requestSetPduParam.Id()
        if not requestSetPduParam.ParamsIsNone():
            self.params = []
            for i in range(requestSetPduParam.ParamsLength()):
                if requestSetPduParam.Params(i) is None:
                    self.params.append(None)
                else:
                    setting_Param_ = Setting_ParamT.InitFromObj(requestSetPduParam.Params(i))
                    self.params.append(setting_Param_)

    # Request_Set_Pdu_ParamT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.params is not None:
            paramslist = []
            for i in range(len(self.params)):
                paramslist.append(self.params[i].Pack(builder))
            Request_Set_Pdu_ParamStartParamsVector(builder, len(self.params))
            for i in reversed(range(len(self.params))):
                builder.PrependUOffsetTRelative(paramslist[i])
            params = builder.EndVector()
        Request_Set_Pdu_ParamStart(builder)
        if self.id is not None:
            Request_Set_Pdu_ParamAddId(builder, id)
        if self.params is not None:
            Request_Set_Pdu_ParamAddParams(builder, params)
        requestSetPduParam = Request_Set_Pdu_ParamEnd(builder)
        return requestSetPduParam
