from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Update(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Update: ...
  @classmethod
  def GetRootAsRequest_Update(cls, buf: bytes, offset: int) -> Request_Update: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Version(self) -> str | None: ...
class Request_UpdateT(object):
  version: str | None
  def __init__(
    self,
    version: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_UpdateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_UpdateT: ...
  @classmethod
  def InitFromObj(cls, requestUpdate: Request_Update) -> Request_UpdateT: ...
  def _UnPack(self, requestUpdate: Request_Update) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_UpdateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_UpdateAddVersion(builder: flatbuffers.Builder, version: uoffset) -> None: ...
def Request_UpdateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

