from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Safety_Io import Request_Safety_Io

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Safety_Io(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Safety_Io: ...
  @classmethod
  def GetRootAsRequest_Safety_Io(cls, buf: bytes, offset: int) -> Request_Safety_Io: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def Mcu0Dio(self, i: int) -> typing.List[bool]: ...
  def Mcu0DioAsNumpy(self) -> np.ndarray: ...
  def Mcu0DioLength(self) -> int: ...
  def Mcu0DioIsNone(self) -> bool: ...
  def Mcu1Dio(self, i: int) -> typing.List[bool]: ...
  def Mcu1DioAsNumpy(self) -> np.ndarray: ...
  def Mcu1DioLength(self) -> int: ...
  def Mcu1DioIsNone(self) -> bool: ...
class Request_Safety_IoT(object):
  id: str | None
  command: str | None
  mcu0Dio: typing.List[bool]
  mcu1Dio: typing.List[bool]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Safety_IoT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Safety_IoT: ...
  @classmethod
  def InitFromObj(cls, requestSafetyIo: Request_Safety_Io) -> Request_Safety_IoT: ...
  def _UnPack(self, requestSafetyIo: Request_Safety_Io) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Safety_IoStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Safety_IoAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Safety_IoAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Request_Safety_IoAddMcu0Dio(builder: flatbuffers.Builder, mcu0Dio: uoffset) -> None: ...
def Request_Safety_IoStartMcu0DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMcu0DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Request_Safety_IoAddMcu1Dio(builder: flatbuffers.Builder, mcu1Dio: uoffset) -> None: ...
def Request_Safety_IoStartMcu1DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMcu1DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Request_Safety_IoEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

