from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Obs_Box(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Obs_Box: ...
  @classmethod
  def GetRootAsRequest_Obs_Box(cls, buf: bytes, offset: int) -> Request_Obs_Box: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def MinZ(self) -> float: ...
  def MaxZ(self) -> float: ...
  def MapRange(self) -> float: ...
class Request_Obs_BoxT(object):
  id: str | None
  command: str | None
  minZ: float
  maxZ: float
  mapRange: float
  def __init__(
    self,
    id: str | None = ...,
    command: str | None = ...,
    minZ: float = ...,
    maxZ: float = ...,
    mapRange: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Obs_BoxT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Obs_BoxT: ...
  @classmethod
  def InitFromObj(cls, requestObsBox: Request_Obs_Box) -> Request_Obs_BoxT: ...
  def _UnPack(self, requestObsBox: Request_Obs_Box) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Obs_BoxStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Obs_BoxAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Obs_BoxAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Request_Obs_BoxAddMinZ(builder: flatbuffers.Builder, minZ: float) -> None: ...
def Request_Obs_BoxAddMaxZ(builder: flatbuffers.Builder, maxZ: float) -> None: ...
def Request_Obs_BoxAddMapRange(builder: flatbuffers.Builder, mapRange: float) -> None: ...
def Request_Obs_BoxEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

