from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Get_Pdu_Param import Request_Get_Pdu_Param

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Get_Pdu_Param(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Get_Pdu_Param: ...
  @classmethod
  def GetRootAsRequest_Get_Pdu_Param(cls, buf: bytes, offset: int) -> Request_Get_Pdu_Param: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Get_Pdu_ParamT(object):
  id: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Get_Pdu_ParamT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Get_Pdu_ParamT: ...
  @classmethod
  def InitFromObj(cls, requestGetPduParam: Request_Get_Pdu_Param) -> Request_Get_Pdu_ParamT: ...
  def _UnPack(self, requestGetPduParam: Request_Get_Pdu_Param) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Get_Pdu_ParamStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Get_Pdu_ParamAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Get_Pdu_ParamEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

