from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Reset_Safety_Flag import Request_Reset_Safety_Flag

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Reset_Safety_Flag(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Reset_Safety_Flag: ...
  @classmethod
  def GetRootAsRequest_Reset_Safety_Flag(cls, buf: bytes, offset: int) -> Request_Reset_Safety_Flag: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def ResetFlag(self) -> str | None: ...
class Request_Reset_Safety_FlagT(object):
  id: str | None
  resetFlag: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Reset_Safety_FlagT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Reset_Safety_FlagT: ...
  @classmethod
  def InitFromObj(cls, requestResetSafetyFlag: Request_Reset_Safety_Flag) -> Request_Reset_Safety_FlagT: ...
  def _UnPack(self, requestResetSafetyFlag: Request_Reset_Safety_Flag) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Reset_Safety_FlagStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Reset_Safety_FlagAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Reset_Safety_FlagAddResetFlag(builder: flatbuffers.Builder, resetFlag: uoffset) -> None: ...
def Request_Reset_Safety_FlagEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

