# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Localization_SemiAutoInit(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Localization_SemiAutoInit()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Localization_SemiAutoInit(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Localization_SemiAutoInit
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Localization_SemiAutoInit
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Request_Localization_SemiAutoInitStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    Request_Localization_SemiAutoInitStart(builder)

def Request_Localization_SemiAutoInitAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Request_Localization_SemiAutoInitAddId(builder, id)

def Request_Localization_SemiAutoInitEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Localization_SemiAutoInitEnd(builder)


class Request_Localization_SemiAutoInitT(object):

    # Request_Localization_SemiAutoInitT
    def __init__(
        self,
        id = None,
    ):
        self.id = id  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestLocalizationSemiAutoInit = Request_Localization_SemiAutoInit()
        requestLocalizationSemiAutoInit.Init(buf, pos)
        return cls.InitFromObj(requestLocalizationSemiAutoInit)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestLocalizationSemiAutoInit):
        x = Request_Localization_SemiAutoInitT()
        x._UnPack(requestLocalizationSemiAutoInit)
        return x

    # Request_Localization_SemiAutoInitT
    def _UnPack(self, requestLocalizationSemiAutoInit):
        if requestLocalizationSemiAutoInit is None:
            return
        self.id = requestLocalizationSemiAutoInit.Id()

    # Request_Localization_SemiAutoInitT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        Request_Localization_SemiAutoInitStart(builder)
        if self.id is not None:
            Request_Localization_SemiAutoInitAddId(builder, id)
        requestLocalizationSemiAutoInit = Request_Localization_SemiAutoInitEnd(builder)
        return requestLocalizationSemiAutoInit
