from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Mapping_Stop import Request_Mapping_Stop

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Mapping_Stop(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Mapping_Stop: ...
  @classmethod
  def GetRootAsRequest_Mapping_Stop(cls, buf: bytes, offset: int) -> Request_Mapping_Stop: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Mapping_StopT(object):
  id: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Mapping_StopT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Mapping_StopT: ...
  @classmethod
  def InitFromObj(cls, requestMappingStop: Request_Mapping_Stop) -> Request_Mapping_StopT: ...
  def _UnPack(self, requestMappingStop: Request_Mapping_Stop) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Mapping_StopStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Mapping_StopAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Mapping_StopEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

