from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Get_Map_Cloud import Request_Get_Map_Cloud

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Get_Map_Cloud(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Get_Map_Cloud: ...
  @classmethod
  def GetRootAsRequest_Get_Map_Cloud(cls, buf: bytes, offset: int) -> Request_Get_Map_Cloud: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def FileName(self) -> str | None: ...
class Request_Get_Map_CloudT(object):
  id: str | None
  mapName: str | None
  fileName: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Get_Map_CloudT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Get_Map_CloudT: ...
  @classmethod
  def InitFromObj(cls, requestGetMapCloud: Request_Get_Map_Cloud) -> Request_Get_Map_CloudT: ...
  def _UnPack(self, requestGetMapCloud: Request_Get_Map_Cloud) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Get_Map_CloudStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Get_Map_CloudAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Get_Map_CloudAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Request_Get_Map_CloudAddFileName(builder: flatbuffers.Builder, fileName: uoffset) -> None: ...
def Request_Get_Map_CloudEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

