from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Mapping_Save import Request_Mapping_Save

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Mapping_Save(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Mapping_Save: ...
  @classmethod
  def GetRootAsRequest_Mapping_Save(cls, buf: bytes, offset: int) -> Request_Mapping_Save: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
class Request_Mapping_SaveT(object):
  id: str | None
  mapName: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Mapping_SaveT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Mapping_SaveT: ...
  @classmethod
  def InitFromObj(cls, requestMappingSave: Request_Mapping_Save) -> Request_Mapping_SaveT: ...
  def _UnPack(self, requestMappingSave: Request_Mapping_Save) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Mapping_SaveStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Mapping_SaveAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Mapping_SaveAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Request_Mapping_SaveEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

