# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Map_Topology(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Map_Topology()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Map_Topology(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Map_Topology
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Map_Topology
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Map_Topology
    def MapName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Map_Topology
    def PageNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Map_Topology
    def PageSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Map_Topology
    def TotalPage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Map_Topology
    def NodeType(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Map_Topology
    def SearchText(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Map_Topology
    def SortOption(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Map_Topology
    def SortDirection(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Request_Map_TopologyStart(builder: flatbuffers.Builder):
    builder.StartObject(9)

def Start(builder: flatbuffers.Builder):
    Request_Map_TopologyStart(builder)

def Request_Map_TopologyAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Request_Map_TopologyAddId(builder, id)

def Request_Map_TopologyAddMapName(builder: flatbuffers.Builder, mapName: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(mapName), 0)

def AddMapName(builder: flatbuffers.Builder, mapName: int):
    Request_Map_TopologyAddMapName(builder, mapName)

def Request_Map_TopologyAddPageNo(builder: flatbuffers.Builder, pageNo: int):
    builder.PrependInt32Slot(2, pageNo, 0)

def AddPageNo(builder: flatbuffers.Builder, pageNo: int):
    Request_Map_TopologyAddPageNo(builder, pageNo)

def Request_Map_TopologyAddPageSize(builder: flatbuffers.Builder, pageSize: int):
    builder.PrependInt32Slot(3, pageSize, 0)

def AddPageSize(builder: flatbuffers.Builder, pageSize: int):
    Request_Map_TopologyAddPageSize(builder, pageSize)

def Request_Map_TopologyAddTotalPage(builder: flatbuffers.Builder, totalPage: int):
    builder.PrependInt32Slot(4, totalPage, 0)

def AddTotalPage(builder: flatbuffers.Builder, totalPage: int):
    Request_Map_TopologyAddTotalPage(builder, totalPage)

def Request_Map_TopologyAddNodeType(builder: flatbuffers.Builder, nodeType: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(nodeType), 0)

def AddNodeType(builder: flatbuffers.Builder, nodeType: int):
    Request_Map_TopologyAddNodeType(builder, nodeType)

def Request_Map_TopologyAddSearchText(builder: flatbuffers.Builder, searchText: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(searchText), 0)

def AddSearchText(builder: flatbuffers.Builder, searchText: int):
    Request_Map_TopologyAddSearchText(builder, searchText)

def Request_Map_TopologyAddSortOption(builder: flatbuffers.Builder, sortOption: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(sortOption), 0)

def AddSortOption(builder: flatbuffers.Builder, sortOption: int):
    Request_Map_TopologyAddSortOption(builder, sortOption)

def Request_Map_TopologyAddSortDirection(builder: flatbuffers.Builder, sortDirection: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(sortDirection), 0)

def AddSortDirection(builder: flatbuffers.Builder, sortDirection: int):
    Request_Map_TopologyAddSortDirection(builder, sortDirection)

def Request_Map_TopologyEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Map_TopologyEnd(builder)


class Request_Map_TopologyT(object):

    # Request_Map_TopologyT
    def __init__(self):
        self.id = None  # type: str
        self.mapName = None  # type: str
        self.pageNo = 0  # type: int
        self.pageSize = 0  # type: int
        self.totalPage = 0  # type: int
        self.nodeType = None  # type: str
        self.searchText = None  # type: str
        self.sortOption = None  # type: str
        self.sortDirection = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestMapTopology = Request_Map_Topology()
        requestMapTopology.Init(buf, pos)
        return cls.InitFromObj(requestMapTopology)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestMapTopology):
        x = Request_Map_TopologyT()
        x._UnPack(requestMapTopology)
        return x

    # Request_Map_TopologyT
    def _UnPack(self, requestMapTopology):
        if requestMapTopology is None:
            return
        self.id = requestMapTopology.Id()
        self.mapName = requestMapTopology.MapName()
        self.pageNo = requestMapTopology.PageNo()
        self.pageSize = requestMapTopology.PageSize()
        self.totalPage = requestMapTopology.TotalPage()
        self.nodeType = requestMapTopology.NodeType()
        self.searchText = requestMapTopology.SearchText()
        self.sortOption = requestMapTopology.SortOption()
        self.sortDirection = requestMapTopology.SortDirection()

    # Request_Map_TopologyT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.mapName is not None:
            mapName = builder.CreateString(self.mapName)
        if self.nodeType is not None:
            nodeType = builder.CreateString(self.nodeType)
        if self.searchText is not None:
            searchText = builder.CreateString(self.searchText)
        if self.sortOption is not None:
            sortOption = builder.CreateString(self.sortOption)
        if self.sortDirection is not None:
            sortDirection = builder.CreateString(self.sortDirection)
        Request_Map_TopologyStart(builder)
        if self.id is not None:
            Request_Map_TopologyAddId(builder, id)
        if self.mapName is not None:
            Request_Map_TopologyAddMapName(builder, mapName)
        Request_Map_TopologyAddPageNo(builder, self.pageNo)
        Request_Map_TopologyAddPageSize(builder, self.pageSize)
        Request_Map_TopologyAddTotalPage(builder, self.totalPage)
        if self.nodeType is not None:
            Request_Map_TopologyAddNodeType(builder, nodeType)
        if self.searchText is not None:
            Request_Map_TopologyAddSearchText(builder, searchText)
        if self.sortOption is not None:
            Request_Map_TopologyAddSortOption(builder, sortOption)
        if self.sortDirection is not None:
            Request_Map_TopologyAddSortDirection(builder, sortDirection)
        requestMapTopology = Request_Map_TopologyEnd(builder)
        return requestMapTopology
