from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Get_Sensor_Index import Request_Get_Sensor_Index

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Get_Sensor_Index(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Get_Sensor_Index: ...
  @classmethod
  def GetRootAsRequest_Get_Sensor_Index(cls, buf: bytes, offset: int) -> Request_Get_Sensor_Index: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Target(self) -> str | None: ...
class Request_Get_Sensor_IndexT(object):
  id: str | None
  target: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Get_Sensor_IndexT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Get_Sensor_IndexT: ...
  @classmethod
  def InitFromObj(cls, requestGetSensorIndex: Request_Get_Sensor_Index) -> Request_Get_Sensor_IndexT: ...
  def _UnPack(self, requestGetSensorIndex: Request_Get_Sensor_Index) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Get_Sensor_IndexStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Get_Sensor_IndexAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Get_Sensor_IndexAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Request_Get_Sensor_IndexEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

