from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Map_Tiles(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Map_Tiles: ...
  @classmethod
  def GetRootAsRequest_Map_Tiles(cls, buf: bytes, offset: int) -> Request_Map_Tiles: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_Map_TilesT(object):
  def __init__(
    self,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Map_TilesT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Map_TilesT: ...
  @classmethod
  def InitFromObj(cls, requestMapTiles: Request_Map_Tiles) -> Request_Map_TilesT: ...
  def _UnPack(self, requestMapTiles: Request_Map_Tiles) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Map_TilesStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Map_TilesEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

