from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_Pause(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_Pause: ...
  @classmethod
  def GetRootAsRequest_Move_Pause(cls, buf: bytes, offset: int) -> Request_Move_Pause: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
class Request_Move_PauseT(object):
  id: str | None
  def __init__(
    self,
    id: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_PauseT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_PauseT: ...
  @classmethod
  def InitFromObj(cls, requestMovePause: Request_Move_Pause) -> Request_Move_PauseT: ...
  def _UnPack(self, requestMovePause: Request_Move_Pause) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_PauseStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_PauseAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Move_PauseEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

