from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_Jog(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_Jog: ...
  @classmethod
  def GetRootAsRequest_Move_Jog(cls, buf: bytes, offset: int) -> Request_Move_Jog: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Vx(self) -> float: ...
  def Vy(self) -> float: ...
  def Wz(self) -> float: ...
class Request_Move_JogT(object):
  vx: float
  vy: float
  wz: float
  def __init__(
    self,
    vx: float = ...,
    vy: float = ...,
    wz: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_JogT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_JogT: ...
  @classmethod
  def InitFromObj(cls, requestMoveJog: Request_Move_Jog) -> Request_Move_JogT: ...
  def _UnPack(self, requestMoveJog: Request_Move_Jog) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_JogStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_JogAddVx(builder: flatbuffers.Builder, vx: float) -> None: ...
def Request_Move_JogAddVy(builder: flatbuffers.Builder, vy: float) -> None: ...
def Request_Move_JogAddWz(builder: flatbuffers.Builder, wz: float) -> None: ...
def Request_Move_JogEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

