from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Map_Topology import Request_Map_Topology

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Map_Topology(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Map_Topology: ...
  @classmethod
  def GetRootAsRequest_Map_Topology(cls, buf: bytes, offset: int) -> Request_Map_Topology: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def PageNo(self) -> int: ...
  def PageSize(self) -> int: ...
  def TotalPage(self) -> int: ...
  def NodeType(self) -> str | None: ...
  def SearchText(self) -> str | None: ...
  def SortOption(self) -> str | None: ...
  def SortDirection(self) -> str | None: ...
class Request_Map_TopologyT(object):
  id: str | None
  mapName: str | None
  pageNo: int
  pageSize: int
  totalPage: int
  nodeType: str | None
  searchText: str | None
  sortOption: str | None
  sortDirection: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Map_TopologyT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Map_TopologyT: ...
  @classmethod
  def InitFromObj(cls, requestMapTopology: Request_Map_Topology) -> Request_Map_TopologyT: ...
  def _UnPack(self, requestMapTopology: Request_Map_Topology) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Map_TopologyStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Map_TopologyAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Map_TopologyAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Request_Map_TopologyAddPageNo(builder: flatbuffers.Builder, pageNo: int) -> None: ...
def Request_Map_TopologyAddPageSize(builder: flatbuffers.Builder, pageSize: int) -> None: ...
def Request_Map_TopologyAddTotalPage(builder: flatbuffers.Builder, totalPage: int) -> None: ...
def Request_Map_TopologyAddNodeType(builder: flatbuffers.Builder, nodeType: uoffset) -> None: ...
def Request_Map_TopologyAddSearchText(builder: flatbuffers.Builder, searchText: uoffset) -> None: ...
def Request_Map_TopologyAddSortOption(builder: flatbuffers.Builder, sortOption: uoffset) -> None: ...
def Request_Map_TopologyAddSortDirection(builder: flatbuffers.Builder, sortDirection: uoffset) -> None: ...
def Request_Map_TopologyEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

