from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Request_Localization_Init import Request_Localization_Init

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Localization_Init(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Localization_Init: ...
  @classmethod
  def GetRootAsRequest_Localization_Init(cls, buf: bytes, offset: int) -> Request_Localization_Init: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def X(self) -> float: ...
  def Y(self) -> float: ...
  def Z(self) -> float: ...
  def Rz(self) -> float: ...
class Request_Localization_InitT(object):
  id: str | None
  command: str | None
  x: float
  y: float
  z: float
  rz: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Localization_InitT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Localization_InitT: ...
  @classmethod
  def InitFromObj(cls, requestLocalizationInit: Request_Localization_Init) -> Request_Localization_InitT: ...
  def _UnPack(self, requestLocalizationInit: Request_Localization_Init) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Localization_InitStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Localization_InitAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Request_Localization_InitAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Request_Localization_InitAddX(builder: flatbuffers.Builder, x: float) -> None: ...
def Request_Localization_InitAddY(builder: flatbuffers.Builder, y: float) -> None: ...
def Request_Localization_InitAddZ(builder: flatbuffers.Builder, z: float) -> None: ...
def Request_Localization_InitAddRz(builder: flatbuffers.Builder, rz: float) -> None: ...
def Request_Localization_InitEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

