from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Move_XLinear import Response_Move_XLinear

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Move_XLinear(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Move_XLinear: ...
  @classmethod
  def GetRootAsResponse_Move_XLinear(cls, buf: bytes, offset: int) -> Response_Move_XLinear: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Target(self) -> float: ...
  def Speed(self) -> float: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Move_XLinearT(object):
  id: str | None
  target: float
  speed: float
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Move_XLinearT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Move_XLinearT: ...
  @classmethod
  def InitFromObj(cls, responseMoveXlinear: Response_Move_XLinear) -> Response_Move_XLinearT: ...
  def _UnPack(self, responseMoveXlinear: Response_Move_XLinear) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Move_XLinearStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Move_XLinearAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Move_XLinearAddTarget(builder: flatbuffers.Builder, target: float) -> None: ...
def Response_Move_XLinearAddSpeed(builder: flatbuffers.Builder, speed: float) -> None: ...
def Response_Move_XLinearAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Move_XLinearAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Move_XLinearEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

