from __future__ import annotations

from rb_flat_buffers.IPC.Node import Node, NodeT
import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Node import Node, NodeT
from rb_flat_buffers.SLAMNAV.Response_Map_Topology import Response_Map_Topology

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Map_Topology(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Map_Topology: ...
  @classmethod
  def GetRootAsResponse_Map_Topology(cls, buf: bytes, offset: int) -> Response_Map_Topology: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def PageNo(self) -> int: ...
  def PageSize(self) -> int: ...
  def TotalPage(self) -> int: ...
  def NodeType(self) -> str | None: ...
  def SearchText(self) -> str | None: ...
  def SortOption(self) -> str | None: ...
  def SortDirection(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
  def Data(self, i: int) -> Node | None: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
class Response_Map_TopologyT(object):
  id: str | None
  mapName: str | None
  pageNo: int
  pageSize: int
  totalPage: int
  nodeType: str | None
  searchText: str | None
  sortOption: str | None
  sortDirection: str | None
  result: str | None
  message: str | None
  data: typing.List[NodeT]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Map_TopologyT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Map_TopologyT: ...
  @classmethod
  def InitFromObj(cls, responseMapTopology: Response_Map_Topology) -> Response_Map_TopologyT: ...
  def _UnPack(self, responseMapTopology: Response_Map_Topology) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Map_TopologyStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Map_TopologyAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Map_TopologyAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Response_Map_TopologyAddPageNo(builder: flatbuffers.Builder, pageNo: int) -> None: ...
def Response_Map_TopologyAddPageSize(builder: flatbuffers.Builder, pageSize: int) -> None: ...
def Response_Map_TopologyAddTotalPage(builder: flatbuffers.Builder, totalPage: int) -> None: ...
def Response_Map_TopologyAddNodeType(builder: flatbuffers.Builder, nodeType: uoffset) -> None: ...
def Response_Map_TopologyAddSearchText(builder: flatbuffers.Builder, searchText: uoffset) -> None: ...
def Response_Map_TopologyAddSortOption(builder: flatbuffers.Builder, sortOption: uoffset) -> None: ...
def Response_Map_TopologyAddSortDirection(builder: flatbuffers.Builder, sortDirection: uoffset) -> None: ...
def Response_Map_TopologyAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Map_TopologyAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Map_TopologyAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def Response_Map_TopologyStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Map_TopologyEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

