from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Localization_Start import Response_Localization_Start

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Localization_Start(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Localization_Start: ...
  @classmethod
  def GetRootAsResponse_Localization_Start(cls, buf: bytes, offset: int) -> Response_Localization_Start: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Localization_StartT(object):
  id: str | None
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Localization_StartT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Localization_StartT: ...
  @classmethod
  def InitFromObj(cls, responseLocalizationStart: Response_Localization_Start) -> Response_Localization_StartT: ...
  def _UnPack(self, responseLocalizationStart: Response_Localization_Start) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Localization_StartStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Localization_StartAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Localization_StartAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Localization_StartAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Localization_StartEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

