# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from rb_flat_buffers.SLAMNAV.Sensor_Info import Sensor_Info, Sensor_InfoT
from typing import Optional
np = import_numpy()

class Response_Set_Sensor_Index(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Set_Sensor_Index()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Set_Sensor_Index(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Set_Sensor_Index
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Set_Sensor_Index
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Set_Sensor_Index
    def Target(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Set_Sensor_Index
    def Index(self, j: int) -> Optional[Sensor_Info]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Sensor_Info()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Response_Set_Sensor_Index
    def IndexLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Response_Set_Sensor_Index
    def IndexIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Response_Set_Sensor_Index
    def Result(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Set_Sensor_Index
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Response_Set_Sensor_IndexStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    Response_Set_Sensor_IndexStart(builder)

def Response_Set_Sensor_IndexAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Response_Set_Sensor_IndexAddId(builder, id)

def Response_Set_Sensor_IndexAddTarget(builder: flatbuffers.Builder, target: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(target), 0)

def AddTarget(builder: flatbuffers.Builder, target: int):
    Response_Set_Sensor_IndexAddTarget(builder, target)

def Response_Set_Sensor_IndexAddIndex(builder: flatbuffers.Builder, index: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(index), 0)

def AddIndex(builder: flatbuffers.Builder, index: int):
    Response_Set_Sensor_IndexAddIndex(builder, index)

def Response_Set_Sensor_IndexStartIndexVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartIndexVector(builder, numElems: int) -> int:
    return Response_Set_Sensor_IndexStartIndexVector(builder, numElems)

def Response_Set_Sensor_IndexAddResult(builder: flatbuffers.Builder, result: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder: flatbuffers.Builder, result: int):
    Response_Set_Sensor_IndexAddResult(builder, result)

def Response_Set_Sensor_IndexAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    Response_Set_Sensor_IndexAddMessage(builder, message)

def Response_Set_Sensor_IndexEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Response_Set_Sensor_IndexEnd(builder)

try:
    from typing import List
except:
    pass

class Response_Set_Sensor_IndexT(object):

    # Response_Set_Sensor_IndexT
    def __init__(self):
        self.id = None  # type: str
        self.target = None  # type: str
        self.index = None  # type: List[Sensor_InfoT]
        self.result = None  # type: str
        self.message = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        responseSetSensorIndex = Response_Set_Sensor_Index()
        responseSetSensorIndex.Init(buf, pos)
        return cls.InitFromObj(responseSetSensorIndex)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, responseSetSensorIndex):
        x = Response_Set_Sensor_IndexT()
        x._UnPack(responseSetSensorIndex)
        return x

    # Response_Set_Sensor_IndexT
    def _UnPack(self, responseSetSensorIndex):
        if responseSetSensorIndex is None:
            return
        self.id = responseSetSensorIndex.Id()
        self.target = responseSetSensorIndex.Target()
        if not responseSetSensorIndex.IndexIsNone():
            self.index = []
            for i in range(responseSetSensorIndex.IndexLength()):
                if responseSetSensorIndex.Index(i) is None:
                    self.index.append(None)
                else:
                    sensor_Info_ = Sensor_InfoT.InitFromObj(responseSetSensorIndex.Index(i))
                    self.index.append(sensor_Info_)
        self.result = responseSetSensorIndex.Result()
        self.message = responseSetSensorIndex.Message()

    # Response_Set_Sensor_IndexT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.target is not None:
            target = builder.CreateString(self.target)
        if self.index is not None:
            indexlist = []
            for i in range(len(self.index)):
                indexlist.append(self.index[i].Pack(builder))
            Response_Set_Sensor_IndexStartIndexVector(builder, len(self.index))
            for i in reversed(range(len(self.index))):
                builder.PrependUOffsetTRelative(indexlist[i])
            index = builder.EndVector()
        if self.result is not None:
            result = builder.CreateString(self.result)
        if self.message is not None:
            message = builder.CreateString(self.message)
        Response_Set_Sensor_IndexStart(builder)
        if self.id is not None:
            Response_Set_Sensor_IndexAddId(builder, id)
        if self.target is not None:
            Response_Set_Sensor_IndexAddTarget(builder, target)
        if self.index is not None:
            Response_Set_Sensor_IndexAddIndex(builder, index)
        if self.result is not None:
            Response_Set_Sensor_IndexAddResult(builder, result)
        if self.message is not None:
            Response_Set_Sensor_IndexAddMessage(builder, message)
        responseSetSensorIndex = Response_Set_Sensor_IndexEnd(builder)
        return responseSetSensorIndex
