from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Get_Pdu_Param import Response_Get_Pdu_Param
from rb_flat_buffers.SLAMNAV.Setting_Param import Setting_Param, Setting_ParamT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Get_Pdu_Param(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Get_Pdu_Param: ...
  @classmethod
  def GetRootAsResponse_Get_Pdu_Param(cls, buf: bytes, offset: int) -> Response_Get_Pdu_Param: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Params(self, i: int) -> Setting_Param | None: ...
  def ParamsLength(self) -> int: ...
  def ParamsIsNone(self) -> bool: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Get_Pdu_ParamT(object):
  id: str | None
  params: typing.List[Setting_ParamT]
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Get_Pdu_ParamT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Get_Pdu_ParamT: ...
  @classmethod
  def InitFromObj(cls, responseGetPduParam: Response_Get_Pdu_Param) -> Response_Get_Pdu_ParamT: ...
  def _UnPack(self, responseGetPduParam: Response_Get_Pdu_Param) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Get_Pdu_ParamStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Get_Pdu_ParamAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Get_Pdu_ParamAddParams(builder: flatbuffers.Builder, params: uoffset) -> None: ...
def Response_Get_Pdu_ParamStartParamsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartParamsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Get_Pdu_ParamAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Get_Pdu_ParamAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Get_Pdu_ParamEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

