# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Response_Control_Frequency(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Control_Frequency()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Control_Frequency(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Control_Frequency
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Control_Frequency
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Control_Frequency
    def Target(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Control_Frequency
    def Onoff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Response_Control_Frequency
    def Frequency(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Response_Control_Frequency
    def Result(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Control_Frequency
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Response_Control_FrequencyStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    Response_Control_FrequencyStart(builder)

def Response_Control_FrequencyAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Response_Control_FrequencyAddId(builder, id)

def Response_Control_FrequencyAddTarget(builder: flatbuffers.Builder, target: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(target), 0)

def AddTarget(builder: flatbuffers.Builder, target: int):
    Response_Control_FrequencyAddTarget(builder, target)

def Response_Control_FrequencyAddOnoff(builder: flatbuffers.Builder, onoff: bool):
    builder.PrependBoolSlot(2, onoff, 0)

def AddOnoff(builder: flatbuffers.Builder, onoff: bool):
    Response_Control_FrequencyAddOnoff(builder, onoff)

def Response_Control_FrequencyAddFrequency(builder: flatbuffers.Builder, frequency: int):
    builder.PrependInt32Slot(3, frequency, 0)

def AddFrequency(builder: flatbuffers.Builder, frequency: int):
    Response_Control_FrequencyAddFrequency(builder, frequency)

def Response_Control_FrequencyAddResult(builder: flatbuffers.Builder, result: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder: flatbuffers.Builder, result: int):
    Response_Control_FrequencyAddResult(builder, result)

def Response_Control_FrequencyAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    Response_Control_FrequencyAddMessage(builder, message)

def Response_Control_FrequencyEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Response_Control_FrequencyEnd(builder)


class Response_Control_FrequencyT(object):

    # Response_Control_FrequencyT
    def __init__(
        self,
        id = None,
        target = None,
        onoff = False,
        frequency = 0,
        result = None,
        message = None,
    ):
        self.id = id  # type: Optional[str]
        self.target = target  # type: Optional[str]
        self.onoff = onoff  # type: bool
        self.frequency = frequency  # type: int
        self.result = result  # type: Optional[str]
        self.message = message  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        responseControlFrequency = Response_Control_Frequency()
        responseControlFrequency.Init(buf, pos)
        return cls.InitFromObj(responseControlFrequency)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, responseControlFrequency):
        x = Response_Control_FrequencyT()
        x._UnPack(responseControlFrequency)
        return x

    # Response_Control_FrequencyT
    def _UnPack(self, responseControlFrequency):
        if responseControlFrequency is None:
            return
        self.id = responseControlFrequency.Id()
        self.target = responseControlFrequency.Target()
        self.onoff = responseControlFrequency.Onoff()
        self.frequency = responseControlFrequency.Frequency()
        self.result = responseControlFrequency.Result()
        self.message = responseControlFrequency.Message()

    # Response_Control_FrequencyT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.target is not None:
            target = builder.CreateString(self.target)
        if self.result is not None:
            result = builder.CreateString(self.result)
        if self.message is not None:
            message = builder.CreateString(self.message)
        Response_Control_FrequencyStart(builder)
        if self.id is not None:
            Response_Control_FrequencyAddId(builder, id)
        if self.target is not None:
            Response_Control_FrequencyAddTarget(builder, target)
        Response_Control_FrequencyAddOnoff(builder, self.onoff)
        Response_Control_FrequencyAddFrequency(builder, self.frequency)
        if self.result is not None:
            Response_Control_FrequencyAddResult(builder, result)
        if self.message is not None:
            Response_Control_FrequencyAddMessage(builder, message)
        responseControlFrequency = Response_Control_FrequencyEnd(builder)
        return responseControlFrequency
