from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Set_Map_Cloud import Response_Set_Map_Cloud

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Set_Map_Cloud(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Set_Map_Cloud: ...
  @classmethod
  def GetRootAsResponse_Set_Map_Cloud(cls, buf: bytes, offset: int) -> Response_Set_Map_Cloud: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def FileName(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Set_Map_CloudT(object):
  id: str | None
  mapName: str | None
  fileName: str | None
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Set_Map_CloudT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Set_Map_CloudT: ...
  @classmethod
  def InitFromObj(cls, responseSetMapCloud: Response_Set_Map_Cloud) -> Response_Set_Map_CloudT: ...
  def _UnPack(self, responseSetMapCloud: Response_Set_Map_Cloud) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Set_Map_CloudStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Set_Map_CloudAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Set_Map_CloudAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Response_Set_Map_CloudAddFileName(builder: flatbuffers.Builder, fileName: uoffset) -> None: ...
def Response_Set_Map_CloudAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Set_Map_CloudAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Set_Map_CloudEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

