from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Map_Load import Response_Map_Load

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Map_Load(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Map_Load: ...
  @classmethod
  def GetRootAsResponse_Map_Load(cls, buf: bytes, offset: int) -> Response_Map_Load: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Map_LoadT(object):
  id: str | None
  mapName: str | None
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Map_LoadT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Map_LoadT: ...
  @classmethod
  def InitFromObj(cls, responseMapLoad: Response_Map_Load) -> Response_Map_LoadT: ...
  def _UnPack(self, responseMapLoad: Response_Map_Load) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Map_LoadStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Map_LoadAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Map_LoadAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Response_Map_LoadAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Map_LoadAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Map_LoadEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

