from __future__ import annotations

from rb_flat_buffers.IPC.Setting_Param import Setting_Param, Setting_ParamT
import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.SLAMNAV.Setting_Param import Setting_Param, Setting_ParamT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Set_Pdu_Param(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Set_Pdu_Param: ...
  @classmethod
  def GetRootAsResponse_Set_Pdu_Param(cls, buf: bytes, offset: int) -> Response_Set_Pdu_Param: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Params(self, i: int) -> Setting_Param | None: ...
  def ParamsLength(self) -> int: ...
  def ParamsIsNone(self) -> bool: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Set_Pdu_ParamT(object):
  id: str | None
  params: typing.List[Setting_ParamT]
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    params: typing.List['Setting_ParamT'] | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Set_Pdu_ParamT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Set_Pdu_ParamT: ...
  @classmethod
  def InitFromObj(cls, responseSetPduParam: Response_Set_Pdu_Param) -> Response_Set_Pdu_ParamT: ...
  def _UnPack(self, responseSetPduParam: Response_Set_Pdu_Param) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Set_Pdu_ParamStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Set_Pdu_ParamAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Set_Pdu_ParamAddParams(builder: flatbuffers.Builder, params: uoffset) -> None: ...
def Response_Set_Pdu_ParamStartParamsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartParamsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Set_Pdu_ParamAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Set_Pdu_ParamAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Set_Pdu_ParamEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

