from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Map_Cloud import Response_Map_Cloud

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Map_Cloud(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Map_Cloud: ...
  @classmethod
  def GetRootAsResponse_Map_Cloud(cls, buf: bytes, offset: int) -> Response_Map_Cloud: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def FileName(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
  def Size(self) -> int: ...
  def Data(self, i: int) -> typing.List[float]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
class Response_Map_CloudT(object):
  id: str | None
  mapName: str | None
  fileName: str | None
  result: str | None
  message: str | None
  size: int
  data: typing.List[float]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Map_CloudT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Map_CloudT: ...
  @classmethod
  def InitFromObj(cls, responseMapCloud: Response_Map_Cloud) -> Response_Map_CloudT: ...
  def _UnPack(self, responseMapCloud: Response_Map_Cloud) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Map_CloudStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Map_CloudAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Map_CloudAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Response_Map_CloudAddFileName(builder: flatbuffers.Builder, fileName: uoffset) -> None: ...
def Response_Map_CloudAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Map_CloudAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Map_CloudAddSize(builder: flatbuffers.Builder, size: int) -> None: ...
def Response_Map_CloudAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def Response_Map_CloudStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Map_CloudEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

