from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Get_Sensor_Index import Response_Get_Sensor_Index
from rb_flat_buffers.SLAMNAV.Sensor_Info import Sensor_Info, Sensor_InfoT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Get_Sensor_Index(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Get_Sensor_Index: ...
  @classmethod
  def GetRootAsResponse_Get_Sensor_Index(cls, buf: bytes, offset: int) -> Response_Get_Sensor_Index: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Target(self) -> str | None: ...
  def Index(self, i: int) -> Sensor_Info | None: ...
  def IndexLength(self) -> int: ...
  def IndexIsNone(self) -> bool: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Get_Sensor_IndexT(object):
  id: str | None
  target: str | None
  index: typing.List[Sensor_InfoT]
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Get_Sensor_IndexT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Get_Sensor_IndexT: ...
  @classmethod
  def InitFromObj(cls, responseGetSensorIndex: Response_Get_Sensor_Index) -> Response_Get_Sensor_IndexT: ...
  def _UnPack(self, responseGetSensorIndex: Response_Get_Sensor_Index) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Get_Sensor_IndexStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Get_Sensor_IndexAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Get_Sensor_IndexAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Response_Get_Sensor_IndexAddIndex(builder: flatbuffers.Builder, index: uoffset) -> None: ...
def Response_Get_Sensor_IndexStartIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Get_Sensor_IndexAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Get_Sensor_IndexAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Get_Sensor_IndexEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

