from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Obs_Box import Response_Obs_Box

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Obs_Box(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Obs_Box: ...
  @classmethod
  def GetRootAsResponse_Obs_Box(cls, buf: bytes, offset: int) -> Response_Obs_Box: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def MinZ(self) -> float: ...
  def MaxZ(self) -> float: ...
  def MapRange(self) -> float: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Obs_BoxT(object):
  id: str | None
  command: str | None
  minZ: float
  maxZ: float
  mapRange: float
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Obs_BoxT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Obs_BoxT: ...
  @classmethod
  def InitFromObj(cls, responseObsBox: Response_Obs_Box) -> Response_Obs_BoxT: ...
  def _UnPack(self, responseObsBox: Response_Obs_Box) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Obs_BoxStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Obs_BoxAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Obs_BoxAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Response_Obs_BoxAddMinZ(builder: flatbuffers.Builder, minZ: float) -> None: ...
def Response_Obs_BoxAddMaxZ(builder: flatbuffers.Builder, maxZ: float) -> None: ...
def Response_Obs_BoxAddMapRange(builder: flatbuffers.Builder, mapRange: float) -> None: ...
def Response_Obs_BoxAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Obs_BoxAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Obs_BoxEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

