from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Control_Frequency(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Control_Frequency: ...
  @classmethod
  def GetRootAsResponse_Control_Frequency(cls, buf: bytes, offset: int) -> Response_Control_Frequency: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Target(self) -> str | None: ...
  def Onoff(self) -> bool: ...
  def Frequency(self) -> int: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Control_FrequencyT(object):
  id: str | None
  target: str | None
  onoff: bool
  frequency: int
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    target: str | None = ...,
    onoff: bool = ...,
    frequency: int = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Control_FrequencyT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Control_FrequencyT: ...
  @classmethod
  def InitFromObj(cls, responseControlFrequency: Response_Control_Frequency) -> Response_Control_FrequencyT: ...
  def _UnPack(self, responseControlFrequency: Response_Control_Frequency) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Control_FrequencyStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Control_FrequencyAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Control_FrequencyAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Response_Control_FrequencyAddOnoff(builder: flatbuffers.Builder, onoff: bool) -> None: ...
def Response_Control_FrequencyAddFrequency(builder: flatbuffers.Builder, frequency: int) -> None: ...
def Response_Control_FrequencyAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Control_FrequencyAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Control_FrequencyEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

