from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Reset_Safety_Flag(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Reset_Safety_Flag: ...
  @classmethod
  def GetRootAsResponse_Reset_Safety_Flag(cls, buf: bytes, offset: int) -> Response_Reset_Safety_Flag: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def ResetFlag(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Reset_Safety_FlagT(object):
  id: str | None
  resetFlag: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    resetFlag: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Reset_Safety_FlagT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Reset_Safety_FlagT: ...
  @classmethod
  def InitFromObj(cls, responseResetSafetyFlag: Response_Reset_Safety_Flag) -> Response_Reset_Safety_FlagT: ...
  def _UnPack(self, responseResetSafetyFlag: Response_Reset_Safety_Flag) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Reset_Safety_FlagStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Reset_Safety_FlagAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Reset_Safety_FlagAddResetFlag(builder: flatbuffers.Builder, resetFlag: uoffset) -> None: ...
def Response_Reset_Safety_FlagAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Reset_Safety_FlagAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Reset_Safety_FlagEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

