# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Response_Map_File(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Map_File()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Map_File(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Map_File
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Map_File
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_File
    def MapName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_File
    def FileName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_File
    def Result(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_File
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_File
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Response_Map_File
    def Data(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Response_Map_File
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Response_Map_File
    def DataLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Response_Map_File
    def DataIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def Response_Map_FileStart(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    Response_Map_FileStart(builder)

def Response_Map_FileAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Response_Map_FileAddId(builder, id)

def Response_Map_FileAddMapName(builder: flatbuffers.Builder, mapName: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(mapName), 0)

def AddMapName(builder: flatbuffers.Builder, mapName: int):
    Response_Map_FileAddMapName(builder, mapName)

def Response_Map_FileAddFileName(builder: flatbuffers.Builder, fileName: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fileName), 0)

def AddFileName(builder: flatbuffers.Builder, fileName: int):
    Response_Map_FileAddFileName(builder, fileName)

def Response_Map_FileAddResult(builder: flatbuffers.Builder, result: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder: flatbuffers.Builder, result: int):
    Response_Map_FileAddResult(builder, result)

def Response_Map_FileAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    Response_Map_FileAddMessage(builder, message)

def Response_Map_FileAddSize(builder: flatbuffers.Builder, size: int):
    builder.PrependUint32Slot(5, size, 0)

def AddSize(builder: flatbuffers.Builder, size: int):
    Response_Map_FileAddSize(builder, size)

def Response_Map_FileAddData(builder: flatbuffers.Builder, data: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder: flatbuffers.Builder, data: int):
    Response_Map_FileAddData(builder, data)

def Response_Map_FileStartDataVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartDataVector(builder, numElems: int) -> int:
    return Response_Map_FileStartDataVector(builder, numElems)

def Response_Map_FileEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Response_Map_FileEnd(builder)

try:
    from typing import List
except:
    pass

class Response_Map_FileT(object):

    # Response_Map_FileT
    def __init__(self):
        self.id = None  # type: str
        self.mapName = None  # type: str
        self.fileName = None  # type: str
        self.result = None  # type: str
        self.message = None  # type: str
        self.size = 0  # type: int
        self.data = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        responseMapFile = Response_Map_File()
        responseMapFile.Init(buf, pos)
        return cls.InitFromObj(responseMapFile)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, responseMapFile):
        x = Response_Map_FileT()
        x._UnPack(responseMapFile)
        return x

    # Response_Map_FileT
    def _UnPack(self, responseMapFile):
        if responseMapFile is None:
            return
        self.id = responseMapFile.Id()
        self.mapName = responseMapFile.MapName()
        self.fileName = responseMapFile.FileName()
        self.result = responseMapFile.Result()
        self.message = responseMapFile.Message()
        self.size = responseMapFile.Size()
        if not responseMapFile.DataIsNone():
            if np is None:
                self.data = []
                for i in range(responseMapFile.DataLength()):
                    self.data.append(responseMapFile.Data(i))
            else:
                self.data = responseMapFile.DataAsNumpy()

    # Response_Map_FileT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.mapName is not None:
            mapName = builder.CreateString(self.mapName)
        if self.fileName is not None:
            fileName = builder.CreateString(self.fileName)
        if self.result is not None:
            result = builder.CreateString(self.result)
        if self.message is not None:
            message = builder.CreateString(self.message)
        if self.data is not None:
            if np is not None and type(self.data) is np.ndarray:
                data = builder.CreateNumpyVector(self.data)
            else:
                Response_Map_FileStartDataVector(builder, len(self.data))
                for i in reversed(range(len(self.data))):
                    builder.PrependUint8(self.data[i])
                data = builder.EndVector()
        Response_Map_FileStart(builder)
        if self.id is not None:
            Response_Map_FileAddId(builder, id)
        if self.mapName is not None:
            Response_Map_FileAddMapName(builder, mapName)
        if self.fileName is not None:
            Response_Map_FileAddFileName(builder, fileName)
        if self.result is not None:
            Response_Map_FileAddResult(builder, result)
        if self.message is not None:
            Response_Map_FileAddMessage(builder, message)
        Response_Map_FileAddSize(builder, self.size)
        if self.data is not None:
            Response_Map_FileAddData(builder, data)
        responseMapFile = Response_Map_FileEnd(builder)
        return responseMapFile
