from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Get_Map_Tiles import Response_Get_Map_Tiles

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Get_Map_Tiles(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Get_Map_Tiles: ...
  @classmethod
  def GetRootAsResponse_Get_Map_Tiles(cls, buf: bytes, offset: int) -> Response_Get_Map_Tiles: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Response_Get_Map_TilesT(object):
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Get_Map_TilesT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Get_Map_TilesT: ...
  @classmethod
  def InitFromObj(cls, responseGetMapTiles: Response_Get_Map_Tiles) -> Response_Get_Map_TilesT: ...
  def _UnPack(self, responseGetMapTiles: Response_Get_Map_Tiles) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Get_Map_TilesStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Get_Map_TilesEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

