from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Move_Rotate import Response_Move_Rotate

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Move_Rotate(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Move_Rotate: ...
  @classmethod
  def GetRootAsResponse_Move_Rotate(cls, buf: bytes, offset: int) -> Response_Move_Rotate: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Target(self) -> float: ...
  def Speed(self) -> float: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Move_RotateT(object):
  id: str | None
  target: float
  speed: float
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Move_RotateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Move_RotateT: ...
  @classmethod
  def InitFromObj(cls, responseMoveRotate: Response_Move_Rotate) -> Response_Move_RotateT: ...
  def _UnPack(self, responseMoveRotate: Response_Move_Rotate) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Move_RotateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Move_RotateAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Move_RotateAddTarget(builder: flatbuffers.Builder, target: float) -> None: ...
def Response_Move_RotateAddSpeed(builder: flatbuffers.Builder, speed: float) -> None: ...
def Response_Move_RotateAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Move_RotateAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Move_RotateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

