from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Safety_Field import Response_Safety_Field

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Safety_Field(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Safety_Field: ...
  @classmethod
  def GetRootAsResponse_Safety_Field(cls, buf: bytes, offset: int) -> Response_Safety_Field: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def SafetyField(self) -> int: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Safety_FieldT(object):
  id: str | None
  command: str | None
  safetyField: int
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Safety_FieldT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Safety_FieldT: ...
  @classmethod
  def InitFromObj(cls, responseSafetyField: Response_Safety_Field) -> Response_Safety_FieldT: ...
  def _UnPack(self, responseSafetyField: Response_Safety_Field) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Safety_FieldStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Safety_FieldAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Safety_FieldAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Response_Safety_FieldAddSafetyField(builder: flatbuffers.Builder, safetyField: int) -> None: ...
def Response_Safety_FieldAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Safety_FieldAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Safety_FieldEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

