# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Response_Reset_Safety_Flag(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Reset_Safety_Flag()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Reset_Safety_Flag(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Reset_Safety_Flag
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Reset_Safety_Flag
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Reset_Safety_Flag
    def ResetFlag(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Reset_Safety_Flag
    def Result(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Reset_Safety_Flag
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Response_Reset_Safety_FlagStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    Response_Reset_Safety_FlagStart(builder)

def Response_Reset_Safety_FlagAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Response_Reset_Safety_FlagAddId(builder, id)

def Response_Reset_Safety_FlagAddResetFlag(builder: flatbuffers.Builder, resetFlag: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(resetFlag), 0)

def AddResetFlag(builder: flatbuffers.Builder, resetFlag: int):
    Response_Reset_Safety_FlagAddResetFlag(builder, resetFlag)

def Response_Reset_Safety_FlagAddResult(builder: flatbuffers.Builder, result: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder: flatbuffers.Builder, result: int):
    Response_Reset_Safety_FlagAddResult(builder, result)

def Response_Reset_Safety_FlagAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    Response_Reset_Safety_FlagAddMessage(builder, message)

def Response_Reset_Safety_FlagEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Response_Reset_Safety_FlagEnd(builder)


class Response_Reset_Safety_FlagT(object):

    # Response_Reset_Safety_FlagT
    def __init__(
        self,
        id = None,
        resetFlag = None,
        result = None,
        message = None,
    ):
        self.id = id  # type: Optional[str]
        self.resetFlag = resetFlag  # type: Optional[str]
        self.result = result  # type: Optional[str]
        self.message = message  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        responseResetSafetyFlag = Response_Reset_Safety_Flag()
        responseResetSafetyFlag.Init(buf, pos)
        return cls.InitFromObj(responseResetSafetyFlag)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, responseResetSafetyFlag):
        x = Response_Reset_Safety_FlagT()
        x._UnPack(responseResetSafetyFlag)
        return x

    # Response_Reset_Safety_FlagT
    def _UnPack(self, responseResetSafetyFlag):
        if responseResetSafetyFlag is None:
            return
        self.id = responseResetSafetyFlag.Id()
        self.resetFlag = responseResetSafetyFlag.ResetFlag()
        self.result = responseResetSafetyFlag.Result()
        self.message = responseResetSafetyFlag.Message()

    # Response_Reset_Safety_FlagT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.resetFlag is not None:
            resetFlag = builder.CreateString(self.resetFlag)
        if self.result is not None:
            result = builder.CreateString(self.result)
        if self.message is not None:
            message = builder.CreateString(self.message)
        Response_Reset_Safety_FlagStart(builder)
        if self.id is not None:
            Response_Reset_Safety_FlagAddId(builder, id)
        if self.resetFlag is not None:
            Response_Reset_Safety_FlagAddResetFlag(builder, resetFlag)
        if self.result is not None:
            Response_Reset_Safety_FlagAddResult(builder, result)
        if self.message is not None:
            Response_Reset_Safety_FlagAddMessage(builder, message)
        responseResetSafetyFlag = Response_Reset_Safety_FlagEnd(builder)
        return responseResetSafetyFlag
