from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Get_Robot_Type(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Get_Robot_Type: ...
  @classmethod
  def GetRootAsResponse_Get_Robot_Type(cls, buf: bytes, offset: int) -> Response_Get_Robot_Type: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def RobotType(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Get_Robot_TypeT(object):
  id: str | None
  robotType: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    robotType: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Get_Robot_TypeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Get_Robot_TypeT: ...
  @classmethod
  def InitFromObj(cls, responseGetRobotType: Response_Get_Robot_Type) -> Response_Get_Robot_TypeT: ...
  def _UnPack(self, responseGetRobotType: Response_Get_Robot_Type) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Get_Robot_TypeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Get_Robot_TypeAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Get_Robot_TypeAddRobotType(builder: flatbuffers.Builder, robotType: uoffset) -> None: ...
def Response_Get_Robot_TypeAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Get_Robot_TypeAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Get_Robot_TypeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

