from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Mapping_Save(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Mapping_Save: ...
  @classmethod
  def GetRootAsResponse_Mapping_Save(cls, buf: bytes, offset: int) -> Response_Mapping_Save: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Mapping_SaveT(object):
  id: str | None
  mapName: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    mapName: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Mapping_SaveT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Mapping_SaveT: ...
  @classmethod
  def InitFromObj(cls, responseMappingSave: Response_Mapping_Save) -> Response_Mapping_SaveT: ...
  def _UnPack(self, responseMappingSave: Response_Mapping_Save) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Mapping_SaveStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Mapping_SaveAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Mapping_SaveAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Response_Mapping_SaveAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Mapping_SaveAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Mapping_SaveEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

