from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Move_Goal import Response_Move_Goal

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Move_Goal(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Move_Goal: ...
  @classmethod
  def GetRootAsResponse_Move_Goal(cls, buf: bytes, offset: int) -> Response_Move_Goal: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def GoalId(self) -> str | None: ...
  def Method(self) -> str | None: ...
  def Preset(self) -> int: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Move_GoalT(object):
  id: str | None
  goalId: str | None
  method: str | None
  preset: int
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Move_GoalT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Move_GoalT: ...
  @classmethod
  def InitFromObj(cls, responseMoveGoal: Response_Move_Goal) -> Response_Move_GoalT: ...
  def _UnPack(self, responseMoveGoal: Response_Move_Goal) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Move_GoalStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Move_GoalAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Move_GoalAddGoalId(builder: flatbuffers.Builder, goalId: uoffset) -> None: ...
def Response_Move_GoalAddMethod(builder: flatbuffers.Builder, method: uoffset) -> None: ...
def Response_Move_GoalAddPreset(builder: flatbuffers.Builder, preset: int) -> None: ...
def Response_Move_GoalAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Move_GoalAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Move_GoalEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

