from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Localization_SemiAutoInit(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Localization_SemiAutoInit: ...
  @classmethod
  def GetRootAsResponse_Localization_SemiAutoInit(cls, buf: bytes, offset: int) -> Response_Localization_SemiAutoInit: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Localization_SemiAutoInitT(object):
  id: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Localization_SemiAutoInitT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Localization_SemiAutoInitT: ...
  @classmethod
  def InitFromObj(cls, responseLocalizationSemiAutoInit: Response_Localization_SemiAutoInit) -> Response_Localization_SemiAutoInitT: ...
  def _UnPack(self, responseLocalizationSemiAutoInit: Response_Localization_SemiAutoInit) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Localization_SemiAutoInitStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Localization_SemiAutoInitAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Localization_SemiAutoInitAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Localization_SemiAutoInitAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Localization_SemiAutoInitEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

