from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Localization_Init(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Localization_Init: ...
  @classmethod
  def GetRootAsResponse_Localization_Init(cls, buf: bytes, offset: int) -> Response_Localization_Init: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def X(self) -> float: ...
  def Y(self) -> float: ...
  def Z(self) -> float: ...
  def Rz(self) -> float: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Localization_InitT(object):
  id: str | None
  command: str | None
  x: float
  y: float
  z: float
  rz: float
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    command: str | None = ...,
    x: float = ...,
    y: float = ...,
    z: float = ...,
    rz: float = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Localization_InitT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Localization_InitT: ...
  @classmethod
  def InitFromObj(cls, responseLocalizationInit: Response_Localization_Init) -> Response_Localization_InitT: ...
  def _UnPack(self, responseLocalizationInit: Response_Localization_Init) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Localization_InitStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Localization_InitAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Localization_InitAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Response_Localization_InitAddX(builder: flatbuffers.Builder, x: float) -> None: ...
def Response_Localization_InitAddY(builder: flatbuffers.Builder, y: float) -> None: ...
def Response_Localization_InitAddZ(builder: flatbuffers.Builder, z: float) -> None: ...
def Response_Localization_InitAddRz(builder: flatbuffers.Builder, rz: float) -> None: ...
def Response_Localization_InitAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Localization_InitAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Localization_InitEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

