from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Mapping import Response_Mapping

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Mapping(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Mapping: ...
  @classmethod
  def GetRootAsResponse_Mapping(cls, buf: bytes, offset: int) -> Response_Mapping: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_MappingT(object):
  id: str | None
  command: str | None
  mapName: str | None
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_MappingT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_MappingT: ...
  @classmethod
  def InitFromObj(cls, responseMapping: Response_Mapping) -> Response_MappingT: ...
  def _UnPack(self, responseMapping: Response_Mapping) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_MappingStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_MappingAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_MappingAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Response_MappingAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Response_MappingAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_MappingAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_MappingEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

