# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Response_Control_LED(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Control_LED()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Control_LED(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Control_LED
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Control_LED
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Control_LED
    def Onoff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Response_Control_LED
    def Color(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Control_LED
    def Result(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Control_LED
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Response_Control_LEDStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    Response_Control_LEDStart(builder)

def Response_Control_LEDAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Response_Control_LEDAddId(builder, id)

def Response_Control_LEDAddOnoff(builder: flatbuffers.Builder, onoff: bool):
    builder.PrependBoolSlot(1, onoff, 0)

def AddOnoff(builder: flatbuffers.Builder, onoff: bool):
    Response_Control_LEDAddOnoff(builder, onoff)

def Response_Control_LEDAddColor(builder: flatbuffers.Builder, color: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(color), 0)

def AddColor(builder: flatbuffers.Builder, color: int):
    Response_Control_LEDAddColor(builder, color)

def Response_Control_LEDAddResult(builder: flatbuffers.Builder, result: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder: flatbuffers.Builder, result: int):
    Response_Control_LEDAddResult(builder, result)

def Response_Control_LEDAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    Response_Control_LEDAddMessage(builder, message)

def Response_Control_LEDEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Response_Control_LEDEnd(builder)


class Response_Control_LEDT(object):

    # Response_Control_LEDT
    def __init__(
        self,
        id = None,
        onoff = False,
        color = None,
        result = None,
        message = None,
    ):
        self.id = id  # type: Optional[str]
        self.onoff = onoff  # type: bool
        self.color = color  # type: Optional[str]
        self.result = result  # type: Optional[str]
        self.message = message  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        responseControlLed = Response_Control_LED()
        responseControlLed.Init(buf, pos)
        return cls.InitFromObj(responseControlLed)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, responseControlLed):
        x = Response_Control_LEDT()
        x._UnPack(responseControlLed)
        return x

    # Response_Control_LEDT
    def _UnPack(self, responseControlLed):
        if responseControlLed is None:
            return
        self.id = responseControlLed.Id()
        self.onoff = responseControlLed.Onoff()
        self.color = responseControlLed.Color()
        self.result = responseControlLed.Result()
        self.message = responseControlLed.Message()

    # Response_Control_LEDT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.color is not None:
            color = builder.CreateString(self.color)
        if self.result is not None:
            result = builder.CreateString(self.result)
        if self.message is not None:
            message = builder.CreateString(self.message)
        Response_Control_LEDStart(builder)
        if self.id is not None:
            Response_Control_LEDAddId(builder, id)
        Response_Control_LEDAddOnoff(builder, self.onoff)
        if self.color is not None:
            Response_Control_LEDAddColor(builder, color)
        if self.result is not None:
            Response_Control_LEDAddResult(builder, result)
        if self.message is not None:
            Response_Control_LEDAddMessage(builder, message)
        responseControlLed = Response_Control_LEDEnd(builder)
        return responseControlLed
