from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Localization(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Localization: ...
  @classmethod
  def GetRootAsResponse_Localization(cls, buf: bytes, offset: int) -> Response_Localization: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def X(self) -> float: ...
  def Y(self) -> float: ...
  def Z(self) -> float: ...
  def Rz(self) -> float: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_LocalizationT(object):
  id: str | None
  command: str | None
  x: float
  y: float
  z: float
  rz: float
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    command: str | None = ...,
    x: float = ...,
    y: float = ...,
    z: float = ...,
    rz: float = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_LocalizationT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_LocalizationT: ...
  @classmethod
  def InitFromObj(cls, responseLocalization: Response_Localization) -> Response_LocalizationT: ...
  def _UnPack(self, responseLocalization: Response_Localization) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_LocalizationStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_LocalizationAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_LocalizationAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Response_LocalizationAddX(builder: flatbuffers.Builder, x: float) -> None: ...
def Response_LocalizationAddY(builder: flatbuffers.Builder, y: float) -> None: ...
def Response_LocalizationAddZ(builder: flatbuffers.Builder, z: float) -> None: ...
def Response_LocalizationAddRz(builder: flatbuffers.Builder, rz: float) -> None: ...
def Response_LocalizationAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_LocalizationAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_LocalizationEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

