from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Mapping_Start(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Mapping_Start: ...
  @classmethod
  def GetRootAsResponse_Mapping_Start(cls, buf: bytes, offset: int) -> Response_Mapping_Start: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Mapping_StartT(object):
  id: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Mapping_StartT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Mapping_StartT: ...
  @classmethod
  def InitFromObj(cls, responseMappingStart: Response_Mapping_Start) -> Response_Mapping_StartT: ...
  def _UnPack(self, responseMappingStart: Response_Mapping_Start) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Mapping_StartStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Mapping_StartAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Mapping_StartAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Mapping_StartAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Mapping_StartEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

