# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Response_Control_Motor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Control_Motor()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Control_Motor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Control_Motor
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Control_Motor
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Control_Motor
    def Onoff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Response_Control_Motor
    def Result(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Control_Motor
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Response_Control_MotorStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    Response_Control_MotorStart(builder)

def Response_Control_MotorAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Response_Control_MotorAddId(builder, id)

def Response_Control_MotorAddOnoff(builder: flatbuffers.Builder, onoff: bool):
    builder.PrependBoolSlot(1, onoff, 0)

def AddOnoff(builder: flatbuffers.Builder, onoff: bool):
    Response_Control_MotorAddOnoff(builder, onoff)

def Response_Control_MotorAddResult(builder: flatbuffers.Builder, result: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder: flatbuffers.Builder, result: int):
    Response_Control_MotorAddResult(builder, result)

def Response_Control_MotorAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    Response_Control_MotorAddMessage(builder, message)

def Response_Control_MotorEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Response_Control_MotorEnd(builder)


class Response_Control_MotorT(object):

    # Response_Control_MotorT
    def __init__(
        self,
        id = None,
        onoff = False,
        result = None,
        message = None,
    ):
        self.id = id  # type: Optional[str]
        self.onoff = onoff  # type: bool
        self.result = result  # type: Optional[str]
        self.message = message  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        responseControlMotor = Response_Control_Motor()
        responseControlMotor.Init(buf, pos)
        return cls.InitFromObj(responseControlMotor)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, responseControlMotor):
        x = Response_Control_MotorT()
        x._UnPack(responseControlMotor)
        return x

    # Response_Control_MotorT
    def _UnPack(self, responseControlMotor):
        if responseControlMotor is None:
            return
        self.id = responseControlMotor.Id()
        self.onoff = responseControlMotor.Onoff()
        self.result = responseControlMotor.Result()
        self.message = responseControlMotor.Message()

    # Response_Control_MotorT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.result is not None:
            result = builder.CreateString(self.result)
        if self.message is not None:
            message = builder.CreateString(self.message)
        Response_Control_MotorStart(builder)
        if self.id is not None:
            Response_Control_MotorAddId(builder, id)
        Response_Control_MotorAddOnoff(builder, self.onoff)
        if self.result is not None:
            Response_Control_MotorAddResult(builder, result)
        if self.message is not None:
            Response_Control_MotorAddMessage(builder, message)
        responseControlMotor = Response_Control_MotorEnd(builder)
        return responseControlMotor
