from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Get_Sensor_Off import Response_Get_Sensor_Off
from rb_flat_buffers.SLAMNAV.Sensor_Info import Sensor_Info, Sensor_InfoT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Get_Sensor_Off(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Get_Sensor_Off: ...
  @classmethod
  def GetRootAsResponse_Get_Sensor_Off(cls, buf: bytes, offset: int) -> Response_Get_Sensor_Off: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Index(self, i: int) -> Sensor_Info | None: ...
  def IndexLength(self) -> int: ...
  def IndexIsNone(self) -> bool: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Get_Sensor_OffT(object):
  id: str | None
  index: typing.List[Sensor_InfoT]
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Get_Sensor_OffT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Get_Sensor_OffT: ...
  @classmethod
  def InitFromObj(cls, responseGetSensorOff: Response_Get_Sensor_Off) -> Response_Get_Sensor_OffT: ...
  def _UnPack(self, responseGetSensorOff: Response_Get_Sensor_Off) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Get_Sensor_OffStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Get_Sensor_OffAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Get_Sensor_OffAddIndex(builder: flatbuffers.Builder, index: uoffset) -> None: ...
def Response_Get_Sensor_OffStartIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Get_Sensor_OffAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Get_Sensor_OffAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Get_Sensor_OffEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

