from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Move_Target(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Move_Target: ...
  @classmethod
  def GetRootAsResponse_Move_Target(cls, buf: bytes, offset: int) -> Response_Move_Target: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Method(self) -> str | None: ...
  def GoalPose(self, i: int) -> typing.List[float]: ...
  def GoalPoseAsNumpy(self) -> np.ndarray: ...
  def GoalPoseLength(self) -> int: ...
  def GoalPoseIsNone(self) -> bool: ...
  def Preset(self) -> int: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Move_TargetT(object):
  id: str | None
  method: str | None
  goalPose: typing.List[float]
  preset: int
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    method: str | None = ...,
    goalPose: typing.List[float] | None = ...,
    preset: int = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Move_TargetT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Move_TargetT: ...
  @classmethod
  def InitFromObj(cls, responseMoveTarget: Response_Move_Target) -> Response_Move_TargetT: ...
  def _UnPack(self, responseMoveTarget: Response_Move_Target) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Move_TargetStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Move_TargetAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Move_TargetAddMethod(builder: flatbuffers.Builder, method: uoffset) -> None: ...
def Response_Move_TargetAddGoalPose(builder: flatbuffers.Builder, goalPose: uoffset) -> None: ...
def Response_Move_TargetStartGoalPoseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartGoalPoseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Move_TargetAddPreset(builder: flatbuffers.Builder, preset: int) -> None: ...
def Response_Move_TargetAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Move_TargetAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Move_TargetEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

