from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Set_Map_Topology(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Set_Map_Topology: ...
  @classmethod
  def GetRootAsResponse_Set_Map_Topology(cls, buf: bytes, offset: int) -> Response_Set_Map_Topology: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Set_Map_TopologyT(object):
  id: str | None
  mapName: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    mapName: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Set_Map_TopologyT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Set_Map_TopologyT: ...
  @classmethod
  def InitFromObj(cls, responseSetMapTopology: Response_Set_Map_Topology) -> Response_Set_Map_TopologyT: ...
  def _UnPack(self, responseSetMapTopology: Response_Set_Map_Topology) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Set_Map_TopologyStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Set_Map_TopologyAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Set_Map_TopologyAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Response_Set_Map_TopologyAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Set_Map_TopologyAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Set_Map_TopologyEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

