# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from rb_flat_buffers.SLAMNAV.Node import Node, NodeT
from typing import Optional
np = import_numpy()

class Response_Map_Topology(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Map_Topology()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Map_Topology(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Map_Topology
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Map_Topology
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Topology
    def MapName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Topology
    def PageNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Response_Map_Topology
    def PageSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Response_Map_Topology
    def TotalPage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Response_Map_Topology
    def NodeType(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Topology
    def SearchText(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Topology
    def SortOption(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Topology
    def SortDirection(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Topology
    def Result(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Topology
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Topology
    def Data(self, j: int) -> Optional[Node]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Node()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Response_Map_Topology
    def DataLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Response_Map_Topology
    def DataIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

def Response_Map_TopologyStart(builder: flatbuffers.Builder):
    builder.StartObject(12)

def Start(builder: flatbuffers.Builder):
    Response_Map_TopologyStart(builder)

def Response_Map_TopologyAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Response_Map_TopologyAddId(builder, id)

def Response_Map_TopologyAddMapName(builder: flatbuffers.Builder, mapName: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(mapName), 0)

def AddMapName(builder: flatbuffers.Builder, mapName: int):
    Response_Map_TopologyAddMapName(builder, mapName)

def Response_Map_TopologyAddPageNo(builder: flatbuffers.Builder, pageNo: int):
    builder.PrependInt32Slot(2, pageNo, 0)

def AddPageNo(builder: flatbuffers.Builder, pageNo: int):
    Response_Map_TopologyAddPageNo(builder, pageNo)

def Response_Map_TopologyAddPageSize(builder: flatbuffers.Builder, pageSize: int):
    builder.PrependInt32Slot(3, pageSize, 0)

def AddPageSize(builder: flatbuffers.Builder, pageSize: int):
    Response_Map_TopologyAddPageSize(builder, pageSize)

def Response_Map_TopologyAddTotalPage(builder: flatbuffers.Builder, totalPage: int):
    builder.PrependInt32Slot(4, totalPage, 0)

def AddTotalPage(builder: flatbuffers.Builder, totalPage: int):
    Response_Map_TopologyAddTotalPage(builder, totalPage)

def Response_Map_TopologyAddNodeType(builder: flatbuffers.Builder, nodeType: int):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(nodeType), 0)

def AddNodeType(builder: flatbuffers.Builder, nodeType: int):
    Response_Map_TopologyAddNodeType(builder, nodeType)

def Response_Map_TopologyAddSearchText(builder: flatbuffers.Builder, searchText: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(searchText), 0)

def AddSearchText(builder: flatbuffers.Builder, searchText: int):
    Response_Map_TopologyAddSearchText(builder, searchText)

def Response_Map_TopologyAddSortOption(builder: flatbuffers.Builder, sortOption: int):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(sortOption), 0)

def AddSortOption(builder: flatbuffers.Builder, sortOption: int):
    Response_Map_TopologyAddSortOption(builder, sortOption)

def Response_Map_TopologyAddSortDirection(builder: flatbuffers.Builder, sortDirection: int):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(sortDirection), 0)

def AddSortDirection(builder: flatbuffers.Builder, sortDirection: int):
    Response_Map_TopologyAddSortDirection(builder, sortDirection)

def Response_Map_TopologyAddResult(builder: flatbuffers.Builder, result: int):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder: flatbuffers.Builder, result: int):
    Response_Map_TopologyAddResult(builder, result)

def Response_Map_TopologyAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    Response_Map_TopologyAddMessage(builder, message)

def Response_Map_TopologyAddData(builder: flatbuffers.Builder, data: int):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder: flatbuffers.Builder, data: int):
    Response_Map_TopologyAddData(builder, data)

def Response_Map_TopologyStartDataVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartDataVector(builder, numElems: int) -> int:
    return Response_Map_TopologyStartDataVector(builder, numElems)

def Response_Map_TopologyEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Response_Map_TopologyEnd(builder)

try:
    from typing import List
except:
    pass

class Response_Map_TopologyT(object):

    # Response_Map_TopologyT
    def __init__(self):
        self.id = None  # type: str
        self.mapName = None  # type: str
        self.pageNo = 0  # type: int
        self.pageSize = 0  # type: int
        self.totalPage = 0  # type: int
        self.nodeType = None  # type: str
        self.searchText = None  # type: str
        self.sortOption = None  # type: str
        self.sortDirection = None  # type: str
        self.result = None  # type: str
        self.message = None  # type: str
        self.data = None  # type: List[NodeT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        responseMapTopology = Response_Map_Topology()
        responseMapTopology.Init(buf, pos)
        return cls.InitFromObj(responseMapTopology)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, responseMapTopology):
        x = Response_Map_TopologyT()
        x._UnPack(responseMapTopology)
        return x

    # Response_Map_TopologyT
    def _UnPack(self, responseMapTopology):
        if responseMapTopology is None:
            return
        self.id = responseMapTopology.Id()
        self.mapName = responseMapTopology.MapName()
        self.pageNo = responseMapTopology.PageNo()
        self.pageSize = responseMapTopology.PageSize()
        self.totalPage = responseMapTopology.TotalPage()
        self.nodeType = responseMapTopology.NodeType()
        self.searchText = responseMapTopology.SearchText()
        self.sortOption = responseMapTopology.SortOption()
        self.sortDirection = responseMapTopology.SortDirection()
        self.result = responseMapTopology.Result()
        self.message = responseMapTopology.Message()
        if not responseMapTopology.DataIsNone():
            self.data = []
            for i in range(responseMapTopology.DataLength()):
                if responseMapTopology.Data(i) is None:
                    self.data.append(None)
                else:
                    node_ = NodeT.InitFromObj(responseMapTopology.Data(i))
                    self.data.append(node_)

    # Response_Map_TopologyT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.mapName is not None:
            mapName = builder.CreateString(self.mapName)
        if self.nodeType is not None:
            nodeType = builder.CreateString(self.nodeType)
        if self.searchText is not None:
            searchText = builder.CreateString(self.searchText)
        if self.sortOption is not None:
            sortOption = builder.CreateString(self.sortOption)
        if self.sortDirection is not None:
            sortDirection = builder.CreateString(self.sortDirection)
        if self.result is not None:
            result = builder.CreateString(self.result)
        if self.message is not None:
            message = builder.CreateString(self.message)
        if self.data is not None:
            datalist = []
            for i in range(len(self.data)):
                datalist.append(self.data[i].Pack(builder))
            Response_Map_TopologyStartDataVector(builder, len(self.data))
            for i in reversed(range(len(self.data))):
                builder.PrependUOffsetTRelative(datalist[i])
            data = builder.EndVector()
        Response_Map_TopologyStart(builder)
        if self.id is not None:
            Response_Map_TopologyAddId(builder, id)
        if self.mapName is not None:
            Response_Map_TopologyAddMapName(builder, mapName)
        Response_Map_TopologyAddPageNo(builder, self.pageNo)
        Response_Map_TopologyAddPageSize(builder, self.pageSize)
        Response_Map_TopologyAddTotalPage(builder, self.totalPage)
        if self.nodeType is not None:
            Response_Map_TopologyAddNodeType(builder, nodeType)
        if self.searchText is not None:
            Response_Map_TopologyAddSearchText(builder, searchText)
        if self.sortOption is not None:
            Response_Map_TopologyAddSortOption(builder, sortOption)
        if self.sortDirection is not None:
            Response_Map_TopologyAddSortDirection(builder, sortDirection)
        if self.result is not None:
            Response_Map_TopologyAddResult(builder, result)
        if self.message is not None:
            Response_Map_TopologyAddMessage(builder, message)
        if self.data is not None:
            Response_Map_TopologyAddData(builder, data)
        responseMapTopology = Response_Map_TopologyEnd(builder)
        return responseMapTopology
