from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Safety_Io import Response_Safety_Io

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Safety_Io(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Safety_Io: ...
  @classmethod
  def GetRootAsResponse_Safety_Io(cls, buf: bytes, offset: int) -> Response_Safety_Io: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def Mcu0Dio(self, i: int) -> typing.List[bool]: ...
  def Mcu0DioAsNumpy(self) -> np.ndarray: ...
  def Mcu0DioLength(self) -> int: ...
  def Mcu0DioIsNone(self) -> bool: ...
  def Mcu1Dio(self, i: int) -> typing.List[bool]: ...
  def Mcu1DioAsNumpy(self) -> np.ndarray: ...
  def Mcu1DioLength(self) -> int: ...
  def Mcu1DioIsNone(self) -> bool: ...
  def Mcu0Din(self, i: int) -> typing.List[bool]: ...
  def Mcu0DinAsNumpy(self) -> np.ndarray: ...
  def Mcu0DinLength(self) -> int: ...
  def Mcu0DinIsNone(self) -> bool: ...
  def Mcu1Din(self, i: int) -> typing.List[bool]: ...
  def Mcu1DinAsNumpy(self) -> np.ndarray: ...
  def Mcu1DinLength(self) -> int: ...
  def Mcu1DinIsNone(self) -> bool: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Safety_IoT(object):
  id: str | None
  command: str | None
  mcu0Dio: typing.List[bool]
  mcu1Dio: typing.List[bool]
  mcu0Din: typing.List[bool]
  mcu1Din: typing.List[bool]
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Safety_IoT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Safety_IoT: ...
  @classmethod
  def InitFromObj(cls, responseSafetyIo: Response_Safety_Io) -> Response_Safety_IoT: ...
  def _UnPack(self, responseSafetyIo: Response_Safety_Io) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Safety_IoStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Safety_IoAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Safety_IoAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Response_Safety_IoAddMcu0Dio(builder: flatbuffers.Builder, mcu0Dio: uoffset) -> None: ...
def Response_Safety_IoStartMcu0DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMcu0DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Safety_IoAddMcu1Dio(builder: flatbuffers.Builder, mcu1Dio: uoffset) -> None: ...
def Response_Safety_IoStartMcu1DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMcu1DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Safety_IoAddMcu0Din(builder: flatbuffers.Builder, mcu0Din: uoffset) -> None: ...
def Response_Safety_IoStartMcu0DinVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMcu0DinVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Safety_IoAddMcu1Din(builder: flatbuffers.Builder, mcu1Din: uoffset) -> None: ...
def Response_Safety_IoStartMcu1DinVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMcu1DinVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Safety_IoAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Safety_IoAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Safety_IoEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

