from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Localization_Stop(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Localization_Stop: ...
  @classmethod
  def GetRootAsResponse_Localization_Stop(cls, buf: bytes, offset: int) -> Response_Localization_Stop: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Localization_StopT(object):
  id: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Localization_StopT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Localization_StopT: ...
  @classmethod
  def InitFromObj(cls, responseLocalizationStop: Response_Localization_Stop) -> Response_Localization_StopT: ...
  def _UnPack(self, responseLocalizationStop: Response_Localization_Stop) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Localization_StopStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Localization_StopAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Localization_StopAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Localization_StopAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Localization_StopEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

