from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Dock(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Dock: ...
  @classmethod
  def GetRootAsResponse_Dock(cls, buf: bytes, offset: int) -> Response_Dock: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_DockT(object):
  id: str | None
  command: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    command: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_DockT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_DockT: ...
  @classmethod
  def InitFromObj(cls, responseDock: Response_Dock) -> Response_DockT: ...
  def _UnPack(self, responseDock: Response_Dock) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_DockStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_DockAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_DockAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def Response_DockAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_DockAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_DockEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

