from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Current_Version import Response_Current_Version

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Current_Version(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Current_Version: ...
  @classmethod
  def GetRootAsResponse_Current_Version(cls, buf: bytes, offset: int) -> Response_Current_Version: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Version(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Current_VersionT(object):
  id: str | None
  version: str | None
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Current_VersionT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Current_VersionT: ...
  @classmethod
  def InitFromObj(cls, responseCurrentVersion: Response_Current_Version) -> Response_Current_VersionT: ...
  def _UnPack(self, responseCurrentVersion: Response_Current_Version) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Current_VersionStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Current_VersionAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Current_VersionAddVersion(builder: flatbuffers.Builder, version: uoffset) -> None: ...
def Response_Current_VersionAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Current_VersionAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Current_VersionEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

