from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Control_LED(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Control_LED: ...
  @classmethod
  def GetRootAsResponse_Control_LED(cls, buf: bytes, offset: int) -> Response_Control_LED: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Onoff(self) -> bool: ...
  def Color(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Control_LEDT(object):
  id: str | None
  onoff: bool
  color: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    onoff: bool = ...,
    color: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Control_LEDT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Control_LEDT: ...
  @classmethod
  def InitFromObj(cls, responseControlLed: Response_Control_LED) -> Response_Control_LEDT: ...
  def _UnPack(self, responseControlLed: Response_Control_LED) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Control_LEDStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Control_LEDAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Control_LEDAddOnoff(builder: flatbuffers.Builder, onoff: bool) -> None: ...
def Response_Control_LEDAddColor(builder: flatbuffers.Builder, color: uoffset) -> None: ...
def Response_Control_LEDAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Control_LEDAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Control_LEDEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

