from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Get_Map_File(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Get_Map_File: ...
  @classmethod
  def GetRootAsResponse_Get_Map_File(cls, buf: bytes, offset: int) -> Response_Get_Map_File: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def MapName(self) -> str | None: ...
  def FileName(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
  def Size(self) -> int: ...
  def Data(self, i: int) -> typing.List[int]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
class Response_Get_Map_FileT(object):
  id: str | None
  mapName: str | None
  fileName: str | None
  result: str | None
  message: str | None
  size: int
  data: typing.List[int]
  def __init__(
    self,
    id: str | None = ...,
    mapName: str | None = ...,
    fileName: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
    size: int = ...,
    data: typing.List[int] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Get_Map_FileT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Get_Map_FileT: ...
  @classmethod
  def InitFromObj(cls, responseGetMapFile: Response_Get_Map_File) -> Response_Get_Map_FileT: ...
  def _UnPack(self, responseGetMapFile: Response_Get_Map_File) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Get_Map_FileStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Get_Map_FileAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Get_Map_FileAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Response_Get_Map_FileAddFileName(builder: flatbuffers.Builder, fileName: uoffset) -> None: ...
def Response_Get_Map_FileAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Get_Map_FileAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Get_Map_FileAddSize(builder: flatbuffers.Builder, size: int) -> None: ...
def Response_Get_Map_FileAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def Response_Get_Map_FileStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Get_Map_FileEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

