# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Response_Map_Cloud(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Map_Cloud()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Map_Cloud(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Map_Cloud
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Map_Cloud
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Cloud
    def MapName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Cloud
    def FileName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Cloud
    def Result(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Cloud
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Map_Cloud
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Response_Map_Cloud
    def Data(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Response_Map_Cloud
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # Response_Map_Cloud
    def DataLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Response_Map_Cloud
    def DataIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def Response_Map_CloudStart(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    Response_Map_CloudStart(builder)

def Response_Map_CloudAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Response_Map_CloudAddId(builder, id)

def Response_Map_CloudAddMapName(builder: flatbuffers.Builder, mapName: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(mapName), 0)

def AddMapName(builder: flatbuffers.Builder, mapName: int):
    Response_Map_CloudAddMapName(builder, mapName)

def Response_Map_CloudAddFileName(builder: flatbuffers.Builder, fileName: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fileName), 0)

def AddFileName(builder: flatbuffers.Builder, fileName: int):
    Response_Map_CloudAddFileName(builder, fileName)

def Response_Map_CloudAddResult(builder: flatbuffers.Builder, result: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder: flatbuffers.Builder, result: int):
    Response_Map_CloudAddResult(builder, result)

def Response_Map_CloudAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    Response_Map_CloudAddMessage(builder, message)

def Response_Map_CloudAddSize(builder: flatbuffers.Builder, size: int):
    builder.PrependInt32Slot(5, size, 0)

def AddSize(builder: flatbuffers.Builder, size: int):
    Response_Map_CloudAddSize(builder, size)

def Response_Map_CloudAddData(builder: flatbuffers.Builder, data: int):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder: flatbuffers.Builder, data: int):
    Response_Map_CloudAddData(builder, data)

def Response_Map_CloudStartDataVector(builder, numElems: int) -> int:
    return builder.StartVector(8, numElems, 8)

def StartDataVector(builder, numElems: int) -> int:
    return Response_Map_CloudStartDataVector(builder, numElems)

def Response_Map_CloudEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Response_Map_CloudEnd(builder)

try:
    from typing import List
except:
    pass

class Response_Map_CloudT(object):

    # Response_Map_CloudT
    def __init__(
        self,
        id = None,
        mapName = None,
        fileName = None,
        result = None,
        message = None,
        size = 0,
        data = None,
    ):
        self.id = id  # type: Optional[str]
        self.mapName = mapName  # type: Optional[str]
        self.fileName = fileName  # type: Optional[str]
        self.result = result  # type: Optional[str]
        self.message = message  # type: Optional[str]
        self.size = size  # type: int
        self.data = data  # type: Optional[List[float]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        responseMapCloud = Response_Map_Cloud()
        responseMapCloud.Init(buf, pos)
        return cls.InitFromObj(responseMapCloud)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, responseMapCloud):
        x = Response_Map_CloudT()
        x._UnPack(responseMapCloud)
        return x

    # Response_Map_CloudT
    def _UnPack(self, responseMapCloud):
        if responseMapCloud is None:
            return
        self.id = responseMapCloud.Id()
        self.mapName = responseMapCloud.MapName()
        self.fileName = responseMapCloud.FileName()
        self.result = responseMapCloud.Result()
        self.message = responseMapCloud.Message()
        self.size = responseMapCloud.Size()
        if not responseMapCloud.DataIsNone():
            if np is None:
                self.data = []
                for i in range(responseMapCloud.DataLength()):
                    self.data.append(responseMapCloud.Data(i))
            else:
                self.data = responseMapCloud.DataAsNumpy()

    # Response_Map_CloudT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.mapName is not None:
            mapName = builder.CreateString(self.mapName)
        if self.fileName is not None:
            fileName = builder.CreateString(self.fileName)
        if self.result is not None:
            result = builder.CreateString(self.result)
        if self.message is not None:
            message = builder.CreateString(self.message)
        if self.data is not None:
            if np is not None and type(self.data) is np.ndarray:
                data = builder.CreateNumpyVector(self.data)
            else:
                Response_Map_CloudStartDataVector(builder, len(self.data))
                for i in reversed(range(len(self.data))):
                    builder.PrependFloat64(self.data[i])
                data = builder.EndVector()
        Response_Map_CloudStart(builder)
        if self.id is not None:
            Response_Map_CloudAddId(builder, id)
        if self.mapName is not None:
            Response_Map_CloudAddMapName(builder, mapName)
        if self.fileName is not None:
            Response_Map_CloudAddFileName(builder, fileName)
        if self.result is not None:
            Response_Map_CloudAddResult(builder, result)
        if self.message is not None:
            Response_Map_CloudAddMessage(builder, message)
        Response_Map_CloudAddSize(builder, self.size)
        if self.data is not None:
            Response_Map_CloudAddData(builder, data)
        responseMapCloud = Response_Map_CloudEnd(builder)
        return responseMapCloud
