from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Move_Circular(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Move_Circular: ...
  @classmethod
  def GetRootAsResponse_Move_Circular(cls, buf: bytes, offset: int) -> Response_Move_Circular: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Target(self) -> float: ...
  def Speed(self) -> float: ...
  def Direction(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Move_CircularT(object):
  id: str | None
  target: float
  speed: float
  direction: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    target: float = ...,
    speed: float = ...,
    direction: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Move_CircularT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Move_CircularT: ...
  @classmethod
  def InitFromObj(cls, responseMoveCircular: Response_Move_Circular) -> Response_Move_CircularT: ...
  def _UnPack(self, responseMoveCircular: Response_Move_Circular) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Move_CircularStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Move_CircularAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Move_CircularAddTarget(builder: flatbuffers.Builder, target: float) -> None: ...
def Response_Move_CircularAddSpeed(builder: flatbuffers.Builder, speed: float) -> None: ...
def Response_Move_CircularAddDirection(builder: flatbuffers.Builder, direction: uoffset) -> None: ...
def Response_Move_CircularAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Move_CircularAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Move_CircularEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

