from __future__ import annotations

from rb_flat_buffers.IPC.Sensor_Info import Sensor_Info, Sensor_InfoT
import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.SLAMNAV.Sensor_Info import Sensor_Info, Sensor_InfoT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Set_Sensor_On(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Set_Sensor_On: ...
  @classmethod
  def GetRootAsResponse_Set_Sensor_On(cls, buf: bytes, offset: int) -> Response_Set_Sensor_On: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Index(self, i: int) -> Sensor_Info | None: ...
  def IndexLength(self) -> int: ...
  def IndexIsNone(self) -> bool: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Set_Sensor_OnT(object):
  id: str | None
  index: typing.List[Sensor_InfoT]
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    index: typing.List['Sensor_InfoT'] | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Set_Sensor_OnT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Set_Sensor_OnT: ...
  @classmethod
  def InitFromObj(cls, responseSetSensorOn: Response_Set_Sensor_On) -> Response_Set_Sensor_OnT: ...
  def _UnPack(self, responseSetSensorOn: Response_Set_Sensor_On) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Set_Sensor_OnStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Set_Sensor_OnAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Set_Sensor_OnAddIndex(builder: flatbuffers.Builder, index: uoffset) -> None: ...
def Response_Set_Sensor_OnStartIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartIndexVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Set_Sensor_OnAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Set_Sensor_OnAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Set_Sensor_OnEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

