from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Random_Sequence(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Random_Sequence: ...
  @classmethod
  def GetRootAsResponse_Random_Sequence(cls, buf: bytes, offset: int) -> Response_Random_Sequence: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Random_SequenceT(object):
  id: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Random_SequenceT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Random_SequenceT: ...
  @classmethod
  def InitFromObj(cls, responseRandomSequence: Response_Random_Sequence) -> Response_Random_SequenceT: ...
  def _UnPack(self, responseRandomSequence: Response_Random_Sequence) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Random_SequenceStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Random_SequenceAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Random_SequenceAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Random_SequenceAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Random_SequenceEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

