from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Localization_AutoInit import Response_Localization_AutoInit

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Localization_AutoInit(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Localization_AutoInit: ...
  @classmethod
  def GetRootAsResponse_Localization_AutoInit(cls, buf: bytes, offset: int) -> Response_Localization_AutoInit: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Localization_AutoInitT(object):
  id: str | None
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Localization_AutoInitT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Localization_AutoInitT: ...
  @classmethod
  def InitFromObj(cls, responseLocalizationAutoInit: Response_Localization_AutoInit) -> Response_Localization_AutoInitT: ...
  def _UnPack(self, responseLocalizationAutoInit: Response_Localization_AutoInit) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Localization_AutoInitStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Localization_AutoInitAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Localization_AutoInitAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Localization_AutoInitAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Localization_AutoInitEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

