from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Map_List(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Map_List: ...
  @classmethod
  def GetRootAsResponse_Map_List(cls, buf: bytes, offset: int) -> Response_Map_List: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def List(self, i: int) -> str: ...
  def ListLength(self) -> int: ...
  def ListIsNone(self) -> bool: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Map_ListT(object):
  id: str | None
  list: typing.List[str]
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    list: typing.List[str] | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Map_ListT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Map_ListT: ...
  @classmethod
  def InitFromObj(cls, responseMapList: Response_Map_List) -> Response_Map_ListT: ...
  def _UnPack(self, responseMapList: Response_Map_List) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Map_ListStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Map_ListAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Map_ListAddList(builder: flatbuffers.Builder, list: uoffset) -> None: ...
def Response_Map_ListStartListVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartListVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Response_Map_ListAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Map_ListAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Map_ListEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

