from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Move_Resume import Response_Move_Resume

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Move_Resume(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Move_Resume: ...
  @classmethod
  def GetRootAsResponse_Move_Resume(cls, buf: bytes, offset: int) -> Response_Move_Resume: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Move_ResumeT(object):
  id: str | None
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Move_ResumeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Move_ResumeT: ...
  @classmethod
  def InitFromObj(cls, responseMoveResume: Response_Move_Resume) -> Response_Move_ResumeT: ...
  def _UnPack(self, responseMoveResume: Response_Move_Resume) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Move_ResumeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Move_ResumeAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Move_ResumeAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Move_ResumeAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Move_ResumeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

