from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Update(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Update: ...
  @classmethod
  def GetRootAsResponse_Update(cls, buf: bytes, offset: int) -> Response_Update: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Branch(self) -> str | None: ...
  def Version(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_UpdateT(object):
  id: str | None
  branch: str | None
  version: str | None
  result: str | None
  message: str | None
  def __init__(
    self,
    id: str | None = ...,
    branch: str | None = ...,
    version: str | None = ...,
    result: str | None = ...,
    message: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_UpdateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_UpdateT: ...
  @classmethod
  def InitFromObj(cls, responseUpdate: Response_Update) -> Response_UpdateT: ...
  def _UnPack(self, responseUpdate: Response_Update) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_UpdateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_UpdateAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_UpdateAddBranch(builder: flatbuffers.Builder, branch: uoffset) -> None: ...
def Response_UpdateAddVersion(builder: flatbuffers.Builder, version: uoffset) -> None: ...
def Response_UpdateAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_UpdateAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_UpdateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

