from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Map_Tiles(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Map_Tiles: ...
  @classmethod
  def GetRootAsResponse_Map_Tiles(cls, buf: bytes, offset: int) -> Response_Map_Tiles: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Response_Map_TilesT(object):
  def __init__(
    self,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Map_TilesT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Map_TilesT: ...
  @classmethod
  def InitFromObj(cls, responseMapTiles: Response_Map_Tiles) -> Response_Map_TilesT: ...
  def _UnPack(self, responseMapTiles: Response_Map_Tiles) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Map_TilesStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Map_TilesEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

