# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Response_Safety_Field(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Safety_Field()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Safety_Field(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Safety_Field
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Safety_Field
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Safety_Field
    def Command(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Safety_Field
    def SafetyField(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Response_Safety_Field
    def Result(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Safety_Field
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Response_Safety_FieldStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    Response_Safety_FieldStart(builder)

def Response_Safety_FieldAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Response_Safety_FieldAddId(builder, id)

def Response_Safety_FieldAddCommand(builder: flatbuffers.Builder, command: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(command), 0)

def AddCommand(builder: flatbuffers.Builder, command: int):
    Response_Safety_FieldAddCommand(builder, command)

def Response_Safety_FieldAddSafetyField(builder: flatbuffers.Builder, safetyField: int):
    builder.PrependInt32Slot(2, safetyField, 0)

def AddSafetyField(builder: flatbuffers.Builder, safetyField: int):
    Response_Safety_FieldAddSafetyField(builder, safetyField)

def Response_Safety_FieldAddResult(builder: flatbuffers.Builder, result: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder: flatbuffers.Builder, result: int):
    Response_Safety_FieldAddResult(builder, result)

def Response_Safety_FieldAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    Response_Safety_FieldAddMessage(builder, message)

def Response_Safety_FieldEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Response_Safety_FieldEnd(builder)


class Response_Safety_FieldT(object):

    # Response_Safety_FieldT
    def __init__(
        self,
        id = None,
        command = None,
        safetyField = 0,
        result = None,
        message = None,
    ):
        self.id = id  # type: Optional[str]
        self.command = command  # type: Optional[str]
        self.safetyField = safetyField  # type: int
        self.result = result  # type: Optional[str]
        self.message = message  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        responseSafetyField = Response_Safety_Field()
        responseSafetyField.Init(buf, pos)
        return cls.InitFromObj(responseSafetyField)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, responseSafetyField):
        x = Response_Safety_FieldT()
        x._UnPack(responseSafetyField)
        return x

    # Response_Safety_FieldT
    def _UnPack(self, responseSafetyField):
        if responseSafetyField is None:
            return
        self.id = responseSafetyField.Id()
        self.command = responseSafetyField.Command()
        self.safetyField = responseSafetyField.SafetyField()
        self.result = responseSafetyField.Result()
        self.message = responseSafetyField.Message()

    # Response_Safety_FieldT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.command is not None:
            command = builder.CreateString(self.command)
        if self.result is not None:
            result = builder.CreateString(self.result)
        if self.message is not None:
            message = builder.CreateString(self.message)
        Response_Safety_FieldStart(builder)
        if self.id is not None:
            Response_Safety_FieldAddId(builder, id)
        if self.command is not None:
            Response_Safety_FieldAddCommand(builder, command)
        Response_Safety_FieldAddSafetyField(builder, self.safetyField)
        if self.result is not None:
            Response_Safety_FieldAddResult(builder, result)
        if self.message is not None:
            Response_Safety_FieldAddMessage(builder, message)
        responseSafetyField = Response_Safety_FieldEnd(builder)
        return responseSafetyField
