from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Control_Motor import Response_Control_Motor

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Control_Motor(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Control_Motor: ...
  @classmethod
  def GetRootAsResponse_Control_Motor(cls, buf: bytes, offset: int) -> Response_Control_Motor: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Onoff(self) -> bool: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Control_MotorT(object):
  id: str | None
  onoff: bool
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Control_MotorT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Control_MotorT: ...
  @classmethod
  def InitFromObj(cls, responseControlMotor: Response_Control_Motor) -> Response_Control_MotorT: ...
  def _UnPack(self, responseControlMotor: Response_Control_Motor) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Control_MotorStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Control_MotorAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Control_MotorAddOnoff(builder: flatbuffers.Builder, onoff: bool) -> None: ...
def Response_Control_MotorAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Control_MotorAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Control_MotorEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

