from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Response_Localization_RandomInit import Response_Localization_RandomInit

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Localization_RandomInit(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Localization_RandomInit: ...
  @classmethod
  def GetRootAsResponse_Localization_RandomInit(cls, buf: bytes, offset: int) -> Response_Localization_RandomInit: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def RandomSeed(self) -> str | None: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
class Response_Localization_RandomInitT(object):
  id: str | None
  randomSeed: str | None
  result: str | None
  message: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Localization_RandomInitT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Localization_RandomInitT: ...
  @classmethod
  def InitFromObj(cls, responseLocalizationRandomInit: Response_Localization_RandomInit) -> Response_Localization_RandomInitT: ...
  def _UnPack(self, responseLocalizationRandomInit: Response_Localization_RandomInit) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Localization_RandomInitStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Localization_RandomInitAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def Response_Localization_RandomInitAddRandomSeed(builder: flatbuffers.Builder, randomSeed: uoffset) -> None: ...
def Response_Localization_RandomInitAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Localization_RandomInitAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def Response_Localization_RandomInitEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

