# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Response_Localization_RandomInit(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Localization_RandomInit()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Localization_RandomInit(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Localization_RandomInit
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Localization_RandomInit
    def Id(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Localization_RandomInit
    def RandomSeed(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Localization_RandomInit
    def Result(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Response_Localization_RandomInit
    def Message(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Response_Localization_RandomInitStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    Response_Localization_RandomInitStart(builder)

def Response_Localization_RandomInitAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder: flatbuffers.Builder, id: int):
    Response_Localization_RandomInitAddId(builder, id)

def Response_Localization_RandomInitAddRandomSeed(builder: flatbuffers.Builder, randomSeed: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(randomSeed), 0)

def AddRandomSeed(builder: flatbuffers.Builder, randomSeed: int):
    Response_Localization_RandomInitAddRandomSeed(builder, randomSeed)

def Response_Localization_RandomInitAddResult(builder: flatbuffers.Builder, result: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder: flatbuffers.Builder, result: int):
    Response_Localization_RandomInitAddResult(builder, result)

def Response_Localization_RandomInitAddMessage(builder: flatbuffers.Builder, message: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder: flatbuffers.Builder, message: int):
    Response_Localization_RandomInitAddMessage(builder, message)

def Response_Localization_RandomInitEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Response_Localization_RandomInitEnd(builder)


class Response_Localization_RandomInitT(object):

    # Response_Localization_RandomInitT
    def __init__(
        self,
        id = None,
        randomSeed = None,
        result = None,
        message = None,
    ):
        self.id = id  # type: Optional[str]
        self.randomSeed = randomSeed  # type: Optional[str]
        self.result = result  # type: Optional[str]
        self.message = message  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        responseLocalizationRandomInit = Response_Localization_RandomInit()
        responseLocalizationRandomInit.Init(buf, pos)
        return cls.InitFromObj(responseLocalizationRandomInit)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, responseLocalizationRandomInit):
        x = Response_Localization_RandomInitT()
        x._UnPack(responseLocalizationRandomInit)
        return x

    # Response_Localization_RandomInitT
    def _UnPack(self, responseLocalizationRandomInit):
        if responseLocalizationRandomInit is None:
            return
        self.id = responseLocalizationRandomInit.Id()
        self.randomSeed = responseLocalizationRandomInit.RandomSeed()
        self.result = responseLocalizationRandomInit.Result()
        self.message = responseLocalizationRandomInit.Message()

    # Response_Localization_RandomInitT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.randomSeed is not None:
            randomSeed = builder.CreateString(self.randomSeed)
        if self.result is not None:
            result = builder.CreateString(self.result)
        if self.message is not None:
            message = builder.CreateString(self.message)
        Response_Localization_RandomInitStart(builder)
        if self.id is not None:
            Response_Localization_RandomInitAddId(builder, id)
        if self.randomSeed is not None:
            Response_Localization_RandomInitAddRandomSeed(builder, randomSeed)
        if self.result is not None:
            Response_Localization_RandomInitAddResult(builder, result)
        if self.message is not None:
            Response_Localization_RandomInitAddMessage(builder, message)
        responseLocalizationRandomInit = Response_Localization_RandomInitEnd(builder)
        return responseLocalizationRandomInit
