from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Sensor_Info import Sensor_Info

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Sensor_Info(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Sensor_Info: ...
  @classmethod
  def GetRootAsSensor_Info(cls, buf: bytes, offset: int) -> Sensor_Info: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> int: ...
  def Serial(self) -> str | None: ...
class Sensor_InfoT(object):
  id: int
  serial: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Sensor_InfoT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Sensor_InfoT: ...
  @classmethod
  def InitFromObj(cls, sensorInfo: Sensor_Info) -> Sensor_InfoT: ...
  def _UnPack(self, sensorInfo: Sensor_Info) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Sensor_InfoStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Sensor_InfoAddId(builder: flatbuffers.Builder, id: int) -> None: ...
def Sensor_InfoAddSerial(builder: flatbuffers.Builder, serial: uoffset) -> None: ...
def Sensor_InfoEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

