from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Setting_Param import Setting_Param

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Setting_Param(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Setting_Param: ...
  @classmethod
  def GetRootAsSetting_Param(cls, buf: bytes, offset: int) -> Setting_Param: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Key(self) -> str | None: ...
  def Type(self) -> str | None: ...
  def Value(self) -> str | None: ...
class Setting_ParamT(object):
  key: str | None
  type: str | None
  value: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Setting_ParamT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Setting_ParamT: ...
  @classmethod
  def InitFromObj(cls, settingParam: Setting_Param) -> Setting_ParamT: ...
  def _UnPack(self, settingParam: Setting_Param) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Setting_ParamStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Setting_ParamAddKey(builder: flatbuffers.Builder, key: uoffset) -> None: ...
def Setting_ParamAddType(builder: flatbuffers.Builder, type: uoffset) -> None: ...
def Setting_ParamAddValue(builder: flatbuffers.Builder, value: uoffset) -> None: ...
def Setting_ParamEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

