# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Status_Robot_Safety_Io_State(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Status_Robot_Safety_Io_State()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatus_Robot_Safety_Io_State(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Status_Robot_Safety_Io_State
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Status_Robot_Safety_Io_State
    def Mcu0Dio(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu0DioAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu0DioLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu0DioIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Status_Robot_Safety_Io_State
    def Mcu1Dio(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu1DioAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu1DioLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu1DioIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Status_Robot_Safety_Io_State
    def Mcu0Din(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu0DinAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu0DinLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu0DinIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Status_Robot_Safety_Io_State
    def Mcu1Din(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu1DinAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu1DinLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Status_Robot_Safety_Io_State
    def Mcu1DinIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def Status_Robot_Safety_Io_StateStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    Status_Robot_Safety_Io_StateStart(builder)

def Status_Robot_Safety_Io_StateAddMcu0Dio(builder: flatbuffers.Builder, mcu0Dio: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(mcu0Dio), 0)

def AddMcu0Dio(builder: flatbuffers.Builder, mcu0Dio: int):
    Status_Robot_Safety_Io_StateAddMcu0Dio(builder, mcu0Dio)

def Status_Robot_Safety_Io_StateStartMcu0DioVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartMcu0DioVector(builder, numElems: int) -> int:
    return Status_Robot_Safety_Io_StateStartMcu0DioVector(builder, numElems)

def Status_Robot_Safety_Io_StateAddMcu1Dio(builder: flatbuffers.Builder, mcu1Dio: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(mcu1Dio), 0)

def AddMcu1Dio(builder: flatbuffers.Builder, mcu1Dio: int):
    Status_Robot_Safety_Io_StateAddMcu1Dio(builder, mcu1Dio)

def Status_Robot_Safety_Io_StateStartMcu1DioVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartMcu1DioVector(builder, numElems: int) -> int:
    return Status_Robot_Safety_Io_StateStartMcu1DioVector(builder, numElems)

def Status_Robot_Safety_Io_StateAddMcu0Din(builder: flatbuffers.Builder, mcu0Din: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(mcu0Din), 0)

def AddMcu0Din(builder: flatbuffers.Builder, mcu0Din: int):
    Status_Robot_Safety_Io_StateAddMcu0Din(builder, mcu0Din)

def Status_Robot_Safety_Io_StateStartMcu0DinVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartMcu0DinVector(builder, numElems: int) -> int:
    return Status_Robot_Safety_Io_StateStartMcu0DinVector(builder, numElems)

def Status_Robot_Safety_Io_StateAddMcu1Din(builder: flatbuffers.Builder, mcu1Din: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(mcu1Din), 0)

def AddMcu1Din(builder: flatbuffers.Builder, mcu1Din: int):
    Status_Robot_Safety_Io_StateAddMcu1Din(builder, mcu1Din)

def Status_Robot_Safety_Io_StateStartMcu1DinVector(builder, numElems: int) -> int:
    return builder.StartVector(1, numElems, 1)

def StartMcu1DinVector(builder, numElems: int) -> int:
    return Status_Robot_Safety_Io_StateStartMcu1DinVector(builder, numElems)

def Status_Robot_Safety_Io_StateEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Status_Robot_Safety_Io_StateEnd(builder)

try:
    from typing import List
except:
    pass

class Status_Robot_Safety_Io_StateT(object):

    # Status_Robot_Safety_Io_StateT
    def __init__(self):
        self.mcu0Dio = None  # type: List[bool]
        self.mcu1Dio = None  # type: List[bool]
        self.mcu0Din = None  # type: List[bool]
        self.mcu1Din = None  # type: List[bool]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        statusRobotSafetyIoState = Status_Robot_Safety_Io_State()
        statusRobotSafetyIoState.Init(buf, pos)
        return cls.InitFromObj(statusRobotSafetyIoState)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, statusRobotSafetyIoState):
        x = Status_Robot_Safety_Io_StateT()
        x._UnPack(statusRobotSafetyIoState)
        return x

    # Status_Robot_Safety_Io_StateT
    def _UnPack(self, statusRobotSafetyIoState):
        if statusRobotSafetyIoState is None:
            return
        if not statusRobotSafetyIoState.Mcu0DioIsNone():
            if np is None:
                self.mcu0Dio = []
                for i in range(statusRobotSafetyIoState.Mcu0DioLength()):
                    self.mcu0Dio.append(statusRobotSafetyIoState.Mcu0Dio(i))
            else:
                self.mcu0Dio = statusRobotSafetyIoState.Mcu0DioAsNumpy()
        if not statusRobotSafetyIoState.Mcu1DioIsNone():
            if np is None:
                self.mcu1Dio = []
                for i in range(statusRobotSafetyIoState.Mcu1DioLength()):
                    self.mcu1Dio.append(statusRobotSafetyIoState.Mcu1Dio(i))
            else:
                self.mcu1Dio = statusRobotSafetyIoState.Mcu1DioAsNumpy()
        if not statusRobotSafetyIoState.Mcu0DinIsNone():
            if np is None:
                self.mcu0Din = []
                for i in range(statusRobotSafetyIoState.Mcu0DinLength()):
                    self.mcu0Din.append(statusRobotSafetyIoState.Mcu0Din(i))
            else:
                self.mcu0Din = statusRobotSafetyIoState.Mcu0DinAsNumpy()
        if not statusRobotSafetyIoState.Mcu1DinIsNone():
            if np is None:
                self.mcu1Din = []
                for i in range(statusRobotSafetyIoState.Mcu1DinLength()):
                    self.mcu1Din.append(statusRobotSafetyIoState.Mcu1Din(i))
            else:
                self.mcu1Din = statusRobotSafetyIoState.Mcu1DinAsNumpy()

    # Status_Robot_Safety_Io_StateT
    def Pack(self, builder):
        if self.mcu0Dio is not None:
            if np is not None and type(self.mcu0Dio) is np.ndarray:
                mcu0Dio = builder.CreateNumpyVector(self.mcu0Dio)
            else:
                Status_Robot_Safety_Io_StateStartMcu0DioVector(builder, len(self.mcu0Dio))
                for i in reversed(range(len(self.mcu0Dio))):
                    builder.PrependBool(self.mcu0Dio[i])
                mcu0Dio = builder.EndVector()
        if self.mcu1Dio is not None:
            if np is not None and type(self.mcu1Dio) is np.ndarray:
                mcu1Dio = builder.CreateNumpyVector(self.mcu1Dio)
            else:
                Status_Robot_Safety_Io_StateStartMcu1DioVector(builder, len(self.mcu1Dio))
                for i in reversed(range(len(self.mcu1Dio))):
                    builder.PrependBool(self.mcu1Dio[i])
                mcu1Dio = builder.EndVector()
        if self.mcu0Din is not None:
            if np is not None and type(self.mcu0Din) is np.ndarray:
                mcu0Din = builder.CreateNumpyVector(self.mcu0Din)
            else:
                Status_Robot_Safety_Io_StateStartMcu0DinVector(builder, len(self.mcu0Din))
                for i in reversed(range(len(self.mcu0Din))):
                    builder.PrependBool(self.mcu0Din[i])
                mcu0Din = builder.EndVector()
        if self.mcu1Din is not None:
            if np is not None and type(self.mcu1Din) is np.ndarray:
                mcu1Din = builder.CreateNumpyVector(self.mcu1Din)
            else:
                Status_Robot_Safety_Io_StateStartMcu1DinVector(builder, len(self.mcu1Din))
                for i in reversed(range(len(self.mcu1Din))):
                    builder.PrependBool(self.mcu1Din[i])
                mcu1Din = builder.EndVector()
        Status_Robot_Safety_Io_StateStart(builder)
        if self.mcu0Dio is not None:
            Status_Robot_Safety_Io_StateAddMcu0Dio(builder, mcu0Dio)
        if self.mcu1Dio is not None:
            Status_Robot_Safety_Io_StateAddMcu1Dio(builder, mcu1Dio)
        if self.mcu0Din is not None:
            Status_Robot_Safety_Io_StateAddMcu0Din(builder, mcu0Din)
        if self.mcu1Din is not None:
            Status_Robot_Safety_Io_StateAddMcu1Din(builder, mcu1Din)
        statusRobotSafetyIoState = Status_Robot_Safety_Io_StateEnd(builder)
        return statusRobotSafetyIoState
