from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Status_Robot_State(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Status_Robot_State: ...
  @classmethod
  def GetRootAsStatus_Robot_State(cls, buf: bytes, offset: int) -> Status_Robot_State: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Charge(self) -> str | None: ...
  def Dock(self) -> bool: ...
  def Emo(self) -> bool: ...
  def Localization(self) -> str | None: ...
  def Power(self) -> bool: ...
class Status_Robot_StateT(object):
  charge: str | None
  dock: bool
  emo: bool
  localization: str | None
  power: bool
  def __init__(
    self,
    charge: str | None = ...,
    dock: bool = ...,
    emo: bool = ...,
    localization: str | None = ...,
    power: bool = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Status_Robot_StateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Status_Robot_StateT: ...
  @classmethod
  def InitFromObj(cls, statusRobotState: Status_Robot_State) -> Status_Robot_StateT: ...
  def _UnPack(self, statusRobotState: Status_Robot_State) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Status_Robot_StateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Status_Robot_StateAddCharge(builder: flatbuffers.Builder, charge: uoffset) -> None: ...
def Status_Robot_StateAddDock(builder: flatbuffers.Builder, dock: bool) -> None: ...
def Status_Robot_StateAddEmo(builder: flatbuffers.Builder, emo: bool) -> None: ...
def Status_Robot_StateAddLocalization(builder: flatbuffers.Builder, localization: uoffset) -> None: ...
def Status_Robot_StateAddPower(builder: flatbuffers.Builder, power: bool) -> None: ...
def Status_Robot_StateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

