# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Status_Power(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Status_Power()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatus_Power(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Status_Power
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Status_Power
    def BatIn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def BatOut(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def BatCurrent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def TotalPower(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def Power(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def BatPercent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def TabosVoltage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def TabosCurrent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def TabosStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def TabosTtf(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def TabosTte(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def TabosSoc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def TabosSoh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def TabosTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def TabosRc(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def TabosAe(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def ChargeCurrent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Status_Power
    def ContactVoltage(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def Status_PowerStart(builder: flatbuffers.Builder):
    builder.StartObject(18)

def Start(builder: flatbuffers.Builder):
    Status_PowerStart(builder)

def Status_PowerAddBatIn(builder: flatbuffers.Builder, batIn: float):
    builder.PrependFloat64Slot(0, batIn, 0.0)

def AddBatIn(builder: flatbuffers.Builder, batIn: float):
    Status_PowerAddBatIn(builder, batIn)

def Status_PowerAddBatOut(builder: flatbuffers.Builder, batOut: float):
    builder.PrependFloat64Slot(1, batOut, 0.0)

def AddBatOut(builder: flatbuffers.Builder, batOut: float):
    Status_PowerAddBatOut(builder, batOut)

def Status_PowerAddBatCurrent(builder: flatbuffers.Builder, batCurrent: float):
    builder.PrependFloat64Slot(2, batCurrent, 0.0)

def AddBatCurrent(builder: flatbuffers.Builder, batCurrent: float):
    Status_PowerAddBatCurrent(builder, batCurrent)

def Status_PowerAddTotalPower(builder: flatbuffers.Builder, totalPower: float):
    builder.PrependFloat64Slot(3, totalPower, 0.0)

def AddTotalPower(builder: flatbuffers.Builder, totalPower: float):
    Status_PowerAddTotalPower(builder, totalPower)

def Status_PowerAddPower(builder: flatbuffers.Builder, power: float):
    builder.PrependFloat64Slot(4, power, 0.0)

def AddPower(builder: flatbuffers.Builder, power: float):
    Status_PowerAddPower(builder, power)

def Status_PowerAddBatPercent(builder: flatbuffers.Builder, batPercent: float):
    builder.PrependFloat64Slot(5, batPercent, 0.0)

def AddBatPercent(builder: flatbuffers.Builder, batPercent: float):
    Status_PowerAddBatPercent(builder, batPercent)

def Status_PowerAddTabosVoltage(builder: flatbuffers.Builder, tabosVoltage: float):
    builder.PrependFloat64Slot(6, tabosVoltage, 0.0)

def AddTabosVoltage(builder: flatbuffers.Builder, tabosVoltage: float):
    Status_PowerAddTabosVoltage(builder, tabosVoltage)

def Status_PowerAddTabosCurrent(builder: flatbuffers.Builder, tabosCurrent: float):
    builder.PrependFloat64Slot(7, tabosCurrent, 0.0)

def AddTabosCurrent(builder: flatbuffers.Builder, tabosCurrent: float):
    Status_PowerAddTabosCurrent(builder, tabosCurrent)

def Status_PowerAddTabosStatus(builder: flatbuffers.Builder, tabosStatus: float):
    builder.PrependFloat64Slot(8, tabosStatus, 0.0)

def AddTabosStatus(builder: flatbuffers.Builder, tabosStatus: float):
    Status_PowerAddTabosStatus(builder, tabosStatus)

def Status_PowerAddTabosTtf(builder: flatbuffers.Builder, tabosTtf: float):
    builder.PrependFloat64Slot(9, tabosTtf, 0.0)

def AddTabosTtf(builder: flatbuffers.Builder, tabosTtf: float):
    Status_PowerAddTabosTtf(builder, tabosTtf)

def Status_PowerAddTabosTte(builder: flatbuffers.Builder, tabosTte: float):
    builder.PrependFloat64Slot(10, tabosTte, 0.0)

def AddTabosTte(builder: flatbuffers.Builder, tabosTte: float):
    Status_PowerAddTabosTte(builder, tabosTte)

def Status_PowerAddTabosSoc(builder: flatbuffers.Builder, tabosSoc: float):
    builder.PrependFloat64Slot(11, tabosSoc, 0.0)

def AddTabosSoc(builder: flatbuffers.Builder, tabosSoc: float):
    Status_PowerAddTabosSoc(builder, tabosSoc)

def Status_PowerAddTabosSoh(builder: flatbuffers.Builder, tabosSoh: float):
    builder.PrependFloat64Slot(12, tabosSoh, 0.0)

def AddTabosSoh(builder: flatbuffers.Builder, tabosSoh: float):
    Status_PowerAddTabosSoh(builder, tabosSoh)

def Status_PowerAddTabosTemp(builder: flatbuffers.Builder, tabosTemp: float):
    builder.PrependFloat64Slot(13, tabosTemp, 0.0)

def AddTabosTemp(builder: flatbuffers.Builder, tabosTemp: float):
    Status_PowerAddTabosTemp(builder, tabosTemp)

def Status_PowerAddTabosRc(builder: flatbuffers.Builder, tabosRc: float):
    builder.PrependFloat64Slot(14, tabosRc, 0.0)

def AddTabosRc(builder: flatbuffers.Builder, tabosRc: float):
    Status_PowerAddTabosRc(builder, tabosRc)

def Status_PowerAddTabosAe(builder: flatbuffers.Builder, tabosAe: float):
    builder.PrependFloat64Slot(15, tabosAe, 0.0)

def AddTabosAe(builder: flatbuffers.Builder, tabosAe: float):
    Status_PowerAddTabosAe(builder, tabosAe)

def Status_PowerAddChargeCurrent(builder: flatbuffers.Builder, chargeCurrent: float):
    builder.PrependFloat64Slot(16, chargeCurrent, 0.0)

def AddChargeCurrent(builder: flatbuffers.Builder, chargeCurrent: float):
    Status_PowerAddChargeCurrent(builder, chargeCurrent)

def Status_PowerAddContactVoltage(builder: flatbuffers.Builder, contactVoltage: float):
    builder.PrependFloat64Slot(17, contactVoltage, 0.0)

def AddContactVoltage(builder: flatbuffers.Builder, contactVoltage: float):
    Status_PowerAddContactVoltage(builder, contactVoltage)

def Status_PowerEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Status_PowerEnd(builder)


class Status_PowerT(object):

    # Status_PowerT
    def __init__(self):
        self.batIn = 0.0  # type: float
        self.batOut = 0.0  # type: float
        self.batCurrent = 0.0  # type: float
        self.totalPower = 0.0  # type: float
        self.power = 0.0  # type: float
        self.batPercent = 0.0  # type: float
        self.tabosVoltage = 0.0  # type: float
        self.tabosCurrent = 0.0  # type: float
        self.tabosStatus = 0.0  # type: float
        self.tabosTtf = 0.0  # type: float
        self.tabosTte = 0.0  # type: float
        self.tabosSoc = 0.0  # type: float
        self.tabosSoh = 0.0  # type: float
        self.tabosTemp = 0.0  # type: float
        self.tabosRc = 0.0  # type: float
        self.tabosAe = 0.0  # type: float
        self.chargeCurrent = 0.0  # type: float
        self.contactVoltage = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        statusPower = Status_Power()
        statusPower.Init(buf, pos)
        return cls.InitFromObj(statusPower)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, statusPower):
        x = Status_PowerT()
        x._UnPack(statusPower)
        return x

    # Status_PowerT
    def _UnPack(self, statusPower):
        if statusPower is None:
            return
        self.batIn = statusPower.BatIn()
        self.batOut = statusPower.BatOut()
        self.batCurrent = statusPower.BatCurrent()
        self.totalPower = statusPower.TotalPower()
        self.power = statusPower.Power()
        self.batPercent = statusPower.BatPercent()
        self.tabosVoltage = statusPower.TabosVoltage()
        self.tabosCurrent = statusPower.TabosCurrent()
        self.tabosStatus = statusPower.TabosStatus()
        self.tabosTtf = statusPower.TabosTtf()
        self.tabosTte = statusPower.TabosTte()
        self.tabosSoc = statusPower.TabosSoc()
        self.tabosSoh = statusPower.TabosSoh()
        self.tabosTemp = statusPower.TabosTemp()
        self.tabosRc = statusPower.TabosRc()
        self.tabosAe = statusPower.TabosAe()
        self.chargeCurrent = statusPower.ChargeCurrent()
        self.contactVoltage = statusPower.ContactVoltage()

    # Status_PowerT
    def Pack(self, builder):
        Status_PowerStart(builder)
        Status_PowerAddBatIn(builder, self.batIn)
        Status_PowerAddBatOut(builder, self.batOut)
        Status_PowerAddBatCurrent(builder, self.batCurrent)
        Status_PowerAddTotalPower(builder, self.totalPower)
        Status_PowerAddPower(builder, self.power)
        Status_PowerAddBatPercent(builder, self.batPercent)
        Status_PowerAddTabosVoltage(builder, self.tabosVoltage)
        Status_PowerAddTabosCurrent(builder, self.tabosCurrent)
        Status_PowerAddTabosStatus(builder, self.tabosStatus)
        Status_PowerAddTabosTtf(builder, self.tabosTtf)
        Status_PowerAddTabosTte(builder, self.tabosTte)
        Status_PowerAddTabosSoc(builder, self.tabosSoc)
        Status_PowerAddTabosSoh(builder, self.tabosSoh)
        Status_PowerAddTabosTemp(builder, self.tabosTemp)
        Status_PowerAddTabosRc(builder, self.tabosRc)
        Status_PowerAddTabosAe(builder, self.tabosAe)
        Status_PowerAddChargeCurrent(builder, self.chargeCurrent)
        Status_PowerAddContactVoltage(builder, self.contactVoltage)
        statusPower = Status_PowerEnd(builder)
        return statusPower
