# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Status_Map(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Status_Map()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStatus_Map(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Status_Map
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Status_Map
    def MapName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Status_Map
    def MapStatus(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Status_MapStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    Status_MapStart(builder)

def Status_MapAddMapName(builder: flatbuffers.Builder, mapName: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(mapName), 0)

def AddMapName(builder: flatbuffers.Builder, mapName: int):
    Status_MapAddMapName(builder, mapName)

def Status_MapAddMapStatus(builder: flatbuffers.Builder, mapStatus: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(mapStatus), 0)

def AddMapStatus(builder: flatbuffers.Builder, mapStatus: int):
    Status_MapAddMapStatus(builder, mapStatus)

def Status_MapEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Status_MapEnd(builder)


class Status_MapT(object):

    # Status_MapT
    def __init__(self):
        self.mapName = None  # type: str
        self.mapStatus = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        statusMap = Status_Map()
        statusMap.Init(buf, pos)
        return cls.InitFromObj(statusMap)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, statusMap):
        x = Status_MapT()
        x._UnPack(statusMap)
        return x

    # Status_MapT
    def _UnPack(self, statusMap):
        if statusMap is None:
            return
        self.mapName = statusMap.MapName()
        self.mapStatus = statusMap.MapStatus()

    # Status_MapT
    def Pack(self, builder):
        if self.mapName is not None:
            mapName = builder.CreateString(self.mapName)
        if self.mapStatus is not None:
            mapStatus = builder.CreateString(self.mapStatus)
        Status_MapStart(builder)
        if self.mapName is not None:
            Status_MapAddMapName(builder, mapName)
        if self.mapStatus is not None:
            Status_MapAddMapStatus(builder, mapStatus)
        statusMap = Status_MapEnd(builder)
        return statusMap
