from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Status_Condition import Status_Condition

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Status_Condition(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Status_Condition: ...
  @classmethod
  def GetRootAsStatus_Condition(cls, buf: bytes, offset: int) -> Status_Condition: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def InlierError(self) -> float: ...
  def InlierRatio(self) -> float: ...
  def MappingError(self) -> float: ...
  def MappingRatio(self) -> float: ...
class Status_ConditionT(object):
  inlierError: float
  inlierRatio: float
  mappingError: float
  mappingRatio: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Status_ConditionT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Status_ConditionT: ...
  @classmethod
  def InitFromObj(cls, statusCondition: Status_Condition) -> Status_ConditionT: ...
  def _UnPack(self, statusCondition: Status_Condition) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Status_ConditionStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Status_ConditionAddInlierError(builder: flatbuffers.Builder, inlierError: float) -> None: ...
def Status_ConditionAddInlierRatio(builder: flatbuffers.Builder, inlierRatio: float) -> None: ...
def Status_ConditionAddMappingError(builder: flatbuffers.Builder, mappingError: float) -> None: ...
def Status_ConditionAddMappingRatio(builder: flatbuffers.Builder, mappingRatio: float) -> None: ...
def Status_ConditionEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

