from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Status_Power import Status_Power

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Status_Power(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Status_Power: ...
  @classmethod
  def GetRootAsStatus_Power(cls, buf: bytes, offset: int) -> Status_Power: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def BatIn(self) -> float: ...
  def BatOut(self) -> float: ...
  def BatCurrent(self) -> float: ...
  def TotalPower(self) -> float: ...
  def Power(self) -> float: ...
  def BatPercent(self) -> float: ...
  def TabosVoltage(self) -> float: ...
  def TabosCurrent(self) -> float: ...
  def TabosStatus(self) -> float: ...
  def TabosTtf(self) -> float: ...
  def TabosTte(self) -> float: ...
  def TabosSoc(self) -> float: ...
  def TabosSoh(self) -> float: ...
  def TabosTemp(self) -> float: ...
  def TabosRc(self) -> float: ...
  def TabosAe(self) -> float: ...
  def ChargeCurrent(self) -> float: ...
  def ContactVoltage(self) -> float: ...
class Status_PowerT(object):
  batIn: float
  batOut: float
  batCurrent: float
  totalPower: float
  power: float
  batPercent: float
  tabosVoltage: float
  tabosCurrent: float
  tabosStatus: float
  tabosTtf: float
  tabosTte: float
  tabosSoc: float
  tabosSoh: float
  tabosTemp: float
  tabosRc: float
  tabosAe: float
  chargeCurrent: float
  contactVoltage: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Status_PowerT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Status_PowerT: ...
  @classmethod
  def InitFromObj(cls, statusPower: Status_Power) -> Status_PowerT: ...
  def _UnPack(self, statusPower: Status_Power) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Status_PowerStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Status_PowerAddBatIn(builder: flatbuffers.Builder, batIn: float) -> None: ...
def Status_PowerAddBatOut(builder: flatbuffers.Builder, batOut: float) -> None: ...
def Status_PowerAddBatCurrent(builder: flatbuffers.Builder, batCurrent: float) -> None: ...
def Status_PowerAddTotalPower(builder: flatbuffers.Builder, totalPower: float) -> None: ...
def Status_PowerAddPower(builder: flatbuffers.Builder, power: float) -> None: ...
def Status_PowerAddBatPercent(builder: flatbuffers.Builder, batPercent: float) -> None: ...
def Status_PowerAddTabosVoltage(builder: flatbuffers.Builder, tabosVoltage: float) -> None: ...
def Status_PowerAddTabosCurrent(builder: flatbuffers.Builder, tabosCurrent: float) -> None: ...
def Status_PowerAddTabosStatus(builder: flatbuffers.Builder, tabosStatus: float) -> None: ...
def Status_PowerAddTabosTtf(builder: flatbuffers.Builder, tabosTtf: float) -> None: ...
def Status_PowerAddTabosTte(builder: flatbuffers.Builder, tabosTte: float) -> None: ...
def Status_PowerAddTabosSoc(builder: flatbuffers.Builder, tabosSoc: float) -> None: ...
def Status_PowerAddTabosSoh(builder: flatbuffers.Builder, tabosSoh: float) -> None: ...
def Status_PowerAddTabosTemp(builder: flatbuffers.Builder, tabosTemp: float) -> None: ...
def Status_PowerAddTabosRc(builder: flatbuffers.Builder, tabosRc: float) -> None: ...
def Status_PowerAddTabosAe(builder: flatbuffers.Builder, tabosAe: float) -> None: ...
def Status_PowerAddChargeCurrent(builder: flatbuffers.Builder, chargeCurrent: float) -> None: ...
def Status_PowerAddContactVoltage(builder: flatbuffers.Builder, contactVoltage: float) -> None: ...
def Status_PowerEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

