from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Status_Motor(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Status_Motor: ...
  @classmethod
  def GetRootAsStatus_Motor(cls, buf: bytes, offset: int) -> Status_Motor: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Connection(self) -> bool: ...
  def Status(self) -> int: ...
  def Temp(self) -> float: ...
  def Current(self) -> float: ...
class Status_MotorT(object):
  connection: bool
  status: int
  temp: float
  current: float
  def __init__(
    self,
    connection: bool = ...,
    status: int = ...,
    temp: float = ...,
    current: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Status_MotorT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Status_MotorT: ...
  @classmethod
  def InitFromObj(cls, statusMotor: Status_Motor) -> Status_MotorT: ...
  def _UnPack(self, statusMotor: Status_Motor) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Status_MotorStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Status_MotorAddConnection(builder: flatbuffers.Builder, connection: bool) -> None: ...
def Status_MotorAddStatus(builder: flatbuffers.Builder, status: int) -> None: ...
def Status_MotorAddTemp(builder: flatbuffers.Builder, temp: float) -> None: ...
def Status_MotorAddCurrent(builder: flatbuffers.Builder, current: float) -> None: ...
def Status_MotorEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

