from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Status_Map import Status_Map

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Status_Map(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Status_Map: ...
  @classmethod
  def GetRootAsStatus_Map(cls, buf: bytes, offset: int) -> Status_Map: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def MapName(self) -> str | None: ...
  def MapStatus(self) -> str | None: ...
class Status_MapT(object):
  mapName: str | None
  mapStatus: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Status_MapT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Status_MapT: ...
  @classmethod
  def InitFromObj(cls, statusMap: Status_Map) -> Status_MapT: ...
  def _UnPack(self, statusMap: Status_Map) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Status_MapStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Status_MapAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def Status_MapAddMapStatus(builder: flatbuffers.Builder, mapStatus: uoffset) -> None: ...
def Status_MapEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

