from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.SLAMNAV.Status_Imu import Status_Imu

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Status_Imu(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Status_Imu: ...
  @classmethod
  def GetRootAsStatus_Imu(cls, buf: bytes, offset: int) -> Status_Imu: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def AccX(self) -> float: ...
  def AccY(self) -> float: ...
  def AccZ(self) -> float: ...
  def GyrX(self) -> float: ...
  def GyrY(self) -> float: ...
  def GyrZ(self) -> float: ...
  def ImuRx(self) -> float: ...
  def ImuRy(self) -> float: ...
  def ImuRz(self) -> float: ...
class Status_ImuT(object):
  accX: float
  accY: float
  accZ: float
  gyrX: float
  gyrY: float
  gyrZ: float
  imuRx: float
  imuRy: float
  imuRz: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Status_ImuT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Status_ImuT: ...
  @classmethod
  def InitFromObj(cls, statusImu: Status_Imu) -> Status_ImuT: ...
  def _UnPack(self, statusImu: Status_Imu) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Status_ImuStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Status_ImuAddAccX(builder: flatbuffers.Builder, accX: float) -> None: ...
def Status_ImuAddAccY(builder: flatbuffers.Builder, accY: float) -> None: ...
def Status_ImuAddAccZ(builder: flatbuffers.Builder, accZ: float) -> None: ...
def Status_ImuAddGyrX(builder: flatbuffers.Builder, gyrX: float) -> None: ...
def Status_ImuAddGyrY(builder: flatbuffers.Builder, gyrY: float) -> None: ...
def Status_ImuAddGyrZ(builder: flatbuffers.Builder, gyrZ: float) -> None: ...
def Status_ImuAddImuRx(builder: flatbuffers.Builder, imuRx: float) -> None: ...
def Status_ImuAddImuRy(builder: flatbuffers.Builder, imuRy: float) -> None: ...
def Status_ImuAddImuRz(builder: flatbuffers.Builder, imuRz: float) -> None: ...
def Status_ImuEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

