from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Status_Setting(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Status_Setting: ...
  @classmethod
  def GetRootAsStatus_Setting(cls, buf: bytes, offset: int) -> Status_Setting: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PlatformType(self) -> str | None: ...
  def PlatformName(self) -> str | None: ...
class Status_SettingT(object):
  platformType: str | None
  platformName: str | None
  def __init__(
    self,
    platformType: str | None = ...,
    platformName: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Status_SettingT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Status_SettingT: ...
  @classmethod
  def InitFromObj(cls, statusSetting: Status_Setting) -> Status_SettingT: ...
  def _UnPack(self, statusSetting: Status_Setting) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Status_SettingStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Status_SettingAddPlatformType(builder: flatbuffers.Builder, platformType: uoffset) -> None: ...
def Status_SettingAddPlatformName(builder: flatbuffers.Builder, platformName: uoffset) -> None: ...
def Status_SettingEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

