from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class State_Change_Move(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> State_Change_Move: ...
  @classmethod
  def GetRootAsState_Change_Move(cls, buf: bytes, offset: int) -> State_Change_Move: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Id(self) -> str | None: ...
  def Command(self) -> str | None: ...
  def CurPose(self, i: int) -> typing.List[float]: ...
  def CurPoseAsNumpy(self) -> np.ndarray: ...
  def CurPoseLength(self) -> int: ...
  def CurPoseIsNone(self) -> bool: ...
  def GoalPose(self, i: int) -> typing.List[float]: ...
  def GoalPoseAsNumpy(self) -> np.ndarray: ...
  def GoalPoseLength(self) -> int: ...
  def GoalPoseIsNone(self) -> bool: ...
  def MapName(self) -> str | None: ...
  def Vel(self, i: int) -> typing.List[float]: ...
  def VelAsNumpy(self) -> np.ndarray: ...
  def VelLength(self) -> int: ...
  def VelIsNone(self) -> bool: ...
  def GoalId(self) -> str | None: ...
  def GoalName(self) -> str | None: ...
  def Method(self) -> str | None: ...
  def Direction(self) -> str | None: ...
  def Preset(self) -> int: ...
  def Result(self) -> str | None: ...
  def Message(self) -> str | None: ...
  def RemainingDist(self) -> float: ...
  def Target(self) -> float: ...
  def Speed(self) -> float: ...
  def BatPercent(self) -> int: ...
class State_Change_MoveT(object):
  id: str | None
  command: str | None
  curPose: typing.List[float]
  goalPose: typing.List[float]
  mapName: str | None
  vel: typing.List[float]
  goalId: str | None
  goalName: str | None
  method: str | None
  direction: str | None
  preset: int
  result: str | None
  message: str | None
  remainingDist: float
  target: float
  speed: float
  batPercent: int
  def __init__(
    self,
    id: str | None = ...,
    command: str | None = ...,
    curPose: typing.List[float] | None = ...,
    goalPose: typing.List[float] | None = ...,
    mapName: str | None = ...,
    vel: typing.List[float] | None = ...,
    goalId: str | None = ...,
    goalName: str | None = ...,
    method: str | None = ...,
    direction: str | None = ...,
    preset: int = ...,
    result: str | None = ...,
    message: str | None = ...,
    remainingDist: float = ...,
    target: float = ...,
    speed: float = ...,
    batPercent: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> State_Change_MoveT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> State_Change_MoveT: ...
  @classmethod
  def InitFromObj(cls, stateChangeMove: State_Change_Move) -> State_Change_MoveT: ...
  def _UnPack(self, stateChangeMove: State_Change_Move) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def State_Change_MoveStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def State_Change_MoveAddId(builder: flatbuffers.Builder, id: uoffset) -> None: ...
def State_Change_MoveAddCommand(builder: flatbuffers.Builder, command: uoffset) -> None: ...
def State_Change_MoveAddCurPose(builder: flatbuffers.Builder, curPose: uoffset) -> None: ...
def State_Change_MoveStartCurPoseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartCurPoseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def State_Change_MoveAddGoalPose(builder: flatbuffers.Builder, goalPose: uoffset) -> None: ...
def State_Change_MoveStartGoalPoseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartGoalPoseVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def State_Change_MoveAddMapName(builder: flatbuffers.Builder, mapName: uoffset) -> None: ...
def State_Change_MoveAddVel(builder: flatbuffers.Builder, vel: uoffset) -> None: ...
def State_Change_MoveStartVelVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartVelVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def State_Change_MoveAddGoalId(builder: flatbuffers.Builder, goalId: uoffset) -> None: ...
def State_Change_MoveAddGoalName(builder: flatbuffers.Builder, goalName: uoffset) -> None: ...
def State_Change_MoveAddMethod(builder: flatbuffers.Builder, method: uoffset) -> None: ...
def State_Change_MoveAddDirection(builder: flatbuffers.Builder, direction: uoffset) -> None: ...
def State_Change_MoveAddPreset(builder: flatbuffers.Builder, preset: int) -> None: ...
def State_Change_MoveAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def State_Change_MoveAddMessage(builder: flatbuffers.Builder, message: uoffset) -> None: ...
def State_Change_MoveAddRemainingDist(builder: flatbuffers.Builder, remainingDist: float) -> None: ...
def State_Change_MoveAddTarget(builder: flatbuffers.Builder, target: float) -> None: ...
def State_Change_MoveAddSpeed(builder: flatbuffers.Builder, speed: float) -> None: ...
def State_Change_MoveAddBatPercent(builder: flatbuffers.Builder, batPercent: int) -> None: ...
def State_Change_MoveEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

