from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from SLAMNAV.Status_Condition import Status_Condition, Status_ConditionT
from SLAMNAV.Status_Imu import Status_Imu, Status_ImuT
from SLAMNAV.Status_Map import Status_Map, Status_MapT
from SLAMNAV.Status_Motor import Status_Motor, Status_MotorT
from SLAMNAV.Status_Power import Status_Power, Status_PowerT
from SLAMNAV.Status_Robot_Safety_Io_State import Status_Robot_Safety_Io_State, Status_Robot_Safety_Io_StateT
from SLAMNAV.Status_Robot_State import Status_Robot_State, Status_Robot_StateT
from SLAMNAV.Status_Setting import Status_Setting, Status_SettingT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Status(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Status: ...
  @classmethod
  def GetRootAsStatus(cls, buf: bytes, offset: int) -> Status: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Imu(self) -> Status_Imu | None: ...
  def Motor0(self) -> Status_Motor | None: ...
  def Motor1(self) -> Status_Motor | None: ...
  def Condition(self) -> Status_Condition | None: ...
  def RobotState(self) -> Status_Robot_State | None: ...
  def RobotSafetyIoState(self) -> Status_Robot_Safety_Io_State | None: ...
  def Power(self) -> Status_Power | None: ...
  def Setting(self) -> Status_Setting | None: ...
  def Map(self) -> Status_Map | None: ...
class StatusT(object):
  imu: Status_ImuT | None
  motor0: Status_MotorT | None
  motor1: Status_MotorT | None
  condition: Status_ConditionT | None
  robotState: Status_Robot_StateT | None
  robotSafetyIoState: Status_Robot_Safety_Io_StateT | None
  power: Status_PowerT | None
  setting: Status_SettingT | None
  map: Status_MapT | None
  def __init__(
    self,
    imu: 'Status_ImuT' | None = ...,
    motor0: 'Status_MotorT' | None = ...,
    motor1: 'Status_MotorT' | None = ...,
    condition: 'Status_ConditionT' | None = ...,
    robotState: 'Status_Robot_StateT' | None = ...,
    robotSafetyIoState: 'Status_Robot_Safety_Io_StateT' | None = ...,
    power: 'Status_PowerT' | None = ...,
    setting: 'Status_SettingT' | None = ...,
    map: 'Status_MapT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> StatusT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> StatusT: ...
  @classmethod
  def InitFromObj(cls, status: Status) -> StatusT: ...
  def _UnPack(self, status: Status) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def StatusStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def StatusAddImu(builder: flatbuffers.Builder, imu: uoffset) -> None: ...
def StatusAddMotor0(builder: flatbuffers.Builder, motor0: uoffset) -> None: ...
def StatusAddMotor1(builder: flatbuffers.Builder, motor1: uoffset) -> None: ...
def StatusAddCondition(builder: flatbuffers.Builder, condition: uoffset) -> None: ...
def StatusAddRobotState(builder: flatbuffers.Builder, robotState: uoffset) -> None: ...
def StatusAddRobotSafetyIoState(builder: flatbuffers.Builder, robotSafetyIoState: uoffset) -> None: ...
def StatusAddPower(builder: flatbuffers.Builder, power: uoffset) -> None: ...
def StatusAddSetting(builder: flatbuffers.Builder, setting: uoffset) -> None: ...
def StatusAddMap(builder: flatbuffers.Builder, map: uoffset) -> None: ...
def StatusEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

