from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Status_Robot_Safety_Io_State(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Status_Robot_Safety_Io_State: ...
  @classmethod
  def GetRootAsStatus_Robot_Safety_Io_State(cls, buf: bytes, offset: int) -> Status_Robot_Safety_Io_State: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Mcu0Dio(self, i: int) -> typing.List[bool]: ...
  def Mcu0DioAsNumpy(self) -> np.ndarray: ...
  def Mcu0DioLength(self) -> int: ...
  def Mcu0DioIsNone(self) -> bool: ...
  def Mcu1Dio(self, i: int) -> typing.List[bool]: ...
  def Mcu1DioAsNumpy(self) -> np.ndarray: ...
  def Mcu1DioLength(self) -> int: ...
  def Mcu1DioIsNone(self) -> bool: ...
  def Mcu0Din(self, i: int) -> typing.List[bool]: ...
  def Mcu0DinAsNumpy(self) -> np.ndarray: ...
  def Mcu0DinLength(self) -> int: ...
  def Mcu0DinIsNone(self) -> bool: ...
  def Mcu1Din(self, i: int) -> typing.List[bool]: ...
  def Mcu1DinAsNumpy(self) -> np.ndarray: ...
  def Mcu1DinLength(self) -> int: ...
  def Mcu1DinIsNone(self) -> bool: ...
class Status_Robot_Safety_Io_StateT(object):
  mcu0Dio: typing.List[bool]
  mcu1Dio: typing.List[bool]
  mcu0Din: typing.List[bool]
  mcu1Din: typing.List[bool]
  def __init__(
    self,
    mcu0Dio: typing.List[bool] | None = ...,
    mcu1Dio: typing.List[bool] | None = ...,
    mcu0Din: typing.List[bool] | None = ...,
    mcu1Din: typing.List[bool] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Status_Robot_Safety_Io_StateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Status_Robot_Safety_Io_StateT: ...
  @classmethod
  def InitFromObj(cls, statusRobotSafetyIoState: Status_Robot_Safety_Io_State) -> Status_Robot_Safety_Io_StateT: ...
  def _UnPack(self, statusRobotSafetyIoState: Status_Robot_Safety_Io_State) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Status_Robot_Safety_Io_StateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Status_Robot_Safety_Io_StateAddMcu0Dio(builder: flatbuffers.Builder, mcu0Dio: uoffset) -> None: ...
def Status_Robot_Safety_Io_StateStartMcu0DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMcu0DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Status_Robot_Safety_Io_StateAddMcu1Dio(builder: flatbuffers.Builder, mcu1Dio: uoffset) -> None: ...
def Status_Robot_Safety_Io_StateStartMcu1DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMcu1DioVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Status_Robot_Safety_Io_StateAddMcu0Din(builder: flatbuffers.Builder, mcu0Din: uoffset) -> None: ...
def Status_Robot_Safety_Io_StateStartMcu0DinVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMcu0DinVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Status_Robot_Safety_Io_StateAddMcu1Din(builder: flatbuffers.Builder, mcu1Din: uoffset) -> None: ...
def Status_Robot_Safety_Io_StateStartMcu1DinVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartMcu1DinVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def Status_Robot_Safety_Io_StateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

