#ifndef CONFIGCALL_H
#define CONFIGCALL_H

#include "system.h"

enum class DB_ADDR_LIST{
    SYS_PORT_NO_MBUS = 0,
    SYS_PORT_NO_SOCKCMD,
    SYS_PORT_NO_SOCKDATA,

    SYS_GATE_PORT,
    SYS_GATE_IP_0,
    SYS_GATE_IP_1,
    SYS_GATE_IP_2,
    SYS_GATE_IP_3,

    ARM_CODE,

    ARM_OUT_COLL_ONOFF,
    ARM_OUT_COLL_REACT,
    ARM_OUT_COLL_LIMIT,

    ARM_SELF_COLL_MODE,
    ARM_SELF_COLL_PARA_INT,
    ARM_SELF_COLL_PARA_EXT,

    ARM_GRAVITY_MODE,
    ARM_GRAVITY_X,
    ARM_GRAVITY_Y,
    ARM_GRAVITY_Z,

    ARM_DIRECT_SENSITIVITY_0,
    ARM_DIRECT_SENSITIVITY_1,
    ARM_DIRECT_SENSITIVITY_2,
    ARM_DIRECT_SENSITIVITY_3,
    ARM_DIRECT_SENSITIVITY_4,
    ARM_DIRECT_SENSITIVITY_5,
    ARM_DIRECT_SENSITIVITY_6,
    
    ARM_TOOL_0_NAME,
    ARM_TOOL_0_TCP_X,
    ARM_TOOL_0_TCP_Y,
    ARM_TOOL_0_TCP_Z,
    ARM_TOOL_0_TCP_RX,
    ARM_TOOL_0_TCP_RY,
    ARM_TOOL_0_TCP_RZ,
    ARM_TOOL_0_MASS_M,
    ARM_TOOL_0_MASS_X,
    ARM_TOOL_0_MASS_Y,
    ARM_TOOL_0_MASS_Z,
    ARM_TOOL_0_BOX_TYPE,
    ARM_TOOL_0_BOX_PARA0,
    ARM_TOOL_0_BOX_PARA1,
    ARM_TOOL_0_BOX_PARA2,
    ARM_TOOL_0_BOX_PARA3,
    ARM_TOOL_0_BOX_PARA4,
    ARM_TOOL_0_BOX_PARA5,
    ARM_TOOL_0_BOX_PARA6,
    ARM_TOOL_0_BOX_PARA7,
    ARM_TOOL_0_BOX_PARA8,

    ARM_TOOL_1_NAME,
    ARM_TOOL_1_TCP_X,
    ARM_TOOL_1_TCP_Y,
    ARM_TOOL_1_TCP_Z,
    ARM_TOOL_1_TCP_RX,
    ARM_TOOL_1_TCP_RY,
    ARM_TOOL_1_TCP_RZ,
    ARM_TOOL_1_MASS_M,
    ARM_TOOL_1_MASS_X,
    ARM_TOOL_1_MASS_Y,
    ARM_TOOL_1_MASS_Z,
    ARM_TOOL_1_BOX_TYPE,
    ARM_TOOL_1_BOX_PARA0,
    ARM_TOOL_1_BOX_PARA1,
    ARM_TOOL_1_BOX_PARA2,
    ARM_TOOL_1_BOX_PARA3,
    ARM_TOOL_1_BOX_PARA4,
    ARM_TOOL_1_BOX_PARA5,
    ARM_TOOL_1_BOX_PARA6,
    ARM_TOOL_1_BOX_PARA7,
    ARM_TOOL_1_BOX_PARA8,

    ARM_TOOL_2_NAME,
    ARM_TOOL_2_TCP_X,
    ARM_TOOL_2_TCP_Y,
    ARM_TOOL_2_TCP_Z,
    ARM_TOOL_2_TCP_RX,
    ARM_TOOL_2_TCP_RY,
    ARM_TOOL_2_TCP_RZ,
    ARM_TOOL_2_MASS_M,
    ARM_TOOL_2_MASS_X,
    ARM_TOOL_2_MASS_Y,
    ARM_TOOL_2_MASS_Z,
    ARM_TOOL_2_BOX_TYPE,
    ARM_TOOL_2_BOX_PARA0,
    ARM_TOOL_2_BOX_PARA1,
    ARM_TOOL_2_BOX_PARA2,
    ARM_TOOL_2_BOX_PARA3,
    ARM_TOOL_2_BOX_PARA4,
    ARM_TOOL_2_BOX_PARA5,
    ARM_TOOL_2_BOX_PARA6,
    ARM_TOOL_2_BOX_PARA7,
    ARM_TOOL_2_BOX_PARA8,

    ARM_TOOL_3_NAME,
    ARM_TOOL_3_TCP_X,
    ARM_TOOL_3_TCP_Y,
    ARM_TOOL_3_TCP_Z,
    ARM_TOOL_3_TCP_RX,
    ARM_TOOL_3_TCP_RY,
    ARM_TOOL_3_TCP_RZ,
    ARM_TOOL_3_MASS_M,
    ARM_TOOL_3_MASS_X,
    ARM_TOOL_3_MASS_Y,
    ARM_TOOL_3_MASS_Z,
    ARM_TOOL_3_BOX_TYPE,
    ARM_TOOL_3_BOX_PARA0,
    ARM_TOOL_3_BOX_PARA1,
    ARM_TOOL_3_BOX_PARA2,
    ARM_TOOL_3_BOX_PARA3,
    ARM_TOOL_3_BOX_PARA4,
    ARM_TOOL_3_BOX_PARA5,
    ARM_TOOL_3_BOX_PARA6,
    ARM_TOOL_3_BOX_PARA7,
    ARM_TOOL_3_BOX_PARA8,

    ARM_TOOL_4_NAME,
    ARM_TOOL_4_TCP_X,
    ARM_TOOL_4_TCP_Y,
    ARM_TOOL_4_TCP_Z,
    ARM_TOOL_4_TCP_RX,
    ARM_TOOL_4_TCP_RY,
    ARM_TOOL_4_TCP_RZ,
    ARM_TOOL_4_MASS_M,
    ARM_TOOL_4_MASS_X,
    ARM_TOOL_4_MASS_Y,
    ARM_TOOL_4_MASS_Z,
    ARM_TOOL_4_BOX_TYPE,
    ARM_TOOL_4_BOX_PARA0,
    ARM_TOOL_4_BOX_PARA1,
    ARM_TOOL_4_BOX_PARA2,
    ARM_TOOL_4_BOX_PARA3,
    ARM_TOOL_4_BOX_PARA4,
    ARM_TOOL_4_BOX_PARA5,
    ARM_TOOL_4_BOX_PARA6,
    ARM_TOOL_4_BOX_PARA7,
    ARM_TOOL_4_BOX_PARA8,

    ARM_TOOL_5_NAME,
    ARM_TOOL_5_TCP_X,
    ARM_TOOL_5_TCP_Y,
    ARM_TOOL_5_TCP_Z,
    ARM_TOOL_5_TCP_RX,
    ARM_TOOL_5_TCP_RY,
    ARM_TOOL_5_TCP_RZ,
    ARM_TOOL_5_MASS_M,
    ARM_TOOL_5_MASS_X,
    ARM_TOOL_5_MASS_Y,
    ARM_TOOL_5_MASS_Z,
    ARM_TOOL_5_BOX_TYPE,
    ARM_TOOL_5_BOX_PARA0,
    ARM_TOOL_5_BOX_PARA1,
    ARM_TOOL_5_BOX_PARA2,
    ARM_TOOL_5_BOX_PARA3,
    ARM_TOOL_5_BOX_PARA4,
    ARM_TOOL_5_BOX_PARA5,
    ARM_TOOL_5_BOX_PARA6,
    ARM_TOOL_5_BOX_PARA7,
    ARM_TOOL_5_BOX_PARA8,

    ARM_TOOL_6_NAME,
    ARM_TOOL_6_TCP_X,
    ARM_TOOL_6_TCP_Y,
    ARM_TOOL_6_TCP_Z,
    ARM_TOOL_6_TCP_RX,
    ARM_TOOL_6_TCP_RY,
    ARM_TOOL_6_TCP_RZ,
    ARM_TOOL_6_MASS_M,
    ARM_TOOL_6_MASS_X,
    ARM_TOOL_6_MASS_Y,
    ARM_TOOL_6_MASS_Z,
    ARM_TOOL_6_BOX_TYPE,
    ARM_TOOL_6_BOX_PARA0,
    ARM_TOOL_6_BOX_PARA1,
    ARM_TOOL_6_BOX_PARA2,
    ARM_TOOL_6_BOX_PARA3,
    ARM_TOOL_6_BOX_PARA4,
    ARM_TOOL_6_BOX_PARA5,
    ARM_TOOL_6_BOX_PARA6,
    ARM_TOOL_6_BOX_PARA7,
    ARM_TOOL_6_BOX_PARA8,

    ARM_TOOL_7_NAME,
    ARM_TOOL_7_TCP_X,
    ARM_TOOL_7_TCP_Y,
    ARM_TOOL_7_TCP_Z,
    ARM_TOOL_7_TCP_RX,
    ARM_TOOL_7_TCP_RY,
    ARM_TOOL_7_TCP_RZ,
    ARM_TOOL_7_MASS_M,
    ARM_TOOL_7_MASS_X,
    ARM_TOOL_7_MASS_Y,
    ARM_TOOL_7_MASS_Z,
    ARM_TOOL_7_BOX_TYPE,
    ARM_TOOL_7_BOX_PARA0,
    ARM_TOOL_7_BOX_PARA1,
    ARM_TOOL_7_BOX_PARA2,
    ARM_TOOL_7_BOX_PARA3,
    ARM_TOOL_7_BOX_PARA4,
    ARM_TOOL_7_BOX_PARA5,
    ARM_TOOL_7_BOX_PARA6,
    ARM_TOOL_7_BOX_PARA7,
    ARM_TOOL_7_BOX_PARA8,

    USER_FRAME_0_NAME,
    USER_FRAME_0_X,
    USER_FRAME_0_Y,
    USER_FRAME_0_Z,
    USER_FRAME_0_RX,
    USER_FRAME_0_RY,
    USER_FRAME_0_RZ,

    USER_FRAME_1_NAME,
    USER_FRAME_1_X,
    USER_FRAME_1_Y,
    USER_FRAME_1_Z,
    USER_FRAME_1_RX,
    USER_FRAME_1_RY,
    USER_FRAME_1_RZ,

    USER_FRAME_2_NAME,
    USER_FRAME_2_X,
    USER_FRAME_2_Y,
    USER_FRAME_2_Z,
    USER_FRAME_2_RX,
    USER_FRAME_2_RY,
    USER_FRAME_2_RZ,

    USER_FRAME_3_NAME,
    USER_FRAME_3_X,
    USER_FRAME_3_Y,
    USER_FRAME_3_Z,
    USER_FRAME_3_RX,
    USER_FRAME_3_RY,
    USER_FRAME_3_RZ,

    USER_FRAME_4_NAME,
    USER_FRAME_4_X,
    USER_FRAME_4_Y,
    USER_FRAME_4_Z,
    USER_FRAME_4_RX,
    USER_FRAME_4_RY,
    USER_FRAME_4_RZ,

    USER_FRAME_5_NAME,
    USER_FRAME_5_X,
    USER_FRAME_5_Y,
    USER_FRAME_5_Z,
    USER_FRAME_5_RX,
    USER_FRAME_5_RY,
    USER_FRAME_5_RZ,

    USER_FRAME_6_NAME,
    USER_FRAME_6_X,
    USER_FRAME_6_Y,
    USER_FRAME_6_Z,
    USER_FRAME_6_RX,
    USER_FRAME_6_RY,
    USER_FRAME_6_RZ,

    USER_FRAME_7_NAME,
    USER_FRAME_7_X,
    USER_FRAME_7_Y,
    USER_FRAME_7_Z,
    USER_FRAME_7_RX,
    USER_FRAME_7_RY,
    USER_FRAME_7_RZ,

    AREA_0_NAME,
    AREA_0_TYPE,
    AREA_0_X,
    AREA_0_Y,
    AREA_0_Z,
    AREA_0_RX,
    AREA_0_RY,
    AREA_0_RZ,
    AREA_0_PARA_A,
    AREA_0_PARA_B,
    AREA_0_PARA_C,

    AREA_1_NAME,
    AREA_1_TYPE,
    AREA_1_X,
    AREA_1_Y,
    AREA_1_Z,
    AREA_1_RX,
    AREA_1_RY,
    AREA_1_RZ,
    AREA_1_PARA_A,
    AREA_1_PARA_B,
    AREA_1_PARA_C,

    AREA_2_NAME,
    AREA_2_TYPE,
    AREA_2_X,
    AREA_2_Y,
    AREA_2_Z,
    AREA_2_RX,
    AREA_2_RY,
    AREA_2_RZ,
    AREA_2_PARA_A,
    AREA_2_PARA_B,
    AREA_2_PARA_C,

    AREA_3_NAME,
    AREA_3_TYPE,
    AREA_3_X,
    AREA_3_Y,
    AREA_3_Z,
    AREA_3_RX,
    AREA_3_RY,
    AREA_3_RZ,
    AREA_3_PARA_A,
    AREA_3_PARA_B,
    AREA_3_PARA_C,

    AREA_4_NAME,
    AREA_4_TYPE,
    AREA_4_X,
    AREA_4_Y,
    AREA_4_Z,
    AREA_4_RX,
    AREA_4_RY,
    AREA_4_RZ,
    AREA_4_PARA_A,
    AREA_4_PARA_B,
    AREA_4_PARA_C,

    AREA_5_NAME,
    AREA_5_TYPE,
    AREA_5_X,
    AREA_5_Y,
    AREA_5_Z,
    AREA_5_RX,
    AREA_5_RY,
    AREA_5_RZ,
    AREA_5_PARA_A,
    AREA_5_PARA_B,
    AREA_5_PARA_C,

    AREA_6_NAME,
    AREA_6_TYPE,
    AREA_6_X,
    AREA_6_Y,
    AREA_6_Z,
    AREA_6_RX,
    AREA_6_RY,
    AREA_6_RZ,
    AREA_6_PARA_A,
    AREA_6_PARA_B,
    AREA_6_PARA_C,

    AREA_7_NAME,
    AREA_7_TYPE,
    AREA_7_X,
    AREA_7_Y,
    AREA_7_Z,
    AREA_7_RX,
    AREA_7_RY,
    AREA_7_RZ,
    AREA_7_PARA_A,
    AREA_7_PARA_B,
    AREA_7_PARA_C,

    DIN_SPECIAL_FUNC_0,
    DIN_SPECIAL_FUNC_1,
    DIN_SPECIAL_FUNC_2,
    DIN_SPECIAL_FUNC_3,
    DIN_SPECIAL_FUNC_4,
    DIN_SPECIAL_FUNC_5,
    DIN_SPECIAL_FUNC_6,
    DIN_SPECIAL_FUNC_7,
    DIN_SPECIAL_FUNC_8,
    DIN_SPECIAL_FUNC_9,
    DIN_SPECIAL_FUNC_10,
    DIN_SPECIAL_FUNC_11,
    DIN_SPECIAL_FUNC_12,
    DIN_SPECIAL_FUNC_13,
    DIN_SPECIAL_FUNC_14,
    DIN_SPECIAL_FUNC_15,
    DIN_SPECIAL_FUNC_16,
    DIN_SPECIAL_FUNC_17,
    DIN_SPECIAL_FUNC_18,
    DIN_SPECIAL_FUNC_19,
    DIN_SPECIAL_FUNC_20,
    DIN_SPECIAL_FUNC_21,
    DIN_SPECIAL_FUNC_22,
    DIN_SPECIAL_FUNC_23,
    DIN_SPECIAL_FUNC_24,
    DIN_SPECIAL_FUNC_25,
    DIN_SPECIAL_FUNC_26,
    DIN_SPECIAL_FUNC_27,
    DIN_SPECIAL_FUNC_28,
    DIN_SPECIAL_FUNC_29,
    DIN_SPECIAL_FUNC_30,
    DIN_SPECIAL_FUNC_31,

    DOUT_SPECIAL_FUNC_0,
    DOUT_SPECIAL_FUNC_1,
    DOUT_SPECIAL_FUNC_2,
    DOUT_SPECIAL_FUNC_3,
    DOUT_SPECIAL_FUNC_4,
    DOUT_SPECIAL_FUNC_5,
    DOUT_SPECIAL_FUNC_6,
    DOUT_SPECIAL_FUNC_7,
    DOUT_SPECIAL_FUNC_8,
    DOUT_SPECIAL_FUNC_9,
    DOUT_SPECIAL_FUNC_10,
    DOUT_SPECIAL_FUNC_11,
    DOUT_SPECIAL_FUNC_12,
    DOUT_SPECIAL_FUNC_13,
    DOUT_SPECIAL_FUNC_14,
    DOUT_SPECIAL_FUNC_15,
    DOUT_SPECIAL_FUNC_16,
    DOUT_SPECIAL_FUNC_17,
    DOUT_SPECIAL_FUNC_18,
    DOUT_SPECIAL_FUNC_19,
    DOUT_SPECIAL_FUNC_20,
    DOUT_SPECIAL_FUNC_21,
    DOUT_SPECIAL_FUNC_22,
    DOUT_SPECIAL_FUNC_23,
    DOUT_SPECIAL_FUNC_24,
    DOUT_SPECIAL_FUNC_25,
    DOUT_SPECIAL_FUNC_26,
    DOUT_SPECIAL_FUNC_27,
    DOUT_SPECIAL_FUNC_28,
    DOUT_SPECIAL_FUNC_29,
    DOUT_SPECIAL_FUNC_30,
    DOUT_SPECIAL_FUNC_31,

    DIN_FILTER_CNT_0,
    DIN_FILTER_CNT_1,
    DIN_FILTER_CNT_2,
    DIN_FILTER_CNT_3,
    DIN_FILTER_CNT_4,
    DIN_FILTER_CNT_5,
    DIN_FILTER_CNT_6,
    DIN_FILTER_CNT_7,
    DIN_FILTER_CNT_8,
    DIN_FILTER_CNT_9,
    DIN_FILTER_CNT_10,
    DIN_FILTER_CNT_11,
    DIN_FILTER_CNT_12,
    DIN_FILTER_CNT_13,
    DIN_FILTER_CNT_14,
    DIN_FILTER_CNT_15,
    DIN_FILTER_CNT_16,
    DIN_FILTER_CNT_17,
    DIN_FILTER_CNT_18,
    DIN_FILTER_CNT_19,
    DIN_FILTER_CNT_20,
    DIN_FILTER_CNT_21,
    DIN_FILTER_CNT_22,
    DIN_FILTER_CNT_23,
    DIN_FILTER_CNT_24,
    DIN_FILTER_CNT_25,
    DIN_FILTER_CNT_26,
    DIN_FILTER_CNT_27,
    DIN_FILTER_CNT_28,
    DIN_FILTER_CNT_29,
    DIN_FILTER_CNT_30,
    DIN_FILTER_CNT_31,

    NUM_OF_LIST
};

struct DB_ADDR_MAP{
    char    name[32];
    int     type;
    //0 : int
    //1 : float
    //2 : string
};

const DB_ADDR_MAP DB_MAP[(int)DB_ADDR_LIST::NUM_OF_LIST] = {
    {"SYS_PORT_NO_MBUS", 0},
    {"SYS_PORT_NO_SOCKCMD", 0},
    {"SYS_PORT_NO_SOCKDATA", 0},

    {"SYS_GATE_PORT", 0},
    {"SYS_GATE_IP_0", 0},
    {"SYS_GATE_IP_1", 0},
    {"SYS_GATE_IP_2", 0},
    {"SYS_GATE_IP_3", 0},

    {"ARM_CODE", 0},

    {"ARM_OUT_COLL_ONOFF", 0},
    {"ARM_OUT_COLL_REACT", 0},
    {"ARM_OUT_COLL_LIMIT", 1},

    {"ARM_SELF_COLL_MODE", 0},
    {"ARM_SELF_COLL_PARA_INT", 1},
    {"ARM_SELF_COLL_PARA_EXT", 1},

    {"ARM_GRAVITY_MODE", 0},
    {"ARM_GRAVITY_X", 1},
    {"ARM_GRAVITY_Y", 1},
    {"ARM_GRAVITY_Z", 1},

    {"ARM_DIRECT_SENSITIVITY_0", 1},
    {"ARM_DIRECT_SENSITIVITY_1", 1},
    {"ARM_DIRECT_SENSITIVITY_2", 1},
    {"ARM_DIRECT_SENSITIVITY_3", 1},
    {"ARM_DIRECT_SENSITIVITY_4", 1},
    {"ARM_DIRECT_SENSITIVITY_5", 1},
    {"ARM_DIRECT_SENSITIVITY_6", 1},

    {"ARM_TOOL_0_NAME", 2},
    {"ARM_TOOL_0_TCP_X", 1},
    {"ARM_TOOL_0_TCP_Y", 1},
    {"ARM_TOOL_0_TCP_Z", 1},
    {"ARM_TOOL_0_TCP_RX", 1},
    {"ARM_TOOL_0_TCP_RY", 1},
    {"ARM_TOOL_0_TCP_RZ", 1},
    {"ARM_TOOL_0_MASS_M", 1},
    {"ARM_TOOL_0_MASS_X", 1},
    {"ARM_TOOL_0_MASS_Y", 1},
    {"ARM_TOOL_0_MASS_Z", 1},
    {"ARM_TOOL_0_BOX_TYPE", 0},
    {"ARM_TOOL_0_BOX_PARA0", 1},
    {"ARM_TOOL_0_BOX_PARA1", 1},
    {"ARM_TOOL_0_BOX_PARA2", 1},
    {"ARM_TOOL_0_BOX_PARA3", 1},
    {"ARM_TOOL_0_BOX_PARA4", 1},
    {"ARM_TOOL_0_BOX_PARA5", 1},
    {"ARM_TOOL_0_BOX_PARA6", 1},
    {"ARM_TOOL_0_BOX_PARA7", 1},
    {"ARM_TOOL_0_BOX_PARA8", 1},

    {"ARM_TOOL_1_NAME", 2},
    {"ARM_TOOL_1_TCP_X", 1},
    {"ARM_TOOL_1_TCP_Y", 1},
    {"ARM_TOOL_1_TCP_Z", 1},
    {"ARM_TOOL_1_TCP_RX", 1},
    {"ARM_TOOL_1_TCP_RY", 1},
    {"ARM_TOOL_1_TCP_RZ", 1},
    {"ARM_TOOL_1_MASS_M", 1},
    {"ARM_TOOL_1_MASS_X", 1},
    {"ARM_TOOL_1_MASS_Y", 1},
    {"ARM_TOOL_1_MASS_Z", 1},
    {"ARM_TOOL_1_BOX_TYPE", 0},
    {"ARM_TOOL_1_BOX_PARA0", 1},
    {"ARM_TOOL_1_BOX_PARA1", 1},
    {"ARM_TOOL_1_BOX_PARA2", 1},
    {"ARM_TOOL_1_BOX_PARA3", 1},
    {"ARM_TOOL_1_BOX_PARA4", 1},
    {"ARM_TOOL_1_BOX_PARA5", 1},
    {"ARM_TOOL_1_BOX_PARA6", 1},
    {"ARM_TOOL_1_BOX_PARA7", 1},
    {"ARM_TOOL_1_BOX_PARA8", 1},

    {"ARM_TOOL_2_NAME", 2},
    {"ARM_TOOL_2_TCP_X", 1},
    {"ARM_TOOL_2_TCP_Y", 1},
    {"ARM_TOOL_2_TCP_Z", 1},
    {"ARM_TOOL_2_TCP_RX", 1},
    {"ARM_TOOL_2_TCP_RY", 1},
    {"ARM_TOOL_2_TCP_RZ", 1},
    {"ARM_TOOL_2_MASS_M", 1},
    {"ARM_TOOL_2_MASS_X", 1},
    {"ARM_TOOL_2_MASS_Y", 1},
    {"ARM_TOOL_2_MASS_Z", 1},
    {"ARM_TOOL_2_BOX_TYPE", 0},
    {"ARM_TOOL_2_BOX_PARA0", 1},
    {"ARM_TOOL_2_BOX_PARA1", 1},
    {"ARM_TOOL_2_BOX_PARA2", 1},
    {"ARM_TOOL_2_BOX_PARA3", 1},
    {"ARM_TOOL_2_BOX_PARA4", 1},
    {"ARM_TOOL_2_BOX_PARA5", 1},
    {"ARM_TOOL_2_BOX_PARA6", 1},
    {"ARM_TOOL_2_BOX_PARA7", 1},
    {"ARM_TOOL_2_BOX_PARA8", 1},

    {"ARM_TOOL_3_NAME", 2},
    {"ARM_TOOL_3_TCP_X", 1},
    {"ARM_TOOL_3_TCP_Y", 1},
    {"ARM_TOOL_3_TCP_Z", 1},
    {"ARM_TOOL_3_TCP_RX", 1},
    {"ARM_TOOL_3_TCP_RY", 1},
    {"ARM_TOOL_3_TCP_RZ", 1},
    {"ARM_TOOL_3_MASS_M", 1},
    {"ARM_TOOL_3_MASS_X", 1},
    {"ARM_TOOL_3_MASS_Y", 1},
    {"ARM_TOOL_3_MASS_Z", 1},
    {"ARM_TOOL_3_BOX_TYPE", 0},
    {"ARM_TOOL_3_BOX_PARA0", 1},
    {"ARM_TOOL_3_BOX_PARA1", 1},
    {"ARM_TOOL_3_BOX_PARA2", 1},
    {"ARM_TOOL_3_BOX_PARA3", 1},
    {"ARM_TOOL_3_BOX_PARA4", 1},
    {"ARM_TOOL_3_BOX_PARA5", 1},
    {"ARM_TOOL_3_BOX_PARA6", 1},
    {"ARM_TOOL_3_BOX_PARA7", 1},
    {"ARM_TOOL_3_BOX_PARA8", 1},

    {"ARM_TOOL_4_NAME", 2},
    {"ARM_TOOL_4_TCP_X", 1},
    {"ARM_TOOL_4_TCP_Y", 1},
    {"ARM_TOOL_4_TCP_Z", 1},
    {"ARM_TOOL_4_TCP_RX", 1},
    {"ARM_TOOL_4_TCP_RY", 1},
    {"ARM_TOOL_4_TCP_RZ", 1},
    {"ARM_TOOL_4_MASS_M", 1},
    {"ARM_TOOL_4_MASS_X", 1},
    {"ARM_TOOL_4_MASS_Y", 1},
    {"ARM_TOOL_4_MASS_Z", 1},
    {"ARM_TOOL_4_BOX_TYPE", 0},
    {"ARM_TOOL_4_BOX_PARA0", 1},
    {"ARM_TOOL_4_BOX_PARA1", 1},
    {"ARM_TOOL_4_BOX_PARA2", 1},
    {"ARM_TOOL_4_BOX_PARA3", 1},
    {"ARM_TOOL_4_BOX_PARA4", 1},
    {"ARM_TOOL_4_BOX_PARA5", 1},
    {"ARM_TOOL_4_BOX_PARA6", 1},
    {"ARM_TOOL_4_BOX_PARA7", 1},
    {"ARM_TOOL_4_BOX_PARA8", 1},

    {"ARM_TOOL_5_NAME", 2},
    {"ARM_TOOL_5_TCP_X", 1},
    {"ARM_TOOL_5_TCP_Y", 1},
    {"ARM_TOOL_5_TCP_Z", 1},
    {"ARM_TOOL_5_TCP_RX", 1},
    {"ARM_TOOL_5_TCP_RY", 1},
    {"ARM_TOOL_5_TCP_RZ", 1},
    {"ARM_TOOL_5_MASS_M", 1},
    {"ARM_TOOL_5_MASS_X", 1},
    {"ARM_TOOL_5_MASS_Y", 1},
    {"ARM_TOOL_5_MASS_Z", 1},
    {"ARM_TOOL_5_BOX_TYPE", 0},
    {"ARM_TOOL_5_BOX_PARA0", 1},
    {"ARM_TOOL_5_BOX_PARA1", 1},
    {"ARM_TOOL_5_BOX_PARA2", 1},
    {"ARM_TOOL_5_BOX_PARA3", 1},
    {"ARM_TOOL_5_BOX_PARA4", 1},
    {"ARM_TOOL_5_BOX_PARA5", 1},
    {"ARM_TOOL_5_BOX_PARA6", 1},
    {"ARM_TOOL_5_BOX_PARA7", 1},
    {"ARM_TOOL_5_BOX_PARA8", 1},

    {"ARM_TOOL_6_NAME", 2},
    {"ARM_TOOL_6_TCP_X", 1},
    {"ARM_TOOL_6_TCP_Y", 1},
    {"ARM_TOOL_6_TCP_Z", 1},
    {"ARM_TOOL_6_TCP_RX", 1},
    {"ARM_TOOL_6_TCP_RY", 1},
    {"ARM_TOOL_6_TCP_RZ", 1},
    {"ARM_TOOL_6_MASS_M", 1},
    {"ARM_TOOL_6_MASS_X", 1},
    {"ARM_TOOL_6_MASS_Y", 1},
    {"ARM_TOOL_6_MASS_Z", 1},
    {"ARM_TOOL_6_BOX_TYPE", 0},
    {"ARM_TOOL_6_BOX_PARA0", 1},
    {"ARM_TOOL_6_BOX_PARA1", 1},
    {"ARM_TOOL_6_BOX_PARA2", 1},
    {"ARM_TOOL_6_BOX_PARA3", 1},
    {"ARM_TOOL_6_BOX_PARA4", 1},
    {"ARM_TOOL_6_BOX_PARA5", 1},
    {"ARM_TOOL_6_BOX_PARA6", 1},
    {"ARM_TOOL_6_BOX_PARA7", 1},
    {"ARM_TOOL_6_BOX_PARA8", 1},

    {"ARM_TOOL_7_NAME", 2},
    {"ARM_TOOL_7_TCP_X", 1},
    {"ARM_TOOL_7_TCP_Y", 1},
    {"ARM_TOOL_7_TCP_Z", 1},
    {"ARM_TOOL_7_TCP_RX", 1},
    {"ARM_TOOL_7_TCP_RY", 1},
    {"ARM_TOOL_7_TCP_RZ", 1},
    {"ARM_TOOL_7_MASS_M", 1},
    {"ARM_TOOL_7_MASS_X", 1},
    {"ARM_TOOL_7_MASS_Y", 1},
    {"ARM_TOOL_7_MASS_Z", 1},
    {"ARM_TOOL_7_BOX_TYPE", 0},
    {"ARM_TOOL_7_BOX_PARA0", 1},
    {"ARM_TOOL_7_BOX_PARA1", 1},
    {"ARM_TOOL_7_BOX_PARA2", 1},
    {"ARM_TOOL_7_BOX_PARA3", 1},
    {"ARM_TOOL_7_BOX_PARA4", 1},
    {"ARM_TOOL_7_BOX_PARA5", 1},
    {"ARM_TOOL_7_BOX_PARA6", 1},
    {"ARM_TOOL_7_BOX_PARA7", 1},
    {"ARM_TOOL_7_BOX_PARA8", 1},

    {"USER_FRAME_0_NAME", 2},
    {"USER_FRAME_0_X", 1},
    {"USER_FRAME_0_Y", 1},
    {"USER_FRAME_0_Z", 1},
    {"USER_FRAME_0_RX", 1},
    {"USER_FRAME_0_RY", 1},
    {"USER_FRAME_0_RZ", 1},

    {"USER_FRAME_1_NAME", 2},
    {"USER_FRAME_1_X", 1},
    {"USER_FRAME_1_Y", 1},
    {"USER_FRAME_1_Z", 1},
    {"USER_FRAME_1_RX", 1},
    {"USER_FRAME_1_RY", 1},
    {"USER_FRAME_1_RZ", 1},

    {"USER_FRAME_2_NAME", 2},
    {"USER_FRAME_2_X", 1},
    {"USER_FRAME_2_Y", 1},
    {"USER_FRAME_2_Z", 1},
    {"USER_FRAME_2_RX", 1},
    {"USER_FRAME_2_RY", 1},
    {"USER_FRAME_2_RZ", 1},

    {"USER_FRAME_3_NAME", 2},
    {"USER_FRAME_3_X", 1},
    {"USER_FRAME_3_Y", 1},
    {"USER_FRAME_3_Z", 1},
    {"USER_FRAME_3_RX", 1},
    {"USER_FRAME_3_RY", 1},
    {"USER_FRAME_3_RZ", 1},

    {"USER_FRAME_4_NAME", 2},
    {"USER_FRAME_4_X", 1},
    {"USER_FRAME_4_Y", 1},
    {"USER_FRAME_4_Z", 1},
    {"USER_FRAME_4_RX", 1},
    {"USER_FRAME_4_RY", 1},
    {"USER_FRAME_4_RZ", 1},

    {"USER_FRAME_5_NAME", 2},
    {"USER_FRAME_5_X", 1},
    {"USER_FRAME_5_Y", 1},
    {"USER_FRAME_5_Z", 1},
    {"USER_FRAME_5_RX", 1},
    {"USER_FRAME_5_RY", 1},
    {"USER_FRAME_5_RZ", 1},

    {"USER_FRAME_6_NAME", 2},
    {"USER_FRAME_6_X", 1},
    {"USER_FRAME_6_Y", 1},
    {"USER_FRAME_6_Z", 1},
    {"USER_FRAME_6_RX", 1},
    {"USER_FRAME_6_RY", 1},
    {"USER_FRAME_6_RZ", 1},

    {"USER_FRAME_7_NAME", 2},
    {"USER_FRAME_7_X", 1},
    {"USER_FRAME_7_Y", 1},
    {"USER_FRAME_7_Z", 1},
    {"USER_FRAME_7_RX", 1},
    {"USER_FRAME_7_RY", 1},
    {"USER_FRAME_7_RZ", 1},

    {"AREA_0_NAME", 2},
    {"AREA_0_TYPE", 0},
    {"AREA_0_X", 1},
    {"AREA_0_Y", 1},
    {"AREA_0_Z", 1},
    {"AREA_0_RX", 1},
    {"AREA_0_RY", 1},
    {"AREA_0_RZ", 1},
    {"AREA_0_PARA_A", 1},
    {"AREA_0_PARA_B", 1},
    {"AREA_0_PARA_C", 1},

    {"AREA_1_NAME", 2},
    {"AREA_1_TYPE", 0},
    {"AREA_1_X", 1},
    {"AREA_1_Y", 1},
    {"AREA_1_Z", 1},
    {"AREA_1_RX", 1},
    {"AREA_1_RY", 1},
    {"AREA_1_RZ", 1},
    {"AREA_1_PARA_A", 1},
    {"AREA_1_PARA_B", 1},
    {"AREA_1_PARA_C", 1},

    {"AREA_2_NAME", 2},
    {"AREA_2_TYPE", 0},
    {"AREA_2_X", 1},
    {"AREA_2_Y", 1},
    {"AREA_2_Z", 1},
    {"AREA_2_RX", 1},
    {"AREA_2_RY", 1},
    {"AREA_2_RZ", 1},
    {"AREA_2_PARA_A", 1},
    {"AREA_2_PARA_B", 1},
    {"AREA_2_PARA_C", 1},

    {"AREA_3_NAME", 2},
    {"AREA_3_TYPE", 0},
    {"AREA_3_X", 1},
    {"AREA_3_Y", 1},
    {"AREA_3_Z", 1},
    {"AREA_3_RX", 1},
    {"AREA_3_RY", 1},
    {"AREA_3_RZ", 1},
    {"AREA_3_PARA_A", 1},
    {"AREA_3_PARA_B", 1},
    {"AREA_3_PARA_C", 1},

    {"AREA_4_NAME", 2},
    {"AREA_4_TYPE", 0},
    {"AREA_4_X", 1},
    {"AREA_4_Y", 1},
    {"AREA_4_Z", 1},
    {"AREA_4_RX", 1},
    {"AREA_4_RY", 1},
    {"AREA_4_RZ", 1},
    {"AREA_4_PARA_A", 1},
    {"AREA_4_PARA_B", 1},
    {"AREA_4_PARA_C", 1},

    {"AREA_5_NAME", 2},
    {"AREA_5_TYPE", 0},
    {"AREA_5_X", 1},
    {"AREA_5_Y", 1},
    {"AREA_5_Z", 1},
    {"AREA_5_RX", 1},
    {"AREA_5_RY", 1},
    {"AREA_5_RZ", 1},
    {"AREA_5_PARA_A", 1},
    {"AREA_5_PARA_B", 1},
    {"AREA_5_PARA_C", 1},

    {"AREA_6_NAME", 2},
    {"AREA_6_TYPE", 0},
    {"AREA_6_X", 1},
    {"AREA_6_Y", 1},
    {"AREA_6_Z", 1},
    {"AREA_6_RX", 1},
    {"AREA_6_RY", 1},
    {"AREA_6_RZ", 1},
    {"AREA_6_PARA_A", 1},
    {"AREA_6_PARA_B", 1},
    {"AREA_6_PARA_C", 1},

    {"AREA_7_NAME", 2},
    {"AREA_7_TYPE", 0},
    {"AREA_7_X", 1},
    {"AREA_7_Y", 1},
    {"AREA_7_Z", 1},
    {"AREA_7_RX", 1},
    {"AREA_7_RY", 1},
    {"AREA_7_RZ", 1},
    {"AREA_7_PARA_A", 1},
    {"AREA_7_PARA_B", 1},
    {"AREA_7_PARA_C", 1},

    {"DIN_SPECIAL_FUNC_0", 0},
    {"DIN_SPECIAL_FUNC_1", 0},
    {"DIN_SPECIAL_FUNC_2", 0},
    {"DIN_SPECIAL_FUNC_3", 0},
    {"DIN_SPECIAL_FUNC_4", 0},
    {"DIN_SPECIAL_FUNC_5", 0},
    {"DIN_SPECIAL_FUNC_6", 0},
    {"DIN_SPECIAL_FUNC_7", 0},
    {"DIN_SPECIAL_FUNC_8", 0},
    {"DIN_SPECIAL_FUNC_9", 0},
    {"DIN_SPECIAL_FUNC_10", 0},
    {"DIN_SPECIAL_FUNC_11", 0},
    {"DIN_SPECIAL_FUNC_12", 0},
    {"DIN_SPECIAL_FUNC_13", 0},
    {"DIN_SPECIAL_FUNC_14", 0},
    {"DIN_SPECIAL_FUNC_15", 0},
    {"DIN_SPECIAL_FUNC_16", 0},
    {"DIN_SPECIAL_FUNC_17", 0},
    {"DIN_SPECIAL_FUNC_18", 0},
    {"DIN_SPECIAL_FUNC_19", 0},
    {"DIN_SPECIAL_FUNC_20", 0},
    {"DIN_SPECIAL_FUNC_21", 0},
    {"DIN_SPECIAL_FUNC_22", 0},
    {"DIN_SPECIAL_FUNC_23", 0},
    {"DIN_SPECIAL_FUNC_24", 0},
    {"DIN_SPECIAL_FUNC_25", 0},
    {"DIN_SPECIAL_FUNC_26", 0},
    {"DIN_SPECIAL_FUNC_27", 0},
    {"DIN_SPECIAL_FUNC_28", 0},
    {"DIN_SPECIAL_FUNC_29", 0},
    {"DIN_SPECIAL_FUNC_30", 0},
    {"DIN_SPECIAL_FUNC_31", 0},

    {"DOUT_SPECIAL_FUNC_0", 0},
    {"DOUT_SPECIAL_FUNC_1", 0},
    {"DOUT_SPECIAL_FUNC_2", 0},
    {"DOUT_SPECIAL_FUNC_3", 0},
    {"DOUT_SPECIAL_FUNC_4", 0},
    {"DOUT_SPECIAL_FUNC_5", 0},
    {"DOUT_SPECIAL_FUNC_6", 0},
    {"DOUT_SPECIAL_FUNC_7", 0},
    {"DOUT_SPECIAL_FUNC_8", 0},
    {"DOUT_SPECIAL_FUNC_9", 0},
    {"DOUT_SPECIAL_FUNC_10", 0},
    {"DOUT_SPECIAL_FUNC_11", 0},
    {"DOUT_SPECIAL_FUNC_12", 0},
    {"DOUT_SPECIAL_FUNC_13", 0},
    {"DOUT_SPECIAL_FUNC_14", 0},
    {"DOUT_SPECIAL_FUNC_15", 0},
    {"DOUT_SPECIAL_FUNC_16", 0},
    {"DOUT_SPECIAL_FUNC_17", 0},
    {"DOUT_SPECIAL_FUNC_18", 0},
    {"DOUT_SPECIAL_FUNC_19", 0},
    {"DOUT_SPECIAL_FUNC_20", 0},
    {"DOUT_SPECIAL_FUNC_21", 0},
    {"DOUT_SPECIAL_FUNC_22", 0},
    {"DOUT_SPECIAL_FUNC_23", 0},
    {"DOUT_SPECIAL_FUNC_24", 0},
    {"DOUT_SPECIAL_FUNC_25", 0},
    {"DOUT_SPECIAL_FUNC_26", 0},
    {"DOUT_SPECIAL_FUNC_27", 0},
    {"DOUT_SPECIAL_FUNC_28", 0},
    {"DOUT_SPECIAL_FUNC_29", 0},
    {"DOUT_SPECIAL_FUNC_30", 0},
    {"DOUT_SPECIAL_FUNC_31", 0},

    {"DIN_FILTER_CNT_0", 0},
    {"DIN_FILTER_CNT_1", 0},
    {"DIN_FILTER_CNT_2", 0},
    {"DIN_FILTER_CNT_3", 0},
    {"DIN_FILTER_CNT_4", 0},
    {"DIN_FILTER_CNT_5", 0},
    {"DIN_FILTER_CNT_6", 0},
    {"DIN_FILTER_CNT_7", 0},
    {"DIN_FILTER_CNT_8", 0},
    {"DIN_FILTER_CNT_9", 0},
    {"DIN_FILTER_CNT_10", 0},
    {"DIN_FILTER_CNT_11", 0},
    {"DIN_FILTER_CNT_12", 0},
    {"DIN_FILTER_CNT_13", 0},
    {"DIN_FILTER_CNT_14", 0},
    {"DIN_FILTER_CNT_15", 0},
    {"DIN_FILTER_CNT_16", 0},
    {"DIN_FILTER_CNT_17", 0},
    {"DIN_FILTER_CNT_18", 0},
    {"DIN_FILTER_CNT_19", 0},
    {"DIN_FILTER_CNT_20", 0},
    {"DIN_FILTER_CNT_21", 0},
    {"DIN_FILTER_CNT_22", 0},
    {"DIN_FILTER_CNT_23", 0},
    {"DIN_FILTER_CNT_24", 0},
    {"DIN_FILTER_CNT_25", 0},
    {"DIN_FILTER_CNT_26", 0},
    {"DIN_FILTER_CNT_27", 0},
    {"DIN_FILTER_CNT_28", 0},
    {"DIN_FILTER_CNT_29", 0},
    {"DIN_FILTER_CNT_30", 0},
    {"DIN_FILTER_CNT_31", 0},
};

namespace rb_config {
    bool initialize(std::string db_name);

    int                             READ_System_Gate_IP(int octet);
    int                             READ_System_Gate_Port(); 

    int                             READ_System_Port_Number(int port_type);

    ROBOT_CONFIG                    READ_Robot_Parameter(int r_code);
    int                             READ_Robot_Model();
    bool                            WRITE_Robot_Model(int mcode);

    std::tuple<int, int, float>     READ_Out_Collision_Para();
    bool                            WRITE_Out_Collision_Para(int onoff, int react, float th);

    std::tuple<int, float, float>   READ_Self_Collision_Para();
    bool                            WRITE_Self_Collision_Para(int mode, float dist_int, float dist_ext);

    std::tuple<int, float, float, float> READ_Gravity_Vector();
    bool                            WRITE_Gravity_Vector(int mode, float gx, float gy, float gz);

    float                           READ_Direct_Teach_Sensitivity(unsigned int j_no);
    bool                            WRITE_Direct_Teach_Sensitivity(unsigned int j_no, float f_value);

    TCP_CONFIG                      READ_Tcp_Parameter(unsigned int t_num);
    bool                            WRITE_Tcp_Parameter(unsigned int t_num, TCP_CONFIG t_conf);

    USERF_CONFIG                    READ_User_Frame(unsigned int u_num);
    bool                            WRITE_User_Frame(unsigned int u_num, USERF_CONFIG u_conf);

    AREA_CONFIG                     READ_Area_Parameter(unsigned int a_num);
    bool                            WRITE_Area_Parameter(unsigned int a_num, AREA_CONFIG a_conf);

    int                             READ_IO_Special_BOX(int in_or_out, unsigned int p_no);
    bool                            WRITE_IO_Special_BOX(int in_or_out, unsigned int p_no, int function_no);
    
    int                             READ_DIN_Filter_Count(unsigned int p_no);
    bool                            WRITE_DIN_Filter_Count(unsigned int p_no, int f_count);
}

#endif // CONFIGCALL_H
