# syntax=docker/dockerfile:1.4
FROM python:3.12-slim

RUN apt-get update && apt-get install -y git curl flatbuffers-compiler dos2unix bash make && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && pip install uv==0.8.18

ENV WORKDIR=/app/backend
WORKDIR ${WORKDIR}

COPY backend/services ./services
COPY backend/packages ./packages
COPY backend/pyproject.toml ./pyproject.toml
COPY backend/uv.lock ./uv.lock

RUN uv sync --all-packages --frozen --group dev

COPY scripts/ ../scripts/
COPY schemas ../schemas
COPY backend/Makefile ./
COPY backend/backend.mk ./

RUN make backend.flatc

COPY scripts/backend/development-entrypoint.sh /usr/local/bin/development-entrypoint.sh
RUN dos2unix /usr/local/bin/development-entrypoint.sh \
  && chmod +x /usr/local/bin/development-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/development-entrypoint.sh"]