FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates dos2unix bash && rm -rf /var/lib/apt/lists/*

WORKDIR /

COPY scripts/backend/production-entrypoint.sh /usr/local/bin/production-entrypoint.sh

RUN dos2unix /usr/local/bin/production-entrypoint.sh \
  && chmod +x /usr/local/bin/production-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/production-entrypoint.sh"]