FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /

COPY scripts/backend/production-entrypoint.sh /usr/local/bin/production-entrypoint.sh
RUN chmod +x /usr/local/bin/production-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/production-entrypoint.sh"]