from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.flow_manager.RB_Flow_Manager_ProgramState import RB_Flow_Manager_ProgramState

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Update_Executor_State(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Update_Executor_State: ...
  @classmethod
  def GetRootAsRequest_Update_Executor_State(cls, buf: bytes, offset: int) -> Request_Update_Executor_State: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def State(self) -> typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED]: ...
  def Error(self) -> str | None: ...
class Request_Update_Executor_StateT(object):
  state: typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED]
  error: str | None
  def __init__(
    self,
    state: typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED] = ...,
    error: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Update_Executor_StateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Update_Executor_StateT: ...
  @classmethod
  def InitFromObj(cls, requestUpdateExecutorState: Request_Update_Executor_State) -> Request_Update_Executor_StateT: ...
  def _UnPack(self, requestUpdateExecutorState: Request_Update_Executor_State) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Update_Executor_StateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Update_Executor_StateAddState(builder: flatbuffers.Builder, state: typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED]) -> None: ...
def Request_Update_Executor_StateAddError(builder: flatbuffers.Builder, error: uoffset) -> None: ...
def Request_Update_Executor_StateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

