from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.flow_manager.RB_Flow_Manager_ProgramState import RB_Flow_Manager_ProgramState
from rb_flat_buffers.flow_manager.Request_Update_Task_State import Request_Update_Task_State

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Update_Task_State(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Update_Task_State: ...
  @classmethod
  def GetRootAsRequest_Update_Task_State(cls, buf: bytes, offset: int) -> Request_Update_Task_State: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TaskId(self) -> str | None: ...
  def State(self) -> typing.Literal[RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED]: ...
class Request_Update_Task_StateT(object):
  taskId: str | None
  state: typing.Literal[RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Update_Task_StateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Update_Task_StateT: ...
  @classmethod
  def InitFromObj(cls, requestUpdateTaskState: Request_Update_Task_State) -> Request_Update_Task_StateT: ...
  def _UnPack(self, requestUpdateTaskState: Request_Update_Task_State) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Update_Task_StateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Update_Task_StateAddTaskId(builder: flatbuffers.Builder, taskId: uoffset) -> None: ...
def Request_Update_Task_StateAddState(builder: flatbuffers.Builder, state: typing.Literal[RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED]) -> None: ...
def Request_Update_Task_StateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

