from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.flow_manager.RB_Flow_Manager_ProgramState import RB_Flow_Manager_ProgramState

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Update_All_Step_State(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Update_All_Step_State: ...
  @classmethod
  def GetRootAsRequest_Update_All_Step_State(cls, buf: bytes, offset: int) -> Request_Update_All_Step_State: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TaskId(self) -> str | None: ...
  def State(self) -> typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED, RB_Flow_Manager_ProgramState.AFTER_COMPLETED]: ...
class Request_Update_All_Step_StateT(object):
  taskId: str | None
  state: typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED, RB_Flow_Manager_ProgramState.AFTER_COMPLETED]
  def __init__(
    self,
    taskId: str | None = ...,
    state: typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED, RB_Flow_Manager_ProgramState.AFTER_COMPLETED] = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Update_All_Step_StateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Update_All_Step_StateT: ...
  @classmethod
  def InitFromObj(cls, requestUpdateAllStepState: Request_Update_All_Step_State) -> Request_Update_All_Step_StateT: ...
  def _UnPack(self, requestUpdateAllStepState: Request_Update_All_Step_State) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Update_All_Step_StateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Update_All_Step_StateAddTaskId(builder: flatbuffers.Builder, taskId: uoffset) -> None: ...
def Request_Update_All_Step_StateAddState(builder: flatbuffers.Builder, state: typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED, RB_Flow_Manager_ProgramState.AFTER_COMPLETED]) -> None: ...
def Request_Update_All_Step_StateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

