from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Test_Advanced(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Test_Advanced: ...
  @classmethod
  def GetRootAsTest_Advanced(cls, buf: bytes, offset: int) -> Test_Advanced: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Test(self) -> float: ...
class Test_AdvancedT(object):
  test: float
  def __init__(
    self,
    test: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Test_AdvancedT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Test_AdvancedT: ...
  @classmethod
  def InitFromObj(cls, testAdvanced: Test_Advanced) -> Test_AdvancedT: ...
  def _UnPack(self, testAdvanced: Test_Advanced) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Test_AdvancedStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Test_AdvancedAddTest(builder: flatbuffers.Builder, test: float) -> None: ...
def Test_AdvancedEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

