from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from Test_General import Test_General

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Test_General(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Test_General: ...
  @classmethod
  def GetRootAsTest_General(cls, buf: bytes, offset: int) -> Test_General: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Test(self) -> float: ...
class Test_GeneralT(object):
  test: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Test_GeneralT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Test_GeneralT: ...
  @classmethod
  def InitFromObj(cls, testGeneral: Test_General) -> Test_GeneralT: ...
  def _UnPack(self, testGeneral: Test_General) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Test_GeneralStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Test_GeneralAddTest(builder: flatbuffers.Builder, test: float) -> None: ...
def Test_GeneralEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

