from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Test(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Test: ...
  @classmethod
  def GetRootAsTest(cls, buf: bytes, offset: int) -> Test: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Test(self) -> float: ...
  def Test2(self, i: int) -> typing.List[float]: ...
  def Test2AsNumpy(self) -> np.ndarray: ...
  def Test2Length(self) -> int: ...
  def Test2IsNone(self) -> bool: ...
class TestT(object):
  test: float
  test2: typing.List[float]
  def __init__(
    self,
    test: float = ...,
    test2: typing.List[float] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> TestT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> TestT: ...
  @classmethod
  def InitFromObj(cls, test: Test) -> TestT: ...
  def _UnPack(self, test: Test) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def TestStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def TestAddTest(builder: flatbuffers.Builder, test: float) -> None: ...
def TestAddTest2(builder: flatbuffers.Builder, test2: uoffset) -> None: ...
def TestStartTest2Vector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartTest2Vector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def TestEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

