from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.BoxParam import BoxParam

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class BoxParam(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def F(self, i: int) -> typing.List[float]: ...
  def FAsNumpy(self) -> np.ndarray: ...
  def FLength(self) -> int: ...
  def FIsNone(self) -> bool: ...
class BoxParamT(object):
  f: typing.List[float]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> BoxParamT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> BoxParamT: ...
  @classmethod
  def InitFromObj(cls, boxParam: BoxParam) -> BoxParamT: ...
  def _UnPack(self, boxParam: BoxParam) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreateBoxParam(builder: flatbuffers.Builder, f: float) -> uoffset: ...

