from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Mat3f import Mat3f

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Mat3f(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def M(self, i: int) -> typing.List[float]: ...
  def MAsNumpy(self) -> np.ndarray: ...
  def MLength(self) -> int: ...
  def MIsNone(self) -> bool: ...
class Mat3fT(object):
  m: typing.List[float]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Mat3fT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Mat3fT: ...
  @classmethod
  def InitFromObj(cls, mat3f: Mat3f) -> Mat3fT: ...
  def _UnPack(self, mat3f: Mat3f) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreateMat3f(builder: flatbuffers.Builder, m: float) -> uoffset: ...

