from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.MoveInput_Type import MoveInput_Type

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MoveInput_Type(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MoveInput_Type: ...
  @classmethod
  def GetRootAsMoveInput_Type(cls, buf: bytes, offset: int) -> MoveInput_Type: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PntType(self) -> int: ...
  def PntPara(self) -> float: ...
class MoveInput_TypeT(object):
  pntType: int
  pntPara: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> MoveInput_TypeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> MoveInput_TypeT: ...
  @classmethod
  def InitFromObj(cls, moveInputType: MoveInput_Type) -> MoveInput_TypeT: ...
  def _UnPack(self, moveInputType: MoveInput_Type) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def MoveInput_TypeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MoveInput_TypeAddPntType(builder: flatbuffers.Builder, pntType: int) -> None: ...
def MoveInput_TypeAddPntPara(builder: flatbuffers.Builder, pntPara: float) -> None: ...
def MoveInput_TypeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

