from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.N_INPUT_f import N_INPUT_f

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class N_INPUT_f(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def F(self, i: int) -> typing.List[float]: ...
  def FAsNumpy(self) -> np.ndarray: ...
  def FLength(self) -> int: ...
  def FIsNone(self) -> bool: ...
class N_INPUT_fT(object):
  f: typing.List[float]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> N_INPUT_fT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> N_INPUT_fT: ...
  @classmethod
  def InitFromObj(cls, nInputF: N_INPUT_f) -> N_INPUT_fT: ...
  def _UnPack(self, nInputF: N_INPUT_f) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreateN_INPUT_f(builder: flatbuffers.Builder, f: float) -> uoffset: ...

