from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.N_CARTE_f import N_CARTE_f, N_CARTE_fT
from flat_buffers.IPC.Request_Move_L import Request_Move_L

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_L(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_L: ...
  @classmethod
  def GetRootAsRequest_Move_L(cls, buf: bytes, offset: int) -> Request_Move_L: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Targetvalue(self) -> N_CARTE_f | None: ...
  def Frame(self) -> int: ...
  def Unit(self) -> int: ...
  def SpeedMmps(self) -> float: ...
  def AccelMmpss(self) -> float: ...
class Request_Move_LT(object):
  targetvalue: N_CARTE_fT | None
  frame: int
  unit: int
  speedMmps: float
  accelMmpss: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_LT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_LT: ...
  @classmethod
  def InitFromObj(cls, requestMoveL: Request_Move_L) -> Request_Move_LT: ...
  def _UnPack(self, requestMoveL: Request_Move_L) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_LStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_LAddTargetvalue(builder: flatbuffers.Builder, targetvalue: uoffset) -> None: ...
def Request_Move_LAddFrame(builder: flatbuffers.Builder, frame: int) -> None: ...
def Request_Move_LAddUnit(builder: flatbuffers.Builder, unit: int) -> None: ...
def Request_Move_LAddSpeedMmps(builder: flatbuffers.Builder, speedMmps: float) -> None: ...
def Request_Move_LAddAccelMmpss(builder: flatbuffers.Builder, accelMmpss: float) -> None: ...
def Request_Move_LEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

