from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.N_CARTE_f import N_CARTE_f, N_CARTE_fT
from flat_buffers.IPC.Request_MotionSmoothJogL import Request_MotionSmoothJogL

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_MotionSmoothJogL(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_MotionSmoothJogL: ...
  @classmethod
  def GetRootAsRequest_MotionSmoothJogL(cls, buf: bytes, offset: int) -> Request_MotionSmoothJogL: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Targetspeed(self) -> N_CARTE_f | None: ...
  def Frame(self) -> int: ...
  def Unit(self) -> int: ...
class Request_MotionSmoothJogLT(object):
  targetspeed: N_CARTE_fT | None
  frame: int
  unit: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_MotionSmoothJogLT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_MotionSmoothJogLT: ...
  @classmethod
  def InitFromObj(cls, requestMotionSmoothJogL: Request_MotionSmoothJogL) -> Request_MotionSmoothJogLT: ...
  def _UnPack(self, requestMotionSmoothJogL: Request_MotionSmoothJogL) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_MotionSmoothJogLStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_MotionSmoothJogLAddTargetspeed(builder: flatbuffers.Builder, targetspeed: uoffset) -> None: ...
def Request_MotionSmoothJogLAddFrame(builder: flatbuffers.Builder, frame: int) -> None: ...
def Request_MotionSmoothJogLAddUnit(builder: flatbuffers.Builder, unit: int) -> None: ...
def Request_MotionSmoothJogLEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

