from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.N_JOINT_f import N_JOINT_f, N_JOINT_fT
from flat_buffers.IPC.Request_Save_Direct_Teach_Sensitivity import Request_Save_Direct_Teach_Sensitivity

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Save_Direct_Teach_Sensitivity(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Save_Direct_Teach_Sensitivity: ...
  @classmethod
  def GetRootAsRequest_Save_Direct_Teach_Sensitivity(cls, buf: bytes, offset: int) -> Request_Save_Direct_Teach_Sensitivity: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Sensitivity(self) -> N_JOINT_f | None: ...
class Request_Save_Direct_Teach_SensitivityT(object):
  sensitivity: N_JOINT_fT | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Save_Direct_Teach_SensitivityT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Save_Direct_Teach_SensitivityT: ...
  @classmethod
  def InitFromObj(cls, requestSaveDirectTeachSensitivity: Request_Save_Direct_Teach_Sensitivity) -> Request_Save_Direct_Teach_SensitivityT: ...
  def _UnPack(self, requestSaveDirectTeachSensitivity: Request_Save_Direct_Teach_Sensitivity) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Save_Direct_Teach_SensitivityStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Save_Direct_Teach_SensitivityAddSensitivity(builder: flatbuffers.Builder, sensitivity: uoffset) -> None: ...
def Request_Save_Direct_Teach_SensitivityEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

