from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.MoveInput_Speed import MoveInput_Speed, MoveInput_SpeedT
from flat_buffers.IPC.MoveInput_Target import MoveInput_Target, MoveInput_TargetT
from flat_buffers.IPC.Request_Move_J import Request_Move_J

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_J(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_J: ...
  @classmethod
  def GetRootAsRequest_Move_J(cls, buf: bytes, offset: int) -> Request_Move_J: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Target(self) -> MoveInput_Target | None: ...
  def Speed(self) -> MoveInput_Speed | None: ...
class Request_Move_JT(object):
  target: MoveInput_TargetT | None
  speed: MoveInput_SpeedT | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_JT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_JT: ...
  @classmethod
  def InitFromObj(cls, requestMoveJ: Request_Move_J) -> Request_Move_JT: ...
  def _UnPack(self, requestMoveJ: Request_Move_J) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_JStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_JAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Request_Move_JAddSpeed(builder: flatbuffers.Builder, speed: uoffset) -> None: ...
def Request_Move_JEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

