# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Request_State_Whoami(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_State_Whoami()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_State_Whoami(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_State_Whoami
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

def Request_State_WhoamiStart(builder: flatbuffers.Builder):
    builder.StartObject(0)

def Start(builder: flatbuffers.Builder):
    Request_State_WhoamiStart(builder)

def Request_State_WhoamiEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_State_WhoamiEnd(builder)


class Request_State_WhoamiT(object):

    # Request_State_WhoamiT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestStateWhoami = Request_State_Whoami()
        requestStateWhoami.Init(buf, pos)
        return cls.InitFromObj(requestStateWhoami)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestStateWhoami):
        x = Request_State_WhoamiT()
        x._UnPack(requestStateWhoami)
        return x

    # Request_State_WhoamiT
    def _UnPack(self, requestStateWhoami):
        if requestStateWhoami is None:
            return

    # Request_State_WhoamiT
    def Pack(self, builder):
        Request_State_WhoamiStart(builder)
        requestStateWhoami = Request_State_WhoamiEnd(builder)
        return requestStateWhoami
