from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Request_State_Whoami import Request_State_Whoami

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_State_Whoami(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_State_Whoami: ...
  @classmethod
  def GetRootAsRequest_State_Whoami(cls, buf: bytes, offset: int) -> Request_State_Whoami: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_State_WhoamiT(object):
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_State_WhoamiT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_State_WhoamiT: ...
  @classmethod
  def InitFromObj(cls, requestStateWhoami: Request_State_Whoami) -> Request_State_WhoamiT: ...
  def _UnPack(self, requestStateWhoami: Request_State_Whoami) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_State_WhoamiStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_State_WhoamiEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

