from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Request_Save_User_Frame import Request_Save_User_Frame

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Save_User_Frame(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Save_User_Frame: ...
  @classmethod
  def GetRootAsRequest_Save_User_Frame(cls, buf: bytes, offset: int) -> Request_Save_User_Frame: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def UserfNo(self) -> int: ...
  def UserfName(self) -> str | None: ...
  def UserfX(self) -> float: ...
  def UserfY(self) -> float: ...
  def UserfZ(self) -> float: ...
  def UserfRx(self) -> float: ...
  def UserfRy(self) -> float: ...
  def UserfRz(self) -> float: ...
class Request_Save_User_FrameT(object):
  userfNo: int
  userfName: str | None
  userfX: float
  userfY: float
  userfZ: float
  userfRx: float
  userfRy: float
  userfRz: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Save_User_FrameT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Save_User_FrameT: ...
  @classmethod
  def InitFromObj(cls, requestSaveUserFrame: Request_Save_User_Frame) -> Request_Save_User_FrameT: ...
  def _UnPack(self, requestSaveUserFrame: Request_Save_User_Frame) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Save_User_FrameStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Save_User_FrameAddUserfNo(builder: flatbuffers.Builder, userfNo: int) -> None: ...
def Request_Save_User_FrameAddUserfName(builder: flatbuffers.Builder, userfName: uoffset) -> None: ...
def Request_Save_User_FrameAddUserfX(builder: flatbuffers.Builder, userfX: float) -> None: ...
def Request_Save_User_FrameAddUserfY(builder: flatbuffers.Builder, userfY: float) -> None: ...
def Request_Save_User_FrameAddUserfZ(builder: flatbuffers.Builder, userfZ: float) -> None: ...
def Request_Save_User_FrameAddUserfRx(builder: flatbuffers.Builder, userfRx: float) -> None: ...
def Request_Save_User_FrameAddUserfRy(builder: flatbuffers.Builder, userfRy: float) -> None: ...
def Request_Save_User_FrameAddUserfRz(builder: flatbuffers.Builder, userfRz: float) -> None: ...
def Request_Save_User_FrameEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

