from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Request_Move_LB_RUN import Request_Move_LB_RUN

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_LB_RUN(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_LB_RUN: ...
  @classmethod
  def GetRootAsRequest_Move_LB_RUN(cls, buf: bytes, offset: int) -> Request_Move_LB_RUN: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Orientation(self) -> int: ...
class Request_Move_LB_RUNT(object):
  orientation: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_LB_RUNT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_LB_RUNT: ...
  @classmethod
  def InitFromObj(cls, requestMoveLbRun: Request_Move_LB_RUN) -> Request_Move_LB_RUNT: ...
  def _UnPack(self, requestMoveLbRun: Request_Move_LB_RUN) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_LB_RUNStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_LB_RUNAddOrientation(builder: flatbuffers.Builder, orientation: int) -> None: ...
def Request_Move_LB_RUNEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

