from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Request_Move_JB_CLR import Request_Move_JB_CLR

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_JB_CLR(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_JB_CLR: ...
  @classmethod
  def GetRootAsRequest_Move_JB_CLR(cls, buf: bytes, offset: int) -> Request_Move_JB_CLR: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_Move_JB_CLRT(object):
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_JB_CLRT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_JB_CLRT: ...
  @classmethod
  def InitFromObj(cls, requestMoveJbClr: Request_Move_JB_CLR) -> Request_Move_JB_CLRT: ...
  def _UnPack(self, requestMoveJbClr: Request_Move_JB_CLR) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_JB_CLRStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_JB_CLREnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

