from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Request_Save_Collision_Parameter import Request_Save_Collision_Parameter

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Save_Collision_Parameter(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Save_Collision_Parameter: ...
  @classmethod
  def GetRootAsRequest_Save_Collision_Parameter(cls, buf: bytes, offset: int) -> Request_Save_Collision_Parameter: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Onoff(self) -> int: ...
  def React(self) -> int: ...
  def Threshold(self) -> float: ...
class Request_Save_Collision_ParameterT(object):
  onoff: int
  react: int
  threshold: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Save_Collision_ParameterT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Save_Collision_ParameterT: ...
  @classmethod
  def InitFromObj(cls, requestSaveCollisionParameter: Request_Save_Collision_Parameter) -> Request_Save_Collision_ParameterT: ...
  def _UnPack(self, requestSaveCollisionParameter: Request_Save_Collision_Parameter) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Save_Collision_ParameterStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Save_Collision_ParameterAddOnoff(builder: flatbuffers.Builder, onoff: int) -> None: ...
def Request_Save_Collision_ParameterAddReact(builder: flatbuffers.Builder, react: int) -> None: ...
def Request_Save_Collision_ParameterAddThreshold(builder: flatbuffers.Builder, threshold: float) -> None: ...
def Request_Save_Collision_ParameterEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

