from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.N_INPUT_f import N_INPUT_f, N_INPUT_fT
from flat_buffers.IPC.Request_Move_J import Request_Move_J

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_J(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_J: ...
  @classmethod
  def GetRootAsRequest_Move_J(cls, buf: bytes, offset: int) -> Request_Move_J: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Targetvalue(self) -> N_INPUT_f | None: ...
  def Frame(self) -> int: ...
  def Unit(self) -> int: ...
  def SpeedRate(self) -> float: ...
  def AccelRate(self) -> float: ...
class Request_Move_JT(object):
  targetvalue: N_INPUT_fT | None
  frame: int
  unit: int
  speedRate: float
  accelRate: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_JT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_JT: ...
  @classmethod
  def InitFromObj(cls, requestMoveJ: Request_Move_J) -> Request_Move_JT: ...
  def _UnPack(self, requestMoveJ: Request_Move_J) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_JStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_JAddTargetvalue(builder: flatbuffers.Builder, targetvalue: uoffset) -> None: ...
def Request_Move_JAddFrame(builder: flatbuffers.Builder, frame: int) -> None: ...
def Request_Move_JAddUnit(builder: flatbuffers.Builder, unit: int) -> None: ...
def Request_Move_JAddSpeedRate(builder: flatbuffers.Builder, speedRate: float) -> None: ...
def Request_Move_JAddAccelRate(builder: flatbuffers.Builder, accelRate: float) -> None: ...
def Request_Move_JEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

