from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Request_MotionPause import Request_MotionPause

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_MotionPause(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_MotionPause: ...
  @classmethod
  def GetRootAsRequest_MotionPause(cls, buf: bytes, offset: int) -> Request_MotionPause: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_MotionPauseT(object):
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_MotionPauseT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_MotionPauseT: ...
  @classmethod
  def InitFromObj(cls, requestMotionPause: Request_MotionPause) -> Request_MotionPauseT: ...
  def _UnPack(self, requestMotionPause: Request_MotionPause) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_MotionPauseStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_MotionPauseEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

