from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Request_MotionSmoothJogStop import Request_MotionSmoothJogStop

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_MotionSmoothJogStop(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_MotionSmoothJogStop: ...
  @classmethod
  def GetRootAsRequest_MotionSmoothJogStop(cls, buf: bytes, offset: int) -> Request_MotionSmoothJogStop: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Stoptime(self) -> float: ...
class Request_MotionSmoothJogStopT(object):
  stoptime: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_MotionSmoothJogStopT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_MotionSmoothJogStopT: ...
  @classmethod
  def InitFromObj(cls, requestMotionSmoothJogStop: Request_MotionSmoothJogStop) -> Request_MotionSmoothJogStopT: ...
  def _UnPack(self, requestMotionSmoothJogStop: Request_MotionSmoothJogStop) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_MotionSmoothJogStopStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_MotionSmoothJogStopAddStoptime(builder: flatbuffers.Builder, stoptime: float) -> None: ...
def Request_MotionSmoothJogStopEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

