# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Request_ServoControl(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_ServoControl()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_ServoControl(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_ServoControl
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_ServoControl
    def ServoOption(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Request_ServoControlStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    Request_ServoControlStart(builder)

def Request_ServoControlAddServoOption(builder: flatbuffers.Builder, servoOption: int):
    builder.PrependInt32Slot(0, servoOption, 0)

def AddServoOption(builder: flatbuffers.Builder, servoOption: int):
    Request_ServoControlAddServoOption(builder, servoOption)

def Request_ServoControlEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_ServoControlEnd(builder)


class Request_ServoControlT(object):

    # Request_ServoControlT
    def __init__(self):
        self.servoOption = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestServoControl = Request_ServoControl()
        requestServoControl.Init(buf, pos)
        return cls.InitFromObj(requestServoControl)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestServoControl):
        x = Request_ServoControlT()
        x._UnPack(requestServoControl)
        return x

    # Request_ServoControlT
    def _UnPack(self, requestServoControl):
        if requestServoControl is None:
            return
        self.servoOption = requestServoControl.ServoOption()

    # Request_ServoControlT
    def Pack(self, builder):
        Request_ServoControlStart(builder)
        Request_ServoControlAddServoOption(builder, self.servoOption)
        requestServoControl = Request_ServoControlEnd(builder)
        return requestServoControl
