from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Request_Move_JB_RUN import Request_Move_JB_RUN

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_JB_RUN(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_JB_RUN: ...
  @classmethod
  def GetRootAsRequest_Move_JB_RUN(cls, buf: bytes, offset: int) -> Request_Move_JB_RUN: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_Move_JB_RUNT(object):
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_JB_RUNT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_JB_RUNT: ...
  @classmethod
  def InitFromObj(cls, requestMoveJbRun: Request_Move_JB_RUN) -> Request_Move_JB_RUNT: ...
  def _UnPack(self, requestMoveJbRun: Request_Move_JB_RUN) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_JB_RUNStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_JB_RUNEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

