# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Request_MotionSmoothJogStop(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_MotionSmoothJogStop()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_MotionSmoothJogStop(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_MotionSmoothJogStop
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_MotionSmoothJogStop
    def Stoptime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Request_MotionSmoothJogStopStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    Request_MotionSmoothJogStopStart(builder)

def Request_MotionSmoothJogStopAddStoptime(builder: flatbuffers.Builder, stoptime: float):
    builder.PrependFloat32Slot(0, stoptime, 0.0)

def AddStoptime(builder: flatbuffers.Builder, stoptime: float):
    Request_MotionSmoothJogStopAddStoptime(builder, stoptime)

def Request_MotionSmoothJogStopEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_MotionSmoothJogStopEnd(builder)


class Request_MotionSmoothJogStopT(object):

    # Request_MotionSmoothJogStopT
    def __init__(self):
        self.stoptime = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestMotionSmoothJogStop = Request_MotionSmoothJogStop()
        requestMotionSmoothJogStop.Init(buf, pos)
        return cls.InitFromObj(requestMotionSmoothJogStop)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestMotionSmoothJogStop):
        x = Request_MotionSmoothJogStopT()
        x._UnPack(requestMotionSmoothJogStop)
        return x

    # Request_MotionSmoothJogStopT
    def _UnPack(self, requestMotionSmoothJogStop):
        if requestMotionSmoothJogStop is None:
            return
        self.stoptime = requestMotionSmoothJogStop.Stoptime()

    # Request_MotionSmoothJogStopT
    def Pack(self, builder):
        Request_MotionSmoothJogStopStart(builder)
        Request_MotionSmoothJogStopAddStoptime(builder, self.stoptime)
        requestMotionSmoothJogStop = Request_MotionSmoothJogStopEnd(builder)
        return requestMotionSmoothJogStop
