from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Request_CallConfigToolList import Request_CallConfigToolList

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_CallConfigToolList(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_CallConfigToolList: ...
  @classmethod
  def GetRootAsRequest_CallConfigToolList(cls, buf: bytes, offset: int) -> Request_CallConfigToolList: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_CallConfigToolListT(object):
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_CallConfigToolListT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_CallConfigToolListT: ...
  @classmethod
  def InitFromObj(cls, requestCallConfigToolList: Request_CallConfigToolList) -> Request_CallConfigToolListT: ...
  def _UnPack(self, requestCallConfigToolList: Request_CallConfigToolList) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_CallConfigToolListStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_CallConfigToolListEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

