from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.N_JOINT_f import N_JOINT_f, N_JOINT_fT
from flat_buffers.IPC.Request_MotionSmoothJogJ import Request_MotionSmoothJogJ

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_MotionSmoothJogJ(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_MotionSmoothJogJ: ...
  @classmethod
  def GetRootAsRequest_MotionSmoothJogJ(cls, buf: bytes, offset: int) -> Request_MotionSmoothJogJ: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Targetspeed(self) -> N_JOINT_f | None: ...
  def Frame(self) -> int: ...
  def Unit(self) -> int: ...
class Request_MotionSmoothJogJT(object):
  targetspeed: N_JOINT_fT | None
  frame: int
  unit: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_MotionSmoothJogJT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_MotionSmoothJogJT: ...
  @classmethod
  def InitFromObj(cls, requestMotionSmoothJogJ: Request_MotionSmoothJogJ) -> Request_MotionSmoothJogJT: ...
  def _UnPack(self, requestMotionSmoothJogJ: Request_MotionSmoothJogJ) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_MotionSmoothJogJStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_MotionSmoothJogJAddTargetspeed(builder: flatbuffers.Builder, targetspeed: uoffset) -> None: ...
def Request_MotionSmoothJogJAddFrame(builder: flatbuffers.Builder, frame: int) -> None: ...
def Request_MotionSmoothJogJAddUnit(builder: flatbuffers.Builder, unit: int) -> None: ...
def Request_MotionSmoothJogJEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

