from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.N_JOINT_f import N_JOINT_f, N_JOINT_fT
from flat_buffers.IPC.Response_CallConfigRobotArm import Response_CallConfigRobotArm

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_CallConfigRobotArm(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_CallConfigRobotArm: ...
  @classmethod
  def GetRootAsResponse_CallConfigRobotArm(cls, buf: bytes, offset: int) -> Response_CallConfigRobotArm: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def OutCollOnoff(self) -> int: ...
  def OutCollReact(self) -> int: ...
  def OutCollLimit(self) -> float: ...
  def DirectTeachingSensitivity(self) -> N_JOINT_f | None: ...
class Response_CallConfigRobotArmT(object):
  outCollOnoff: int
  outCollReact: int
  outCollLimit: float
  directTeachingSensitivity: N_JOINT_fT | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_CallConfigRobotArmT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_CallConfigRobotArmT: ...
  @classmethod
  def InitFromObj(cls, responseCallConfigRobotArm: Response_CallConfigRobotArm) -> Response_CallConfigRobotArmT: ...
  def _UnPack(self, responseCallConfigRobotArm: Response_CallConfigRobotArm) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_CallConfigRobotArmStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_CallConfigRobotArmAddOutCollOnoff(builder: flatbuffers.Builder, outCollOnoff: int) -> None: ...
def Response_CallConfigRobotArmAddOutCollReact(builder: flatbuffers.Builder, outCollReact: int) -> None: ...
def Response_CallConfigRobotArmAddOutCollLimit(builder: flatbuffers.Builder, outCollLimit: float) -> None: ...
def Response_CallConfigRobotArmAddDirectTeachingSensitivity(builder: flatbuffers.Builder, directTeachingSensitivity: uoffset) -> None: ...
def Response_CallConfigRobotArmEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

