from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Response_CallWhoamI import Response_CallWhoamI

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_CallWhoamI(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_CallWhoamI: ...
  @classmethod
  def GetRootAsResponse_CallWhoamI(cls, buf: bytes, offset: int) -> Response_CallWhoamI: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Category(self) -> str | None: ...
  def Model(self) -> str | None: ...
  def Version(self) -> str | None: ...
  def Alias(self) -> str | None: ...
class Response_CallWhoamIT(object):
  category: str | None
  model: str | None
  version: str | None
  alias: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_CallWhoamIT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_CallWhoamIT: ...
  @classmethod
  def InitFromObj(cls, responseCallWhoamI: Response_CallWhoamI) -> Response_CallWhoamIT: ...
  def _UnPack(self, responseCallWhoamI: Response_CallWhoamI) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_CallWhoamIStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_CallWhoamIAddCategory(builder: flatbuffers.Builder, category: uoffset) -> None: ...
def Response_CallWhoamIAddModel(builder: flatbuffers.Builder, model: uoffset) -> None: ...
def Response_CallWhoamIAddVersion(builder: flatbuffers.Builder, version: uoffset) -> None: ...
def Response_CallWhoamIAddAlias(builder: flatbuffers.Builder, alias: uoffset) -> None: ...
def Response_CallWhoamIEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

