from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.State_Config_Tool import State_Config_Tool, State_Config_ToolT
from flat_buffers.IPC.State_Config_ToolList import State_Config_ToolList

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class State_Config_ToolList(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> State_Config_ToolList: ...
  @classmethod
  def GetRootAsState_Config_ToolList(cls, buf: bytes, offset: int) -> State_Config_ToolList: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TConfigs0(self) -> State_Config_Tool | None: ...
  def TConfigs1(self) -> State_Config_Tool | None: ...
  def TConfigs2(self) -> State_Config_Tool | None: ...
  def TConfigs3(self) -> State_Config_Tool | None: ...
  def TConfigs4(self) -> State_Config_Tool | None: ...
  def TConfigs5(self) -> State_Config_Tool | None: ...
  def TConfigs6(self) -> State_Config_Tool | None: ...
  def TConfigs7(self) -> State_Config_Tool | None: ...
class State_Config_ToolListT(object):
  tConfigs0: State_Config_ToolT | None
  tConfigs1: State_Config_ToolT | None
  tConfigs2: State_Config_ToolT | None
  tConfigs3: State_Config_ToolT | None
  tConfigs4: State_Config_ToolT | None
  tConfigs5: State_Config_ToolT | None
  tConfigs6: State_Config_ToolT | None
  tConfigs7: State_Config_ToolT | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> State_Config_ToolListT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> State_Config_ToolListT: ...
  @classmethod
  def InitFromObj(cls, stateConfigToolList: State_Config_ToolList) -> State_Config_ToolListT: ...
  def _UnPack(self, stateConfigToolList: State_Config_ToolList) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def State_Config_ToolListStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def State_Config_ToolListAddTConfigs0(builder: flatbuffers.Builder, tConfigs0: uoffset) -> None: ...
def State_Config_ToolListAddTConfigs1(builder: flatbuffers.Builder, tConfigs1: uoffset) -> None: ...
def State_Config_ToolListAddTConfigs2(builder: flatbuffers.Builder, tConfigs2: uoffset) -> None: ...
def State_Config_ToolListAddTConfigs3(builder: flatbuffers.Builder, tConfigs3: uoffset) -> None: ...
def State_Config_ToolListAddTConfigs4(builder: flatbuffers.Builder, tConfigs4: uoffset) -> None: ...
def State_Config_ToolListAddTConfigs5(builder: flatbuffers.Builder, tConfigs5: uoffset) -> None: ...
def State_Config_ToolListAddTConfigs6(builder: flatbuffers.Builder, tConfigs6: uoffset) -> None: ...
def State_Config_ToolListAddTConfigs7(builder: flatbuffers.Builder, tConfigs7: uoffset) -> None: ...
def State_Config_ToolListEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

