# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from flat_buffers.IPC.N_JOINT_f import N_JOINT_f, N_JOINT_fT
from typing import Optional
np = import_numpy()

class State_Config_RobotArm(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = State_Config_RobotArm()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsState_Config_RobotArm(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # State_Config_RobotArm
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # State_Config_RobotArm
    def OutCollOnoff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Config_RobotArm
    def OutCollReact(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Config_RobotArm
    def OutCollLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Config_RobotArm
    def DirectTeachingSensitivity(self) -> Optional[N_JOINT_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_JOINT_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def State_Config_RobotArmStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    State_Config_RobotArmStart(builder)

def State_Config_RobotArmAddOutCollOnoff(builder: flatbuffers.Builder, outCollOnoff: int):
    builder.PrependUint8Slot(0, outCollOnoff, 0)

def AddOutCollOnoff(builder: flatbuffers.Builder, outCollOnoff: int):
    State_Config_RobotArmAddOutCollOnoff(builder, outCollOnoff)

def State_Config_RobotArmAddOutCollReact(builder: flatbuffers.Builder, outCollReact: int):
    builder.PrependUint8Slot(1, outCollReact, 0)

def AddOutCollReact(builder: flatbuffers.Builder, outCollReact: int):
    State_Config_RobotArmAddOutCollReact(builder, outCollReact)

def State_Config_RobotArmAddOutCollLimit(builder: flatbuffers.Builder, outCollLimit: float):
    builder.PrependFloat32Slot(2, outCollLimit, 0.0)

def AddOutCollLimit(builder: flatbuffers.Builder, outCollLimit: float):
    State_Config_RobotArmAddOutCollLimit(builder, outCollLimit)

def State_Config_RobotArmAddDirectTeachingSensitivity(builder: flatbuffers.Builder, directTeachingSensitivity: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(directTeachingSensitivity), 0)

def AddDirectTeachingSensitivity(builder: flatbuffers.Builder, directTeachingSensitivity: Any):
    State_Config_RobotArmAddDirectTeachingSensitivity(builder, directTeachingSensitivity)

def State_Config_RobotArmEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return State_Config_RobotArmEnd(builder)

try:
    from typing import Optional
except:
    pass

class State_Config_RobotArmT(object):

    # State_Config_RobotArmT
    def __init__(self):
        self.outCollOnoff = 0  # type: int
        self.outCollReact = 0  # type: int
        self.outCollLimit = 0.0  # type: float
        self.directTeachingSensitivity = None  # type: Optional[N_JOINT_fT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        stateConfigRobotArm = State_Config_RobotArm()
        stateConfigRobotArm.Init(buf, pos)
        return cls.InitFromObj(stateConfigRobotArm)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, stateConfigRobotArm):
        x = State_Config_RobotArmT()
        x._UnPack(stateConfigRobotArm)
        return x

    # State_Config_RobotArmT
    def _UnPack(self, stateConfigRobotArm):
        if stateConfigRobotArm is None:
            return
        self.outCollOnoff = stateConfigRobotArm.OutCollOnoff()
        self.outCollReact = stateConfigRobotArm.OutCollReact()
        self.outCollLimit = stateConfigRobotArm.OutCollLimit()
        if stateConfigRobotArm.DirectTeachingSensitivity() is not None:
            self.directTeachingSensitivity = N_JOINT_fT.InitFromObj(stateConfigRobotArm.DirectTeachingSensitivity())

    # State_Config_RobotArmT
    def Pack(self, builder):
        State_Config_RobotArmStart(builder)
        State_Config_RobotArmAddOutCollOnoff(builder, self.outCollOnoff)
        State_Config_RobotArmAddOutCollReact(builder, self.outCollReact)
        State_Config_RobotArmAddOutCollLimit(builder, self.outCollLimit)
        if self.directTeachingSensitivity is not None:
            directTeachingSensitivity = self.directTeachingSensitivity.Pack(builder)
            State_Config_RobotArmAddDirectTeachingSensitivity(builder, directTeachingSensitivity)
        stateConfigRobotArm = State_Config_RobotArmEnd(builder)
        return stateConfigRobotArm
