from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.State_Log import State_Log

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class State_Log(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> State_Log: ...
  @classmethod
  def GetRootAsState_Log(cls, buf: bytes, offset: int) -> State_Log: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Level(self) -> int: ...
  def Timestamp(self) -> str | None: ...
  def Contents(self) -> str | None: ...
class State_LogT(object):
  level: int
  timestamp: str | None
  contents: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> State_LogT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> State_LogT: ...
  @classmethod
  def InitFromObj(cls, stateLog: State_Log) -> State_LogT: ...
  def _UnPack(self, stateLog: State_Log) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def State_LogStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def State_LogAddLevel(builder: flatbuffers.Builder, level: int) -> None: ...
def State_LogAddTimestamp(builder: flatbuffers.Builder, timestamp: uoffset) -> None: ...
def State_LogAddContents(builder: flatbuffers.Builder, contents: uoffset) -> None: ...
def State_LogEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

