from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.State_Message import State_Message

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class State_Message(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> State_Message: ...
  @classmethod
  def GetRootAsState_Message(cls, buf: bytes, offset: int) -> State_Message: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Type(self) -> int: ...
  def Code(self) -> int: ...
  def SubStr(self) -> str | None: ...
class State_MessageT(object):
  type: int
  code: int
  subStr: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> State_MessageT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> State_MessageT: ...
  @classmethod
  def InitFromObj(cls, stateMessage: State_Message) -> State_MessageT: ...
  def _UnPack(self, stateMessage: State_Message) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def State_MessageStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def State_MessageAddType(builder: flatbuffers.Builder, type: int) -> None: ...
def State_MessageAddCode(builder: flatbuffers.Builder, code: int) -> None: ...
def State_MessageAddSubStr(builder: flatbuffers.Builder, subStr: uoffset) -> None: ...
def State_MessageEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

