from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.N_JOINT_f import N_JOINT_f, N_JOINT_fT
from flat_buffers.IPC.State_Config_RobotArm import State_Config_RobotArm

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class State_Config_RobotArm(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> State_Config_RobotArm: ...
  @classmethod
  def GetRootAsState_Config_RobotArm(cls, buf: bytes, offset: int) -> State_Config_RobotArm: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def OutCollOnoff(self) -> int: ...
  def OutCollReact(self) -> int: ...
  def OutCollLimit(self) -> float: ...
  def DirectTeachingSensitivity(self) -> N_JOINT_f | None: ...
class State_Config_RobotArmT(object):
  outCollOnoff: int
  outCollReact: int
  outCollLimit: float
  directTeachingSensitivity: N_JOINT_fT | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> State_Config_RobotArmT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> State_Config_RobotArmT: ...
  @classmethod
  def InitFromObj(cls, stateConfigRobotArm: State_Config_RobotArm) -> State_Config_RobotArmT: ...
  def _UnPack(self, stateConfigRobotArm: State_Config_RobotArm) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def State_Config_RobotArmStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def State_Config_RobotArmAddOutCollOnoff(builder: flatbuffers.Builder, outCollOnoff: int) -> None: ...
def State_Config_RobotArmAddOutCollReact(builder: flatbuffers.Builder, outCollReact: int) -> None: ...
def State_Config_RobotArmAddOutCollLimit(builder: flatbuffers.Builder, outCollLimit: float) -> None: ...
def State_Config_RobotArmAddDirectTeachingSensitivity(builder: flatbuffers.Builder, directTeachingSensitivity: uoffset) -> None: ...
def State_Config_RobotArmEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

