from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.State_Whoami import State_Whoami

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class State_Whoami(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> State_Whoami: ...
  @classmethod
  def GetRootAsState_Whoami(cls, buf: bytes, offset: int) -> State_Whoami: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Category(self) -> str | None: ...
  def Name(self) -> str | None: ...
  def Model(self) -> str | None: ...
  def Version(self) -> str | None: ...
  def Alias(self) -> str | None: ...
class State_WhoamiT(object):
  category: str | None
  name: str | None
  model: str | None
  version: str | None
  alias: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> State_WhoamiT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> State_WhoamiT: ...
  @classmethod
  def InitFromObj(cls, stateWhoami: State_Whoami) -> State_WhoamiT: ...
  def _UnPack(self, stateWhoami: State_Whoami) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def State_WhoamiStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def State_WhoamiAddCategory(builder: flatbuffers.Builder, category: uoffset) -> None: ...
def State_WhoamiAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def State_WhoamiAddModel(builder: flatbuffers.Builder, model: uoffset) -> None: ...
def State_WhoamiAddVersion(builder: flatbuffers.Builder, version: uoffset) -> None: ...
def State_WhoamiAddAlias(builder: flatbuffers.Builder, alias: uoffset) -> None: ...
def State_WhoamiEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

