from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.State_Config_Area import State_Config_Area
from flat_buffers.IPC.Vec3f import Vec3f, Vec3fT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class State_Config_Area(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> State_Config_Area: ...
  @classmethod
  def GetRootAsState_Config_Area(cls, buf: bytes, offset: int) -> State_Config_Area: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def AreaName(self) -> str | None: ...
  def AreaType(self) -> int: ...
  def AreaOffset(self) -> Vec3f | None: ...
  def AreaEuler(self) -> Vec3f | None: ...
  def AreaPara(self) -> Vec3f | None: ...
class State_Config_AreaT(object):
  areaName: str | None
  areaType: int
  areaOffset: Vec3fT | None
  areaEuler: Vec3fT | None
  areaPara: Vec3fT | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> State_Config_AreaT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> State_Config_AreaT: ...
  @classmethod
  def InitFromObj(cls, stateConfigArea: State_Config_Area) -> State_Config_AreaT: ...
  def _UnPack(self, stateConfigArea: State_Config_Area) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def State_Config_AreaStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def State_Config_AreaAddAreaName(builder: flatbuffers.Builder, areaName: uoffset) -> None: ...
def State_Config_AreaAddAreaType(builder: flatbuffers.Builder, areaType: int) -> None: ...
def State_Config_AreaAddAreaOffset(builder: flatbuffers.Builder, areaOffset: uoffset) -> None: ...
def State_Config_AreaAddAreaEuler(builder: flatbuffers.Builder, areaEuler: uoffset) -> None: ...
def State_Config_AreaAddAreaPara(builder: flatbuffers.Builder, areaPara: uoffset) -> None: ...
def State_Config_AreaEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

