from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.N_DIN_u import N_DIN_u, N_DIN_uT
from flat_buffers.IPC.N_DOUT_u import N_DOUT_u, N_DOUT_uT
from flat_buffers.IPC.State_Config_Area import State_Config_Area, State_Config_AreaT
from flat_buffers.IPC.State_Config_ControlBox import State_Config_ControlBox

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class State_Config_ControlBox(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> State_Config_ControlBox: ...
  @classmethod
  def GetRootAsState_Config_ControlBox(cls, buf: bytes, offset: int) -> State_Config_ControlBox: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def DoutSpecialFunc(self) -> N_DOUT_u | None: ...
  def DinSpecialFunc(self) -> N_DIN_u | None: ...
  def DinFilterCount(self) -> N_DIN_u | None: ...
  def AreaConfigs0(self) -> State_Config_Area | None: ...
  def AreaConfigs1(self) -> State_Config_Area | None: ...
  def AreaConfigs2(self) -> State_Config_Area | None: ...
  def AreaConfigs3(self) -> State_Config_Area | None: ...
  def AreaConfigs4(self) -> State_Config_Area | None: ...
  def AreaConfigs5(self) -> State_Config_Area | None: ...
  def AreaConfigs6(self) -> State_Config_Area | None: ...
  def AreaConfigs7(self) -> State_Config_Area | None: ...
class State_Config_ControlBoxT(object):
  doutSpecialFunc: N_DOUT_uT | None
  dinSpecialFunc: N_DIN_uT | None
  dinFilterCount: N_DIN_uT | None
  areaConfigs0: State_Config_AreaT | None
  areaConfigs1: State_Config_AreaT | None
  areaConfigs2: State_Config_AreaT | None
  areaConfigs3: State_Config_AreaT | None
  areaConfigs4: State_Config_AreaT | None
  areaConfigs5: State_Config_AreaT | None
  areaConfigs6: State_Config_AreaT | None
  areaConfigs7: State_Config_AreaT | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> State_Config_ControlBoxT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> State_Config_ControlBoxT: ...
  @classmethod
  def InitFromObj(cls, stateConfigControlBox: State_Config_ControlBox) -> State_Config_ControlBoxT: ...
  def _UnPack(self, stateConfigControlBox: State_Config_ControlBox) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def State_Config_ControlBoxStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def State_Config_ControlBoxAddDoutSpecialFunc(builder: flatbuffers.Builder, doutSpecialFunc: uoffset) -> None: ...
def State_Config_ControlBoxAddDinSpecialFunc(builder: flatbuffers.Builder, dinSpecialFunc: uoffset) -> None: ...
def State_Config_ControlBoxAddDinFilterCount(builder: flatbuffers.Builder, dinFilterCount: uoffset) -> None: ...
def State_Config_ControlBoxAddAreaConfigs0(builder: flatbuffers.Builder, areaConfigs0: uoffset) -> None: ...
def State_Config_ControlBoxAddAreaConfigs1(builder: flatbuffers.Builder, areaConfigs1: uoffset) -> None: ...
def State_Config_ControlBoxAddAreaConfigs2(builder: flatbuffers.Builder, areaConfigs2: uoffset) -> None: ...
def State_Config_ControlBoxAddAreaConfigs3(builder: flatbuffers.Builder, areaConfigs3: uoffset) -> None: ...
def State_Config_ControlBoxAddAreaConfigs4(builder: flatbuffers.Builder, areaConfigs4: uoffset) -> None: ...
def State_Config_ControlBoxAddAreaConfigs5(builder: flatbuffers.Builder, areaConfigs5: uoffset) -> None: ...
def State_Config_ControlBoxAddAreaConfigs6(builder: flatbuffers.Builder, areaConfigs6: uoffset) -> None: ...
def State_Config_ControlBoxAddAreaConfigs7(builder: flatbuffers.Builder, areaConfigs7: uoffset) -> None: ...
def State_Config_ControlBoxEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

