from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.N_CARTE_f import N_CARTE_f, N_CARTE_fT
from flat_buffers.IPC.N_DIN_u import N_DIN_u, N_DIN_uT
from flat_buffers.IPC.N_DOUT_u import N_DOUT_u, N_DOUT_uT
from flat_buffers.IPC.N_JOINT_f import N_JOINT_f, N_JOINT_fT
from flat_buffers.IPC.State_Core import State_Core

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class State_Core(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> State_Core: ...
  @classmethod
  def GetRootAsState_Core(cls, buf: bytes, offset: int) -> State_Core: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def JointQRef(self) -> N_JOINT_f | None: ...
  def JointQEnc(self) -> N_JOINT_f | None: ...
  def JointTEsti(self) -> N_JOINT_f | None: ...
  def JointTMeas(self) -> N_JOINT_f | None: ...
  def JointTemper(self) -> N_JOINT_f | None: ...
  def CarteXRef(self) -> N_CARTE_f | None: ...
  def CarteXEnc(self) -> N_CARTE_f | None: ...
  def CboxDigitalInput(self) -> N_DIN_u | None: ...
  def CboxDigitalOutput(self) -> N_DOUT_u | None: ...
  def MotionMode(self) -> int: ...
  def MotionSpeedBar(self) -> float: ...
  def MotionIsPause(self) -> int: ...
  def StatusLan2can(self) -> int: ...
  def StatusSwitchEmg(self) -> int: ...
  def StatusPowerOut(self) -> int: ...
  def StatusServoNum(self) -> int: ...
  def StatusIsRefon(self) -> int: ...
  def StatusOutColl(self) -> int: ...
  def StatusSelfColl(self) -> int: ...
  def StatusDtMode(self) -> int: ...
class State_CoreT(object):
  jointQRef: N_JOINT_fT | None
  jointQEnc: N_JOINT_fT | None
  jointTEsti: N_JOINT_fT | None
  jointTMeas: N_JOINT_fT | None
  jointTemper: N_JOINT_fT | None
  carteXRef: N_CARTE_fT | None
  carteXEnc: N_CARTE_fT | None
  cboxDigitalInput: N_DIN_uT | None
  cboxDigitalOutput: N_DOUT_uT | None
  motionMode: int
  motionSpeedBar: float
  motionIsPause: int
  statusLan2can: int
  statusSwitchEmg: int
  statusPowerOut: int
  statusServoNum: int
  statusIsRefon: int
  statusOutColl: int
  statusSelfColl: int
  statusDtMode: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> State_CoreT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> State_CoreT: ...
  @classmethod
  def InitFromObj(cls, stateCore: State_Core) -> State_CoreT: ...
  def _UnPack(self, stateCore: State_Core) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def State_CoreStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def State_CoreAddJointQRef(builder: flatbuffers.Builder, jointQRef: uoffset) -> None: ...
def State_CoreAddJointQEnc(builder: flatbuffers.Builder, jointQEnc: uoffset) -> None: ...
def State_CoreAddJointTEsti(builder: flatbuffers.Builder, jointTEsti: uoffset) -> None: ...
def State_CoreAddJointTMeas(builder: flatbuffers.Builder, jointTMeas: uoffset) -> None: ...
def State_CoreAddJointTemper(builder: flatbuffers.Builder, jointTemper: uoffset) -> None: ...
def State_CoreAddCarteXRef(builder: flatbuffers.Builder, carteXRef: uoffset) -> None: ...
def State_CoreAddCarteXEnc(builder: flatbuffers.Builder, carteXEnc: uoffset) -> None: ...
def State_CoreAddCboxDigitalInput(builder: flatbuffers.Builder, cboxDigitalInput: uoffset) -> None: ...
def State_CoreAddCboxDigitalOutput(builder: flatbuffers.Builder, cboxDigitalOutput: uoffset) -> None: ...
def State_CoreAddMotionMode(builder: flatbuffers.Builder, motionMode: int) -> None: ...
def State_CoreAddMotionSpeedBar(builder: flatbuffers.Builder, motionSpeedBar: float) -> None: ...
def State_CoreAddMotionIsPause(builder: flatbuffers.Builder, motionIsPause: int) -> None: ...
def State_CoreAddStatusLan2can(builder: flatbuffers.Builder, statusLan2can: int) -> None: ...
def State_CoreAddStatusSwitchEmg(builder: flatbuffers.Builder, statusSwitchEmg: int) -> None: ...
def State_CoreAddStatusPowerOut(builder: flatbuffers.Builder, statusPowerOut: int) -> None: ...
def State_CoreAddStatusServoNum(builder: flatbuffers.Builder, statusServoNum: int) -> None: ...
def State_CoreAddStatusIsRefon(builder: flatbuffers.Builder, statusIsRefon: int) -> None: ...
def State_CoreAddStatusOutColl(builder: flatbuffers.Builder, statusOutColl: int) -> None: ...
def State_CoreAddStatusSelfColl(builder: flatbuffers.Builder, statusSelfColl: int) -> None: ...
def State_CoreAddStatusDtMode(builder: flatbuffers.Builder, statusDtMode: int) -> None: ...
def State_CoreEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

