from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.BoxParam import BoxParam, BoxParamT
from flat_buffers.IPC.State_Config_Tool import State_Config_Tool
from flat_buffers.IPC.Vec3f import Vec3f, Vec3fT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class State_Config_Tool(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> State_Config_Tool: ...
  @classmethod
  def GetRootAsState_Config_Tool(cls, buf: bytes, offset: int) -> State_Config_Tool: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ToolName(self) -> str | None: ...
  def ComMass(self) -> float: ...
  def ComOffset(self) -> Vec3f | None: ...
  def TcpOffset(self) -> Vec3f | None: ...
  def TcpEuler(self) -> Vec3f | None: ...
  def BoxType(self) -> int: ...
  def BoxParameter(self) -> BoxParam | None: ...
class State_Config_ToolT(object):
  toolName: str | None
  comMass: float
  comOffset: Vec3fT | None
  tcpOffset: Vec3fT | None
  tcpEuler: Vec3fT | None
  boxType: int
  boxParameter: BoxParamT | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> State_Config_ToolT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> State_Config_ToolT: ...
  @classmethod
  def InitFromObj(cls, stateConfigTool: State_Config_Tool) -> State_Config_ToolT: ...
  def _UnPack(self, stateConfigTool: State_Config_Tool) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def State_Config_ToolStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def State_Config_ToolAddToolName(builder: flatbuffers.Builder, toolName: uoffset) -> None: ...
def State_Config_ToolAddComMass(builder: flatbuffers.Builder, comMass: float) -> None: ...
def State_Config_ToolAddComOffset(builder: flatbuffers.Builder, comOffset: uoffset) -> None: ...
def State_Config_ToolAddTcpOffset(builder: flatbuffers.Builder, tcpOffset: uoffset) -> None: ...
def State_Config_ToolAddTcpEuler(builder: flatbuffers.Builder, tcpEuler: uoffset) -> None: ...
def State_Config_ToolAddBoxType(builder: flatbuffers.Builder, boxType: int) -> None: ...
def State_Config_ToolAddBoxParameter(builder: flatbuffers.Builder, boxParameter: uoffset) -> None: ...
def State_Config_ToolEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

