from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.IPC.Vec3f import Vec3f

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Vec3f(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def V(self, i: int) -> typing.List[float]: ...
  def VAsNumpy(self) -> np.ndarray: ...
  def VLength(self) -> int: ...
  def VIsNone(self) -> bool: ...
class Vec3fT(object):
  v: typing.List[float]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Vec3fT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Vec3fT: ...
  @classmethod
  def InitFromObj(cls, vec3f: Vec3f) -> Vec3fT: ...
  def _UnPack(self, vec3f: Vec3f) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreateVec3f(builder: flatbuffers.Builder, v: float) -> uoffset: ...

