# AUTO-GENERATED by scripts/backend/fbs_to_pydantic.py. Derek said 'DO NOT EDIT. ㅡㅡ#'
from __future__ import annotations

from enum import Enum
from typing import List
from pydantic import BaseModel, ConfigDict, Field

from .common_struct_models import *  # noqa: F401,F403
from .func_return_models import *  # noqa: F401,F403

NAMESPACE = "IPC"

class NullSpacePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    pass

class Request_MotionSpeedBarPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    alpha: float | None = Field(default=None)

class Request_MotionPausePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    pass

class Request_MotionResumePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    pass

class Request_MotionResetOutCollPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    pass

class Request_MotionHaltPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    pass

class Request_ProgramBeforePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    option: int | None = Field(default=None)

class Request_ProgramAfterPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    option: int | None = Field(default=None)

__all__ = [
    "NullSpacePD",
    "Request_MotionSpeedBarPD",
    "Request_MotionPausePD",
    "Request_MotionResumePD",
    "Request_MotionResetOutCollPD",
    "Request_MotionHaltPD",
    "Request_ProgramBeforePD",
    "Request_ProgramAfterPD",
]
