# AUTO-GENERATED by scripts/backend/fbs_to_pydantic.py. Derek said 'DO NOT EDIT. ㅡㅡ#'
from __future__ import annotations

from enum import Enum
from typing import List
from pydantic import BaseModel, ConfigDict, Field

NAMESPACE = "IPC"

class Response_FunctionsPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    return_value: int | None = Field(alias="returnValue", default=None)

class Request_PrintInfoPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    pass

__all__ = [
    "Response_FunctionsPD",
    "Request_PrintInfoPD",
]
