# AUTO-GENERATED by scripts/backend/fbs_to_pydantic.py. Derek said 'DO NOT EDIT. ㅡㅡ#'
from __future__ import annotations

from enum import Enum
from typing import List
from pydantic import BaseModel, ConfigDict, Field

from .common_struct_models import *  # noqa: F401,F403
from .func_return_models import *  # noqa: F401,F403

NAMESPACE = "IPC"

class Request_Save_Collision_ParameterPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    onoff: int | None = Field(default=None)
    react: int | None = Field(default=None)
    threshold: float | None = Field(default=None)

class Request_Save_SelfColl_ParameterPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    mode: int | None = Field(default=None)
    dist_internal: float | None = Field(alias="distInternal", default=None)
    dist_external: float | None = Field(alias="distExternal", default=None)

class Request_Save_Gravity_ParameterPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    mode: int | None = Field(default=None)
    gx: float | None = Field(default=None)
    gy: float | None = Field(default=None)
    gz: float | None = Field(default=None)

class Request_Save_Direct_Teach_SensitivityPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    sensitivity: N_JOINT_fPD | None = Field(default=None)

class Request_Save_Tool_List_ParaPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    tool_no: int | None = Field(alias="toolNo", default=None)
    tool_name: str | None = Field(alias="toolName", json_schema_extra={"example": ""}, default=None)
    tcp_x: float | None = Field(alias="tcpX", default=None)
    tcp_y: float | None = Field(alias="tcpY", default=None)
    tcp_z: float | None = Field(alias="tcpZ", default=None)
    tcp_rx: float | None = Field(alias="tcpRx", default=None)
    tcp_ry: float | None = Field(alias="tcpRy", default=None)
    tcp_rz: float | None = Field(alias="tcpRz", default=None)
    mass_m: float | None = Field(alias="massM", default=None)
    mass_x: float | None = Field(alias="massX", default=None)
    mass_y: float | None = Field(alias="massY", default=None)
    mass_z: float | None = Field(alias="massZ", default=None)
    box_type: int | None = Field(alias="boxType", default=None)
    box_para_0: float | None = Field(alias="boxPara0", default=None)
    box_para_1: float | None = Field(alias="boxPara1", default=None)
    box_para_2: float | None = Field(alias="boxPara2", default=None)
    box_para_3: float | None = Field(alias="boxPara3", default=None)
    box_para_4: float | None = Field(alias="boxPara4", default=None)
    box_para_5: float | None = Field(alias="boxPara5", default=None)
    box_para_6: float | None = Field(alias="boxPara6", default=None)
    box_para_7: float | None = Field(alias="boxPara7", default=None)
    box_para_8: float | None = Field(alias="boxPara8", default=None)

__all__ = [
    "Request_Save_Collision_ParameterPD",
    "Request_Save_SelfColl_ParameterPD",
    "Request_Save_Gravity_ParameterPD",
    "Request_Save_Direct_Teach_SensitivityPD",
    "Request_Save_Tool_List_ParaPD",
]
