# AUTO-GENERATED by scripts/backend/fbs_to_pydantic.py. Derek said 'DO NOT EDIT. ㅡㅡ#'
from __future__ import annotations

from enum import Enum
from typing import List
from pydantic import BaseModel, ConfigDict, Field

from .common_struct_models import *  # noqa: F401,F403
from .func_return_models import *  # noqa: F401,F403

NAMESPACE = "IPC"

class Request_Get_Core_DataPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    option: int | None = Field(default=None)
    name: str | None = Field(default=None)

class Response_Get_Core_DataPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    valid: int | None = Field(default=None)
    type: int | None = Field(default=None)
    payload_num: float | None = Field(alias="payloadNum", default=None)
    payload_arr: dict | None = Field(alias="payloadArr", default=None)
    payload_str: str | None = Field(alias="payloadStr", default=None)

class Request_Get_Relative_ValuePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    relative_value: dict | None = Field(alias="relativeValue", default=None)
    reference_value: dict | None = Field(alias="referenceValue", default=None)
    move_type: int | None = Field(alias="moveType", default=None)

class Response_Get_Relative_ValuePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    calculated_result: int | None = Field(alias="calculatedResult", default=None)
    calculated_value: dict | None = Field(alias="calculatedValue", default=None)

class Request_Get_Absolute_ValuePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    reference_value: dict | None = Field(alias="referenceValue", default=None)
    move_type: int | None = Field(alias="moveType", default=None)

class Response_Get_Absolute_ValuePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    calculated_result: int | None = Field(alias="calculatedResult", default=None)
    calculated_value: dict | None = Field(alias="calculatedValue", default=None)

class Request_Get_Tcp_ValuePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    option: int | None = Field(default=None)

class Response_Get_Tcp_ValuePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    carte_info: dict | None = Field(alias="carteInfo", default=None)

class Request_Get_Joint_ValuePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    option: int | None = Field(default=None)

class Response_Get_Joint_ValuePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    joint_info: dict | None = Field(alias="jointInfo", default=None)

__all__ = [
    "Request_Get_Core_DataPD",
    "Response_Get_Core_DataPD",
    "Request_Get_Relative_ValuePD",
    "Response_Get_Relative_ValuePD",
    "Request_Get_Absolute_ValuePD",
    "Response_Get_Absolute_ValuePD",
    "Request_Get_Tcp_ValuePD",
    "Response_Get_Tcp_ValuePD",
    "Request_Get_Joint_ValuePD",
    "Response_Get_Joint_ValuePD",
]
