from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RB_Program_Dialog(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RB_Program_Dialog: ...
  @classmethod
  def GetRootAsRB_Program_Dialog(cls, buf: bytes, offset: int) -> RB_Program_Dialog: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def RobotModel(self) -> str | None: ...
  def Title(self) -> str | None: ...
  def Content(self) -> str | None: ...
class RB_Program_DialogT(object):
  robotModel: str | None
  title: str | None
  content: str | None
  def __init__(
    self,
    robotModel: str | None = ...,
    title: str | None = ...,
    content: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> RB_Program_DialogT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> RB_Program_DialogT: ...
  @classmethod
  def InitFromObj(cls, rbProgramDialog: RB_Program_Dialog) -> RB_Program_DialogT: ...
  def _UnPack(self, rbProgramDialog: RB_Program_Dialog) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def RB_Program_DialogStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RB_Program_DialogAddRobotModel(builder: flatbuffers.Builder, robotModel: uoffset) -> None: ...
def RB_Program_DialogAddTitle(builder: flatbuffers.Builder, title: uoffset) -> None: ...
def RB_Program_DialogAddContent(builder: flatbuffers.Builder, content: uoffset) -> None: ...
def RB_Program_DialogEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

