from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.program.RB_Program_Log_Type import RB_Program_Log_Type

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RB_Program_Log(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RB_Program_Log: ...
  @classmethod
  def GetRootAsRB_Program_Log(cls, buf: bytes, offset: int) -> RB_Program_Log: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Content(self) -> str | None: ...
  def RobotModel(self) -> str | None: ...
  def Type(self) -> typing.Literal[RB_Program_Log_Type.INFO, RB_Program_Log_Type.WARNING, RB_Program_Log_Type.ERROR, RB_Program_Log_Type.USER, RB_Program_Log_Type.DEBUG, RB_Program_Log_Type.GENERAL]: ...
class RB_Program_LogT(object):
  content: str | None
  robotModel: str | None
  type: typing.Literal[RB_Program_Log_Type.INFO, RB_Program_Log_Type.WARNING, RB_Program_Log_Type.ERROR, RB_Program_Log_Type.USER, RB_Program_Log_Type.DEBUG, RB_Program_Log_Type.GENERAL]
  def __init__(
    self,
    content: str | None = ...,
    robotModel: str | None = ...,
    type: typing.Literal[RB_Program_Log_Type.INFO, RB_Program_Log_Type.WARNING, RB_Program_Log_Type.ERROR, RB_Program_Log_Type.USER, RB_Program_Log_Type.DEBUG, RB_Program_Log_Type.GENERAL] = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> RB_Program_LogT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> RB_Program_LogT: ...
  @classmethod
  def InitFromObj(cls, rbProgramLog: RB_Program_Log) -> RB_Program_LogT: ...
  def _UnPack(self, rbProgramLog: RB_Program_Log) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def RB_Program_LogStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RB_Program_LogAddContent(builder: flatbuffers.Builder, content: uoffset) -> None: ...
def RB_Program_LogAddRobotModel(builder: flatbuffers.Builder, robotModel: uoffset) -> None: ...
def RB_Program_LogAddType(builder: flatbuffers.Builder, type: typing.Literal[RB_Program_Log_Type.INFO, RB_Program_Log_Type.WARNING, RB_Program_Log_Type.ERROR, RB_Program_Log_Type.USER, RB_Program_Log_Type.DEBUG, RB_Program_Log_Type.GENERAL]) -> None: ...
def RB_Program_LogEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

