from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.program.RB_Program_Task_Status import RB_Program_Task_Status

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RB_Program_Task_Status(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RB_Program_Task_Status: ...
  @classmethod
  def GetRootAsRB_Program_Task_Status(cls, buf: bytes, offset: int) -> RB_Program_Task_Status: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TaskId(self) -> str | None: ...
  def ProgramId(self) -> str | None: ...
  def SyncTaskIds(self, i: int) -> str: ...
  def SyncTaskIdsLength(self) -> int: ...
  def SyncTaskIdsIsNone(self) -> bool: ...
  def NodePath(self, i: int) -> str: ...
  def NodePathLength(self) -> int: ...
  def NodePathIsNone(self) -> bool: ...
  def Status(self) -> str | None: ...
  def Offset(self) -> int: ...
class RB_Program_Task_StatusT(object):
  taskId: str | None
  programId: str | None
  syncTaskIds: typing.List[str]
  nodePath: typing.List[str]
  status: str | None
  offset: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> RB_Program_Task_StatusT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> RB_Program_Task_StatusT: ...
  @classmethod
  def InitFromObj(cls, rbProgramTaskStatus: RB_Program_Task_Status) -> RB_Program_Task_StatusT: ...
  def _UnPack(self, rbProgramTaskStatus: RB_Program_Task_Status) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def RB_Program_Task_StatusStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RB_Program_Task_StatusAddTaskId(builder: flatbuffers.Builder, taskId: uoffset) -> None: ...
def RB_Program_Task_StatusAddProgramId(builder: flatbuffers.Builder, programId: uoffset) -> None: ...
def RB_Program_Task_StatusAddSyncTaskIds(builder: flatbuffers.Builder, syncTaskIds: uoffset) -> None: ...
def RB_Program_Task_StatusStartSyncTaskIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSyncTaskIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RB_Program_Task_StatusAddNodePath(builder: flatbuffers.Builder, nodePath: uoffset) -> None: ...
def RB_Program_Task_StatusStartNodePathVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartNodePathVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RB_Program_Task_StatusAddStatus(builder: flatbuffers.Builder, status: uoffset) -> None: ...
def RB_Program_Task_StatusAddOffset(builder: flatbuffers.Builder, offset: int) -> None: ...
def RB_Program_Task_StatusEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

