from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.program.RB_Program_Task_Checkpoint import RB_Program_Task_Checkpoint

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class RB_Program_Task_Checkpoint(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> RB_Program_Task_Checkpoint: ...
  @classmethod
  def GetRootAsRB_Program_Task_Checkpoint(cls, buf: bytes, offset: int) -> RB_Program_Task_Checkpoint: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TaskId(self) -> str | None: ...
  def ProgramId(self) -> str | None: ...
  def SyncTaskIds(self, i: int) -> str: ...
  def SyncTaskIdsLength(self) -> int: ...
  def SyncTaskIdsIsNone(self) -> bool: ...
  def NodePath(self, i: int) -> str: ...
  def NodePathLength(self) -> int: ...
  def NodePathIsNone(self) -> bool: ...
  def Offset(self) -> int: ...
  def Status(self) -> str | None: ...
class RB_Program_Task_CheckpointT(object):
  taskId: str | None
  programId: str | None
  syncTaskIds: typing.List[str]
  nodePath: typing.List[str]
  offset: int
  status: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> RB_Program_Task_CheckpointT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> RB_Program_Task_CheckpointT: ...
  @classmethod
  def InitFromObj(cls, rbProgramTaskCheckpoint: RB_Program_Task_Checkpoint) -> RB_Program_Task_CheckpointT: ...
  def _UnPack(self, rbProgramTaskCheckpoint: RB_Program_Task_Checkpoint) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def RB_Program_Task_CheckpointStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def RB_Program_Task_CheckpointAddTaskId(builder: flatbuffers.Builder, taskId: uoffset) -> None: ...
def RB_Program_Task_CheckpointAddProgramId(builder: flatbuffers.Builder, programId: uoffset) -> None: ...
def RB_Program_Task_CheckpointAddSyncTaskIds(builder: flatbuffers.Builder, syncTaskIds: uoffset) -> None: ...
def RB_Program_Task_CheckpointStartSyncTaskIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSyncTaskIdsVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RB_Program_Task_CheckpointAddNodePath(builder: flatbuffers.Builder, nodePath: uoffset) -> None: ...
def RB_Program_Task_CheckpointStartNodePathVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartNodePathVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def RB_Program_Task_CheckpointAddOffset(builder: flatbuffers.Builder, offset: int) -> None: ...
def RB_Program_Task_CheckpointAddStatus(builder: flatbuffers.Builder, status: uoffset) -> None: ...
def RB_Program_Task_CheckpointEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

