# automatically generated by the FlatBuffers compiler, do not modify

# namespace: program

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class RB_Program_Log(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RB_Program_Log()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRB_Program_Log(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RB_Program_Log
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RB_Program_Log
    def Content(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RB_Program_Log
    def RobotModel(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RB_Program_Log
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def RB_Program_LogStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    RB_Program_LogStart(builder)

def RB_Program_LogAddContent(builder: flatbuffers.Builder, content: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(content), 0)

def AddContent(builder: flatbuffers.Builder, content: int):
    RB_Program_LogAddContent(builder, content)

def RB_Program_LogAddRobotModel(builder: flatbuffers.Builder, robotModel: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(robotModel), 0)

def AddRobotModel(builder: flatbuffers.Builder, robotModel: int):
    RB_Program_LogAddRobotModel(builder, robotModel)

def RB_Program_LogAddType(builder: flatbuffers.Builder, type: int):
    builder.PrependInt8Slot(2, type, 0)

def AddType(builder: flatbuffers.Builder, type: int):
    RB_Program_LogAddType(builder, type)

def RB_Program_LogEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RB_Program_LogEnd(builder)


class RB_Program_LogT(object):

    # RB_Program_LogT
    def __init__(
        self,
        content = None,
        robotModel = None,
        type = 0,
    ):
        self.content = content  # type: Optional[str]
        self.robotModel = robotModel  # type: Optional[str]
        self.type = type  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        rbProgramLog = RB_Program_Log()
        rbProgramLog.Init(buf, pos)
        return cls.InitFromObj(rbProgramLog)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, rbProgramLog):
        x = RB_Program_LogT()
        x._UnPack(rbProgramLog)
        return x

    # RB_Program_LogT
    def _UnPack(self, rbProgramLog):
        if rbProgramLog is None:
            return
        self.content = rbProgramLog.Content()
        self.robotModel = rbProgramLog.RobotModel()
        self.type = rbProgramLog.Type()

    # RB_Program_LogT
    def Pack(self, builder):
        if self.content is not None:
            content = builder.CreateString(self.content)
        if self.robotModel is not None:
            robotModel = builder.CreateString(self.robotModel)
        RB_Program_LogStart(builder)
        if self.content is not None:
            RB_Program_LogAddContent(builder, content)
        if self.robotModel is not None:
            RB_Program_LogAddRobotModel(builder, robotModel)
        RB_Program_LogAddType(builder, self.type)
        rbProgramLog = RB_Program_LogEnd(builder)
        return rbProgramLog
