from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.program.Request_Program_At_End import Request_Program_At_End

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Program_At_End(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Program_At_End: ...
  @classmethod
  def GetRootAsRequest_Program_At_End(cls, buf: bytes, offset: int) -> Request_Program_At_End: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TaskId(self) -> str | None: ...
class Request_Program_At_EndT(object):
  taskId: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Program_At_EndT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Program_At_EndT: ...
  @classmethod
  def InitFromObj(cls, requestProgramAtEnd: Request_Program_At_End) -> Request_Program_At_EndT: ...
  def _UnPack(self, requestProgramAtEnd: Request_Program_At_End) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Program_At_EndStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Program_At_EndAddTaskId(builder: flatbuffers.Builder, taskId: uoffset) -> None: ...
def Request_Program_At_EndEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

