from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.flow_manager.RB_Flow_Manager_ProgramState import RB_Flow_Manager_ProgramState
from rb_flat_buffers.program.RB_Program_Sub_Task_Type import RB_Program_Sub_Task_Type

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Update_Sub_Task_State(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Update_Sub_Task_State: ...
  @classmethod
  def GetRootAsRequest_Update_Sub_Task_State(cls, buf: bytes, offset: int) -> Request_Update_Sub_Task_State: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SubTaskId(self) -> str | None: ...
  def SubTaskType(self) -> typing.Literal[RB_Program_Sub_Task_Type.SUB_TASK_INSERT, RB_Program_Sub_Task_Type.SUB_TASK_CHANGE]: ...
  def State(self) -> typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED, RB_Flow_Manager_ProgramState.AFTER_COMPLETED]: ...
class Request_Update_Sub_Task_StateT(object):
  subTaskId: str | None
  subTaskType: typing.Literal[RB_Program_Sub_Task_Type.SUB_TASK_INSERT, RB_Program_Sub_Task_Type.SUB_TASK_CHANGE]
  state: typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED, RB_Flow_Manager_ProgramState.AFTER_COMPLETED]
  def __init__(
    self,
    subTaskId: str | None = ...,
    subTaskType: typing.Literal[RB_Program_Sub_Task_Type.SUB_TASK_INSERT, RB_Program_Sub_Task_Type.SUB_TASK_CHANGE] = ...,
    state: typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED, RB_Flow_Manager_ProgramState.AFTER_COMPLETED] = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Update_Sub_Task_StateT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Update_Sub_Task_StateT: ...
  @classmethod
  def InitFromObj(cls, requestUpdateSubTaskState: Request_Update_Sub_Task_State) -> Request_Update_Sub_Task_StateT: ...
  def _UnPack(self, requestUpdateSubTaskState: Request_Update_Sub_Task_State) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Update_Sub_Task_StateStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Update_Sub_Task_StateAddSubTaskId(builder: flatbuffers.Builder, subTaskId: uoffset) -> None: ...
def Request_Update_Sub_Task_StateAddSubTaskType(builder: flatbuffers.Builder, subTaskType: typing.Literal[RB_Program_Sub_Task_Type.SUB_TASK_INSERT, RB_Program_Sub_Task_Type.SUB_TASK_CHANGE]) -> None: ...
def Request_Update_Sub_Task_StateAddState(builder: flatbuffers.Builder, state: typing.Literal[RB_Flow_Manager_ProgramState.IDLE, RB_Flow_Manager_ProgramState.RUNNING, RB_Flow_Manager_ProgramState.PAUSED, RB_Flow_Manager_ProgramState.STOPPED, RB_Flow_Manager_ProgramState.WAITING, RB_Flow_Manager_ProgramState.ERROR, RB_Flow_Manager_ProgramState.COMPLETED, RB_Flow_Manager_ProgramState.AFTER_COMPLETED]) -> None: ...
def Request_Update_Sub_Task_StateEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

