from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.program.Request_Program_At_Start import Request_Program_At_Start

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Program_At_Start(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Program_At_Start: ...
  @classmethod
  def GetRootAsRequest_Program_At_Start(cls, buf: bytes, offset: int) -> Request_Program_At_Start: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TaskId(self) -> str | None: ...
class Request_Program_At_StartT(object):
  taskId: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Program_At_StartT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Program_At_StartT: ...
  @classmethod
  def InitFromObj(cls, requestProgramAtStart: Request_Program_At_Start) -> Request_Program_At_StartT: ...
  def _UnPack(self, requestProgramAtStart: Request_Program_At_Start) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Program_At_StartStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Program_At_StartAddTaskId(builder: flatbuffers.Builder, taskId: uoffset) -> None: ...
def Request_Program_At_StartEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

