# automatically generated by the FlatBuffers compiler, do not modify

# namespace: program

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Update_Sub_Task_State(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Update_Sub_Task_State()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Update_Sub_Task_State(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Update_Sub_Task_State
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Update_Sub_Task_State
    def SubTaskId(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Update_Sub_Task_State
    def SubTaskType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Request_Update_Sub_Task_State
    def State(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def Request_Update_Sub_Task_StateStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    Request_Update_Sub_Task_StateStart(builder)

def Request_Update_Sub_Task_StateAddSubTaskId(builder: flatbuffers.Builder, subTaskId: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(subTaskId), 0)

def AddSubTaskId(builder: flatbuffers.Builder, subTaskId: int):
    Request_Update_Sub_Task_StateAddSubTaskId(builder, subTaskId)

def Request_Update_Sub_Task_StateAddSubTaskType(builder: flatbuffers.Builder, subTaskType: int):
    builder.PrependInt8Slot(1, subTaskType, 0)

def AddSubTaskType(builder: flatbuffers.Builder, subTaskType: int):
    Request_Update_Sub_Task_StateAddSubTaskType(builder, subTaskType)

def Request_Update_Sub_Task_StateAddState(builder: flatbuffers.Builder, state: int):
    builder.PrependInt8Slot(2, state, 0)

def AddState(builder: flatbuffers.Builder, state: int):
    Request_Update_Sub_Task_StateAddState(builder, state)

def Request_Update_Sub_Task_StateEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Update_Sub_Task_StateEnd(builder)


class Request_Update_Sub_Task_StateT(object):

    # Request_Update_Sub_Task_StateT
    def __init__(self):
        self.subTaskId = None  # type: str
        self.subTaskType = 0  # type: int
        self.state = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestUpdateSubTaskState = Request_Update_Sub_Task_State()
        requestUpdateSubTaskState.Init(buf, pos)
        return cls.InitFromObj(requestUpdateSubTaskState)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestUpdateSubTaskState):
        x = Request_Update_Sub_Task_StateT()
        x._UnPack(requestUpdateSubTaskState)
        return x

    # Request_Update_Sub_Task_StateT
    def _UnPack(self, requestUpdateSubTaskState):
        if requestUpdateSubTaskState is None:
            return
        self.subTaskId = requestUpdateSubTaskState.SubTaskId()
        self.subTaskType = requestUpdateSubTaskState.SubTaskType()
        self.state = requestUpdateSubTaskState.State()

    # Request_Update_Sub_Task_StateT
    def Pack(self, builder):
        if self.subTaskId is not None:
            subTaskId = builder.CreateString(self.subTaskId)
        Request_Update_Sub_Task_StateStart(builder)
        if self.subTaskId is not None:
            Request_Update_Sub_Task_StateAddSubTaskId(builder, subTaskId)
        Request_Update_Sub_Task_StateAddSubTaskType(builder, self.subTaskType)
        Request_Update_Sub_Task_StateAddState(builder, self.state)
        requestUpdateSubTaskState = Request_Update_Sub_Task_StateEnd(builder)
        return requestUpdateSubTaskState
