from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.program.Request_Exec_Control_Program import Request_Exec_Control_Program

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Exec_Control_Program(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Exec_Control_Program: ...
  @classmethod
  def GetRootAsRequest_Exec_Control_Program(cls, buf: bytes, offset: int) -> Request_Exec_Control_Program: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def RobotModel(self) -> str | None: ...
  def ProgramId(self) -> str | None: ...
class Request_Exec_Control_ProgramT(object):
  robotModel: str | None
  programId: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Exec_Control_ProgramT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Exec_Control_ProgramT: ...
  @classmethod
  def InitFromObj(cls, requestExecControlProgram: Request_Exec_Control_Program) -> Request_Exec_Control_ProgramT: ...
  def _UnPack(self, requestExecControlProgram: Request_Exec_Control_Program) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Exec_Control_ProgramStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Exec_Control_ProgramAddRobotModel(builder: flatbuffers.Builder, robotModel: uoffset) -> None: ...
def Request_Exec_Control_ProgramAddProgramId(builder: flatbuffers.Builder, programId: uoffset) -> None: ...
def Request_Exec_Control_ProgramEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

