from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.program.Response_Exec_Control_Program import Response_Exec_Control_Program

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Exec_Control_Program(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Exec_Control_Program: ...
  @classmethod
  def GetRootAsResponse_Exec_Control_Program(cls, buf: bytes, offset: int) -> Response_Exec_Control_Program: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ManipulateReturnValue(self) -> int: ...
  def AmrReturnValue(self) -> int: ...
class Response_Exec_Control_ProgramT(object):
  manipulateReturnValue: int
  amrReturnValue: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Exec_Control_ProgramT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Exec_Control_ProgramT: ...
  @classmethod
  def InitFromObj(cls, responseExecControlProgram: Response_Exec_Control_Program) -> Response_Exec_Control_ProgramT: ...
  def _UnPack(self, responseExecControlProgram: Response_Exec_Control_Program) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Exec_Control_ProgramStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Exec_Control_ProgramAddManipulateReturnValue(builder: flatbuffers.Builder, manipulateReturnValue: int) -> None: ...
def Response_Exec_Control_ProgramAddAmrReturnValue(builder: flatbuffers.Builder, amrReturnValue: int) -> None: ...
def Response_Exec_Control_ProgramEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

