from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.IPC.FileMessage import FileMessage, FileMessageT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class EmailMessage(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> EmailMessage: ...
  @classmethod
  def GetRootAsEmailMessage(cls, buf: bytes, offset: int) -> EmailMessage: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def FromEmail(self) -> str | None: ...
  def ToEmail(self) -> str | None: ...
  def Subject(self) -> str | None: ...
  def Body(self) -> str | None: ...
  def Attachment(self, i: int) -> FileMessage | None: ...
  def AttachmentLength(self) -> int: ...
  def AttachmentIsNone(self) -> bool: ...
class EmailMessageT(object):
  fromEmail: str | None
  toEmail: str | None
  subject: str | None
  body: str | None
  attachment: typing.List[FileMessageT]
  def __init__(
    self,
    fromEmail: str | None = ...,
    toEmail: str | None = ...,
    subject: str | None = ...,
    body: str | None = ...,
    attachment: typing.List['FileMessageT'] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> EmailMessageT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> EmailMessageT: ...
  @classmethod
  def InitFromObj(cls, emailMessage: EmailMessage) -> EmailMessageT: ...
  def _UnPack(self, emailMessage: EmailMessage) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def EmailMessageStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def EmailMessageAddFromEmail(builder: flatbuffers.Builder, fromEmail: uoffset) -> None: ...
def EmailMessageAddToEmail(builder: flatbuffers.Builder, toEmail: uoffset) -> None: ...
def EmailMessageAddSubject(builder: flatbuffers.Builder, subject: uoffset) -> None: ...
def EmailMessageAddBody(builder: flatbuffers.Builder, body: uoffset) -> None: ...
def EmailMessageAddAttachment(builder: flatbuffers.Builder, attachment: uoffset) -> None: ...
def EmailMessageStartAttachmentVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartAttachmentVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def EmailMessageEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

