# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

class FilePayload(object):
    NONE = 0
    FileMeta = 1
    FileChunk = 2
    FileAck = 3
    FileRequest = 4

def FilePayloadCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == FilePayload.FileMeta:
        return FileMetaT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FilePayload.FileChunk:
        return FileChunkT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FilePayload.FileAck:
        return FileAckT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FilePayload.FileRequest:
        return FileRequestT.InitFromBuf(table.Bytes, table.Pos)
    return None
