from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.IPC.FileAck import FileAckT
from rb_flat_buffers.IPC.FileChunk import FileChunkT
from rb_flat_buffers.IPC.FileMeta import FileMetaT
from rb_flat_buffers.IPC.FilePayload import FilePayload
from rb_flat_buffers.IPC.FileRequest import FileRequestT
from flatbuffers import table

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FileMessage(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FileMessage: ...
  @classmethod
  def GetRootAsFileMessage(cls, buf: bytes, offset: int) -> FileMessage: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PayloadType(self) -> typing.Literal[FilePayload.NONE, FilePayload.FileMeta, FilePayload.FileChunk, FilePayload.FileAck, FilePayload.FileRequest]: ...
  def Payload(self) -> table.Table | None: ...
class FileMessageT(object):
  payloadType: typing.Literal[FilePayload.NONE, FilePayload.FileMeta, FilePayload.FileChunk, FilePayload.FileAck, FilePayload.FileRequest]
  payload: typing.Union[None, FileMetaT, FileChunkT, FileAckT, FileRequestT]
  def __init__(
    self,
    payloadType: typing.Literal[FilePayload.NONE, FilePayload.FileMeta, FilePayload.FileChunk, FilePayload.FileAck, FilePayload.FileRequest] = ...,
    payload: typing.Union[None, FileMetaT, FileChunkT, FileAckT, FileRequestT] = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FileMessageT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FileMessageT: ...
  @classmethod
  def InitFromObj(cls, fileMessage: FileMessage) -> FileMessageT: ...
  def _UnPack(self, fileMessage: FileMessage) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def FileMessageStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FileMessageAddPayloadType(builder: flatbuffers.Builder, payloadType: typing.Literal[FilePayload.NONE, FilePayload.FileMeta, FilePayload.FileChunk, FilePayload.FileAck, FilePayload.FileRequest]) -> None: ...
def FileMessageAddPayload(builder: flatbuffers.Builder, payload: uoffset) -> None: ...
def FileMessageEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

