# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from flatbuffers.table import Table
from typing import Optional
np = import_numpy()

from rb_flat_buffers.IPC.FileRequest import FileRequest, FileRequestT
from rb_flat_buffers.IPC.FileMeta import FileMeta, FileMetaT
from rb_flat_buffers.IPC.FileChunk import FileChunk, FileChunkT
from rb_flat_buffers.IPC.FileAck import FileAck, FileAckT
class FileMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FileMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFileMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FileMessage
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FileMessage
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FileMessage
    def Payload(self) -> Optional[flatbuffers.table.Table]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def FileMessageStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    FileMessageStart(builder)

def FileMessageAddPayloadType(builder: flatbuffers.Builder, payloadType: int):
    builder.PrependUint8Slot(0, payloadType, 0)

def AddPayloadType(builder: flatbuffers.Builder, payloadType: int):
    FileMessageAddPayloadType(builder, payloadType)

def FileMessageAddPayload(builder: flatbuffers.Builder, payload: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder: flatbuffers.Builder, payload: int):
    FileMessageAddPayload(builder, payload)

def FileMessageEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FileMessageEnd(builder)

try:
    from typing import Union
except:
    pass

class FileMessageT(object):

    # FileMessageT
    def __init__(
        self,
        payloadType = 0,
        payload = None,
    ):
        self.payloadType = payloadType  # type: int
        self.payload = payload  # type: Union[None, 'FileMetaT', 'FileChunkT', 'FileAckT', 'FileRequestT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fileMessage = FileMessage()
        fileMessage.Init(buf, pos)
        return cls.InitFromObj(fileMessage)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fileMessage):
        x = FileMessageT()
        x._UnPack(fileMessage)
        return x

    # FileMessageT
    def _UnPack(self, fileMessage):
        if fileMessage is None:
            return
        self.payloadType = fileMessage.PayloadType()
        self.payload = FilePayloadCreator(self.payloadType, fileMessage.Payload())

    # FileMessageT
    def Pack(self, builder):
        if self.payload is not None:
            payload = self.payload.Pack(builder)
        FileMessageStart(builder)
        FileMessageAddPayloadType(builder, self.payloadType)
        if self.payload is not None:
            FileMessageAddPayload(builder, payload)
        fileMessage = FileMessageEnd(builder)
        return fileMessage
