from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.FileRequest import FileRequest

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FileRequest(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FileRequest: ...
  @classmethod
  def GetRootAsFileRequest(cls, buf: bytes, offset: int) -> FileRequest: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Session(self) -> str | None: ...
  def WantIndex(self) -> int: ...
class FileRequestT(object):
  session: str | None
  wantIndex: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FileRequestT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FileRequestT: ...
  @classmethod
  def InitFromObj(cls, fileRequest: FileRequest) -> FileRequestT: ...
  def _UnPack(self, fileRequest: FileRequest) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def FileRequestStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FileRequestAddSession(builder: flatbuffers.Builder, session: uoffset) -> None: ...
def FileRequestAddWantIndex(builder: flatbuffers.Builder, wantIndex: int) -> None: ...
def FileRequestEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

