from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FileAck(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FileAck: ...
  @classmethod
  def GetRootAsFileAck(cls, buf: bytes, offset: int) -> FileAck: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Session(self) -> str | None: ...
  def Index(self) -> int: ...
  def Ok(self) -> bool: ...
class FileAckT(object):
  session: str | None
  index: int
  ok: bool
  def __init__(
    self,
    session: str | None = ...,
    index: int = ...,
    ok: bool = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FileAckT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FileAckT: ...
  @classmethod
  def InitFromObj(cls, fileAck: FileAck) -> FileAckT: ...
  def _UnPack(self, fileAck: FileAck) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def FileAckStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FileAckAddSession(builder: flatbuffers.Builder, session: uoffset) -> None: ...
def FileAckAddIndex(builder: flatbuffers.Builder, index: int) -> None: ...
def FileAckAddOk(builder: flatbuffers.Builder, ok: bool) -> None: ...
def FileAckEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

