from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.FileChunk import FileChunk

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FileChunk(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FileChunk: ...
  @classmethod
  def GetRootAsFileChunk(cls, buf: bytes, offset: int) -> FileChunk: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Session(self) -> str | None: ...
  def Index(self) -> int: ...
  def Offset(self) -> int: ...
  def Data(self, i: int) -> typing.List[int]: ...
  def DataAsNumpy(self) -> np.ndarray: ...
  def DataLength(self) -> int: ...
  def DataIsNone(self) -> bool: ...
class FileChunkT(object):
  session: str | None
  index: int
  offset: int
  data: typing.List[int]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FileChunkT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FileChunkT: ...
  @classmethod
  def InitFromObj(cls, fileChunk: FileChunk) -> FileChunkT: ...
  def _UnPack(self, fileChunk: FileChunk) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def FileChunkStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FileChunkAddSession(builder: flatbuffers.Builder, session: uoffset) -> None: ...
def FileChunkAddIndex(builder: flatbuffers.Builder, index: int) -> None: ...
def FileChunkAddOffset(builder: flatbuffers.Builder, offset: int) -> None: ...
def FileChunkAddData(builder: flatbuffers.Builder, data: uoffset) -> None: ...
def FileChunkStartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartDataVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def FileChunkEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

