from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FileMeta(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> FileMeta: ...
  @classmethod
  def GetRootAsFileMeta(cls, buf: bytes, offset: int) -> FileMeta: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Session(self) -> str | None: ...
  def Name(self) -> str | None: ...
  def Size(self) -> int: ...
  def Mime(self) -> str | None: ...
  def ChunkSize(self) -> int: ...
  def TotalChunks(self) -> int: ...
  def Sha256(self, i: int) -> typing.List[int]: ...
  def Sha256AsNumpy(self) -> np.ndarray: ...
  def Sha256Length(self) -> int: ...
  def Sha256IsNone(self) -> bool: ...
class FileMetaT(object):
  session: str | None
  name: str | None
  size: int
  mime: str | None
  chunkSize: int
  totalChunks: int
  sha256: typing.List[int]
  def __init__(
    self,
    session: str | None = ...,
    name: str | None = ...,
    size: int = ...,
    mime: str | None = ...,
    chunkSize: int = ...,
    totalChunks: int = ...,
    sha256: typing.List[int] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FileMetaT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FileMetaT: ...
  @classmethod
  def InitFromObj(cls, fileMeta: FileMeta) -> FileMetaT: ...
  def _UnPack(self, fileMeta: FileMeta) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def FileMetaStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def FileMetaAddSession(builder: flatbuffers.Builder, session: uoffset) -> None: ...
def FileMetaAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def FileMetaAddSize(builder: flatbuffers.Builder, size: int) -> None: ...
def FileMetaAddMime(builder: flatbuffers.Builder, mime: uoffset) -> None: ...
def FileMetaAddChunkSize(builder: flatbuffers.Builder, chunkSize: int) -> None: ...
def FileMetaAddTotalChunks(builder: flatbuffers.Builder, totalChunks: int) -> None: ...
def FileMetaAddSha256(builder: flatbuffers.Builder, sha256: uoffset) -> None: ...
def FileMetaStartSha256Vector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def StartSha256Vector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def FileMetaEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

