from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.FloatArray32 import FloatArray32

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class FloatArray32(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def Arr(self, i: int) -> typing.List[float]: ...
  def ArrAsNumpy(self) -> np.ndarray: ...
  def ArrLength(self) -> int: ...
  def ArrIsNone(self) -> bool: ...
class FloatArray32T(object):
  arr: typing.List[float]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> FloatArray32T: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> FloatArray32T: ...
  @classmethod
  def InitFromObj(cls, floatArray32: FloatArray32) -> FloatArray32T: ...
  def _UnPack(self, floatArray32: FloatArray32) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreateFloatArray32(builder: flatbuffers.Builder, arr: float) -> uoffset: ...

