# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Mat3f(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 36

    # Mat3f
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Mat3f
    def M(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + i * 4)) for i in range(self.MLength())]
        elif j >= 0 and j < self.MLength():
            return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + j * 4))
        else:
            return None

    # Mat3f
    def MAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Float32Flags, self._tab.Pos + 0, self.MLength())

    # Mat3f
    def MLength(self) -> int:
        return 9

    # Mat3f
    def MIsNone(self) -> bool:
        return False


def CreateMat3f(builder, m):
    builder.Prep(4, 36)
    for _idx0 in range(9 , 0, -1):
        builder.PrependFloat32(m[_idx0-1])
    return builder.Offset()

try:
    from typing import List
except:
    pass

class Mat3fT(object):

    # Mat3fT
    def __init__(self):
        self.m = None  # type: List[float]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        mat3f = Mat3f()
        mat3f.Init(buf, pos)
        return cls.InitFromObj(mat3f)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, mat3f):
        x = Mat3fT()
        x._UnPack(mat3f)
        return x

    # Mat3fT
    def _UnPack(self, mat3f):
        if mat3f is None:
            return
        if not mat3f.MIsNone():
            if np is None:
                self.m = []
                for i in range(mat3f.MLength()):
                    self.m.append(mat3f.M(i))
            else:
                self.m = mat3f.MAsNumpy()

    # Mat3fT
    def Pack(self, builder):
        return CreateMat3f(builder, self.m)
