from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MoveInput_Speed(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MoveInput_Speed: ...
  @classmethod
  def GetRootAsMoveInput_Speed(cls, buf: bytes, offset: int) -> MoveInput_Speed: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SpdMode(self) -> int: ...
  def SpdVelPara(self) -> float: ...
  def SpdAccPara(self) -> float: ...
class MoveInput_SpeedT(object):
  spdMode: int
  spdVelPara: float
  spdAccPara: float
  def __init__(
    self,
    spdMode: int = ...,
    spdVelPara: float = ...,
    spdAccPara: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> MoveInput_SpeedT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> MoveInput_SpeedT: ...
  @classmethod
  def InitFromObj(cls, moveInputSpeed: MoveInput_Speed) -> MoveInput_SpeedT: ...
  def _UnPack(self, moveInputSpeed: MoveInput_Speed) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def MoveInput_SpeedStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MoveInput_SpeedAddSpdMode(builder: flatbuffers.Builder, spdMode: int) -> None: ...
def MoveInput_SpeedAddSpdVelPara(builder: flatbuffers.Builder, spdVelPara: float) -> None: ...
def MoveInput_SpeedAddSpdAccPara(builder: flatbuffers.Builder, spdAccPara: float) -> None: ...
def MoveInput_SpeedEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

