from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.IPC.N_INPUT_f import N_INPUT_f, N_INPUT_fT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class MoveInput_Target(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> MoveInput_Target: ...
  @classmethod
  def GetRootAsMoveInput_Target(cls, buf: bytes, offset: int) -> MoveInput_Target: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TarValues(self) -> N_INPUT_f | None: ...
  def TarFrame(self) -> int: ...
  def TarUnit(self) -> int: ...
class MoveInput_TargetT(object):
  tarValues: N_INPUT_fT | None
  tarFrame: int
  tarUnit: int
  def __init__(
    self,
    tarValues: 'N_INPUT_fT' | None = ...,
    tarFrame: int = ...,
    tarUnit: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> MoveInput_TargetT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> MoveInput_TargetT: ...
  @classmethod
  def InitFromObj(cls, moveInputTarget: MoveInput_Target) -> MoveInput_TargetT: ...
  def _UnPack(self, moveInputTarget: MoveInput_Target) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def MoveInput_TargetStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def MoveInput_TargetAddTarValues(builder: flatbuffers.Builder, tarValues: uoffset) -> None: ...
def MoveInput_TargetAddTarFrame(builder: flatbuffers.Builder, tarFrame: int) -> None: ...
def MoveInput_TargetAddTarUnit(builder: flatbuffers.Builder, tarUnit: int) -> None: ...
def MoveInput_TargetEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

