from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class N_CARTE_f(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def F(self, i: int) -> typing.List[float]: ...
  def FAsNumpy(self) -> np.ndarray: ...
  def FLength(self) -> int: ...
  def FIsNone(self) -> bool: ...
class N_CARTE_fT(object):
  f: typing.List[float]
  def __init__(
    self,
    f: typing.List[float] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> N_CARTE_fT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> N_CARTE_fT: ...
  @classmethod
  def InitFromObj(cls, nCarteF: N_CARTE_f) -> N_CARTE_fT: ...
  def _UnPack(self, nCarteF: N_CARTE_f) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreateN_CARTE_f(builder: flatbuffers.Builder, f: float) -> uoffset: ...

