from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class N_DIN_u(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def U(self, i: int) -> typing.List[int]: ...
  def UAsNumpy(self) -> np.ndarray: ...
  def ULength(self) -> int: ...
  def UIsNone(self) -> bool: ...
class N_DIN_uT(object):
  u: typing.List[int]
  def __init__(
    self,
    u: typing.List[int] | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> N_DIN_uT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> N_DIN_uT: ...
  @classmethod
  def InitFromObj(cls, nDinU: N_DIN_u) -> N_DIN_uT: ...
  def _UnPack(self, nDinU: N_DIN_u) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreateN_DIN_u(builder: flatbuffers.Builder, u: int) -> uoffset: ...

