from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.N_DOUT_u import N_DOUT_u

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class N_DOUT_u(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def U(self, i: int) -> typing.List[int]: ...
  def UAsNumpy(self) -> np.ndarray: ...
  def ULength(self) -> int: ...
  def UIsNone(self) -> bool: ...
class N_DOUT_uT(object):
  u: typing.List[int]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> N_DOUT_uT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> N_DOUT_uT: ...
  @classmethod
  def InitFromObj(cls, nDoutU: N_DOUT_u) -> N_DOUT_uT: ...
  def _UnPack(self, nDoutU: N_DOUT_u) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreateN_DOUT_u(builder: flatbuffers.Builder, u: int) -> uoffset: ...

