# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class N_INPUT_f(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 28

    # N_INPUT_f
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # N_INPUT_f
    def F(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + i * 4)) for i in range(self.FLength())]
        elif j >= 0 and j < self.FLength():
            return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + j * 4))
        else:
            return None

    # N_INPUT_f
    def FAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Float32Flags, self._tab.Pos + 0, self.FLength())

    # N_INPUT_f
    def FLength(self) -> int:
        return 7

    # N_INPUT_f
    def FIsNone(self) -> bool:
        return False


def CreateN_INPUT_f(builder, f):
    builder.Prep(4, 28)
    for _idx0 in range(7 , 0, -1):
        builder.PrependFloat32(f[_idx0-1])
    return builder.Offset()

try:
    from typing import List
except:
    pass

class N_INPUT_fT(object):

    # N_INPUT_fT
    def __init__(
        self,
        f = None,
    ):
        self.f = f  # type: Optional[List[float]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        nInputF = N_INPUT_f()
        nInputF.Init(buf, pos)
        return cls.InitFromObj(nInputF)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, nInputF):
        x = N_INPUT_fT()
        x._UnPack(nInputF)
        return x

    # N_INPUT_fT
    def _UnPack(self, nInputF):
        if nInputF is None:
            return
        if not nInputF.FIsNone():
            if np is None:
                self.f = []
                for i in range(nInputF.FLength()):
                    self.f.append(nInputF.F(i))
            else:
                self.f = nInputF.FAsNumpy()

    # N_INPUT_fT
    def Pack(self, builder):
        return CreateNInputF(builder, self.f)
