from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_SideDout_Bitcombination import Request_SideDout_Bitcombination

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_SideDout_Bitcombination(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_SideDout_Bitcombination: ...
  @classmethod
  def GetRootAsRequest_SideDout_Bitcombination(cls, buf: bytes, offset: int) -> Request_SideDout_Bitcombination: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PortStart(self) -> int: ...
  def PortEnd(self) -> int: ...
  def DesiredValue(self) -> int: ...
  def DirectionOption(self) -> int: ...
class Request_SideDout_BitcombinationT(object):
  portStart: int
  portEnd: int
  desiredValue: int
  directionOption: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_SideDout_BitcombinationT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_SideDout_BitcombinationT: ...
  @classmethod
  def InitFromObj(cls, requestSideDoutBitcombination: Request_SideDout_Bitcombination) -> Request_SideDout_BitcombinationT: ...
  def _UnPack(self, requestSideDoutBitcombination: Request_SideDout_Bitcombination) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_SideDout_BitcombinationStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_SideDout_BitcombinationAddPortStart(builder: flatbuffers.Builder, portStart: int) -> None: ...
def Request_SideDout_BitcombinationAddPortEnd(builder: flatbuffers.Builder, portEnd: int) -> None: ...
def Request_SideDout_BitcombinationAddDesiredValue(builder: flatbuffers.Builder, desiredValue: int) -> None: ...
def Request_SideDout_BitcombinationAddDirectionOption(builder: flatbuffers.Builder, directionOption: int) -> None: ...
def Request_SideDout_BitcombinationEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

