# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Save_Area_Para(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Save_Area_Para()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Save_Area_Para(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Save_Area_Para
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Save_Area_Para
    def AreaNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Save_Area_Para
    def AreaName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Save_Area_Para
    def AreaType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Save_Area_Para
    def AreaX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Area_Para
    def AreaY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Area_Para
    def AreaZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Area_Para
    def AreaRx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Area_Para
    def AreaRy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Area_Para
    def AreaRz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Area_Para
    def AreaPara0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Area_Para
    def AreaPara1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Area_Para
    def AreaPara2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Request_Save_Area_ParaStart(builder: flatbuffers.Builder):
    builder.StartObject(12)

def Start(builder: flatbuffers.Builder):
    Request_Save_Area_ParaStart(builder)

def Request_Save_Area_ParaAddAreaNo(builder: flatbuffers.Builder, areaNo: int):
    builder.PrependInt32Slot(0, areaNo, 0)

def AddAreaNo(builder: flatbuffers.Builder, areaNo: int):
    Request_Save_Area_ParaAddAreaNo(builder, areaNo)

def Request_Save_Area_ParaAddAreaName(builder: flatbuffers.Builder, areaName: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(areaName), 0)

def AddAreaName(builder: flatbuffers.Builder, areaName: int):
    Request_Save_Area_ParaAddAreaName(builder, areaName)

def Request_Save_Area_ParaAddAreaType(builder: flatbuffers.Builder, areaType: int):
    builder.PrependInt32Slot(2, areaType, 0)

def AddAreaType(builder: flatbuffers.Builder, areaType: int):
    Request_Save_Area_ParaAddAreaType(builder, areaType)

def Request_Save_Area_ParaAddAreaX(builder: flatbuffers.Builder, areaX: float):
    builder.PrependFloat32Slot(3, areaX, 0.0)

def AddAreaX(builder: flatbuffers.Builder, areaX: float):
    Request_Save_Area_ParaAddAreaX(builder, areaX)

def Request_Save_Area_ParaAddAreaY(builder: flatbuffers.Builder, areaY: float):
    builder.PrependFloat32Slot(4, areaY, 0.0)

def AddAreaY(builder: flatbuffers.Builder, areaY: float):
    Request_Save_Area_ParaAddAreaY(builder, areaY)

def Request_Save_Area_ParaAddAreaZ(builder: flatbuffers.Builder, areaZ: float):
    builder.PrependFloat32Slot(5, areaZ, 0.0)

def AddAreaZ(builder: flatbuffers.Builder, areaZ: float):
    Request_Save_Area_ParaAddAreaZ(builder, areaZ)

def Request_Save_Area_ParaAddAreaRx(builder: flatbuffers.Builder, areaRx: float):
    builder.PrependFloat32Slot(6, areaRx, 0.0)

def AddAreaRx(builder: flatbuffers.Builder, areaRx: float):
    Request_Save_Area_ParaAddAreaRx(builder, areaRx)

def Request_Save_Area_ParaAddAreaRy(builder: flatbuffers.Builder, areaRy: float):
    builder.PrependFloat32Slot(7, areaRy, 0.0)

def AddAreaRy(builder: flatbuffers.Builder, areaRy: float):
    Request_Save_Area_ParaAddAreaRy(builder, areaRy)

def Request_Save_Area_ParaAddAreaRz(builder: flatbuffers.Builder, areaRz: float):
    builder.PrependFloat32Slot(8, areaRz, 0.0)

def AddAreaRz(builder: flatbuffers.Builder, areaRz: float):
    Request_Save_Area_ParaAddAreaRz(builder, areaRz)

def Request_Save_Area_ParaAddAreaPara0(builder: flatbuffers.Builder, areaPara0: float):
    builder.PrependFloat32Slot(9, areaPara0, 0.0)

def AddAreaPara0(builder: flatbuffers.Builder, areaPara0: float):
    Request_Save_Area_ParaAddAreaPara0(builder, areaPara0)

def Request_Save_Area_ParaAddAreaPara1(builder: flatbuffers.Builder, areaPara1: float):
    builder.PrependFloat32Slot(10, areaPara1, 0.0)

def AddAreaPara1(builder: flatbuffers.Builder, areaPara1: float):
    Request_Save_Area_ParaAddAreaPara1(builder, areaPara1)

def Request_Save_Area_ParaAddAreaPara2(builder: flatbuffers.Builder, areaPara2: float):
    builder.PrependFloat32Slot(11, areaPara2, 0.0)

def AddAreaPara2(builder: flatbuffers.Builder, areaPara2: float):
    Request_Save_Area_ParaAddAreaPara2(builder, areaPara2)

def Request_Save_Area_ParaEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Save_Area_ParaEnd(builder)


class Request_Save_Area_ParaT(object):

    # Request_Save_Area_ParaT
    def __init__(self):
        self.areaNo = 0  # type: int
        self.areaName = None  # type: str
        self.areaType = 0  # type: int
        self.areaX = 0.0  # type: float
        self.areaY = 0.0  # type: float
        self.areaZ = 0.0  # type: float
        self.areaRx = 0.0  # type: float
        self.areaRy = 0.0  # type: float
        self.areaRz = 0.0  # type: float
        self.areaPara0 = 0.0  # type: float
        self.areaPara1 = 0.0  # type: float
        self.areaPara2 = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestSaveAreaPara = Request_Save_Area_Para()
        requestSaveAreaPara.Init(buf, pos)
        return cls.InitFromObj(requestSaveAreaPara)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestSaveAreaPara):
        x = Request_Save_Area_ParaT()
        x._UnPack(requestSaveAreaPara)
        return x

    # Request_Save_Area_ParaT
    def _UnPack(self, requestSaveAreaPara):
        if requestSaveAreaPara is None:
            return
        self.areaNo = requestSaveAreaPara.AreaNo()
        self.areaName = requestSaveAreaPara.AreaName()
        self.areaType = requestSaveAreaPara.AreaType()
        self.areaX = requestSaveAreaPara.AreaX()
        self.areaY = requestSaveAreaPara.AreaY()
        self.areaZ = requestSaveAreaPara.AreaZ()
        self.areaRx = requestSaveAreaPara.AreaRx()
        self.areaRy = requestSaveAreaPara.AreaRy()
        self.areaRz = requestSaveAreaPara.AreaRz()
        self.areaPara0 = requestSaveAreaPara.AreaPara0()
        self.areaPara1 = requestSaveAreaPara.AreaPara1()
        self.areaPara2 = requestSaveAreaPara.AreaPara2()

    # Request_Save_Area_ParaT
    def Pack(self, builder):
        if self.areaName is not None:
            areaName = builder.CreateString(self.areaName)
        Request_Save_Area_ParaStart(builder)
        Request_Save_Area_ParaAddAreaNo(builder, self.areaNo)
        if self.areaName is not None:
            Request_Save_Area_ParaAddAreaName(builder, areaName)
        Request_Save_Area_ParaAddAreaType(builder, self.areaType)
        Request_Save_Area_ParaAddAreaX(builder, self.areaX)
        Request_Save_Area_ParaAddAreaY(builder, self.areaY)
        Request_Save_Area_ParaAddAreaZ(builder, self.areaZ)
        Request_Save_Area_ParaAddAreaRx(builder, self.areaRx)
        Request_Save_Area_ParaAddAreaRy(builder, self.areaRy)
        Request_Save_Area_ParaAddAreaRz(builder, self.areaRz)
        Request_Save_Area_ParaAddAreaPara0(builder, self.areaPara0)
        Request_Save_Area_ParaAddAreaPara1(builder, self.areaPara1)
        Request_Save_Area_ParaAddAreaPara2(builder, self.areaPara2)
        requestSaveAreaPara = Request_Save_Area_ParaEnd(builder)
        return requestSaveAreaPara
