from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_SideDout_General import Request_SideDout_General

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_SideDout_General(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_SideDout_General: ...
  @classmethod
  def GetRootAsRequest_SideDout_General(cls, buf: bytes, offset: int) -> Request_SideDout_General: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PortNum(self) -> int: ...
  def DesiredOut(self) -> int: ...
class Request_SideDout_GeneralT(object):
  portNum: int
  desiredOut: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_SideDout_GeneralT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_SideDout_GeneralT: ...
  @classmethod
  def InitFromObj(cls, requestSideDoutGeneral: Request_SideDout_General) -> Request_SideDout_GeneralT: ...
  def _UnPack(self, requestSideDoutGeneral: Request_SideDout_General) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_SideDout_GeneralStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_SideDout_GeneralAddPortNum(builder: flatbuffers.Builder, portNum: int) -> None: ...
def Request_SideDout_GeneralAddDesiredOut(builder: flatbuffers.Builder, desiredOut: int) -> None: ...
def Request_SideDout_GeneralEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

