from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_CallConfigRobotArm(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_CallConfigRobotArm: ...
  @classmethod
  def GetRootAsRequest_CallConfigRobotArm(cls, buf: bytes, offset: int) -> Request_CallConfigRobotArm: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_CallConfigRobotArmT(object):
  def __init__(
    self,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_CallConfigRobotArmT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_CallConfigRobotArmT: ...
  @classmethod
  def InitFromObj(cls, requestCallConfigRobotArm: Request_CallConfigRobotArm) -> Request_CallConfigRobotArmT: ...
  def _UnPack(self, requestCallConfigRobotArm: Request_CallConfigRobotArm) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_CallConfigRobotArmStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_CallConfigRobotArmEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

