# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from rb_flat_buffers.IPC.N_JOINT_f import N_JOINT_f, N_JOINT_fT
from typing import Optional
np = import_numpy()

class Request_Set_Joint_Impedance(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Set_Joint_Impedance()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Set_Joint_Impedance(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Set_Joint_Impedance
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Set_Joint_Impedance
    def Onoff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_Joint_Impedance
    def Stiffness(self) -> Optional[N_JOINT_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_JOINT_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Request_Set_Joint_Impedance
    def Torquelimit(self) -> Optional[N_JOINT_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_JOINT_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Request_Set_Joint_ImpedanceStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    Request_Set_Joint_ImpedanceStart(builder)

def Request_Set_Joint_ImpedanceAddOnoff(builder: flatbuffers.Builder, onoff: int):
    builder.PrependInt32Slot(0, onoff, 0)

def AddOnoff(builder: flatbuffers.Builder, onoff: int):
    Request_Set_Joint_ImpedanceAddOnoff(builder, onoff)

def Request_Set_Joint_ImpedanceAddStiffness(builder: flatbuffers.Builder, stiffness: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(stiffness), 0)

def AddStiffness(builder: flatbuffers.Builder, stiffness: Any):
    Request_Set_Joint_ImpedanceAddStiffness(builder, stiffness)

def Request_Set_Joint_ImpedanceAddTorquelimit(builder: flatbuffers.Builder, torquelimit: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(torquelimit), 0)

def AddTorquelimit(builder: flatbuffers.Builder, torquelimit: Any):
    Request_Set_Joint_ImpedanceAddTorquelimit(builder, torquelimit)

def Request_Set_Joint_ImpedanceEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Set_Joint_ImpedanceEnd(builder)

try:
    from typing import Optional
except:
    pass

class Request_Set_Joint_ImpedanceT(object):

    # Request_Set_Joint_ImpedanceT
    def __init__(
        self,
        onoff = 0,
        stiffness = None,
        torquelimit = None,
    ):
        self.onoff = onoff  # type: int
        self.stiffness = stiffness  # type: Optional[N_JOINT_fT]
        self.torquelimit = torquelimit  # type: Optional[N_JOINT_fT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestSetJointImpedance = Request_Set_Joint_Impedance()
        requestSetJointImpedance.Init(buf, pos)
        return cls.InitFromObj(requestSetJointImpedance)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestSetJointImpedance):
        x = Request_Set_Joint_ImpedanceT()
        x._UnPack(requestSetJointImpedance)
        return x

    # Request_Set_Joint_ImpedanceT
    def _UnPack(self, requestSetJointImpedance):
        if requestSetJointImpedance is None:
            return
        self.onoff = requestSetJointImpedance.Onoff()
        if requestSetJointImpedance.Stiffness() is not None:
            self.stiffness = N_JOINT_fT.InitFromObj(requestSetJointImpedance.Stiffness())
        if requestSetJointImpedance.Torquelimit() is not None:
            self.torquelimit = N_JOINT_fT.InitFromObj(requestSetJointImpedance.Torquelimit())

    # Request_Set_Joint_ImpedanceT
    def Pack(self, builder):
        Request_Set_Joint_ImpedanceStart(builder)
        Request_Set_Joint_ImpedanceAddOnoff(builder, self.onoff)
        if self.stiffness is not None:
            stiffness = self.stiffness.Pack(builder)
            Request_Set_Joint_ImpedanceAddStiffness(builder, stiffness)
        if self.torquelimit is not None:
            torquelimit = self.torquelimit.Pack(builder)
            Request_Set_Joint_ImpedanceAddTorquelimit(builder, torquelimit)
        requestSetJointImpedance = Request_Set_Joint_ImpedanceEnd(builder)
        return requestSetJointImpedance
