from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.IPC.MoveInput_Target import MoveInput_Target, MoveInput_TargetT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_SmoothJogL(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_SmoothJogL: ...
  @classmethod
  def GetRootAsRequest_Move_SmoothJogL(cls, buf: bytes, offset: int) -> Request_Move_SmoothJogL: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Target(self) -> MoveInput_Target | None: ...
class Request_Move_SmoothJogLT(object):
  target: MoveInput_TargetT | None
  def __init__(
    self,
    target: 'MoveInput_TargetT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_SmoothJogLT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_SmoothJogLT: ...
  @classmethod
  def InitFromObj(cls, requestMoveSmoothJogL: Request_Move_SmoothJogL) -> Request_Move_SmoothJogLT: ...
  def _UnPack(self, requestMoveSmoothJogL: Request_Move_SmoothJogL) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_SmoothJogLStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_SmoothJogLAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Request_Move_SmoothJogLEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

