from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from IPC.MoveInput_Target import MoveInput_Target, MoveInput_TargetT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Set_Shift(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Set_Shift: ...
  @classmethod
  def GetRootAsRequest_Set_Shift(cls, buf: bytes, offset: int) -> Request_Set_Shift: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ShiftNo(self) -> int: ...
  def ShiftMode(self) -> int: ...
  def Target(self) -> MoveInput_Target | None: ...
class Request_Set_ShiftT(object):
  shiftNo: int
  shiftMode: int
  target: MoveInput_TargetT | None
  def __init__(
    self,
    shiftNo: int = ...,
    shiftMode: int = ...,
    target: 'MoveInput_TargetT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Set_ShiftT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Set_ShiftT: ...
  @classmethod
  def InitFromObj(cls, requestSetShift: Request_Set_Shift) -> Request_Set_ShiftT: ...
  def _UnPack(self, requestSetShift: Request_Set_Shift) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Set_ShiftStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Set_ShiftAddShiftNo(builder: flatbuffers.Builder, shiftNo: int) -> None: ...
def Request_Set_ShiftAddShiftMode(builder: flatbuffers.Builder, shiftMode: int) -> None: ...
def Request_Set_ShiftAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Request_Set_ShiftEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

