# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Request_ProgramAfter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_ProgramAfter()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_ProgramAfter(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_ProgramAfter
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_ProgramAfter
    def Option(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Request_ProgramAfterStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    Request_ProgramAfterStart(builder)

def Request_ProgramAfterAddOption(builder: flatbuffers.Builder, option: int):
    builder.PrependInt32Slot(0, option, 0)

def AddOption(builder: flatbuffers.Builder, option: int):
    Request_ProgramAfterAddOption(builder, option)

def Request_ProgramAfterEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_ProgramAfterEnd(builder)


class Request_ProgramAfterT(object):

    # Request_ProgramAfterT
    def __init__(
        self,
        option = 0,
    ):
        self.option = option  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestProgramAfter = Request_ProgramAfter()
        requestProgramAfter.Init(buf, pos)
        return cls.InitFromObj(requestProgramAfter)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestProgramAfter):
        x = Request_ProgramAfterT()
        x._UnPack(requestProgramAfter)
        return x

    # Request_ProgramAfterT
    def _UnPack(self, requestProgramAfter):
        if requestProgramAfter is None:
            return
        self.option = requestProgramAfter.Option()

    # Request_ProgramAfterT
    def Pack(self, builder):
        Request_ProgramAfterStart(builder)
        Request_ProgramAfterAddOption(builder, self.option)
        requestProgramAfter = Request_ProgramAfterEnd(builder)
        return requestProgramAfter
