# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

class Request_Save_Tool_List_Para(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Save_Tool_List_Para()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Save_Tool_List_Para(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Save_Tool_List_Para
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Save_Tool_List_Para
    def ToolNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Save_Tool_List_Para
    def ToolName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Request_Save_Tool_List_Para
    def TcpX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def TcpY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def TcpZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def TcpRx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def TcpRy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def TcpRz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def MassM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def MassX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def MassY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def MassZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def BoxType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Save_Tool_List_Para
    def BoxPara0(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def BoxPara1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def BoxPara2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def BoxPara3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def BoxPara4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def BoxPara5(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def BoxPara6(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def BoxPara7(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Save_Tool_List_Para
    def BoxPara8(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Request_Save_Tool_List_ParaStart(builder: flatbuffers.Builder):
    builder.StartObject(22)

def Start(builder: flatbuffers.Builder):
    Request_Save_Tool_List_ParaStart(builder)

def Request_Save_Tool_List_ParaAddToolNo(builder: flatbuffers.Builder, toolNo: int):
    builder.PrependInt32Slot(0, toolNo, 0)

def AddToolNo(builder: flatbuffers.Builder, toolNo: int):
    Request_Save_Tool_List_ParaAddToolNo(builder, toolNo)

def Request_Save_Tool_List_ParaAddToolName(builder: flatbuffers.Builder, toolName: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(toolName), 0)

def AddToolName(builder: flatbuffers.Builder, toolName: int):
    Request_Save_Tool_List_ParaAddToolName(builder, toolName)

def Request_Save_Tool_List_ParaAddTcpX(builder: flatbuffers.Builder, tcpX: float):
    builder.PrependFloat32Slot(2, tcpX, 0.0)

def AddTcpX(builder: flatbuffers.Builder, tcpX: float):
    Request_Save_Tool_List_ParaAddTcpX(builder, tcpX)

def Request_Save_Tool_List_ParaAddTcpY(builder: flatbuffers.Builder, tcpY: float):
    builder.PrependFloat32Slot(3, tcpY, 0.0)

def AddTcpY(builder: flatbuffers.Builder, tcpY: float):
    Request_Save_Tool_List_ParaAddTcpY(builder, tcpY)

def Request_Save_Tool_List_ParaAddTcpZ(builder: flatbuffers.Builder, tcpZ: float):
    builder.PrependFloat32Slot(4, tcpZ, 0.0)

def AddTcpZ(builder: flatbuffers.Builder, tcpZ: float):
    Request_Save_Tool_List_ParaAddTcpZ(builder, tcpZ)

def Request_Save_Tool_List_ParaAddTcpRx(builder: flatbuffers.Builder, tcpRx: float):
    builder.PrependFloat32Slot(5, tcpRx, 0.0)

def AddTcpRx(builder: flatbuffers.Builder, tcpRx: float):
    Request_Save_Tool_List_ParaAddTcpRx(builder, tcpRx)

def Request_Save_Tool_List_ParaAddTcpRy(builder: flatbuffers.Builder, tcpRy: float):
    builder.PrependFloat32Slot(6, tcpRy, 0.0)

def AddTcpRy(builder: flatbuffers.Builder, tcpRy: float):
    Request_Save_Tool_List_ParaAddTcpRy(builder, tcpRy)

def Request_Save_Tool_List_ParaAddTcpRz(builder: flatbuffers.Builder, tcpRz: float):
    builder.PrependFloat32Slot(7, tcpRz, 0.0)

def AddTcpRz(builder: flatbuffers.Builder, tcpRz: float):
    Request_Save_Tool_List_ParaAddTcpRz(builder, tcpRz)

def Request_Save_Tool_List_ParaAddMassM(builder: flatbuffers.Builder, massM: float):
    builder.PrependFloat32Slot(8, massM, 0.0)

def AddMassM(builder: flatbuffers.Builder, massM: float):
    Request_Save_Tool_List_ParaAddMassM(builder, massM)

def Request_Save_Tool_List_ParaAddMassX(builder: flatbuffers.Builder, massX: float):
    builder.PrependFloat32Slot(9, massX, 0.0)

def AddMassX(builder: flatbuffers.Builder, massX: float):
    Request_Save_Tool_List_ParaAddMassX(builder, massX)

def Request_Save_Tool_List_ParaAddMassY(builder: flatbuffers.Builder, massY: float):
    builder.PrependFloat32Slot(10, massY, 0.0)

def AddMassY(builder: flatbuffers.Builder, massY: float):
    Request_Save_Tool_List_ParaAddMassY(builder, massY)

def Request_Save_Tool_List_ParaAddMassZ(builder: flatbuffers.Builder, massZ: float):
    builder.PrependFloat32Slot(11, massZ, 0.0)

def AddMassZ(builder: flatbuffers.Builder, massZ: float):
    Request_Save_Tool_List_ParaAddMassZ(builder, massZ)

def Request_Save_Tool_List_ParaAddBoxType(builder: flatbuffers.Builder, boxType: int):
    builder.PrependInt32Slot(12, boxType, 0)

def AddBoxType(builder: flatbuffers.Builder, boxType: int):
    Request_Save_Tool_List_ParaAddBoxType(builder, boxType)

def Request_Save_Tool_List_ParaAddBoxPara0(builder: flatbuffers.Builder, boxPara0: float):
    builder.PrependFloat32Slot(13, boxPara0, 0.0)

def AddBoxPara0(builder: flatbuffers.Builder, boxPara0: float):
    Request_Save_Tool_List_ParaAddBoxPara0(builder, boxPara0)

def Request_Save_Tool_List_ParaAddBoxPara1(builder: flatbuffers.Builder, boxPara1: float):
    builder.PrependFloat32Slot(14, boxPara1, 0.0)

def AddBoxPara1(builder: flatbuffers.Builder, boxPara1: float):
    Request_Save_Tool_List_ParaAddBoxPara1(builder, boxPara1)

def Request_Save_Tool_List_ParaAddBoxPara2(builder: flatbuffers.Builder, boxPara2: float):
    builder.PrependFloat32Slot(15, boxPara2, 0.0)

def AddBoxPara2(builder: flatbuffers.Builder, boxPara2: float):
    Request_Save_Tool_List_ParaAddBoxPara2(builder, boxPara2)

def Request_Save_Tool_List_ParaAddBoxPara3(builder: flatbuffers.Builder, boxPara3: float):
    builder.PrependFloat32Slot(16, boxPara3, 0.0)

def AddBoxPara3(builder: flatbuffers.Builder, boxPara3: float):
    Request_Save_Tool_List_ParaAddBoxPara3(builder, boxPara3)

def Request_Save_Tool_List_ParaAddBoxPara4(builder: flatbuffers.Builder, boxPara4: float):
    builder.PrependFloat32Slot(17, boxPara4, 0.0)

def AddBoxPara4(builder: flatbuffers.Builder, boxPara4: float):
    Request_Save_Tool_List_ParaAddBoxPara4(builder, boxPara4)

def Request_Save_Tool_List_ParaAddBoxPara5(builder: flatbuffers.Builder, boxPara5: float):
    builder.PrependFloat32Slot(18, boxPara5, 0.0)

def AddBoxPara5(builder: flatbuffers.Builder, boxPara5: float):
    Request_Save_Tool_List_ParaAddBoxPara5(builder, boxPara5)

def Request_Save_Tool_List_ParaAddBoxPara6(builder: flatbuffers.Builder, boxPara6: float):
    builder.PrependFloat32Slot(19, boxPara6, 0.0)

def AddBoxPara6(builder: flatbuffers.Builder, boxPara6: float):
    Request_Save_Tool_List_ParaAddBoxPara6(builder, boxPara6)

def Request_Save_Tool_List_ParaAddBoxPara7(builder: flatbuffers.Builder, boxPara7: float):
    builder.PrependFloat32Slot(20, boxPara7, 0.0)

def AddBoxPara7(builder: flatbuffers.Builder, boxPara7: float):
    Request_Save_Tool_List_ParaAddBoxPara7(builder, boxPara7)

def Request_Save_Tool_List_ParaAddBoxPara8(builder: flatbuffers.Builder, boxPara8: float):
    builder.PrependFloat32Slot(21, boxPara8, 0.0)

def AddBoxPara8(builder: flatbuffers.Builder, boxPara8: float):
    Request_Save_Tool_List_ParaAddBoxPara8(builder, boxPara8)

def Request_Save_Tool_List_ParaEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Save_Tool_List_ParaEnd(builder)


class Request_Save_Tool_List_ParaT(object):

    # Request_Save_Tool_List_ParaT
    def __init__(
        self,
        toolNo = 0,
        toolName = None,
        tcpX = 0.0,
        tcpY = 0.0,
        tcpZ = 0.0,
        tcpRx = 0.0,
        tcpRy = 0.0,
        tcpRz = 0.0,
        massM = 0.0,
        massX = 0.0,
        massY = 0.0,
        massZ = 0.0,
        boxType = 0,
        boxPara0 = 0.0,
        boxPara1 = 0.0,
        boxPara2 = 0.0,
        boxPara3 = 0.0,
        boxPara4 = 0.0,
        boxPara5 = 0.0,
        boxPara6 = 0.0,
        boxPara7 = 0.0,
        boxPara8 = 0.0,
    ):
        self.toolNo = toolNo  # type: int
        self.toolName = toolName  # type: Optional[str]
        self.tcpX = tcpX  # type: float
        self.tcpY = tcpY  # type: float
        self.tcpZ = tcpZ  # type: float
        self.tcpRx = tcpRx  # type: float
        self.tcpRy = tcpRy  # type: float
        self.tcpRz = tcpRz  # type: float
        self.massM = massM  # type: float
        self.massX = massX  # type: float
        self.massY = massY  # type: float
        self.massZ = massZ  # type: float
        self.boxType = boxType  # type: int
        self.boxPara0 = boxPara0  # type: float
        self.boxPara1 = boxPara1  # type: float
        self.boxPara2 = boxPara2  # type: float
        self.boxPara3 = boxPara3  # type: float
        self.boxPara4 = boxPara4  # type: float
        self.boxPara5 = boxPara5  # type: float
        self.boxPara6 = boxPara6  # type: float
        self.boxPara7 = boxPara7  # type: float
        self.boxPara8 = boxPara8  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestSaveToolListPara = Request_Save_Tool_List_Para()
        requestSaveToolListPara.Init(buf, pos)
        return cls.InitFromObj(requestSaveToolListPara)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestSaveToolListPara):
        x = Request_Save_Tool_List_ParaT()
        x._UnPack(requestSaveToolListPara)
        return x

    # Request_Save_Tool_List_ParaT
    def _UnPack(self, requestSaveToolListPara):
        if requestSaveToolListPara is None:
            return
        self.toolNo = requestSaveToolListPara.ToolNo()
        self.toolName = requestSaveToolListPara.ToolName()
        self.tcpX = requestSaveToolListPara.TcpX()
        self.tcpY = requestSaveToolListPara.TcpY()
        self.tcpZ = requestSaveToolListPara.TcpZ()
        self.tcpRx = requestSaveToolListPara.TcpRx()
        self.tcpRy = requestSaveToolListPara.TcpRy()
        self.tcpRz = requestSaveToolListPara.TcpRz()
        self.massM = requestSaveToolListPara.MassM()
        self.massX = requestSaveToolListPara.MassX()
        self.massY = requestSaveToolListPara.MassY()
        self.massZ = requestSaveToolListPara.MassZ()
        self.boxType = requestSaveToolListPara.BoxType()
        self.boxPara0 = requestSaveToolListPara.BoxPara0()
        self.boxPara1 = requestSaveToolListPara.BoxPara1()
        self.boxPara2 = requestSaveToolListPara.BoxPara2()
        self.boxPara3 = requestSaveToolListPara.BoxPara3()
        self.boxPara4 = requestSaveToolListPara.BoxPara4()
        self.boxPara5 = requestSaveToolListPara.BoxPara5()
        self.boxPara6 = requestSaveToolListPara.BoxPara6()
        self.boxPara7 = requestSaveToolListPara.BoxPara7()
        self.boxPara8 = requestSaveToolListPara.BoxPara8()

    # Request_Save_Tool_List_ParaT
    def Pack(self, builder):
        if self.toolName is not None:
            toolName = builder.CreateString(self.toolName)
        Request_Save_Tool_List_ParaStart(builder)
        Request_Save_Tool_List_ParaAddToolNo(builder, self.toolNo)
        if self.toolName is not None:
            Request_Save_Tool_List_ParaAddToolName(builder, toolName)
        Request_Save_Tool_List_ParaAddTcpX(builder, self.tcpX)
        Request_Save_Tool_List_ParaAddTcpY(builder, self.tcpY)
        Request_Save_Tool_List_ParaAddTcpZ(builder, self.tcpZ)
        Request_Save_Tool_List_ParaAddTcpRx(builder, self.tcpRx)
        Request_Save_Tool_List_ParaAddTcpRy(builder, self.tcpRy)
        Request_Save_Tool_List_ParaAddTcpRz(builder, self.tcpRz)
        Request_Save_Tool_List_ParaAddMassM(builder, self.massM)
        Request_Save_Tool_List_ParaAddMassX(builder, self.massX)
        Request_Save_Tool_List_ParaAddMassY(builder, self.massY)
        Request_Save_Tool_List_ParaAddMassZ(builder, self.massZ)
        Request_Save_Tool_List_ParaAddBoxType(builder, self.boxType)
        Request_Save_Tool_List_ParaAddBoxPara0(builder, self.boxPara0)
        Request_Save_Tool_List_ParaAddBoxPara1(builder, self.boxPara1)
        Request_Save_Tool_List_ParaAddBoxPara2(builder, self.boxPara2)
        Request_Save_Tool_List_ParaAddBoxPara3(builder, self.boxPara3)
        Request_Save_Tool_List_ParaAddBoxPara4(builder, self.boxPara4)
        Request_Save_Tool_List_ParaAddBoxPara5(builder, self.boxPara5)
        Request_Save_Tool_List_ParaAddBoxPara6(builder, self.boxPara6)
        Request_Save_Tool_List_ParaAddBoxPara7(builder, self.boxPara7)
        Request_Save_Tool_List_ParaAddBoxPara8(builder, self.boxPara8)
        requestSaveToolListPara = Request_Save_Tool_List_ParaEnd(builder)
        return requestSaveToolListPara
