from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Save_Robot_Code import Request_Save_Robot_Code

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Save_Robot_Code(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Save_Robot_Code: ...
  @classmethod
  def GetRootAsRequest_Save_Robot_Code(cls, buf: bytes, offset: int) -> Request_Save_Robot_Code: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Code(self) -> int: ...
  def Option(self) -> int: ...
class Request_Save_Robot_CodeT(object):
  code: int
  option: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Save_Robot_CodeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Save_Robot_CodeT: ...
  @classmethod
  def InitFromObj(cls, requestSaveRobotCode: Request_Save_Robot_Code) -> Request_Save_Robot_CodeT: ...
  def _UnPack(self, requestSaveRobotCode: Request_Save_Robot_Code) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Save_Robot_CodeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Save_Robot_CodeAddCode(builder: flatbuffers.Builder, code: int) -> None: ...
def Request_Save_Robot_CodeAddOption(builder: flatbuffers.Builder, option: int) -> None: ...
def Request_Save_Robot_CodeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

