from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.MoveInput_Speed import MoveInput_Speed, MoveInput_SpeedT
from rb_flat_buffers.IPC.MoveInput_Target import MoveInput_Target, MoveInput_TargetT
from rb_flat_buffers.IPC.MoveInput_Type import MoveInput_Type, MoveInput_TypeT
from rb_flat_buffers.IPC.Request_Move_JB_ADD import Request_Move_JB_ADD

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_JB_ADD(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_JB_ADD: ...
  @classmethod
  def GetRootAsRequest_Move_JB_ADD(cls, buf: bytes, offset: int) -> Request_Move_JB_ADD: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Target(self) -> MoveInput_Target | None: ...
  def Speed(self) -> MoveInput_Speed | None: ...
  def Type(self) -> MoveInput_Type | None: ...
class Request_Move_JB_ADDT(object):
  target: MoveInput_TargetT | None
  speed: MoveInput_SpeedT | None
  type: MoveInput_TypeT | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_JB_ADDT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_JB_ADDT: ...
  @classmethod
  def InitFromObj(cls, requestMoveJbAdd: Request_Move_JB_ADD) -> Request_Move_JB_ADDT: ...
  def _UnPack(self, requestMoveJbAdd: Request_Move_JB_ADD) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_JB_ADDStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_JB_ADDAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Request_Move_JB_ADDAddSpeed(builder: flatbuffers.Builder, speed: uoffset) -> None: ...
def Request_Move_JB_ADDAddType(builder: flatbuffers.Builder, type: uoffset) -> None: ...
def Request_Move_JB_ADDEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

