from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_ReferenceControl(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_ReferenceControl: ...
  @classmethod
  def GetRootAsRequest_ReferenceControl(cls, buf: bytes, offset: int) -> Request_ReferenceControl: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def RefcontrolOption(self) -> int: ...
class Request_ReferenceControlT(object):
  refcontrolOption: int
  def __init__(
    self,
    refcontrolOption: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_ReferenceControlT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_ReferenceControlT: ...
  @classmethod
  def InitFromObj(cls, requestReferenceControl: Request_ReferenceControl) -> Request_ReferenceControlT: ...
  def _UnPack(self, requestReferenceControl: Request_ReferenceControl) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_ReferenceControlStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_ReferenceControlAddRefcontrolOption(builder: flatbuffers.Builder, refcontrolOption: int) -> None: ...
def Request_ReferenceControlEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

