from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_CallConfigControlBox import Request_CallConfigControlBox

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_CallConfigControlBox(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_CallConfigControlBox: ...
  @classmethod
  def GetRootAsRequest_CallConfigControlBox(cls, buf: bytes, offset: int) -> Request_CallConfigControlBox: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_CallConfigControlBoxT(object):
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_CallConfigControlBoxT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_CallConfigControlBoxT: ...
  @classmethod
  def InitFromObj(cls, requestCallConfigControlBox: Request_CallConfigControlBox) -> Request_CallConfigControlBoxT: ...
  def _UnPack(self, requestCallConfigControlBox: Request_CallConfigControlBox) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_CallConfigControlBoxStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_CallConfigControlBoxEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

