from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_PowerControl(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_PowerControl: ...
  @classmethod
  def GetRootAsRequest_PowerControl(cls, buf: bytes, offset: int) -> Request_PowerControl: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PowerOption(self) -> int: ...
class Request_PowerControlT(object):
  powerOption: int
  def __init__(
    self,
    powerOption: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_PowerControlT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_PowerControlT: ...
  @classmethod
  def InitFromObj(cls, requestPowerControl: Request_PowerControl) -> Request_PowerControlT: ...
  def _UnPack(self, requestPowerControl: Request_PowerControl) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_PowerControlStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_PowerControlAddPowerOption(builder: flatbuffers.Builder, powerOption: int) -> None: ...
def Request_PowerControlEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

