from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Set_Out_Collision_Para import Request_Set_Out_Collision_Para

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Set_Out_Collision_Para(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Set_Out_Collision_Para: ...
  @classmethod
  def GetRootAsRequest_Set_Out_Collision_Para(cls, buf: bytes, offset: int) -> Request_Set_Out_Collision_Para: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Onoff(self) -> int: ...
  def ReactMode(self) -> int: ...
  def Threshold(self) -> float: ...
class Request_Set_Out_Collision_ParaT(object):
  onoff: int
  reactMode: int
  threshold: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Set_Out_Collision_ParaT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Set_Out_Collision_ParaT: ...
  @classmethod
  def InitFromObj(cls, requestSetOutCollisionPara: Request_Set_Out_Collision_Para) -> Request_Set_Out_Collision_ParaT: ...
  def _UnPack(self, requestSetOutCollisionPara: Request_Set_Out_Collision_Para) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Set_Out_Collision_ParaStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Set_Out_Collision_ParaAddOnoff(builder: flatbuffers.Builder, onoff: int) -> None: ...
def Request_Set_Out_Collision_ParaAddReactMode(builder: flatbuffers.Builder, reactMode: int) -> None: ...
def Request_Set_Out_Collision_ParaAddThreshold(builder: flatbuffers.Builder, threshold: float) -> None: ...
def Request_Set_Out_Collision_ParaEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

