from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Save_SideDin_SpecialFunc(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Save_SideDin_SpecialFunc: ...
  @classmethod
  def GetRootAsRequest_Save_SideDin_SpecialFunc(cls, buf: bytes, offset: int) -> Request_Save_SideDin_SpecialFunc: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PortNum(self) -> int: ...
  def DesiredFunction(self) -> int: ...
class Request_Save_SideDin_SpecialFuncT(object):
  portNum: int
  desiredFunction: int
  def __init__(
    self,
    portNum: int = ...,
    desiredFunction: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Save_SideDin_SpecialFuncT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Save_SideDin_SpecialFuncT: ...
  @classmethod
  def InitFromObj(cls, requestSaveSideDinSpecialFunc: Request_Save_SideDin_SpecialFunc) -> Request_Save_SideDin_SpecialFuncT: ...
  def _UnPack(self, requestSaveSideDinSpecialFunc: Request_Save_SideDin_SpecialFunc) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Save_SideDin_SpecialFuncStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Save_SideDin_SpecialFuncAddPortNum(builder: flatbuffers.Builder, portNum: int) -> None: ...
def Request_Save_SideDin_SpecialFuncAddDesiredFunction(builder: flatbuffers.Builder, desiredFunction: int) -> None: ...
def Request_Save_SideDin_SpecialFuncEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

