from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Save_SelfColl_Parameter import Request_Save_SelfColl_Parameter

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Save_SelfColl_Parameter(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Save_SelfColl_Parameter: ...
  @classmethod
  def GetRootAsRequest_Save_SelfColl_Parameter(cls, buf: bytes, offset: int) -> Request_Save_SelfColl_Parameter: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Mode(self) -> int: ...
  def DistInternal(self) -> float: ...
  def DistExternal(self) -> float: ...
class Request_Save_SelfColl_ParameterT(object):
  mode: int
  distInternal: float
  distExternal: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Save_SelfColl_ParameterT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Save_SelfColl_ParameterT: ...
  @classmethod
  def InitFromObj(cls, requestSaveSelfCollParameter: Request_Save_SelfColl_Parameter) -> Request_Save_SelfColl_ParameterT: ...
  def _UnPack(self, requestSaveSelfCollParameter: Request_Save_SelfColl_Parameter) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Save_SelfColl_ParameterStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Save_SelfColl_ParameterAddMode(builder: flatbuffers.Builder, mode: int) -> None: ...
def Request_Save_SelfColl_ParameterAddDistInternal(builder: flatbuffers.Builder, distInternal: float) -> None: ...
def Request_Save_SelfColl_ParameterAddDistExternal(builder: flatbuffers.Builder, distExternal: float) -> None: ...
def Request_Save_SelfColl_ParameterEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

