from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_SideDout_Pulse import Request_SideDout_Pulse

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_SideDout_Pulse(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_SideDout_Pulse: ...
  @classmethod
  def GetRootAsRequest_SideDout_Pulse(cls, buf: bytes, offset: int) -> Request_SideDout_Pulse: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PortNum(self) -> int: ...
  def BlockMode(self) -> int: ...
  def Direction(self) -> int: ...
  def Time1(self) -> float: ...
  def Time2(self) -> float: ...
  def Time3(self) -> float: ...
class Request_SideDout_PulseT(object):
  portNum: int
  blockMode: int
  direction: int
  time1: float
  time2: float
  time3: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_SideDout_PulseT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_SideDout_PulseT: ...
  @classmethod
  def InitFromObj(cls, requestSideDoutPulse: Request_SideDout_Pulse) -> Request_SideDout_PulseT: ...
  def _UnPack(self, requestSideDoutPulse: Request_SideDout_Pulse) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_SideDout_PulseStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_SideDout_PulseAddPortNum(builder: flatbuffers.Builder, portNum: int) -> None: ...
def Request_SideDout_PulseAddBlockMode(builder: flatbuffers.Builder, blockMode: int) -> None: ...
def Request_SideDout_PulseAddDirection(builder: flatbuffers.Builder, direction: int) -> None: ...
def Request_SideDout_PulseAddTime1(builder: flatbuffers.Builder, time1: float) -> None: ...
def Request_SideDout_PulseAddTime2(builder: flatbuffers.Builder, time2: float) -> None: ...
def Request_SideDout_PulseAddTime3(builder: flatbuffers.Builder, time3: float) -> None: ...
def Request_SideDout_PulseEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

