# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Request_Set_User_Frame_6Dof(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Set_User_Frame_6Dof()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Set_User_Frame_6Dof(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Set_User_Frame_6Dof
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Set_User_Frame_6Dof
    def UserFrameNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_User_Frame_6Dof
    def SettingOption(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_User_Frame_6Dof
    def TargetX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_6Dof
    def TargetY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_6Dof
    def TargetZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_6Dof
    def TargetRx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_6Dof
    def TargetRy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_6Dof
    def TargetRz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Request_Set_User_Frame_6DofStart(builder: flatbuffers.Builder):
    builder.StartObject(8)

def Start(builder: flatbuffers.Builder):
    Request_Set_User_Frame_6DofStart(builder)

def Request_Set_User_Frame_6DofAddUserFrameNum(builder: flatbuffers.Builder, userFrameNum: int):
    builder.PrependInt32Slot(0, userFrameNum, 0)

def AddUserFrameNum(builder: flatbuffers.Builder, userFrameNum: int):
    Request_Set_User_Frame_6DofAddUserFrameNum(builder, userFrameNum)

def Request_Set_User_Frame_6DofAddSettingOption(builder: flatbuffers.Builder, settingOption: int):
    builder.PrependInt32Slot(1, settingOption, 0)

def AddSettingOption(builder: flatbuffers.Builder, settingOption: int):
    Request_Set_User_Frame_6DofAddSettingOption(builder, settingOption)

def Request_Set_User_Frame_6DofAddTargetX(builder: flatbuffers.Builder, targetX: float):
    builder.PrependFloat32Slot(2, targetX, 0.0)

def AddTargetX(builder: flatbuffers.Builder, targetX: float):
    Request_Set_User_Frame_6DofAddTargetX(builder, targetX)

def Request_Set_User_Frame_6DofAddTargetY(builder: flatbuffers.Builder, targetY: float):
    builder.PrependFloat32Slot(3, targetY, 0.0)

def AddTargetY(builder: flatbuffers.Builder, targetY: float):
    Request_Set_User_Frame_6DofAddTargetY(builder, targetY)

def Request_Set_User_Frame_6DofAddTargetZ(builder: flatbuffers.Builder, targetZ: float):
    builder.PrependFloat32Slot(4, targetZ, 0.0)

def AddTargetZ(builder: flatbuffers.Builder, targetZ: float):
    Request_Set_User_Frame_6DofAddTargetZ(builder, targetZ)

def Request_Set_User_Frame_6DofAddTargetRx(builder: flatbuffers.Builder, targetRx: float):
    builder.PrependFloat32Slot(5, targetRx, 0.0)

def AddTargetRx(builder: flatbuffers.Builder, targetRx: float):
    Request_Set_User_Frame_6DofAddTargetRx(builder, targetRx)

def Request_Set_User_Frame_6DofAddTargetRy(builder: flatbuffers.Builder, targetRy: float):
    builder.PrependFloat32Slot(6, targetRy, 0.0)

def AddTargetRy(builder: flatbuffers.Builder, targetRy: float):
    Request_Set_User_Frame_6DofAddTargetRy(builder, targetRy)

def Request_Set_User_Frame_6DofAddTargetRz(builder: flatbuffers.Builder, targetRz: float):
    builder.PrependFloat32Slot(7, targetRz, 0.0)

def AddTargetRz(builder: flatbuffers.Builder, targetRz: float):
    Request_Set_User_Frame_6DofAddTargetRz(builder, targetRz)

def Request_Set_User_Frame_6DofEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Set_User_Frame_6DofEnd(builder)


class Request_Set_User_Frame_6DofT(object):

    # Request_Set_User_Frame_6DofT
    def __init__(self):
        self.userFrameNum = 0  # type: int
        self.settingOption = 0  # type: int
        self.targetX = 0.0  # type: float
        self.targetY = 0.0  # type: float
        self.targetZ = 0.0  # type: float
        self.targetRx = 0.0  # type: float
        self.targetRy = 0.0  # type: float
        self.targetRz = 0.0  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestSetUserFrame6Dof = Request_Set_User_Frame_6Dof()
        requestSetUserFrame6Dof.Init(buf, pos)
        return cls.InitFromObj(requestSetUserFrame6Dof)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestSetUserFrame6Dof):
        x = Request_Set_User_Frame_6DofT()
        x._UnPack(requestSetUserFrame6Dof)
        return x

    # Request_Set_User_Frame_6DofT
    def _UnPack(self, requestSetUserFrame6Dof):
        if requestSetUserFrame6Dof is None:
            return
        self.userFrameNum = requestSetUserFrame6Dof.UserFrameNum()
        self.settingOption = requestSetUserFrame6Dof.SettingOption()
        self.targetX = requestSetUserFrame6Dof.TargetX()
        self.targetY = requestSetUserFrame6Dof.TargetY()
        self.targetZ = requestSetUserFrame6Dof.TargetZ()
        self.targetRx = requestSetUserFrame6Dof.TargetRx()
        self.targetRy = requestSetUserFrame6Dof.TargetRy()
        self.targetRz = requestSetUserFrame6Dof.TargetRz()

    # Request_Set_User_Frame_6DofT
    def Pack(self, builder):
        Request_Set_User_Frame_6DofStart(builder)
        Request_Set_User_Frame_6DofAddUserFrameNum(builder, self.userFrameNum)
        Request_Set_User_Frame_6DofAddSettingOption(builder, self.settingOption)
        Request_Set_User_Frame_6DofAddTargetX(builder, self.targetX)
        Request_Set_User_Frame_6DofAddTargetY(builder, self.targetY)
        Request_Set_User_Frame_6DofAddTargetZ(builder, self.targetZ)
        Request_Set_User_Frame_6DofAddTargetRx(builder, self.targetRx)
        Request_Set_User_Frame_6DofAddTargetRy(builder, self.targetRy)
        Request_Set_User_Frame_6DofAddTargetRz(builder, self.targetRz)
        requestSetUserFrame6Dof = Request_Set_User_Frame_6DofEnd(builder)
        return requestSetUserFrame6Dof
