from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Set_User_Frame(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Set_User_Frame: ...
  @classmethod
  def GetRootAsRequest_Set_User_Frame(cls, buf: bytes, offset: int) -> Request_Set_User_Frame: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def UserFrameNum(self) -> int: ...
class Request_Set_User_FrameT(object):
  userFrameNum: int
  def __init__(
    self,
    userFrameNum: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Set_User_FrameT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Set_User_FrameT: ...
  @classmethod
  def InitFromObj(cls, requestSetUserFrame: Request_Set_User_Frame) -> Request_Set_User_FrameT: ...
  def _UnPack(self, requestSetUserFrame: Request_Set_User_Frame) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Set_User_FrameStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Set_User_FrameAddUserFrameNum(builder: flatbuffers.Builder, userFrameNum: int) -> None: ...
def Request_Set_User_FrameEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

