# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Request_Set_User_Frame_TCP(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Set_User_Frame_TCP()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Set_User_Frame_TCP(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Set_User_Frame_TCP
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Set_User_Frame_TCP
    def UserFrameNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_User_Frame_TCP
    def SettingOption(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Request_Set_User_Frame_TCPStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    Request_Set_User_Frame_TCPStart(builder)

def Request_Set_User_Frame_TCPAddUserFrameNum(builder: flatbuffers.Builder, userFrameNum: int):
    builder.PrependInt32Slot(0, userFrameNum, 0)

def AddUserFrameNum(builder: flatbuffers.Builder, userFrameNum: int):
    Request_Set_User_Frame_TCPAddUserFrameNum(builder, userFrameNum)

def Request_Set_User_Frame_TCPAddSettingOption(builder: flatbuffers.Builder, settingOption: int):
    builder.PrependInt32Slot(1, settingOption, 0)

def AddSettingOption(builder: flatbuffers.Builder, settingOption: int):
    Request_Set_User_Frame_TCPAddSettingOption(builder, settingOption)

def Request_Set_User_Frame_TCPEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Set_User_Frame_TCPEnd(builder)


class Request_Set_User_Frame_TCPT(object):

    # Request_Set_User_Frame_TCPT
    def __init__(self):
        self.userFrameNum = 0  # type: int
        self.settingOption = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestSetUserFrameTcp = Request_Set_User_Frame_TCP()
        requestSetUserFrameTcp.Init(buf, pos)
        return cls.InitFromObj(requestSetUserFrameTcp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestSetUserFrameTcp):
        x = Request_Set_User_Frame_TCPT()
        x._UnPack(requestSetUserFrameTcp)
        return x

    # Request_Set_User_Frame_TCPT
    def _UnPack(self, requestSetUserFrameTcp):
        if requestSetUserFrameTcp is None:
            return
        self.userFrameNum = requestSetUserFrameTcp.UserFrameNum()
        self.settingOption = requestSetUserFrameTcp.SettingOption()

    # Request_Set_User_Frame_TCPT
    def Pack(self, builder):
        Request_Set_User_Frame_TCPStart(builder)
        Request_Set_User_Frame_TCPAddUserFrameNum(builder, self.userFrameNum)
        Request_Set_User_Frame_TCPAddSettingOption(builder, self.settingOption)
        requestSetUserFrameTcp = Request_Set_User_Frame_TCPEnd(builder)
        return requestSetUserFrameTcp
