from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_ProgramAfter(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_ProgramAfter: ...
  @classmethod
  def GetRootAsRequest_ProgramAfter(cls, buf: bytes, offset: int) -> Request_ProgramAfter: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Option(self) -> int: ...
class Request_ProgramAfterT(object):
  option: int
  def __init__(
    self,
    option: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_ProgramAfterT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_ProgramAfterT: ...
  @classmethod
  def InitFromObj(cls, requestProgramAfter: Request_ProgramAfter) -> Request_ProgramAfterT: ...
  def _UnPack(self, requestProgramAfter: Request_ProgramAfter) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_ProgramAfterStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_ProgramAfterAddOption(builder: flatbuffers.Builder, option: int) -> None: ...
def Request_ProgramAfterEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

