from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Flange_Digital_Out import Request_Flange_Digital_Out

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Flange_Digital_Out(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Flange_Digital_Out: ...
  @classmethod
  def GetRootAsRequest_Flange_Digital_Out(cls, buf: bytes, offset: int) -> Request_Flange_Digital_Out: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PortNum(self) -> int: ...
  def DesiredOut(self) -> int: ...
class Request_Flange_Digital_OutT(object):
  portNum: int
  desiredOut: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Flange_Digital_OutT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Flange_Digital_OutT: ...
  @classmethod
  def InitFromObj(cls, requestFlangeDigitalOut: Request_Flange_Digital_Out) -> Request_Flange_Digital_OutT: ...
  def _UnPack(self, requestFlangeDigitalOut: Request_Flange_Digital_Out) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Flange_Digital_OutStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Flange_Digital_OutAddPortNum(builder: flatbuffers.Builder, portNum: int) -> None: ...
def Request_Flange_Digital_OutAddDesiredOut(builder: flatbuffers.Builder, desiredOut: int) -> None: ...
def Request_Flange_Digital_OutEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

