from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.IPC.MoveInput_Speed import MoveInput_Speed, MoveInput_SpeedT
from rb_flat_buffers.IPC.MoveInput_Target import MoveInput_Target, MoveInput_TargetT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_TickJogL(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_TickJogL: ...
  @classmethod
  def GetRootAsRequest_Move_TickJogL(cls, buf: bytes, offset: int) -> Request_Move_TickJogL: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Target(self) -> MoveInput_Target | None: ...
  def Speed(self) -> MoveInput_Speed | None: ...
class Request_Move_TickJogLT(object):
  target: MoveInput_TargetT | None
  speed: MoveInput_SpeedT | None
  def __init__(
    self,
    target: 'MoveInput_TargetT' | None = ...,
    speed: 'MoveInput_SpeedT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_TickJogLT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_TickJogLT: ...
  @classmethod
  def InitFromObj(cls, requestMoveTickJogL: Request_Move_TickJogL) -> Request_Move_TickJogLT: ...
  def _UnPack(self, requestMoveTickJogL: Request_Move_TickJogL) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_TickJogLStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_TickJogLAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Request_Move_TickJogLAddSpeed(builder: flatbuffers.Builder, speed: uoffset) -> None: ...
def Request_Move_TickJogLEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

