from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Set_Tool_List(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Set_Tool_List: ...
  @classmethod
  def GetRootAsRequest_Set_Tool_List(cls, buf: bytes, offset: int) -> Request_Set_Tool_List: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TargetToolNum(self) -> int: ...
class Request_Set_Tool_ListT(object):
  targetToolNum: int
  def __init__(
    self,
    targetToolNum: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Set_Tool_ListT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Set_Tool_ListT: ...
  @classmethod
  def InitFromObj(cls, requestSetToolList: Request_Set_Tool_List) -> Request_Set_Tool_ListT: ...
  def _UnPack(self, requestSetToolList: Request_Set_Tool_List) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Set_Tool_ListStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Set_Tool_ListAddTargetToolNum(builder: flatbuffers.Builder, targetToolNum: int) -> None: ...
def Request_Set_Tool_ListEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

