from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from IPC.MoveInput_Speed import MoveInput_Speed, MoveInput_SpeedT
from IPC.MoveInput_Target import MoveInput_Target, MoveInput_TargetT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_TickJogJ(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_TickJogJ: ...
  @classmethod
  def GetRootAsRequest_Move_TickJogJ(cls, buf: bytes, offset: int) -> Request_Move_TickJogJ: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Target(self) -> MoveInput_Target | None: ...
  def Speed(self) -> MoveInput_Speed | None: ...
class Request_Move_TickJogJT(object):
  target: MoveInput_TargetT | None
  speed: MoveInput_SpeedT | None
  def __init__(
    self,
    target: 'MoveInput_TargetT' | None = ...,
    speed: 'MoveInput_SpeedT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_TickJogJT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_TickJogJT: ...
  @classmethod
  def InitFromObj(cls, requestMoveTickJogJ: Request_Move_TickJogJ) -> Request_Move_TickJogJT: ...
  def _UnPack(self, requestMoveTickJogJ: Request_Move_TickJogJ) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_TickJogJStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_TickJogJAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Request_Move_TickJogJAddSpeed(builder: flatbuffers.Builder, speed: uoffset) -> None: ...
def Request_Move_TickJogJEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

