from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Get_Core_Data(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Get_Core_Data: ...
  @classmethod
  def GetRootAsRequest_Get_Core_Data(cls, buf: bytes, offset: int) -> Request_Get_Core_Data: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Option(self) -> int: ...
  def Name(self) -> str | None: ...
class Request_Get_Core_DataT(object):
  option: int
  name: str | None
  def __init__(
    self,
    option: int = ...,
    name: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Get_Core_DataT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Get_Core_DataT: ...
  @classmethod
  def InitFromObj(cls, requestGetCoreData: Request_Get_Core_Data) -> Request_Get_Core_DataT: ...
  def _UnPack(self, requestGetCoreData: Request_Get_Core_Data) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Get_Core_DataStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Get_Core_DataAddOption(builder: flatbuffers.Builder, option: int) -> None: ...
def Request_Get_Core_DataAddName(builder: flatbuffers.Builder, name: uoffset) -> None: ...
def Request_Get_Core_DataEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

