from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.IPC.MoveInput_Speed import MoveInput_Speed, MoveInput_SpeedT
from rb_flat_buffers.IPC.MoveInput_Target import MoveInput_Target, MoveInput_TargetT
from rb_flat_buffers.IPC.MoveInput_Type import MoveInput_Type, MoveInput_TypeT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_XB_ADD(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_XB_ADD: ...
  @classmethod
  def GetRootAsRequest_Move_XB_ADD(cls, buf: bytes, offset: int) -> Request_Move_XB_ADD: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Target(self) -> MoveInput_Target | None: ...
  def Speed(self) -> MoveInput_Speed | None: ...
  def Type(self) -> MoveInput_Type | None: ...
  def Method(self) -> int: ...
class Request_Move_XB_ADDT(object):
  target: MoveInput_TargetT | None
  speed: MoveInput_SpeedT | None
  type: MoveInput_TypeT | None
  method: int
  def __init__(
    self,
    target: 'MoveInput_TargetT' | None = ...,
    speed: 'MoveInput_SpeedT' | None = ...,
    type: 'MoveInput_TypeT' | None = ...,
    method: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_XB_ADDT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_XB_ADDT: ...
  @classmethod
  def InitFromObj(cls, requestMoveXbAdd: Request_Move_XB_ADD) -> Request_Move_XB_ADDT: ...
  def _UnPack(self, requestMoveXbAdd: Request_Move_XB_ADD) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_XB_ADDStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_XB_ADDAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Request_Move_XB_ADDAddSpeed(builder: flatbuffers.Builder, speed: uoffset) -> None: ...
def Request_Move_XB_ADDAddType(builder: flatbuffers.Builder, type: uoffset) -> None: ...
def Request_Move_XB_ADDAddMethod(builder: flatbuffers.Builder, method: int) -> None: ...
def Request_Move_XB_ADDEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

