from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Move_SmoothJogStop import Request_Move_SmoothJogStop

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_SmoothJogStop(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_SmoothJogStop: ...
  @classmethod
  def GetRootAsRequest_Move_SmoothJogStop(cls, buf: bytes, offset: int) -> Request_Move_SmoothJogStop: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Stoptime(self) -> float: ...
class Request_Move_SmoothJogStopT(object):
  stoptime: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_SmoothJogStopT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_SmoothJogStopT: ...
  @classmethod
  def InitFromObj(cls, requestMoveSmoothJogStop: Request_Move_SmoothJogStop) -> Request_Move_SmoothJogStopT: ...
  def _UnPack(self, requestMoveSmoothJogStop: Request_Move_SmoothJogStop) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_SmoothJogStopStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_SmoothJogStopAddStoptime(builder: flatbuffers.Builder, stoptime: float) -> None: ...
def Request_Move_SmoothJogStopEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

