from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Set_User_Frame_3Points(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Set_User_Frame_3Points: ...
  @classmethod
  def GetRootAsRequest_Set_User_Frame_3Points(cls, buf: bytes, offset: int) -> Request_Set_User_Frame_3Points: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def UserFrameNum(self) -> int: ...
  def SettingOption(self) -> int: ...
  def OrderOption(self) -> int: ...
  def Point1X(self) -> float: ...
  def Point1Y(self) -> float: ...
  def Point1Z(self) -> float: ...
  def Point2X(self) -> float: ...
  def Point2Y(self) -> float: ...
  def Point2Z(self) -> float: ...
  def Point3X(self) -> float: ...
  def Point3Y(self) -> float: ...
  def Point3Z(self) -> float: ...
class Request_Set_User_Frame_3PointsT(object):
  userFrameNum: int
  settingOption: int
  orderOption: int
  point1X: float
  point1Y: float
  point1Z: float
  point2X: float
  point2Y: float
  point2Z: float
  point3X: float
  point3Y: float
  point3Z: float
  def __init__(
    self,
    userFrameNum: int = ...,
    settingOption: int = ...,
    orderOption: int = ...,
    point1X: float = ...,
    point1Y: float = ...,
    point1Z: float = ...,
    point2X: float = ...,
    point2Y: float = ...,
    point2Z: float = ...,
    point3X: float = ...,
    point3Y: float = ...,
    point3Z: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Set_User_Frame_3PointsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Set_User_Frame_3PointsT: ...
  @classmethod
  def InitFromObj(cls, requestSetUserFrame3Points: Request_Set_User_Frame_3Points) -> Request_Set_User_Frame_3PointsT: ...
  def _UnPack(self, requestSetUserFrame3Points: Request_Set_User_Frame_3Points) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Set_User_Frame_3PointsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Set_User_Frame_3PointsAddUserFrameNum(builder: flatbuffers.Builder, userFrameNum: int) -> None: ...
def Request_Set_User_Frame_3PointsAddSettingOption(builder: flatbuffers.Builder, settingOption: int) -> None: ...
def Request_Set_User_Frame_3PointsAddOrderOption(builder: flatbuffers.Builder, orderOption: int) -> None: ...
def Request_Set_User_Frame_3PointsAddPoint1X(builder: flatbuffers.Builder, point1X: float) -> None: ...
def Request_Set_User_Frame_3PointsAddPoint1Y(builder: flatbuffers.Builder, point1Y: float) -> None: ...
def Request_Set_User_Frame_3PointsAddPoint1Z(builder: flatbuffers.Builder, point1Z: float) -> None: ...
def Request_Set_User_Frame_3PointsAddPoint2X(builder: flatbuffers.Builder, point2X: float) -> None: ...
def Request_Set_User_Frame_3PointsAddPoint2Y(builder: flatbuffers.Builder, point2Y: float) -> None: ...
def Request_Set_User_Frame_3PointsAddPoint2Z(builder: flatbuffers.Builder, point2Z: float) -> None: ...
def Request_Set_User_Frame_3PointsAddPoint3X(builder: flatbuffers.Builder, point3X: float) -> None: ...
def Request_Set_User_Frame_3PointsAddPoint3Y(builder: flatbuffers.Builder, point3Y: float) -> None: ...
def Request_Set_User_Frame_3PointsAddPoint3Z(builder: flatbuffers.Builder, point3Z: float) -> None: ...
def Request_Set_User_Frame_3PointsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

