from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_MotionResume import Request_MotionResume

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_MotionResume(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_MotionResume: ...
  @classmethod
  def GetRootAsRequest_MotionResume(cls, buf: bytes, offset: int) -> Request_MotionResume: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_MotionResumeT(object):
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_MotionResumeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_MotionResumeT: ...
  @classmethod
  def InitFromObj(cls, requestMotionResume: Request_MotionResume) -> Request_MotionResumeT: ...
  def _UnPack(self, requestMotionResume: Request_MotionResume) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_MotionResumeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_MotionResumeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

