from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Save_Tool_List_Para import Request_Save_Tool_List_Para

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Save_Tool_List_Para(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Save_Tool_List_Para: ...
  @classmethod
  def GetRootAsRequest_Save_Tool_List_Para(cls, buf: bytes, offset: int) -> Request_Save_Tool_List_Para: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ToolNo(self) -> int: ...
  def ToolName(self) -> str | None: ...
  def TcpX(self) -> float: ...
  def TcpY(self) -> float: ...
  def TcpZ(self) -> float: ...
  def TcpRx(self) -> float: ...
  def TcpRy(self) -> float: ...
  def TcpRz(self) -> float: ...
  def MassM(self) -> float: ...
  def MassX(self) -> float: ...
  def MassY(self) -> float: ...
  def MassZ(self) -> float: ...
  def BoxType(self) -> int: ...
  def BoxPara0(self) -> float: ...
  def BoxPara1(self) -> float: ...
  def BoxPara2(self) -> float: ...
  def BoxPara3(self) -> float: ...
  def BoxPara4(self) -> float: ...
  def BoxPara5(self) -> float: ...
  def BoxPara6(self) -> float: ...
  def BoxPara7(self) -> float: ...
  def BoxPara8(self) -> float: ...
class Request_Save_Tool_List_ParaT(object):
  toolNo: int
  toolName: str | None
  tcpX: float
  tcpY: float
  tcpZ: float
  tcpRx: float
  tcpRy: float
  tcpRz: float
  massM: float
  massX: float
  massY: float
  massZ: float
  boxType: int
  boxPara0: float
  boxPara1: float
  boxPara2: float
  boxPara3: float
  boxPara4: float
  boxPara5: float
  boxPara6: float
  boxPara7: float
  boxPara8: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Save_Tool_List_ParaT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Save_Tool_List_ParaT: ...
  @classmethod
  def InitFromObj(cls, requestSaveToolListPara: Request_Save_Tool_List_Para) -> Request_Save_Tool_List_ParaT: ...
  def _UnPack(self, requestSaveToolListPara: Request_Save_Tool_List_Para) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Save_Tool_List_ParaStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Save_Tool_List_ParaAddToolNo(builder: flatbuffers.Builder, toolNo: int) -> None: ...
def Request_Save_Tool_List_ParaAddToolName(builder: flatbuffers.Builder, toolName: uoffset) -> None: ...
def Request_Save_Tool_List_ParaAddTcpX(builder: flatbuffers.Builder, tcpX: float) -> None: ...
def Request_Save_Tool_List_ParaAddTcpY(builder: flatbuffers.Builder, tcpY: float) -> None: ...
def Request_Save_Tool_List_ParaAddTcpZ(builder: flatbuffers.Builder, tcpZ: float) -> None: ...
def Request_Save_Tool_List_ParaAddTcpRx(builder: flatbuffers.Builder, tcpRx: float) -> None: ...
def Request_Save_Tool_List_ParaAddTcpRy(builder: flatbuffers.Builder, tcpRy: float) -> None: ...
def Request_Save_Tool_List_ParaAddTcpRz(builder: flatbuffers.Builder, tcpRz: float) -> None: ...
def Request_Save_Tool_List_ParaAddMassM(builder: flatbuffers.Builder, massM: float) -> None: ...
def Request_Save_Tool_List_ParaAddMassX(builder: flatbuffers.Builder, massX: float) -> None: ...
def Request_Save_Tool_List_ParaAddMassY(builder: flatbuffers.Builder, massY: float) -> None: ...
def Request_Save_Tool_List_ParaAddMassZ(builder: flatbuffers.Builder, massZ: float) -> None: ...
def Request_Save_Tool_List_ParaAddBoxType(builder: flatbuffers.Builder, boxType: int) -> None: ...
def Request_Save_Tool_List_ParaAddBoxPara0(builder: flatbuffers.Builder, boxPara0: float) -> None: ...
def Request_Save_Tool_List_ParaAddBoxPara1(builder: flatbuffers.Builder, boxPara1: float) -> None: ...
def Request_Save_Tool_List_ParaAddBoxPara2(builder: flatbuffers.Builder, boxPara2: float) -> None: ...
def Request_Save_Tool_List_ParaAddBoxPara3(builder: flatbuffers.Builder, boxPara3: float) -> None: ...
def Request_Save_Tool_List_ParaAddBoxPara4(builder: flatbuffers.Builder, boxPara4: float) -> None: ...
def Request_Save_Tool_List_ParaAddBoxPara5(builder: flatbuffers.Builder, boxPara5: float) -> None: ...
def Request_Save_Tool_List_ParaAddBoxPara6(builder: flatbuffers.Builder, boxPara6: float) -> None: ...
def Request_Save_Tool_List_ParaAddBoxPara7(builder: flatbuffers.Builder, boxPara7: float) -> None: ...
def Request_Save_Tool_List_ParaAddBoxPara8(builder: flatbuffers.Builder, boxPara8: float) -> None: ...
def Request_Save_Tool_List_ParaEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

