from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Save_Area_Para(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Save_Area_Para: ...
  @classmethod
  def GetRootAsRequest_Save_Area_Para(cls, buf: bytes, offset: int) -> Request_Save_Area_Para: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def AreaNo(self) -> int: ...
  def AreaName(self) -> str | None: ...
  def AreaType(self) -> int: ...
  def AreaX(self) -> float: ...
  def AreaY(self) -> float: ...
  def AreaZ(self) -> float: ...
  def AreaRx(self) -> float: ...
  def AreaRy(self) -> float: ...
  def AreaRz(self) -> float: ...
  def AreaPara0(self) -> float: ...
  def AreaPara1(self) -> float: ...
  def AreaPara2(self) -> float: ...
class Request_Save_Area_ParaT(object):
  areaNo: int
  areaName: str | None
  areaType: int
  areaX: float
  areaY: float
  areaZ: float
  areaRx: float
  areaRy: float
  areaRz: float
  areaPara0: float
  areaPara1: float
  areaPara2: float
  def __init__(
    self,
    areaNo: int = ...,
    areaName: str | None = ...,
    areaType: int = ...,
    areaX: float = ...,
    areaY: float = ...,
    areaZ: float = ...,
    areaRx: float = ...,
    areaRy: float = ...,
    areaRz: float = ...,
    areaPara0: float = ...,
    areaPara1: float = ...,
    areaPara2: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Save_Area_ParaT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Save_Area_ParaT: ...
  @classmethod
  def InitFromObj(cls, requestSaveAreaPara: Request_Save_Area_Para) -> Request_Save_Area_ParaT: ...
  def _UnPack(self, requestSaveAreaPara: Request_Save_Area_Para) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Save_Area_ParaStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Save_Area_ParaAddAreaNo(builder: flatbuffers.Builder, areaNo: int) -> None: ...
def Request_Save_Area_ParaAddAreaName(builder: flatbuffers.Builder, areaName: uoffset) -> None: ...
def Request_Save_Area_ParaAddAreaType(builder: flatbuffers.Builder, areaType: int) -> None: ...
def Request_Save_Area_ParaAddAreaX(builder: flatbuffers.Builder, areaX: float) -> None: ...
def Request_Save_Area_ParaAddAreaY(builder: flatbuffers.Builder, areaY: float) -> None: ...
def Request_Save_Area_ParaAddAreaZ(builder: flatbuffers.Builder, areaZ: float) -> None: ...
def Request_Save_Area_ParaAddAreaRx(builder: flatbuffers.Builder, areaRx: float) -> None: ...
def Request_Save_Area_ParaAddAreaRy(builder: flatbuffers.Builder, areaRy: float) -> None: ...
def Request_Save_Area_ParaAddAreaRz(builder: flatbuffers.Builder, areaRz: float) -> None: ...
def Request_Save_Area_ParaAddAreaPara0(builder: flatbuffers.Builder, areaPara0: float) -> None: ...
def Request_Save_Area_ParaAddAreaPara1(builder: flatbuffers.Builder, areaPara1: float) -> None: ...
def Request_Save_Area_ParaAddAreaPara2(builder: flatbuffers.Builder, areaPara2: float) -> None: ...
def Request_Save_Area_ParaEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

