from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.IPC.N_JOINT_f import N_JOINT_f, N_JOINT_fT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Set_Joint_Impedance(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Set_Joint_Impedance: ...
  @classmethod
  def GetRootAsRequest_Set_Joint_Impedance(cls, buf: bytes, offset: int) -> Request_Set_Joint_Impedance: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Onoff(self) -> int: ...
  def Stiffness(self) -> N_JOINT_f | None: ...
  def Torquelimit(self) -> N_JOINT_f | None: ...
class Request_Set_Joint_ImpedanceT(object):
  onoff: int
  stiffness: N_JOINT_fT | None
  torquelimit: N_JOINT_fT | None
  def __init__(
    self,
    onoff: int = ...,
    stiffness: 'N_JOINT_fT' | None = ...,
    torquelimit: 'N_JOINT_fT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Set_Joint_ImpedanceT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Set_Joint_ImpedanceT: ...
  @classmethod
  def InitFromObj(cls, requestSetJointImpedance: Request_Set_Joint_Impedance) -> Request_Set_Joint_ImpedanceT: ...
  def _UnPack(self, requestSetJointImpedance: Request_Set_Joint_Impedance) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Set_Joint_ImpedanceStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Set_Joint_ImpedanceAddOnoff(builder: flatbuffers.Builder, onoff: int) -> None: ...
def Request_Set_Joint_ImpedanceAddStiffness(builder: flatbuffers.Builder, stiffness: uoffset) -> None: ...
def Request_Set_Joint_ImpedanceAddTorquelimit(builder: flatbuffers.Builder, torquelimit: uoffset) -> None: ...
def Request_Set_Joint_ImpedanceEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

