from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_SideAout_General import Request_SideAout_General

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_SideAout_General(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_SideAout_General: ...
  @classmethod
  def GetRootAsRequest_SideAout_General(cls, buf: bytes, offset: int) -> Request_SideAout_General: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PortNum(self) -> int: ...
  def DesiredVoltage(self) -> float: ...
class Request_SideAout_GeneralT(object):
  portNum: int
  desiredVoltage: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_SideAout_GeneralT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_SideAout_GeneralT: ...
  @classmethod
  def InitFromObj(cls, requestSideAoutGeneral: Request_SideAout_General) -> Request_SideAout_GeneralT: ...
  def _UnPack(self, requestSideAoutGeneral: Request_SideAout_General) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_SideAout_GeneralStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_SideAout_GeneralAddPortNum(builder: flatbuffers.Builder, portNum: int) -> None: ...
def Request_SideAout_GeneralAddDesiredVoltage(builder: flatbuffers.Builder, desiredVoltage: float) -> None: ...
def Request_SideAout_GeneralEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

