from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Save_SideDin_FilterCount import Request_Save_SideDin_FilterCount

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Save_SideDin_FilterCount(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Save_SideDin_FilterCount: ...
  @classmethod
  def GetRootAsRequest_Save_SideDin_FilterCount(cls, buf: bytes, offset: int) -> Request_Save_SideDin_FilterCount: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PortNum(self) -> int: ...
  def DesiredCount(self) -> int: ...
class Request_Save_SideDin_FilterCountT(object):
  portNum: int
  desiredCount: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Save_SideDin_FilterCountT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Save_SideDin_FilterCountT: ...
  @classmethod
  def InitFromObj(cls, requestSaveSideDinFilterCount: Request_Save_SideDin_FilterCount) -> Request_Save_SideDin_FilterCountT: ...
  def _UnPack(self, requestSaveSideDinFilterCount: Request_Save_SideDin_FilterCount) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Save_SideDin_FilterCountStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Save_SideDin_FilterCountAddPortNum(builder: flatbuffers.Builder, portNum: int) -> None: ...
def Request_Save_SideDin_FilterCountAddDesiredCount(builder: flatbuffers.Builder, desiredCount: int) -> None: ...
def Request_Save_SideDin_FilterCountEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

