# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Request_Save_SideDout_SpecialFunc(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Save_SideDout_SpecialFunc()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Save_SideDout_SpecialFunc(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Save_SideDout_SpecialFunc
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Save_SideDout_SpecialFunc
    def PortNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Save_SideDout_SpecialFunc
    def DesiredFunction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Request_Save_SideDout_SpecialFuncStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    Request_Save_SideDout_SpecialFuncStart(builder)

def Request_Save_SideDout_SpecialFuncAddPortNum(builder: flatbuffers.Builder, portNum: int):
    builder.PrependInt32Slot(0, portNum, 0)

def AddPortNum(builder: flatbuffers.Builder, portNum: int):
    Request_Save_SideDout_SpecialFuncAddPortNum(builder, portNum)

def Request_Save_SideDout_SpecialFuncAddDesiredFunction(builder: flatbuffers.Builder, desiredFunction: int):
    builder.PrependInt32Slot(1, desiredFunction, 0)

def AddDesiredFunction(builder: flatbuffers.Builder, desiredFunction: int):
    Request_Save_SideDout_SpecialFuncAddDesiredFunction(builder, desiredFunction)

def Request_Save_SideDout_SpecialFuncEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Save_SideDout_SpecialFuncEnd(builder)


class Request_Save_SideDout_SpecialFuncT(object):

    # Request_Save_SideDout_SpecialFuncT
    def __init__(self):
        self.portNum = 0  # type: int
        self.desiredFunction = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestSaveSideDoutSpecialFunc = Request_Save_SideDout_SpecialFunc()
        requestSaveSideDoutSpecialFunc.Init(buf, pos)
        return cls.InitFromObj(requestSaveSideDoutSpecialFunc)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestSaveSideDoutSpecialFunc):
        x = Request_Save_SideDout_SpecialFuncT()
        x._UnPack(requestSaveSideDoutSpecialFunc)
        return x

    # Request_Save_SideDout_SpecialFuncT
    def _UnPack(self, requestSaveSideDoutSpecialFunc):
        if requestSaveSideDoutSpecialFunc is None:
            return
        self.portNum = requestSaveSideDoutSpecialFunc.PortNum()
        self.desiredFunction = requestSaveSideDoutSpecialFunc.DesiredFunction()

    # Request_Save_SideDout_SpecialFuncT
    def Pack(self, builder):
        Request_Save_SideDout_SpecialFuncStart(builder)
        Request_Save_SideDout_SpecialFuncAddPortNum(builder, self.portNum)
        Request_Save_SideDout_SpecialFuncAddDesiredFunction(builder, self.desiredFunction)
        requestSaveSideDoutSpecialFunc = Request_Save_SideDout_SpecialFuncEnd(builder)
        return requestSaveSideDoutSpecialFunc
