from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_SideDout_Toggle import Request_SideDout_Toggle

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_SideDout_Toggle(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_SideDout_Toggle: ...
  @classmethod
  def GetRootAsRequest_SideDout_Toggle(cls, buf: bytes, offset: int) -> Request_SideDout_Toggle: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def PortNum(self) -> int: ...
class Request_SideDout_ToggleT(object):
  portNum: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_SideDout_ToggleT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_SideDout_ToggleT: ...
  @classmethod
  def InitFromObj(cls, requestSideDoutToggle: Request_SideDout_Toggle) -> Request_SideDout_ToggleT: ...
  def _UnPack(self, requestSideDoutToggle: Request_SideDout_Toggle) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_SideDout_ToggleStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_SideDout_ToggleAddPortNum(builder: flatbuffers.Builder, portNum: int) -> None: ...
def Request_SideDout_ToggleEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

