from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_MotionSpeedBar(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_MotionSpeedBar: ...
  @classmethod
  def GetRootAsRequest_MotionSpeedBar(cls, buf: bytes, offset: int) -> Request_MotionSpeedBar: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Alpha(self) -> float: ...
class Request_MotionSpeedBarT(object):
  alpha: float
  def __init__(
    self,
    alpha: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_MotionSpeedBarT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_MotionSpeedBarT: ...
  @classmethod
  def InitFromObj(cls, requestMotionSpeedBar: Request_MotionSpeedBar) -> Request_MotionSpeedBarT: ...
  def _UnPack(self, requestMotionSpeedBar: Request_MotionSpeedBar) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_MotionSpeedBarStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_MotionSpeedBarAddAlpha(builder: flatbuffers.Builder, alpha: float) -> None: ...
def Request_MotionSpeedBarEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

