from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_CallWhoAmI(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_CallWhoAmI: ...
  @classmethod
  def GetRootAsRequest_CallWhoAmI(cls, buf: bytes, offset: int) -> Request_CallWhoAmI: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_CallWhoAmIT(object):
  def __init__(
    self,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_CallWhoAmIT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_CallWhoAmIT: ...
  @classmethod
  def InitFromObj(cls, requestCallWhoAmI: Request_CallWhoAmI) -> Request_CallWhoAmIT: ...
  def _UnPack(self, requestCallWhoAmI: Request_CallWhoAmI) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_CallWhoAmIStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_CallWhoAmIEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

