from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Save_Gravity_Parameter import Request_Save_Gravity_Parameter

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Save_Gravity_Parameter(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Save_Gravity_Parameter: ...
  @classmethod
  def GetRootAsRequest_Save_Gravity_Parameter(cls, buf: bytes, offset: int) -> Request_Save_Gravity_Parameter: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Mode(self) -> int: ...
  def Gx(self) -> float: ...
  def Gy(self) -> float: ...
  def Gz(self) -> float: ...
class Request_Save_Gravity_ParameterT(object):
  mode: int
  gx: float
  gy: float
  gz: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Save_Gravity_ParameterT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Save_Gravity_ParameterT: ...
  @classmethod
  def InitFromObj(cls, requestSaveGravityParameter: Request_Save_Gravity_Parameter) -> Request_Save_Gravity_ParameterT: ...
  def _UnPack(self, requestSaveGravityParameter: Request_Save_Gravity_Parameter) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Save_Gravity_ParameterStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Save_Gravity_ParameterAddMode(builder: flatbuffers.Builder, mode: int) -> None: ...
def Request_Save_Gravity_ParameterAddGx(builder: flatbuffers.Builder, gx: float) -> None: ...
def Request_Save_Gravity_ParameterAddGy(builder: flatbuffers.Builder, gy: float) -> None: ...
def Request_Save_Gravity_ParameterAddGz(builder: flatbuffers.Builder, gz: float) -> None: ...
def Request_Save_Gravity_ParameterEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

