from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_MotionResetOutColl(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_MotionResetOutColl: ...
  @classmethod
  def GetRootAsRequest_MotionResetOutColl(cls, buf: bytes, offset: int) -> Request_MotionResetOutColl: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_MotionResetOutCollT(object):
  def __init__(
    self,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_MotionResetOutCollT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_MotionResetOutCollT: ...
  @classmethod
  def InitFromObj(cls, requestMotionResetOutColl: Request_MotionResetOutColl) -> Request_MotionResetOutCollT: ...
  def _UnPack(self, requestMotionResetOutColl: Request_MotionResetOutColl) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_MotionResetOutCollStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_MotionResetOutCollEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

