from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_ServoControl(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_ServoControl: ...
  @classmethod
  def GetRootAsRequest_ServoControl(cls, buf: bytes, offset: int) -> Request_ServoControl: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ServoOption(self) -> int: ...
class Request_ServoControlT(object):
  servoOption: int
  def __init__(
    self,
    servoOption: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_ServoControlT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_ServoControlT: ...
  @classmethod
  def InitFromObj(cls, requestServoControl: Request_ServoControl) -> Request_ServoControlT: ...
  def _UnPack(self, requestServoControl: Request_ServoControl) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_ServoControlStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_ServoControlAddServoOption(builder: flatbuffers.Builder, servoOption: int) -> None: ...
def Request_ServoControlEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

