from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_ProgramBefore(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_ProgramBefore: ...
  @classmethod
  def GetRootAsRequest_ProgramBefore(cls, buf: bytes, offset: int) -> Request_ProgramBefore: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Option(self) -> int: ...
class Request_ProgramBeforeT(object):
  option: int
  def __init__(
    self,
    option: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_ProgramBeforeT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_ProgramBeforeT: ...
  @classmethod
  def InitFromObj(cls, requestProgramBefore: Request_ProgramBefore) -> Request_ProgramBeforeT: ...
  def _UnPack(self, requestProgramBefore: Request_ProgramBefore) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_ProgramBeforeStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_ProgramBeforeAddOption(builder: flatbuffers.Builder, option: int) -> None: ...
def Request_ProgramBeforeEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

