from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Set_Free_Drive(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Set_Free_Drive: ...
  @classmethod
  def GetRootAsRequest_Set_Free_Drive(cls, buf: bytes, offset: int) -> Request_Set_Free_Drive: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Onoff(self) -> int: ...
  def Sensitivity(self) -> float: ...
class Request_Set_Free_DriveT(object):
  onoff: int
  sensitivity: float
  def __init__(
    self,
    onoff: int = ...,
    sensitivity: float = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Set_Free_DriveT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Set_Free_DriveT: ...
  @classmethod
  def InitFromObj(cls, requestSetFreeDrive: Request_Set_Free_Drive) -> Request_Set_Free_DriveT: ...
  def _UnPack(self, requestSetFreeDrive: Request_Set_Free_Drive) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Set_Free_DriveStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Set_Free_DriveAddOnoff(builder: flatbuffers.Builder, onoff: int) -> None: ...
def Request_Set_Free_DriveAddSensitivity(builder: flatbuffers.Builder, sensitivity: float) -> None: ...
def Request_Set_Free_DriveEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

