from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.MoveInput_Target import MoveInput_Target, MoveInput_TargetT
from rb_flat_buffers.IPC.Request_Move_SmoothJogJ import Request_Move_SmoothJogJ

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_SmoothJogJ(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_SmoothJogJ: ...
  @classmethod
  def GetRootAsRequest_Move_SmoothJogJ(cls, buf: bytes, offset: int) -> Request_Move_SmoothJogJ: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Target(self) -> MoveInput_Target | None: ...
class Request_Move_SmoothJogJT(object):
  target: MoveInput_TargetT | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_SmoothJogJT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_SmoothJogJT: ...
  @classmethod
  def InitFromObj(cls, requestMoveSmoothJogJ: Request_Move_SmoothJogJ) -> Request_Move_SmoothJogJT: ...
  def _UnPack(self, requestMoveSmoothJogJ: Request_Move_SmoothJogJ) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_SmoothJogJStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_SmoothJogJAddTarget(builder: flatbuffers.Builder, target: uoffset) -> None: ...
def Request_Move_SmoothJogJEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

