from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_MotionHalt(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_MotionHalt: ...
  @classmethod
  def GetRootAsRequest_MotionHalt(cls, buf: bytes, offset: int) -> Request_MotionHalt: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
class Request_MotionHaltT(object):
  def __init__(
    self,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_MotionHaltT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_MotionHaltT: ...
  @classmethod
  def InitFromObj(cls, requestMotionHalt: Request_MotionHalt) -> Request_MotionHaltT: ...
  def _UnPack(self, requestMotionHalt: Request_MotionHalt) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_MotionHaltStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_MotionHaltEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

