# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Request_SideDout_Pulse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_SideDout_Pulse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_SideDout_Pulse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_SideDout_Pulse
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_SideDout_Pulse
    def PortNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_SideDout_Pulse
    def BlockMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_SideDout_Pulse
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_SideDout_Pulse
    def Time1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_SideDout_Pulse
    def Time2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_SideDout_Pulse
    def Time3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Request_SideDout_PulseStart(builder: flatbuffers.Builder):
    builder.StartObject(6)

def Start(builder: flatbuffers.Builder):
    Request_SideDout_PulseStart(builder)

def Request_SideDout_PulseAddPortNum(builder: flatbuffers.Builder, portNum: int):
    builder.PrependInt32Slot(0, portNum, 0)

def AddPortNum(builder: flatbuffers.Builder, portNum: int):
    Request_SideDout_PulseAddPortNum(builder, portNum)

def Request_SideDout_PulseAddBlockMode(builder: flatbuffers.Builder, blockMode: int):
    builder.PrependInt32Slot(1, blockMode, 0)

def AddBlockMode(builder: flatbuffers.Builder, blockMode: int):
    Request_SideDout_PulseAddBlockMode(builder, blockMode)

def Request_SideDout_PulseAddDirection(builder: flatbuffers.Builder, direction: int):
    builder.PrependInt32Slot(2, direction, 0)

def AddDirection(builder: flatbuffers.Builder, direction: int):
    Request_SideDout_PulseAddDirection(builder, direction)

def Request_SideDout_PulseAddTime1(builder: flatbuffers.Builder, time1: float):
    builder.PrependFloat32Slot(3, time1, 0.0)

def AddTime1(builder: flatbuffers.Builder, time1: float):
    Request_SideDout_PulseAddTime1(builder, time1)

def Request_SideDout_PulseAddTime2(builder: flatbuffers.Builder, time2: float):
    builder.PrependFloat32Slot(4, time2, 0.0)

def AddTime2(builder: flatbuffers.Builder, time2: float):
    Request_SideDout_PulseAddTime2(builder, time2)

def Request_SideDout_PulseAddTime3(builder: flatbuffers.Builder, time3: float):
    builder.PrependFloat32Slot(5, time3, 0.0)

def AddTime3(builder: flatbuffers.Builder, time3: float):
    Request_SideDout_PulseAddTime3(builder, time3)

def Request_SideDout_PulseEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_SideDout_PulseEnd(builder)


class Request_SideDout_PulseT(object):

    # Request_SideDout_PulseT
    def __init__(
        self,
        portNum = 0,
        blockMode = 0,
        direction = 0,
        time1 = 0.0,
        time2 = 0.0,
        time3 = 0.0,
    ):
        self.portNum = portNum  # type: int
        self.blockMode = blockMode  # type: int
        self.direction = direction  # type: int
        self.time1 = time1  # type: float
        self.time2 = time2  # type: float
        self.time3 = time3  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestSideDoutPulse = Request_SideDout_Pulse()
        requestSideDoutPulse.Init(buf, pos)
        return cls.InitFromObj(requestSideDoutPulse)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestSideDoutPulse):
        x = Request_SideDout_PulseT()
        x._UnPack(requestSideDoutPulse)
        return x

    # Request_SideDout_PulseT
    def _UnPack(self, requestSideDoutPulse):
        if requestSideDoutPulse is None:
            return
        self.portNum = requestSideDoutPulse.PortNum()
        self.blockMode = requestSideDoutPulse.BlockMode()
        self.direction = requestSideDoutPulse.Direction()
        self.time1 = requestSideDoutPulse.Time1()
        self.time2 = requestSideDoutPulse.Time2()
        self.time3 = requestSideDoutPulse.Time3()

    # Request_SideDout_PulseT
    def Pack(self, builder):
        Request_SideDout_PulseStart(builder)
        Request_SideDout_PulseAddPortNum(builder, self.portNum)
        Request_SideDout_PulseAddBlockMode(builder, self.blockMode)
        Request_SideDout_PulseAddDirection(builder, self.direction)
        Request_SideDout_PulseAddTime1(builder, self.time1)
        Request_SideDout_PulseAddTime2(builder, self.time2)
        Request_SideDout_PulseAddTime3(builder, self.time3)
        requestSideDoutPulse = Request_SideDout_PulseEnd(builder)
        return requestSideDoutPulse
