from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Set_User_Frame_TCP import Request_Set_User_Frame_TCP

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Set_User_Frame_TCP(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Set_User_Frame_TCP: ...
  @classmethod
  def GetRootAsRequest_Set_User_Frame_TCP(cls, buf: bytes, offset: int) -> Request_Set_User_Frame_TCP: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def UserFrameNum(self) -> int: ...
  def SettingOption(self) -> int: ...
class Request_Set_User_Frame_TCPT(object):
  userFrameNum: int
  settingOption: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Set_User_Frame_TCPT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Set_User_Frame_TCPT: ...
  @classmethod
  def InitFromObj(cls, requestSetUserFrameTcp: Request_Set_User_Frame_TCP) -> Request_Set_User_Frame_TCPT: ...
  def _UnPack(self, requestSetUserFrameTcp: Request_Set_User_Frame_TCP) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Set_User_Frame_TCPStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Set_User_Frame_TCPAddUserFrameNum(builder: flatbuffers.Builder, userFrameNum: int) -> None: ...
def Request_Set_User_Frame_TCPAddSettingOption(builder: flatbuffers.Builder, settingOption: int) -> None: ...
def Request_Set_User_Frame_TCPEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

