# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from rb_flat_buffers.IPC.MoveInput_Speed import MoveInput_Speed, MoveInput_SpeedT
from rb_flat_buffers.IPC.MoveInput_Target import MoveInput_Target, MoveInput_TargetT
from typing import Optional
np = import_numpy()

class Request_Move_TickJogJ(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Move_TickJogJ()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Move_TickJogJ(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Move_TickJogJ
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Move_TickJogJ
    def Target(self) -> Optional[MoveInput_Target]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = MoveInput_Target()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Request_Move_TickJogJ
    def Speed(self) -> Optional[MoveInput_Speed]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = MoveInput_Speed()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Request_Move_TickJogJStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    Request_Move_TickJogJStart(builder)

def Request_Move_TickJogJAddTarget(builder: flatbuffers.Builder, target: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(target), 0)

def AddTarget(builder: flatbuffers.Builder, target: int):
    Request_Move_TickJogJAddTarget(builder, target)

def Request_Move_TickJogJAddSpeed(builder: flatbuffers.Builder, speed: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(speed), 0)

def AddSpeed(builder: flatbuffers.Builder, speed: int):
    Request_Move_TickJogJAddSpeed(builder, speed)

def Request_Move_TickJogJEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Move_TickJogJEnd(builder)

try:
    from typing import Optional
except:
    pass

class Request_Move_TickJogJT(object):

    # Request_Move_TickJogJT
    def __init__(self):
        self.target = None  # type: Optional[MoveInput_TargetT]
        self.speed = None  # type: Optional[MoveInput_SpeedT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestMoveTickJogJ = Request_Move_TickJogJ()
        requestMoveTickJogJ.Init(buf, pos)
        return cls.InitFromObj(requestMoveTickJogJ)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestMoveTickJogJ):
        x = Request_Move_TickJogJT()
        x._UnPack(requestMoveTickJogJ)
        return x

    # Request_Move_TickJogJT
    def _UnPack(self, requestMoveTickJogJ):
        if requestMoveTickJogJ is None:
            return
        if requestMoveTickJogJ.Target() is not None:
            self.target = MoveInput_TargetT.InitFromObj(requestMoveTickJogJ.Target())
        if requestMoveTickJogJ.Speed() is not None:
            self.speed = MoveInput_SpeedT.InitFromObj(requestMoveTickJogJ.Speed())

    # Request_Move_TickJogJT
    def Pack(self, builder):
        if self.target is not None:
            target = self.target.Pack(builder)
        if self.speed is not None:
            speed = self.speed.Pack(builder)
        Request_Move_TickJogJStart(builder)
        if self.target is not None:
            Request_Move_TickJogJAddTarget(builder, target)
        if self.speed is not None:
            Request_Move_TickJogJAddSpeed(builder, speed)
        requestMoveTickJogJ = Request_Move_TickJogJEnd(builder)
        return requestMoveTickJogJ
