from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Set_User_Frame_6Dof import Request_Set_User_Frame_6Dof

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Set_User_Frame_6Dof(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Set_User_Frame_6Dof: ...
  @classmethod
  def GetRootAsRequest_Set_User_Frame_6Dof(cls, buf: bytes, offset: int) -> Request_Set_User_Frame_6Dof: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def UserFrameNum(self) -> int: ...
  def SettingOption(self) -> int: ...
  def TargetX(self) -> float: ...
  def TargetY(self) -> float: ...
  def TargetZ(self) -> float: ...
  def TargetRx(self) -> float: ...
  def TargetRy(self) -> float: ...
  def TargetRz(self) -> float: ...
class Request_Set_User_Frame_6DofT(object):
  userFrameNum: int
  settingOption: int
  targetX: float
  targetY: float
  targetZ: float
  targetRx: float
  targetRy: float
  targetRz: float
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Set_User_Frame_6DofT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Set_User_Frame_6DofT: ...
  @classmethod
  def InitFromObj(cls, requestSetUserFrame6Dof: Request_Set_User_Frame_6Dof) -> Request_Set_User_Frame_6DofT: ...
  def _UnPack(self, requestSetUserFrame6Dof: Request_Set_User_Frame_6Dof) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Set_User_Frame_6DofStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Set_User_Frame_6DofAddUserFrameNum(builder: flatbuffers.Builder, userFrameNum: int) -> None: ...
def Request_Set_User_Frame_6DofAddSettingOption(builder: flatbuffers.Builder, settingOption: int) -> None: ...
def Request_Set_User_Frame_6DofAddTargetX(builder: flatbuffers.Builder, targetX: float) -> None: ...
def Request_Set_User_Frame_6DofAddTargetY(builder: flatbuffers.Builder, targetY: float) -> None: ...
def Request_Set_User_Frame_6DofAddTargetZ(builder: flatbuffers.Builder, targetZ: float) -> None: ...
def Request_Set_User_Frame_6DofAddTargetRx(builder: flatbuffers.Builder, targetRx: float) -> None: ...
def Request_Set_User_Frame_6DofAddTargetRy(builder: flatbuffers.Builder, targetRy: float) -> None: ...
def Request_Set_User_Frame_6DofAddTargetRz(builder: flatbuffers.Builder, targetRz: float) -> None: ...
def Request_Set_User_Frame_6DofEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

