# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Request_Save_Collision_Parameter(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Save_Collision_Parameter()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Save_Collision_Parameter(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Save_Collision_Parameter
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Save_Collision_Parameter
    def Onoff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Save_Collision_Parameter
    def React(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Save_Collision_Parameter
    def Threshold(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Request_Save_Collision_ParameterStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    Request_Save_Collision_ParameterStart(builder)

def Request_Save_Collision_ParameterAddOnoff(builder: flatbuffers.Builder, onoff: int):
    builder.PrependInt32Slot(0, onoff, 0)

def AddOnoff(builder: flatbuffers.Builder, onoff: int):
    Request_Save_Collision_ParameterAddOnoff(builder, onoff)

def Request_Save_Collision_ParameterAddReact(builder: flatbuffers.Builder, react: int):
    builder.PrependInt32Slot(1, react, 0)

def AddReact(builder: flatbuffers.Builder, react: int):
    Request_Save_Collision_ParameterAddReact(builder, react)

def Request_Save_Collision_ParameterAddThreshold(builder: flatbuffers.Builder, threshold: float):
    builder.PrependFloat32Slot(2, threshold, 0.0)

def AddThreshold(builder: flatbuffers.Builder, threshold: float):
    Request_Save_Collision_ParameterAddThreshold(builder, threshold)

def Request_Save_Collision_ParameterEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Request_Save_Collision_ParameterEnd(builder)


class Request_Save_Collision_ParameterT(object):

    # Request_Save_Collision_ParameterT
    def __init__(
        self,
        onoff = 0,
        react = 0,
        threshold = 0.0,
    ):
        self.onoff = onoff  # type: int
        self.react = react  # type: int
        self.threshold = threshold  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        requestSaveCollisionParameter = Request_Save_Collision_Parameter()
        requestSaveCollisionParameter.Init(buf, pos)
        return cls.InitFromObj(requestSaveCollisionParameter)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, requestSaveCollisionParameter):
        x = Request_Save_Collision_ParameterT()
        x._UnPack(requestSaveCollisionParameter)
        return x

    # Request_Save_Collision_ParameterT
    def _UnPack(self, requestSaveCollisionParameter):
        if requestSaveCollisionParameter is None:
            return
        self.onoff = requestSaveCollisionParameter.Onoff()
        self.react = requestSaveCollisionParameter.React()
        self.threshold = requestSaveCollisionParameter.Threshold()

    # Request_Save_Collision_ParameterT
    def Pack(self, builder):
        Request_Save_Collision_ParameterStart(builder)
        Request_Save_Collision_ParameterAddOnoff(builder, self.onoff)
        Request_Save_Collision_ParameterAddReact(builder, self.react)
        Request_Save_Collision_ParameterAddThreshold(builder, self.threshold)
        requestSaveCollisionParameter = Request_Save_Collision_ParameterEnd(builder)
        return requestSaveCollisionParameter
