from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Flange_Power import Request_Flange_Power

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Flange_Power(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Flange_Power: ...
  @classmethod
  def GetRootAsRequest_Flange_Power(cls, buf: bytes, offset: int) -> Request_Flange_Power: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def DesiredVoltage(self) -> int: ...
class Request_Flange_PowerT(object):
  desiredVoltage: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Flange_PowerT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Flange_PowerT: ...
  @classmethod
  def InitFromObj(cls, requestFlangePower: Request_Flange_Power) -> Request_Flange_PowerT: ...
  def _UnPack(self, requestFlangePower: Request_Flange_Power) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Flange_PowerStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Flange_PowerAddDesiredVoltage(builder: flatbuffers.Builder, desiredVoltage: int) -> None: ...
def Request_Flange_PowerEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

