from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.Request_Move_XB_RUN import Request_Move_XB_RUN

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Request_Move_XB_RUN(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Request_Move_XB_RUN: ...
  @classmethod
  def GetRootAsRequest_Move_XB_RUN(cls, buf: bytes, offset: int) -> Request_Move_XB_RUN: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def RunningMode(self) -> int: ...
class Request_Move_XB_RUNT(object):
  runningMode: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Request_Move_XB_RUNT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Request_Move_XB_RUNT: ...
  @classmethod
  def InitFromObj(cls, requestMoveXbRun: Request_Move_XB_RUN) -> Request_Move_XB_RUNT: ...
  def _UnPack(self, requestMoveXbRun: Request_Move_XB_RUN) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Request_Move_XB_RUNStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Request_Move_XB_RUNAddRunningMode(builder: flatbuffers.Builder, runningMode: int) -> None: ...
def Request_Move_XB_RUNEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

