from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.N_DIN_u import N_DIN_u, N_DIN_uT
from rb_flat_buffers.IPC.N_DOUT_u import N_DOUT_u, N_DOUT_uT
from rb_flat_buffers.IPC.Response_CallConfigControlBox import Response_CallConfigControlBox
from rb_flat_buffers.IPC.ST_Config_Area import ST_Config_Area, ST_Config_AreaT
from rb_flat_buffers.IPC.ST_Config_UserFrame import ST_Config_UserFrame, ST_Config_UserFrameT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_CallConfigControlBox(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_CallConfigControlBox: ...
  @classmethod
  def GetRootAsResponse_CallConfigControlBox(cls, buf: bytes, offset: int) -> Response_CallConfigControlBox: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def DoutSpecialFunc(self) -> N_DOUT_u | None: ...
  def DinSpecialFunc(self) -> N_DIN_u | None: ...
  def DinFilterCount(self) -> N_DIN_u | None: ...
  def AreaConfigs0(self) -> ST_Config_Area | None: ...
  def AreaConfigs1(self) -> ST_Config_Area | None: ...
  def AreaConfigs2(self) -> ST_Config_Area | None: ...
  def AreaConfigs3(self) -> ST_Config_Area | None: ...
  def AreaConfigs4(self) -> ST_Config_Area | None: ...
  def AreaConfigs5(self) -> ST_Config_Area | None: ...
  def AreaConfigs6(self) -> ST_Config_Area | None: ...
  def AreaConfigs7(self) -> ST_Config_Area | None: ...
  def UserFrame0(self) -> ST_Config_UserFrame | None: ...
  def UserFrame1(self) -> ST_Config_UserFrame | None: ...
  def UserFrame2(self) -> ST_Config_UserFrame | None: ...
  def UserFrame3(self) -> ST_Config_UserFrame | None: ...
  def UserFrame4(self) -> ST_Config_UserFrame | None: ...
  def UserFrame5(self) -> ST_Config_UserFrame | None: ...
  def UserFrame6(self) -> ST_Config_UserFrame | None: ...
  def UserFrame7(self) -> ST_Config_UserFrame | None: ...
class Response_CallConfigControlBoxT(object):
  doutSpecialFunc: N_DOUT_uT | None
  dinSpecialFunc: N_DIN_uT | None
  dinFilterCount: N_DIN_uT | None
  areaConfigs0: ST_Config_AreaT | None
  areaConfigs1: ST_Config_AreaT | None
  areaConfigs2: ST_Config_AreaT | None
  areaConfigs3: ST_Config_AreaT | None
  areaConfigs4: ST_Config_AreaT | None
  areaConfigs5: ST_Config_AreaT | None
  areaConfigs6: ST_Config_AreaT | None
  areaConfigs7: ST_Config_AreaT | None
  userFrame0: ST_Config_UserFrameT | None
  userFrame1: ST_Config_UserFrameT | None
  userFrame2: ST_Config_UserFrameT | None
  userFrame3: ST_Config_UserFrameT | None
  userFrame4: ST_Config_UserFrameT | None
  userFrame5: ST_Config_UserFrameT | None
  userFrame6: ST_Config_UserFrameT | None
  userFrame7: ST_Config_UserFrameT | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_CallConfigControlBoxT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_CallConfigControlBoxT: ...
  @classmethod
  def InitFromObj(cls, responseCallConfigControlBox: Response_CallConfigControlBox) -> Response_CallConfigControlBoxT: ...
  def _UnPack(self, responseCallConfigControlBox: Response_CallConfigControlBox) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_CallConfigControlBoxStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_CallConfigControlBoxAddDoutSpecialFunc(builder: flatbuffers.Builder, doutSpecialFunc: uoffset) -> None: ...
def Response_CallConfigControlBoxAddDinSpecialFunc(builder: flatbuffers.Builder, dinSpecialFunc: uoffset) -> None: ...
def Response_CallConfigControlBoxAddDinFilterCount(builder: flatbuffers.Builder, dinFilterCount: uoffset) -> None: ...
def Response_CallConfigControlBoxAddAreaConfigs0(builder: flatbuffers.Builder, areaConfigs0: uoffset) -> None: ...
def Response_CallConfigControlBoxAddAreaConfigs1(builder: flatbuffers.Builder, areaConfigs1: uoffset) -> None: ...
def Response_CallConfigControlBoxAddAreaConfigs2(builder: flatbuffers.Builder, areaConfigs2: uoffset) -> None: ...
def Response_CallConfigControlBoxAddAreaConfigs3(builder: flatbuffers.Builder, areaConfigs3: uoffset) -> None: ...
def Response_CallConfigControlBoxAddAreaConfigs4(builder: flatbuffers.Builder, areaConfigs4: uoffset) -> None: ...
def Response_CallConfigControlBoxAddAreaConfigs5(builder: flatbuffers.Builder, areaConfigs5: uoffset) -> None: ...
def Response_CallConfigControlBoxAddAreaConfigs6(builder: flatbuffers.Builder, areaConfigs6: uoffset) -> None: ...
def Response_CallConfigControlBoxAddAreaConfigs7(builder: flatbuffers.Builder, areaConfigs7: uoffset) -> None: ...
def Response_CallConfigControlBoxAddUserFrame0(builder: flatbuffers.Builder, userFrame0: uoffset) -> None: ...
def Response_CallConfigControlBoxAddUserFrame1(builder: flatbuffers.Builder, userFrame1: uoffset) -> None: ...
def Response_CallConfigControlBoxAddUserFrame2(builder: flatbuffers.Builder, userFrame2: uoffset) -> None: ...
def Response_CallConfigControlBoxAddUserFrame3(builder: flatbuffers.Builder, userFrame3: uoffset) -> None: ...
def Response_CallConfigControlBoxAddUserFrame4(builder: flatbuffers.Builder, userFrame4: uoffset) -> None: ...
def Response_CallConfigControlBoxAddUserFrame5(builder: flatbuffers.Builder, userFrame5: uoffset) -> None: ...
def Response_CallConfigControlBoxAddUserFrame6(builder: flatbuffers.Builder, userFrame6: uoffset) -> None: ...
def Response_CallConfigControlBoxAddUserFrame7(builder: flatbuffers.Builder, userFrame7: uoffset) -> None: ...
def Response_CallConfigControlBoxEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

