from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from IPC.ST_Tool_Para import ST_Tool_Para, ST_Tool_ParaT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_CallConfigToolList(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_CallConfigToolList: ...
  @classmethod
  def GetRootAsResponse_CallConfigToolList(cls, buf: bytes, offset: int) -> Response_CallConfigToolList: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TConfigs0(self) -> ST_Tool_Para | None: ...
  def TConfigs1(self) -> ST_Tool_Para | None: ...
  def TConfigs2(self) -> ST_Tool_Para | None: ...
  def TConfigs3(self) -> ST_Tool_Para | None: ...
  def TConfigs4(self) -> ST_Tool_Para | None: ...
  def TConfigs5(self) -> ST_Tool_Para | None: ...
  def TConfigs6(self) -> ST_Tool_Para | None: ...
  def TConfigs7(self) -> ST_Tool_Para | None: ...
class Response_CallConfigToolListT(object):
  tConfigs0: ST_Tool_ParaT | None
  tConfigs1: ST_Tool_ParaT | None
  tConfigs2: ST_Tool_ParaT | None
  tConfigs3: ST_Tool_ParaT | None
  tConfigs4: ST_Tool_ParaT | None
  tConfigs5: ST_Tool_ParaT | None
  tConfigs6: ST_Tool_ParaT | None
  tConfigs7: ST_Tool_ParaT | None
  def __init__(
    self,
    tConfigs0: 'ST_Tool_ParaT' | None = ...,
    tConfigs1: 'ST_Tool_ParaT' | None = ...,
    tConfigs2: 'ST_Tool_ParaT' | None = ...,
    tConfigs3: 'ST_Tool_ParaT' | None = ...,
    tConfigs4: 'ST_Tool_ParaT' | None = ...,
    tConfigs5: 'ST_Tool_ParaT' | None = ...,
    tConfigs6: 'ST_Tool_ParaT' | None = ...,
    tConfigs7: 'ST_Tool_ParaT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_CallConfigToolListT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_CallConfigToolListT: ...
  @classmethod
  def InitFromObj(cls, responseCallConfigToolList: Response_CallConfigToolList) -> Response_CallConfigToolListT: ...
  def _UnPack(self, responseCallConfigToolList: Response_CallConfigToolList) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_CallConfigToolListStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_CallConfigToolListAddTConfigs0(builder: flatbuffers.Builder, tConfigs0: uoffset) -> None: ...
def Response_CallConfigToolListAddTConfigs1(builder: flatbuffers.Builder, tConfigs1: uoffset) -> None: ...
def Response_CallConfigToolListAddTConfigs2(builder: flatbuffers.Builder, tConfigs2: uoffset) -> None: ...
def Response_CallConfigToolListAddTConfigs3(builder: flatbuffers.Builder, tConfigs3: uoffset) -> None: ...
def Response_CallConfigToolListAddTConfigs4(builder: flatbuffers.Builder, tConfigs4: uoffset) -> None: ...
def Response_CallConfigToolListAddTConfigs5(builder: flatbuffers.Builder, tConfigs5: uoffset) -> None: ...
def Response_CallConfigToolListAddTConfigs6(builder: flatbuffers.Builder, tConfigs6: uoffset) -> None: ...
def Response_CallConfigToolListAddTConfigs7(builder: flatbuffers.Builder, tConfigs7: uoffset) -> None: ...
def Response_CallConfigToolListEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

