# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from rb_flat_buffers.IPC.FloatArray32 import FloatArray32, FloatArray32T
from typing import Optional
np = import_numpy()

class Response_Get_Core_Data(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response_Get_Core_Data()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse_Get_Core_Data(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response_Get_Core_Data
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response_Get_Core_Data
    def Valid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Response_Get_Core_Data
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Response_Get_Core_Data
    def PayloadNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Response_Get_Core_Data
    def PayloadArr(self) -> Optional[FloatArray32]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = FloatArray32()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Response_Get_Core_Data
    def PayloadStr(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Response_Get_Core_DataStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    Response_Get_Core_DataStart(builder)

def Response_Get_Core_DataAddValid(builder: flatbuffers.Builder, valid: int):
    builder.PrependInt32Slot(0, valid, 0)

def AddValid(builder: flatbuffers.Builder, valid: int):
    Response_Get_Core_DataAddValid(builder, valid)

def Response_Get_Core_DataAddType(builder: flatbuffers.Builder, type: int):
    builder.PrependInt32Slot(1, type, 0)

def AddType(builder: flatbuffers.Builder, type: int):
    Response_Get_Core_DataAddType(builder, type)

def Response_Get_Core_DataAddPayloadNum(builder: flatbuffers.Builder, payloadNum: float):
    builder.PrependFloat32Slot(2, payloadNum, 0.0)

def AddPayloadNum(builder: flatbuffers.Builder, payloadNum: float):
    Response_Get_Core_DataAddPayloadNum(builder, payloadNum)

def Response_Get_Core_DataAddPayloadArr(builder: flatbuffers.Builder, payloadArr: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(payloadArr), 0)

def AddPayloadArr(builder: flatbuffers.Builder, payloadArr: Any):
    Response_Get_Core_DataAddPayloadArr(builder, payloadArr)

def Response_Get_Core_DataAddPayloadStr(builder: flatbuffers.Builder, payloadStr: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(payloadStr), 0)

def AddPayloadStr(builder: flatbuffers.Builder, payloadStr: int):
    Response_Get_Core_DataAddPayloadStr(builder, payloadStr)

def Response_Get_Core_DataEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return Response_Get_Core_DataEnd(builder)

try:
    from typing import Optional
except:
    pass

class Response_Get_Core_DataT(object):

    # Response_Get_Core_DataT
    def __init__(
        self,
        valid = 0,
        type = 0,
        payloadNum = 0.0,
        payloadArr = None,
        payloadStr = None,
    ):
        self.valid = valid  # type: int
        self.type = type  # type: int
        self.payloadNum = payloadNum  # type: float
        self.payloadArr = payloadArr  # type: Optional[FloatArray32T]
        self.payloadStr = payloadStr  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        responseGetCoreData = Response_Get_Core_Data()
        responseGetCoreData.Init(buf, pos)
        return cls.InitFromObj(responseGetCoreData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, responseGetCoreData):
        x = Response_Get_Core_DataT()
        x._UnPack(responseGetCoreData)
        return x

    # Response_Get_Core_DataT
    def _UnPack(self, responseGetCoreData):
        if responseGetCoreData is None:
            return
        self.valid = responseGetCoreData.Valid()
        self.type = responseGetCoreData.Type()
        self.payloadNum = responseGetCoreData.PayloadNum()
        if responseGetCoreData.PayloadArr() is not None:
            self.payloadArr = FloatArray32T.InitFromObj(responseGetCoreData.PayloadArr())
        self.payloadStr = responseGetCoreData.PayloadStr()

    # Response_Get_Core_DataT
    def Pack(self, builder):
        if self.payloadStr is not None:
            payloadStr = builder.CreateString(self.payloadStr)
        Response_Get_Core_DataStart(builder)
        Response_Get_Core_DataAddValid(builder, self.valid)
        Response_Get_Core_DataAddType(builder, self.type)
        Response_Get_Core_DataAddPayloadNum(builder, self.payloadNum)
        if self.payloadArr is not None:
            payloadArr = self.payloadArr.Pack(builder)
            Response_Get_Core_DataAddPayloadArr(builder, payloadArr)
        if self.payloadStr is not None:
            Response_Get_Core_DataAddPayloadStr(builder, payloadStr)
        responseGetCoreData = Response_Get_Core_DataEnd(builder)
        return responseGetCoreData
