from __future__ import annotations

import flatbuffers
import numpy as np

import typing

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Functions(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Functions: ...
  @classmethod
  def GetRootAsResponse_Functions(cls, buf: bytes, offset: int) -> Response_Functions: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ReturnValue(self) -> int: ...
class Response_FunctionsT(object):
  returnValue: int
  def __init__(
    self,
    returnValue: int = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_FunctionsT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_FunctionsT: ...
  @classmethod
  def InitFromObj(cls, responseFunctions: Response_Functions) -> Response_FunctionsT: ...
  def _UnPack(self, responseFunctions: Response_Functions) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_FunctionsStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_FunctionsAddReturnValue(builder: flatbuffers.Builder, returnValue: int) -> None: ...
def Response_FunctionsEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

