from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.IPC.FloatArray32 import FloatArray32, FloatArray32T

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Get_Core_Data(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Get_Core_Data: ...
  @classmethod
  def GetRootAsResponse_Get_Core_Data(cls, buf: bytes, offset: int) -> Response_Get_Core_Data: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Valid(self) -> int: ...
  def Type(self) -> int: ...
  def PayloadNum(self) -> float: ...
  def PayloadArr(self) -> FloatArray32 | None: ...
  def PayloadStr(self) -> str | None: ...
class Response_Get_Core_DataT(object):
  valid: int
  type: int
  payloadNum: float
  payloadArr: FloatArray32T | None
  payloadStr: str | None
  def __init__(
    self,
    valid: int = ...,
    type: int = ...,
    payloadNum: float = ...,
    payloadArr: 'FloatArray32T' | None = ...,
    payloadStr: str | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Get_Core_DataT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Get_Core_DataT: ...
  @classmethod
  def InitFromObj(cls, responseGetCoreData: Response_Get_Core_Data) -> Response_Get_Core_DataT: ...
  def _UnPack(self, responseGetCoreData: Response_Get_Core_Data) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Get_Core_DataStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Get_Core_DataAddValid(builder: flatbuffers.Builder, valid: int) -> None: ...
def Response_Get_Core_DataAddType(builder: flatbuffers.Builder, type: int) -> None: ...
def Response_Get_Core_DataAddPayloadNum(builder: flatbuffers.Builder, payloadNum: float) -> None: ...
def Response_Get_Core_DataAddPayloadArr(builder: flatbuffers.Builder, payloadArr: uoffset) -> None: ...
def Response_Get_Core_DataAddPayloadStr(builder: flatbuffers.Builder, payloadStr: uoffset) -> None: ...
def Response_Get_Core_DataEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

