from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.ST_Box_Para import ST_Box_Para

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ST_Box_Para(object):
  @classmethod
  def SizeOf(cls) -> int: ...

  def Init(self, buf: bytes, pos: int) -> None: ...
  def F(self, i: int) -> typing.List[float]: ...
  def FAsNumpy(self) -> np.ndarray: ...
  def FLength(self) -> int: ...
  def FIsNone(self) -> bool: ...
class ST_Box_ParaT(object):
  f: typing.List[float]
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ST_Box_ParaT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ST_Box_ParaT: ...
  @classmethod
  def InitFromObj(cls, stBoxPara: ST_Box_Para) -> ST_Box_ParaT: ...
  def _UnPack(self, stBoxPara: ST_Box_Para) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...

def CreateST_Box_Para(builder: flatbuffers.Builder, f: float) -> uoffset: ...

