from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from IPC.Vec3f import Vec3f, Vec3fT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ST_Config_UserFrame(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ST_Config_UserFrame: ...
  @classmethod
  def GetRootAsST_Config_UserFrame(cls, buf: bytes, offset: int) -> ST_Config_UserFrame: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def UserfName(self) -> str | None: ...
  def UserfOffset(self) -> Vec3f | None: ...
  def UserfEuler(self) -> Vec3f | None: ...
class ST_Config_UserFrameT(object):
  userfName: str | None
  userfOffset: Vec3fT | None
  userfEuler: Vec3fT | None
  def __init__(
    self,
    userfName: str | None = ...,
    userfOffset: 'Vec3fT' | None = ...,
    userfEuler: 'Vec3fT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ST_Config_UserFrameT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ST_Config_UserFrameT: ...
  @classmethod
  def InitFromObj(cls, stConfigUserFrame: ST_Config_UserFrame) -> ST_Config_UserFrameT: ...
  def _UnPack(self, stConfigUserFrame: ST_Config_UserFrame) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ST_Config_UserFrameStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ST_Config_UserFrameAddUserfName(builder: flatbuffers.Builder, userfName: uoffset) -> None: ...
def ST_Config_UserFrameAddUserfOffset(builder: flatbuffers.Builder, userfOffset: uoffset) -> None: ...
def ST_Config_UserFrameAddUserfEuler(builder: flatbuffers.Builder, userfEuler: uoffset) -> None: ...
def ST_Config_UserFrameEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

