from __future__ import annotations

import flatbuffers
import numpy as np

import typing
from rb_flat_buffers.IPC.ST_Box_Para import ST_Box_Para, ST_Box_ParaT
from rb_flat_buffers.IPC.Vec3f import Vec3f, Vec3fT

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class ST_Tool_Para(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ST_Tool_Para: ...
  @classmethod
  def GetRootAsST_Tool_Para(cls, buf: bytes, offset: int) -> ST_Tool_Para: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def ToolName(self) -> str | None: ...
  def ComMass(self) -> float: ...
  def ComOffset(self) -> Vec3f | None: ...
  def TcpOffset(self) -> Vec3f | None: ...
  def TcpEuler(self) -> Vec3f | None: ...
  def BoxType(self) -> int: ...
  def BoxParameter(self) -> ST_Box_Para | None: ...
class ST_Tool_ParaT(object):
  toolName: str | None
  comMass: float
  comOffset: Vec3fT | None
  tcpOffset: Vec3fT | None
  tcpEuler: Vec3fT | None
  boxType: int
  boxParameter: ST_Box_ParaT | None
  def __init__(
    self,
    toolName: str | None = ...,
    comMass: float = ...,
    comOffset: 'Vec3fT' | None = ...,
    tcpOffset: 'Vec3fT' | None = ...,
    tcpEuler: 'Vec3fT' | None = ...,
    boxType: int = ...,
    boxParameter: 'ST_Box_ParaT' | None = ...,
  ) -> None: ...
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> ST_Tool_ParaT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> ST_Tool_ParaT: ...
  @classmethod
  def InitFromObj(cls, stToolPara: ST_Tool_Para) -> ST_Tool_ParaT: ...
  def _UnPack(self, stToolPara: ST_Tool_Para) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def ST_Tool_ParaStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def ST_Tool_ParaAddToolName(builder: flatbuffers.Builder, toolName: uoffset) -> None: ...
def ST_Tool_ParaAddComMass(builder: flatbuffers.Builder, comMass: float) -> None: ...
def ST_Tool_ParaAddComOffset(builder: flatbuffers.Builder, comOffset: uoffset) -> None: ...
def ST_Tool_ParaAddTcpOffset(builder: flatbuffers.Builder, tcpOffset: uoffset) -> None: ...
def ST_Tool_ParaAddTcpEuler(builder: flatbuffers.Builder, tcpEuler: uoffset) -> None: ...
def ST_Tool_ParaAddBoxType(builder: flatbuffers.Builder, boxType: int) -> None: ...
def ST_Tool_ParaAddBoxParameter(builder: flatbuffers.Builder, boxParameter: uoffset) -> None: ...
def ST_Tool_ParaEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

