# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from rb_flat_buffers.IPC.N_AIN_f import N_AIN_f, N_AIN_fT
from rb_flat_buffers.IPC.N_AOUT_f import N_AOUT_f, N_AOUT_fT
from rb_flat_buffers.IPC.N_CARTE_f import N_CARTE_f, N_CARTE_fT
from rb_flat_buffers.IPC.N_DIN_u import N_DIN_u, N_DIN_uT
from rb_flat_buffers.IPC.N_DOUT_u import N_DOUT_u, N_DOUT_uT
from rb_flat_buffers.IPC.N_JOINT_f import N_JOINT_f, N_JOINT_fT
from typing import Optional
np = import_numpy()

class State_Core(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = State_Core()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsState_Core(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # State_Core
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # State_Core
    def HeartBeat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def JointQRef(self) -> Optional[N_JOINT_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_JOINT_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def JointQEnc(self) -> Optional[N_JOINT_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_JOINT_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def JointTEsti(self) -> Optional[N_JOINT_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_JOINT_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def JointTMeas(self) -> Optional[N_JOINT_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_JOINT_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def JointTemper(self) -> Optional[N_JOINT_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_JOINT_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def CarteXRef(self) -> Optional[N_CARTE_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_CARTE_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def CarteXEnc(self) -> Optional[N_CARTE_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_CARTE_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def UserfSelectionNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def UserfXRef(self) -> Optional[N_CARTE_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_CARTE_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def ToolSelectionNo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def ToolName(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # State_Core
    def ToolTcpX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def ToolTcpY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def ToolTcpZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def ToolTcpRx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def ToolTcpRy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def ToolTcpRz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def ToolComM(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def ToolComX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def ToolComY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def ToolComZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def CboxDigitalInput(self) -> Optional[N_DIN_u]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_DIN_u()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def CboxDigitalOutput(self) -> Optional[N_DOUT_u]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_DOUT_u()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def CboxAnalogInput(self) -> Optional[N_AIN_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_AIN_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def CboxAnalogOutput(self) -> Optional[N_AOUT_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_AOUT_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def ExDigitalInput(self) -> Optional[N_DIN_u]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_DIN_u()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def ExDigitalOutput(self) -> Optional[N_DOUT_u]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_DOUT_u()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def ExAnalogInput(self) -> Optional[N_AIN_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_AIN_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def ExAnalogOutput(self) -> Optional[N_AOUT_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_AOUT_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def ToolDigitalInput(self) -> Optional[N_DIN_u]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_DIN_u()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def ToolDigitalOutput(self) -> Optional[N_DOUT_u]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_DOUT_u()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def ToolAnalogInput(self) -> Optional[N_AIN_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_AIN_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def ToolAnalogOutput(self) -> Optional[N_AOUT_f]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            x = o + self._tab.Pos
            obj = N_AOUT_f()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # State_Core
    def ToolVoltageOutput(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def MotionMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def MotionSpeedBar(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # State_Core
    def MotionIsPause(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def StatusLan2can(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def StatusSwitchEmg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def StatusPowerOut(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def StatusServoNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(86))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def StatusIsRefon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def StatusOutColl(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def StatusSelfColl(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(92))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # State_Core
    def StatusDtMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(94))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def State_CoreStart(builder: flatbuffers.Builder):
    builder.StartObject(46)

def Start(builder: flatbuffers.Builder):
    State_CoreStart(builder)

def State_CoreAddHeartBeat(builder: flatbuffers.Builder, heartBeat: int):
    builder.PrependUint8Slot(0, heartBeat, 0)

def AddHeartBeat(builder: flatbuffers.Builder, heartBeat: int):
    State_CoreAddHeartBeat(builder, heartBeat)

def State_CoreAddJointQRef(builder: flatbuffers.Builder, jointQRef: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(jointQRef), 0)

def AddJointQRef(builder: flatbuffers.Builder, jointQRef: Any):
    State_CoreAddJointQRef(builder, jointQRef)

def State_CoreAddJointQEnc(builder: flatbuffers.Builder, jointQEnc: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(jointQEnc), 0)

def AddJointQEnc(builder: flatbuffers.Builder, jointQEnc: Any):
    State_CoreAddJointQEnc(builder, jointQEnc)

def State_CoreAddJointTEsti(builder: flatbuffers.Builder, jointTEsti: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(jointTEsti), 0)

def AddJointTEsti(builder: flatbuffers.Builder, jointTEsti: Any):
    State_CoreAddJointTEsti(builder, jointTEsti)

def State_CoreAddJointTMeas(builder: flatbuffers.Builder, jointTMeas: Any):
    builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(jointTMeas), 0)

def AddJointTMeas(builder: flatbuffers.Builder, jointTMeas: Any):
    State_CoreAddJointTMeas(builder, jointTMeas)

def State_CoreAddJointTemper(builder: flatbuffers.Builder, jointTemper: Any):
    builder.PrependStructSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(jointTemper), 0)

def AddJointTemper(builder: flatbuffers.Builder, jointTemper: Any):
    State_CoreAddJointTemper(builder, jointTemper)

def State_CoreAddCarteXRef(builder: flatbuffers.Builder, carteXRef: Any):
    builder.PrependStructSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(carteXRef), 0)

def AddCarteXRef(builder: flatbuffers.Builder, carteXRef: Any):
    State_CoreAddCarteXRef(builder, carteXRef)

def State_CoreAddCarteXEnc(builder: flatbuffers.Builder, carteXEnc: Any):
    builder.PrependStructSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(carteXEnc), 0)

def AddCarteXEnc(builder: flatbuffers.Builder, carteXEnc: Any):
    State_CoreAddCarteXEnc(builder, carteXEnc)

def State_CoreAddUserfSelectionNo(builder: flatbuffers.Builder, userfSelectionNo: int):
    builder.PrependInt32Slot(8, userfSelectionNo, 0)

def AddUserfSelectionNo(builder: flatbuffers.Builder, userfSelectionNo: int):
    State_CoreAddUserfSelectionNo(builder, userfSelectionNo)

def State_CoreAddUserfXRef(builder: flatbuffers.Builder, userfXRef: Any):
    builder.PrependStructSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(userfXRef), 0)

def AddUserfXRef(builder: flatbuffers.Builder, userfXRef: Any):
    State_CoreAddUserfXRef(builder, userfXRef)

def State_CoreAddToolSelectionNo(builder: flatbuffers.Builder, toolSelectionNo: int):
    builder.PrependInt32Slot(10, toolSelectionNo, 0)

def AddToolSelectionNo(builder: flatbuffers.Builder, toolSelectionNo: int):
    State_CoreAddToolSelectionNo(builder, toolSelectionNo)

def State_CoreAddToolName(builder: flatbuffers.Builder, toolName: int):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(toolName), 0)

def AddToolName(builder: flatbuffers.Builder, toolName: int):
    State_CoreAddToolName(builder, toolName)

def State_CoreAddToolTcpX(builder: flatbuffers.Builder, toolTcpX: float):
    builder.PrependFloat32Slot(12, toolTcpX, 0.0)

def AddToolTcpX(builder: flatbuffers.Builder, toolTcpX: float):
    State_CoreAddToolTcpX(builder, toolTcpX)

def State_CoreAddToolTcpY(builder: flatbuffers.Builder, toolTcpY: float):
    builder.PrependFloat32Slot(13, toolTcpY, 0.0)

def AddToolTcpY(builder: flatbuffers.Builder, toolTcpY: float):
    State_CoreAddToolTcpY(builder, toolTcpY)

def State_CoreAddToolTcpZ(builder: flatbuffers.Builder, toolTcpZ: float):
    builder.PrependFloat32Slot(14, toolTcpZ, 0.0)

def AddToolTcpZ(builder: flatbuffers.Builder, toolTcpZ: float):
    State_CoreAddToolTcpZ(builder, toolTcpZ)

def State_CoreAddToolTcpRx(builder: flatbuffers.Builder, toolTcpRx: float):
    builder.PrependFloat32Slot(15, toolTcpRx, 0.0)

def AddToolTcpRx(builder: flatbuffers.Builder, toolTcpRx: float):
    State_CoreAddToolTcpRx(builder, toolTcpRx)

def State_CoreAddToolTcpRy(builder: flatbuffers.Builder, toolTcpRy: float):
    builder.PrependFloat32Slot(16, toolTcpRy, 0.0)

def AddToolTcpRy(builder: flatbuffers.Builder, toolTcpRy: float):
    State_CoreAddToolTcpRy(builder, toolTcpRy)

def State_CoreAddToolTcpRz(builder: flatbuffers.Builder, toolTcpRz: float):
    builder.PrependFloat32Slot(17, toolTcpRz, 0.0)

def AddToolTcpRz(builder: flatbuffers.Builder, toolTcpRz: float):
    State_CoreAddToolTcpRz(builder, toolTcpRz)

def State_CoreAddToolComM(builder: flatbuffers.Builder, toolComM: float):
    builder.PrependFloat32Slot(18, toolComM, 0.0)

def AddToolComM(builder: flatbuffers.Builder, toolComM: float):
    State_CoreAddToolComM(builder, toolComM)

def State_CoreAddToolComX(builder: flatbuffers.Builder, toolComX: float):
    builder.PrependFloat32Slot(19, toolComX, 0.0)

def AddToolComX(builder: flatbuffers.Builder, toolComX: float):
    State_CoreAddToolComX(builder, toolComX)

def State_CoreAddToolComY(builder: flatbuffers.Builder, toolComY: float):
    builder.PrependFloat32Slot(20, toolComY, 0.0)

def AddToolComY(builder: flatbuffers.Builder, toolComY: float):
    State_CoreAddToolComY(builder, toolComY)

def State_CoreAddToolComZ(builder: flatbuffers.Builder, toolComZ: float):
    builder.PrependFloat32Slot(21, toolComZ, 0.0)

def AddToolComZ(builder: flatbuffers.Builder, toolComZ: float):
    State_CoreAddToolComZ(builder, toolComZ)

def State_CoreAddCboxDigitalInput(builder: flatbuffers.Builder, cboxDigitalInput: Any):
    builder.PrependStructSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(cboxDigitalInput), 0)

def AddCboxDigitalInput(builder: flatbuffers.Builder, cboxDigitalInput: Any):
    State_CoreAddCboxDigitalInput(builder, cboxDigitalInput)

def State_CoreAddCboxDigitalOutput(builder: flatbuffers.Builder, cboxDigitalOutput: Any):
    builder.PrependStructSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(cboxDigitalOutput), 0)

def AddCboxDigitalOutput(builder: flatbuffers.Builder, cboxDigitalOutput: Any):
    State_CoreAddCboxDigitalOutput(builder, cboxDigitalOutput)

def State_CoreAddCboxAnalogInput(builder: flatbuffers.Builder, cboxAnalogInput: Any):
    builder.PrependStructSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(cboxAnalogInput), 0)

def AddCboxAnalogInput(builder: flatbuffers.Builder, cboxAnalogInput: Any):
    State_CoreAddCboxAnalogInput(builder, cboxAnalogInput)

def State_CoreAddCboxAnalogOutput(builder: flatbuffers.Builder, cboxAnalogOutput: Any):
    builder.PrependStructSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(cboxAnalogOutput), 0)

def AddCboxAnalogOutput(builder: flatbuffers.Builder, cboxAnalogOutput: Any):
    State_CoreAddCboxAnalogOutput(builder, cboxAnalogOutput)

def State_CoreAddExDigitalInput(builder: flatbuffers.Builder, exDigitalInput: Any):
    builder.PrependStructSlot(26, flatbuffers.number_types.UOffsetTFlags.py_type(exDigitalInput), 0)

def AddExDigitalInput(builder: flatbuffers.Builder, exDigitalInput: Any):
    State_CoreAddExDigitalInput(builder, exDigitalInput)

def State_CoreAddExDigitalOutput(builder: flatbuffers.Builder, exDigitalOutput: Any):
    builder.PrependStructSlot(27, flatbuffers.number_types.UOffsetTFlags.py_type(exDigitalOutput), 0)

def AddExDigitalOutput(builder: flatbuffers.Builder, exDigitalOutput: Any):
    State_CoreAddExDigitalOutput(builder, exDigitalOutput)

def State_CoreAddExAnalogInput(builder: flatbuffers.Builder, exAnalogInput: Any):
    builder.PrependStructSlot(28, flatbuffers.number_types.UOffsetTFlags.py_type(exAnalogInput), 0)

def AddExAnalogInput(builder: flatbuffers.Builder, exAnalogInput: Any):
    State_CoreAddExAnalogInput(builder, exAnalogInput)

def State_CoreAddExAnalogOutput(builder: flatbuffers.Builder, exAnalogOutput: Any):
    builder.PrependStructSlot(29, flatbuffers.number_types.UOffsetTFlags.py_type(exAnalogOutput), 0)

def AddExAnalogOutput(builder: flatbuffers.Builder, exAnalogOutput: Any):
    State_CoreAddExAnalogOutput(builder, exAnalogOutput)

def State_CoreAddToolDigitalInput(builder: flatbuffers.Builder, toolDigitalInput: Any):
    builder.PrependStructSlot(30, flatbuffers.number_types.UOffsetTFlags.py_type(toolDigitalInput), 0)

def AddToolDigitalInput(builder: flatbuffers.Builder, toolDigitalInput: Any):
    State_CoreAddToolDigitalInput(builder, toolDigitalInput)

def State_CoreAddToolDigitalOutput(builder: flatbuffers.Builder, toolDigitalOutput: Any):
    builder.PrependStructSlot(31, flatbuffers.number_types.UOffsetTFlags.py_type(toolDigitalOutput), 0)

def AddToolDigitalOutput(builder: flatbuffers.Builder, toolDigitalOutput: Any):
    State_CoreAddToolDigitalOutput(builder, toolDigitalOutput)

def State_CoreAddToolAnalogInput(builder: flatbuffers.Builder, toolAnalogInput: Any):
    builder.PrependStructSlot(32, flatbuffers.number_types.UOffsetTFlags.py_type(toolAnalogInput), 0)

def AddToolAnalogInput(builder: flatbuffers.Builder, toolAnalogInput: Any):
    State_CoreAddToolAnalogInput(builder, toolAnalogInput)

def State_CoreAddToolAnalogOutput(builder: flatbuffers.Builder, toolAnalogOutput: Any):
    builder.PrependStructSlot(33, flatbuffers.number_types.UOffsetTFlags.py_type(toolAnalogOutput), 0)

def AddToolAnalogOutput(builder: flatbuffers.Builder, toolAnalogOutput: Any):
    State_CoreAddToolAnalogOutput(builder, toolAnalogOutput)

def State_CoreAddToolVoltageOutput(builder: flatbuffers.Builder, toolVoltageOutput: float):
    builder.PrependFloat32Slot(34, toolVoltageOutput, 0.0)

def AddToolVoltageOutput(builder: flatbuffers.Builder, toolVoltageOutput: float):
    State_CoreAddToolVoltageOutput(builder, toolVoltageOutput)

def State_CoreAddMotionMode(builder: flatbuffers.Builder, motionMode: int):
    builder.PrependUint8Slot(35, motionMode, 0)

def AddMotionMode(builder: flatbuffers.Builder, motionMode: int):
    State_CoreAddMotionMode(builder, motionMode)

def State_CoreAddMotionSpeedBar(builder: flatbuffers.Builder, motionSpeedBar: float):
    builder.PrependFloat32Slot(36, motionSpeedBar, 0.0)

def AddMotionSpeedBar(builder: flatbuffers.Builder, motionSpeedBar: float):
    State_CoreAddMotionSpeedBar(builder, motionSpeedBar)

def State_CoreAddMotionIsPause(builder: flatbuffers.Builder, motionIsPause: int):
    builder.PrependUint8Slot(37, motionIsPause, 0)

def AddMotionIsPause(builder: flatbuffers.Builder, motionIsPause: int):
    State_CoreAddMotionIsPause(builder, motionIsPause)

def State_CoreAddStatusLan2can(builder: flatbuffers.Builder, statusLan2can: int):
    builder.PrependUint8Slot(38, statusLan2can, 0)

def AddStatusLan2can(builder: flatbuffers.Builder, statusLan2can: int):
    State_CoreAddStatusLan2can(builder, statusLan2can)

def State_CoreAddStatusSwitchEmg(builder: flatbuffers.Builder, statusSwitchEmg: int):
    builder.PrependUint8Slot(39, statusSwitchEmg, 0)

def AddStatusSwitchEmg(builder: flatbuffers.Builder, statusSwitchEmg: int):
    State_CoreAddStatusSwitchEmg(builder, statusSwitchEmg)

def State_CoreAddStatusPowerOut(builder: flatbuffers.Builder, statusPowerOut: int):
    builder.PrependUint8Slot(40, statusPowerOut, 0)

def AddStatusPowerOut(builder: flatbuffers.Builder, statusPowerOut: int):
    State_CoreAddStatusPowerOut(builder, statusPowerOut)

def State_CoreAddStatusServoNum(builder: flatbuffers.Builder, statusServoNum: int):
    builder.PrependUint8Slot(41, statusServoNum, 0)

def AddStatusServoNum(builder: flatbuffers.Builder, statusServoNum: int):
    State_CoreAddStatusServoNum(builder, statusServoNum)

def State_CoreAddStatusIsRefon(builder: flatbuffers.Builder, statusIsRefon: int):
    builder.PrependUint8Slot(42, statusIsRefon, 0)

def AddStatusIsRefon(builder: flatbuffers.Builder, statusIsRefon: int):
    State_CoreAddStatusIsRefon(builder, statusIsRefon)

def State_CoreAddStatusOutColl(builder: flatbuffers.Builder, statusOutColl: int):
    builder.PrependUint8Slot(43, statusOutColl, 0)

def AddStatusOutColl(builder: flatbuffers.Builder, statusOutColl: int):
    State_CoreAddStatusOutColl(builder, statusOutColl)

def State_CoreAddStatusSelfColl(builder: flatbuffers.Builder, statusSelfColl: int):
    builder.PrependUint8Slot(44, statusSelfColl, 0)

def AddStatusSelfColl(builder: flatbuffers.Builder, statusSelfColl: int):
    State_CoreAddStatusSelfColl(builder, statusSelfColl)

def State_CoreAddStatusDtMode(builder: flatbuffers.Builder, statusDtMode: int):
    builder.PrependUint8Slot(45, statusDtMode, 0)

def AddStatusDtMode(builder: flatbuffers.Builder, statusDtMode: int):
    State_CoreAddStatusDtMode(builder, statusDtMode)

def State_CoreEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return State_CoreEnd(builder)

try:
    from typing import Optional
except:
    pass

class State_CoreT(object):

    # State_CoreT
    def __init__(
        self,
        heartBeat = 0,
        jointQRef = None,
        jointQEnc = None,
        jointTEsti = None,
        jointTMeas = None,
        jointTemper = None,
        carteXRef = None,
        carteXEnc = None,
        userfSelectionNo = 0,
        userfXRef = None,
        toolSelectionNo = 0,
        toolName = None,
        toolTcpX = 0.0,
        toolTcpY = 0.0,
        toolTcpZ = 0.0,
        toolTcpRx = 0.0,
        toolTcpRy = 0.0,
        toolTcpRz = 0.0,
        toolComM = 0.0,
        toolComX = 0.0,
        toolComY = 0.0,
        toolComZ = 0.0,
        cboxDigitalInput = None,
        cboxDigitalOutput = None,
        cboxAnalogInput = None,
        cboxAnalogOutput = None,
        exDigitalInput = None,
        exDigitalOutput = None,
        exAnalogInput = None,
        exAnalogOutput = None,
        toolDigitalInput = None,
        toolDigitalOutput = None,
        toolAnalogInput = None,
        toolAnalogOutput = None,
        toolVoltageOutput = 0.0,
        motionMode = 0,
        motionSpeedBar = 0.0,
        motionIsPause = 0,
        statusLan2can = 0,
        statusSwitchEmg = 0,
        statusPowerOut = 0,
        statusServoNum = 0,
        statusIsRefon = 0,
        statusOutColl = 0,
        statusSelfColl = 0,
        statusDtMode = 0,
    ):
        self.heartBeat = heartBeat  # type: int
        self.jointQRef = jointQRef  # type: Optional[N_JOINT_fT]
        self.jointQEnc = jointQEnc  # type: Optional[N_JOINT_fT]
        self.jointTEsti = jointTEsti  # type: Optional[N_JOINT_fT]
        self.jointTMeas = jointTMeas  # type: Optional[N_JOINT_fT]
        self.jointTemper = jointTemper  # type: Optional[N_JOINT_fT]
        self.carteXRef = carteXRef  # type: Optional[N_CARTE_fT]
        self.carteXEnc = carteXEnc  # type: Optional[N_CARTE_fT]
        self.userfSelectionNo = userfSelectionNo  # type: int
        self.userfXRef = userfXRef  # type: Optional[N_CARTE_fT]
        self.toolSelectionNo = toolSelectionNo  # type: int
        self.toolName = toolName  # type: Optional[str]
        self.toolTcpX = toolTcpX  # type: float
        self.toolTcpY = toolTcpY  # type: float
        self.toolTcpZ = toolTcpZ  # type: float
        self.toolTcpRx = toolTcpRx  # type: float
        self.toolTcpRy = toolTcpRy  # type: float
        self.toolTcpRz = toolTcpRz  # type: float
        self.toolComM = toolComM  # type: float
        self.toolComX = toolComX  # type: float
        self.toolComY = toolComY  # type: float
        self.toolComZ = toolComZ  # type: float
        self.cboxDigitalInput = cboxDigitalInput  # type: Optional[N_DIN_uT]
        self.cboxDigitalOutput = cboxDigitalOutput  # type: Optional[N_DOUT_uT]
        self.cboxAnalogInput = cboxAnalogInput  # type: Optional[N_AIN_fT]
        self.cboxAnalogOutput = cboxAnalogOutput  # type: Optional[N_AOUT_fT]
        self.exDigitalInput = exDigitalInput  # type: Optional[N_DIN_uT]
        self.exDigitalOutput = exDigitalOutput  # type: Optional[N_DOUT_uT]
        self.exAnalogInput = exAnalogInput  # type: Optional[N_AIN_fT]
        self.exAnalogOutput = exAnalogOutput  # type: Optional[N_AOUT_fT]
        self.toolDigitalInput = toolDigitalInput  # type: Optional[N_DIN_uT]
        self.toolDigitalOutput = toolDigitalOutput  # type: Optional[N_DOUT_uT]
        self.toolAnalogInput = toolAnalogInput  # type: Optional[N_AIN_fT]
        self.toolAnalogOutput = toolAnalogOutput  # type: Optional[N_AOUT_fT]
        self.toolVoltageOutput = toolVoltageOutput  # type: float
        self.motionMode = motionMode  # type: int
        self.motionSpeedBar = motionSpeedBar  # type: float
        self.motionIsPause = motionIsPause  # type: int
        self.statusLan2can = statusLan2can  # type: int
        self.statusSwitchEmg = statusSwitchEmg  # type: int
        self.statusPowerOut = statusPowerOut  # type: int
        self.statusServoNum = statusServoNum  # type: int
        self.statusIsRefon = statusIsRefon  # type: int
        self.statusOutColl = statusOutColl  # type: int
        self.statusSelfColl = statusSelfColl  # type: int
        self.statusDtMode = statusDtMode  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        stateCore = State_Core()
        stateCore.Init(buf, pos)
        return cls.InitFromObj(stateCore)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, stateCore):
        x = State_CoreT()
        x._UnPack(stateCore)
        return x

    # State_CoreT
    def _UnPack(self, stateCore):
        if stateCore is None:
            return
        self.heartBeat = stateCore.HeartBeat()
        if stateCore.JointQRef() is not None:
            self.jointQRef = N_JOINT_fT.InitFromObj(stateCore.JointQRef())
        if stateCore.JointQEnc() is not None:
            self.jointQEnc = N_JOINT_fT.InitFromObj(stateCore.JointQEnc())
        if stateCore.JointTEsti() is not None:
            self.jointTEsti = N_JOINT_fT.InitFromObj(stateCore.JointTEsti())
        if stateCore.JointTMeas() is not None:
            self.jointTMeas = N_JOINT_fT.InitFromObj(stateCore.JointTMeas())
        if stateCore.JointTemper() is not None:
            self.jointTemper = N_JOINT_fT.InitFromObj(stateCore.JointTemper())
        if stateCore.CarteXRef() is not None:
            self.carteXRef = N_CARTE_fT.InitFromObj(stateCore.CarteXRef())
        if stateCore.CarteXEnc() is not None:
            self.carteXEnc = N_CARTE_fT.InitFromObj(stateCore.CarteXEnc())
        self.userfSelectionNo = stateCore.UserfSelectionNo()
        if stateCore.UserfXRef() is not None:
            self.userfXRef = N_CARTE_fT.InitFromObj(stateCore.UserfXRef())
        self.toolSelectionNo = stateCore.ToolSelectionNo()
        self.toolName = stateCore.ToolName()
        self.toolTcpX = stateCore.ToolTcpX()
        self.toolTcpY = stateCore.ToolTcpY()
        self.toolTcpZ = stateCore.ToolTcpZ()
        self.toolTcpRx = stateCore.ToolTcpRx()
        self.toolTcpRy = stateCore.ToolTcpRy()
        self.toolTcpRz = stateCore.ToolTcpRz()
        self.toolComM = stateCore.ToolComM()
        self.toolComX = stateCore.ToolComX()
        self.toolComY = stateCore.ToolComY()
        self.toolComZ = stateCore.ToolComZ()
        if stateCore.CboxDigitalInput() is not None:
            self.cboxDigitalInput = N_DIN_uT.InitFromObj(stateCore.CboxDigitalInput())
        if stateCore.CboxDigitalOutput() is not None:
            self.cboxDigitalOutput = N_DOUT_uT.InitFromObj(stateCore.CboxDigitalOutput())
        if stateCore.CboxAnalogInput() is not None:
            self.cboxAnalogInput = N_AIN_fT.InitFromObj(stateCore.CboxAnalogInput())
        if stateCore.CboxAnalogOutput() is not None:
            self.cboxAnalogOutput = N_AOUT_fT.InitFromObj(stateCore.CboxAnalogOutput())
        if stateCore.ExDigitalInput() is not None:
            self.exDigitalInput = N_DIN_uT.InitFromObj(stateCore.ExDigitalInput())
        if stateCore.ExDigitalOutput() is not None:
            self.exDigitalOutput = N_DOUT_uT.InitFromObj(stateCore.ExDigitalOutput())
        if stateCore.ExAnalogInput() is not None:
            self.exAnalogInput = N_AIN_fT.InitFromObj(stateCore.ExAnalogInput())
        if stateCore.ExAnalogOutput() is not None:
            self.exAnalogOutput = N_AOUT_fT.InitFromObj(stateCore.ExAnalogOutput())
        if stateCore.ToolDigitalInput() is not None:
            self.toolDigitalInput = N_DIN_uT.InitFromObj(stateCore.ToolDigitalInput())
        if stateCore.ToolDigitalOutput() is not None:
            self.toolDigitalOutput = N_DOUT_uT.InitFromObj(stateCore.ToolDigitalOutput())
        if stateCore.ToolAnalogInput() is not None:
            self.toolAnalogInput = N_AIN_fT.InitFromObj(stateCore.ToolAnalogInput())
        if stateCore.ToolAnalogOutput() is not None:
            self.toolAnalogOutput = N_AOUT_fT.InitFromObj(stateCore.ToolAnalogOutput())
        self.toolVoltageOutput = stateCore.ToolVoltageOutput()
        self.motionMode = stateCore.MotionMode()
        self.motionSpeedBar = stateCore.MotionSpeedBar()
        self.motionIsPause = stateCore.MotionIsPause()
        self.statusLan2can = stateCore.StatusLan2can()
        self.statusSwitchEmg = stateCore.StatusSwitchEmg()
        self.statusPowerOut = stateCore.StatusPowerOut()
        self.statusServoNum = stateCore.StatusServoNum()
        self.statusIsRefon = stateCore.StatusIsRefon()
        self.statusOutColl = stateCore.StatusOutColl()
        self.statusSelfColl = stateCore.StatusSelfColl()
        self.statusDtMode = stateCore.StatusDtMode()

    # State_CoreT
    def Pack(self, builder):
        if self.toolName is not None:
            toolName = builder.CreateString(self.toolName)
        State_CoreStart(builder)
        State_CoreAddHeartBeat(builder, self.heartBeat)
        if self.jointQRef is not None:
            jointQRef = self.jointQRef.Pack(builder)
            State_CoreAddJointQRef(builder, jointQRef)
        if self.jointQEnc is not None:
            jointQEnc = self.jointQEnc.Pack(builder)
            State_CoreAddJointQEnc(builder, jointQEnc)
        if self.jointTEsti is not None:
            jointTEsti = self.jointTEsti.Pack(builder)
            State_CoreAddJointTEsti(builder, jointTEsti)
        if self.jointTMeas is not None:
            jointTMeas = self.jointTMeas.Pack(builder)
            State_CoreAddJointTMeas(builder, jointTMeas)
        if self.jointTemper is not None:
            jointTemper = self.jointTemper.Pack(builder)
            State_CoreAddJointTemper(builder, jointTemper)
        if self.carteXRef is not None:
            carteXRef = self.carteXRef.Pack(builder)
            State_CoreAddCarteXRef(builder, carteXRef)
        if self.carteXEnc is not None:
            carteXEnc = self.carteXEnc.Pack(builder)
            State_CoreAddCarteXEnc(builder, carteXEnc)
        State_CoreAddUserfSelectionNo(builder, self.userfSelectionNo)
        if self.userfXRef is not None:
            userfXRef = self.userfXRef.Pack(builder)
            State_CoreAddUserfXRef(builder, userfXRef)
        State_CoreAddToolSelectionNo(builder, self.toolSelectionNo)
        if self.toolName is not None:
            State_CoreAddToolName(builder, toolName)
        State_CoreAddToolTcpX(builder, self.toolTcpX)
        State_CoreAddToolTcpY(builder, self.toolTcpY)
        State_CoreAddToolTcpZ(builder, self.toolTcpZ)
        State_CoreAddToolTcpRx(builder, self.toolTcpRx)
        State_CoreAddToolTcpRy(builder, self.toolTcpRy)
        State_CoreAddToolTcpRz(builder, self.toolTcpRz)
        State_CoreAddToolComM(builder, self.toolComM)
        State_CoreAddToolComX(builder, self.toolComX)
        State_CoreAddToolComY(builder, self.toolComY)
        State_CoreAddToolComZ(builder, self.toolComZ)
        if self.cboxDigitalInput is not None:
            cboxDigitalInput = self.cboxDigitalInput.Pack(builder)
            State_CoreAddCboxDigitalInput(builder, cboxDigitalInput)
        if self.cboxDigitalOutput is not None:
            cboxDigitalOutput = self.cboxDigitalOutput.Pack(builder)
            State_CoreAddCboxDigitalOutput(builder, cboxDigitalOutput)
        if self.cboxAnalogInput is not None:
            cboxAnalogInput = self.cboxAnalogInput.Pack(builder)
            State_CoreAddCboxAnalogInput(builder, cboxAnalogInput)
        if self.cboxAnalogOutput is not None:
            cboxAnalogOutput = self.cboxAnalogOutput.Pack(builder)
            State_CoreAddCboxAnalogOutput(builder, cboxAnalogOutput)
        if self.exDigitalInput is not None:
            exDigitalInput = self.exDigitalInput.Pack(builder)
            State_CoreAddExDigitalInput(builder, exDigitalInput)
        if self.exDigitalOutput is not None:
            exDigitalOutput = self.exDigitalOutput.Pack(builder)
            State_CoreAddExDigitalOutput(builder, exDigitalOutput)
        if self.exAnalogInput is not None:
            exAnalogInput = self.exAnalogInput.Pack(builder)
            State_CoreAddExAnalogInput(builder, exAnalogInput)
        if self.exAnalogOutput is not None:
            exAnalogOutput = self.exAnalogOutput.Pack(builder)
            State_CoreAddExAnalogOutput(builder, exAnalogOutput)
        if self.toolDigitalInput is not None:
            toolDigitalInput = self.toolDigitalInput.Pack(builder)
            State_CoreAddToolDigitalInput(builder, toolDigitalInput)
        if self.toolDigitalOutput is not None:
            toolDigitalOutput = self.toolDigitalOutput.Pack(builder)
            State_CoreAddToolDigitalOutput(builder, toolDigitalOutput)
        if self.toolAnalogInput is not None:
            toolAnalogInput = self.toolAnalogInput.Pack(builder)
            State_CoreAddToolAnalogInput(builder, toolAnalogInput)
        if self.toolAnalogOutput is not None:
            toolAnalogOutput = self.toolAnalogOutput.Pack(builder)
            State_CoreAddToolAnalogOutput(builder, toolAnalogOutput)
        State_CoreAddToolVoltageOutput(builder, self.toolVoltageOutput)
        State_CoreAddMotionMode(builder, self.motionMode)
        State_CoreAddMotionSpeedBar(builder, self.motionSpeedBar)
        State_CoreAddMotionIsPause(builder, self.motionIsPause)
        State_CoreAddStatusLan2can(builder, self.statusLan2can)
        State_CoreAddStatusSwitchEmg(builder, self.statusSwitchEmg)
        State_CoreAddStatusPowerOut(builder, self.statusPowerOut)
        State_CoreAddStatusServoNum(builder, self.statusServoNum)
        State_CoreAddStatusIsRefon(builder, self.statusIsRefon)
        State_CoreAddStatusOutColl(builder, self.statusOutColl)
        State_CoreAddStatusSelfColl(builder, self.statusSelfColl)
        State_CoreAddStatusDtMode(builder, self.statusDtMode)
        stateCore = State_CoreEnd(builder)
        return stateCore
