from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.IPC.N_AIN_f import N_AIN_f, N_AIN_fT
from rb_flat_buffers.IPC.N_AOUT_f import N_AOUT_f, N_AOUT_fT
from rb_flat_buffers.IPC.N_CARTE_f import N_CARTE_f, N_CARTE_fT
from rb_flat_buffers.IPC.N_DIN_u import N_DIN_u, N_DIN_uT
from rb_flat_buffers.IPC.N_DOUT_u import N_DOUT_u, N_DOUT_uT
from rb_flat_buffers.IPC.N_JOINT_f import N_JOINT_f, N_JOINT_fT
from rb_flat_buffers.IPC.State_Core import State_Core

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class State_Core(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> State_Core: ...
  @classmethod
  def GetRootAsState_Core(cls, buf: bytes, offset: int) -> State_Core: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def HeartBeat(self) -> int: ...
  def JointQRef(self) -> N_JOINT_f | None: ...
  def JointQEnc(self) -> N_JOINT_f | None: ...
  def JointTEsti(self) -> N_JOINT_f | None: ...
  def JointTMeas(self) -> N_JOINT_f | None: ...
  def JointTemper(self) -> N_JOINT_f | None: ...
  def CarteXRef(self) -> N_CARTE_f | None: ...
  def CarteXEnc(self) -> N_CARTE_f | None: ...
  def UserfSelectionNo(self) -> int: ...
  def UserfXRef(self) -> N_CARTE_f | None: ...
  def ToolSelectionNo(self) -> int: ...
  def ToolName(self) -> str | None: ...
  def ToolTcpX(self) -> float: ...
  def ToolTcpY(self) -> float: ...
  def ToolTcpZ(self) -> float: ...
  def ToolTcpRx(self) -> float: ...
  def ToolTcpRy(self) -> float: ...
  def ToolTcpRz(self) -> float: ...
  def ToolComM(self) -> float: ...
  def ToolComX(self) -> float: ...
  def ToolComY(self) -> float: ...
  def ToolComZ(self) -> float: ...
  def CboxDigitalInput(self) -> N_DIN_u | None: ...
  def CboxDigitalOutput(self) -> N_DOUT_u | None: ...
  def CboxAnalogInput(self) -> N_AIN_f | None: ...
  def CboxAnalogOutput(self) -> N_AOUT_f | None: ...
  def ExDigitalInput(self) -> N_DIN_u | None: ...
  def ExDigitalOutput(self) -> N_DOUT_u | None: ...
  def ExAnalogInput(self) -> N_AIN_f | None: ...
  def ExAnalogOutput(self) -> N_AOUT_f | None: ...
  def ToolDigitalInput(self) -> N_DIN_u | None: ...
  def ToolDigitalOutput(self) -> N_DOUT_u | None: ...
  def ToolAnalogInput(self) -> N_AIN_f | None: ...
  def ToolAnalogOutput(self) -> N_AOUT_f | None: ...
  def MotionMode(self) -> int: ...
  def MotionSpeedBar(self) -> float: ...
  def MotionIsPause(self) -> int: ...
  def StatusLan2can(self) -> int: ...
  def StatusSwitchEmg(self) -> int: ...
  def StatusPowerOut(self) -> int: ...
  def StatusServoNum(self) -> int: ...
  def StatusIsRefon(self) -> int: ...
  def StatusOutColl(self) -> int: ...
  def StatusSelfColl(self) -> int: ...
  def StatusDtMode(self) -> int: ...
class State_CoreT(object):
  heartBeat: int
  jointQRef: N_JOINT_fT | None
  jointQEnc: N_JOINT_fT | None
  jointTEsti: N_JOINT_fT | None
  jointTMeas: N_JOINT_fT | None
  jointTemper: N_JOINT_fT | None
  carteXRef: N_CARTE_fT | None
  carteXEnc: N_CARTE_fT | None
  userfSelectionNo: int
  userfXRef: N_CARTE_fT | None
  toolSelectionNo: int
  toolName: str | None
  toolTcpX: float
  toolTcpY: float
  toolTcpZ: float
  toolTcpRx: float
  toolTcpRy: float
  toolTcpRz: float
  toolComM: float
  toolComX: float
  toolComY: float
  toolComZ: float
  cboxDigitalInput: N_DIN_uT | None
  cboxDigitalOutput: N_DOUT_uT | None
  cboxAnalogInput: N_AIN_fT | None
  cboxAnalogOutput: N_AOUT_fT | None
  exDigitalInput: N_DIN_uT | None
  exDigitalOutput: N_DOUT_uT | None
  exAnalogInput: N_AIN_fT | None
  exAnalogOutput: N_AOUT_fT | None
  toolDigitalInput: N_DIN_uT | None
  toolDigitalOutput: N_DOUT_uT | None
  toolAnalogInput: N_AIN_fT | None
  toolAnalogOutput: N_AOUT_fT | None
  motionMode: int
  motionSpeedBar: float
  motionIsPause: int
  statusLan2can: int
  statusSwitchEmg: int
  statusPowerOut: int
  statusServoNum: int
  statusIsRefon: int
  statusOutColl: int
  statusSelfColl: int
  statusDtMode: int
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> State_CoreT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> State_CoreT: ...
  @classmethod
  def InitFromObj(cls, stateCore: State_Core) -> State_CoreT: ...
  def _UnPack(self, stateCore: State_Core) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def State_CoreStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def State_CoreAddHeartBeat(builder: flatbuffers.Builder, heartBeat: int) -> None: ...
def State_CoreAddJointQRef(builder: flatbuffers.Builder, jointQRef: uoffset) -> None: ...
def State_CoreAddJointQEnc(builder: flatbuffers.Builder, jointQEnc: uoffset) -> None: ...
def State_CoreAddJointTEsti(builder: flatbuffers.Builder, jointTEsti: uoffset) -> None: ...
def State_CoreAddJointTMeas(builder: flatbuffers.Builder, jointTMeas: uoffset) -> None: ...
def State_CoreAddJointTemper(builder: flatbuffers.Builder, jointTemper: uoffset) -> None: ...
def State_CoreAddCarteXRef(builder: flatbuffers.Builder, carteXRef: uoffset) -> None: ...
def State_CoreAddCarteXEnc(builder: flatbuffers.Builder, carteXEnc: uoffset) -> None: ...
def State_CoreAddUserfSelectionNo(builder: flatbuffers.Builder, userfSelectionNo: int) -> None: ...
def State_CoreAddUserfXRef(builder: flatbuffers.Builder, userfXRef: uoffset) -> None: ...
def State_CoreAddToolSelectionNo(builder: flatbuffers.Builder, toolSelectionNo: int) -> None: ...
def State_CoreAddToolName(builder: flatbuffers.Builder, toolName: uoffset) -> None: ...
def State_CoreAddToolTcpX(builder: flatbuffers.Builder, toolTcpX: float) -> None: ...
def State_CoreAddToolTcpY(builder: flatbuffers.Builder, toolTcpY: float) -> None: ...
def State_CoreAddToolTcpZ(builder: flatbuffers.Builder, toolTcpZ: float) -> None: ...
def State_CoreAddToolTcpRx(builder: flatbuffers.Builder, toolTcpRx: float) -> None: ...
def State_CoreAddToolTcpRy(builder: flatbuffers.Builder, toolTcpRy: float) -> None: ...
def State_CoreAddToolTcpRz(builder: flatbuffers.Builder, toolTcpRz: float) -> None: ...
def State_CoreAddToolComM(builder: flatbuffers.Builder, toolComM: float) -> None: ...
def State_CoreAddToolComX(builder: flatbuffers.Builder, toolComX: float) -> None: ...
def State_CoreAddToolComY(builder: flatbuffers.Builder, toolComY: float) -> None: ...
def State_CoreAddToolComZ(builder: flatbuffers.Builder, toolComZ: float) -> None: ...
def State_CoreAddCboxDigitalInput(builder: flatbuffers.Builder, cboxDigitalInput: uoffset) -> None: ...
def State_CoreAddCboxDigitalOutput(builder: flatbuffers.Builder, cboxDigitalOutput: uoffset) -> None: ...
def State_CoreAddCboxAnalogInput(builder: flatbuffers.Builder, cboxAnalogInput: uoffset) -> None: ...
def State_CoreAddCboxAnalogOutput(builder: flatbuffers.Builder, cboxAnalogOutput: uoffset) -> None: ...
def State_CoreAddExDigitalInput(builder: flatbuffers.Builder, exDigitalInput: uoffset) -> None: ...
def State_CoreAddExDigitalOutput(builder: flatbuffers.Builder, exDigitalOutput: uoffset) -> None: ...
def State_CoreAddExAnalogInput(builder: flatbuffers.Builder, exAnalogInput: uoffset) -> None: ...
def State_CoreAddExAnalogOutput(builder: flatbuffers.Builder, exAnalogOutput: uoffset) -> None: ...
def State_CoreAddToolDigitalInput(builder: flatbuffers.Builder, toolDigitalInput: uoffset) -> None: ...
def State_CoreAddToolDigitalOutput(builder: flatbuffers.Builder, toolDigitalOutput: uoffset) -> None: ...
def State_CoreAddToolAnalogInput(builder: flatbuffers.Builder, toolAnalogInput: uoffset) -> None: ...
def State_CoreAddToolAnalogOutput(builder: flatbuffers.Builder, toolAnalogOutput: uoffset) -> None: ...
def State_CoreAddMotionMode(builder: flatbuffers.Builder, motionMode: int) -> None: ...
def State_CoreAddMotionSpeedBar(builder: flatbuffers.Builder, motionSpeedBar: float) -> None: ...
def State_CoreAddMotionIsPause(builder: flatbuffers.Builder, motionIsPause: int) -> None: ...
def State_CoreAddStatusLan2can(builder: flatbuffers.Builder, statusLan2can: int) -> None: ...
def State_CoreAddStatusSwitchEmg(builder: flatbuffers.Builder, statusSwitchEmg: int) -> None: ...
def State_CoreAddStatusPowerOut(builder: flatbuffers.Builder, statusPowerOut: int) -> None: ...
def State_CoreAddStatusServoNum(builder: flatbuffers.Builder, statusServoNum: int) -> None: ...
def State_CoreAddStatusIsRefon(builder: flatbuffers.Builder, statusIsRefon: int) -> None: ...
def State_CoreAddStatusOutColl(builder: flatbuffers.Builder, statusOutColl: int) -> None: ...
def State_CoreAddStatusSelfColl(builder: flatbuffers.Builder, statusSelfColl: int) -> None: ...
def State_CoreAddStatusDtMode(builder: flatbuffers.Builder, statusDtMode: int) -> None: ...
def State_CoreEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

