# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

class Vec3f(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 12

    # Vec3f
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vec3f
    def V(self, j = None):
        if j is None:
            return [self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + i * 4)) for i in range(self.VLength())]
        elif j >= 0 and j < self.VLength():
            return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + j * 4))
        else:
            return None

    # Vec3f
    def VAsNumpy(self):
        return self._tab.GetArrayAsNumpy(flatbuffers.number_types.Float32Flags, self._tab.Pos + 0, self.VLength())

    # Vec3f
    def VLength(self) -> int:
        return 3

    # Vec3f
    def VIsNone(self) -> bool:
        return False


def CreateVec3f(builder, v):
    builder.Prep(4, 12)
    for _idx0 in range(3 , 0, -1):
        builder.PrependFloat32(v[_idx0-1])
    return builder.Offset()

try:
    from typing import List
except:
    pass

class Vec3fT(object):

    # Vec3fT
    def __init__(
        self,
        v = None,
    ):
        self.v = v  # type: Optional[List[float]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        vec3f = Vec3f()
        vec3f.Init(buf, pos)
        return cls.InitFromObj(vec3f)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, vec3f):
        x = Vec3fT()
        x._UnPack(vec3f)
        return x

    # Vec3fT
    def _UnPack(self, vec3f):
        if vec3f is None:
            return
        if not vec3f.VIsNone():
            if np is None:
                self.v = []
                for i in range(vec3f.VLength()):
                    self.v.append(vec3f.V(i))
            else:
                self.v = vec3f.VAsNumpy()

    # Vec3fT
    def Pack(self, builder):
        return CreateVec3f(builder, self.v)
