from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flat_buffers.deploy.Response_Deploy_Progress import Response_Deploy_Progress

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Deploy_Progress(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Deploy_Progress: ...
  @classmethod
  def GetRootAsResponse_Deploy_Progress(cls, buf: bytes, offset: int) -> Response_Deploy_Progress: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def SwName(self) -> str | None: ...
  def Mode(self) -> str | None: ...
  def Tag(self) -> str | None: ...
  def Percentage(self) -> int: ...
  def ServiceName(self) -> str | None: ...
  def Result(self) -> str | None: ...
class Response_Deploy_ProgressT(object):
  swName: str | None
  mode: str | None
  tag: str | None
  percentage: int
  serviceName: str | None
  result: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Deploy_ProgressT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Deploy_ProgressT: ...
  @classmethod
  def InitFromObj(cls, responseDeployProgress: Response_Deploy_Progress) -> Response_Deploy_ProgressT: ...
  def _UnPack(self, responseDeployProgress: Response_Deploy_Progress) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Deploy_ProgressStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Deploy_ProgressAddSwName(builder: flatbuffers.Builder, swName: uoffset) -> None: ...
def Response_Deploy_ProgressAddMode(builder: flatbuffers.Builder, mode: uoffset) -> None: ...
def Response_Deploy_ProgressAddTag(builder: flatbuffers.Builder, tag: uoffset) -> None: ...
def Response_Deploy_ProgressAddPercentage(builder: flatbuffers.Builder, percentage: int) -> None: ...
def Response_Deploy_ProgressAddServiceName(builder: flatbuffers.Builder, serviceName: uoffset) -> None: ...
def Response_Deploy_ProgressAddResult(builder: flatbuffers.Builder, result: uoffset) -> None: ...
def Response_Deploy_ProgressEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

