# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Request_Set_Fixed_Speed_Mode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Set_Fixed_Speed_Mode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Set_Fixed_Speed_Mode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Set_Fixed_Speed_Mode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Set_Fixed_Speed_Mode
    def TargetMove(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_Fixed_Speed_Mode
    def VelOption(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_Fixed_Speed_Mode
    def VelParameter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_Fixed_Speed_Mode
    def AccOption(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_Fixed_Speed_Mode
    def AccParameter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Request_Set_Fixed_Speed_ModeStart(builder):
    builder.StartObject(5)

def Start(builder):
    Request_Set_Fixed_Speed_ModeStart(builder)

def Request_Set_Fixed_Speed_ModeAddTargetMove(builder, targetMove):
    builder.PrependInt32Slot(0, targetMove, 0)

def AddTargetMove(builder, targetMove):
    Request_Set_Fixed_Speed_ModeAddTargetMove(builder, targetMove)

def Request_Set_Fixed_Speed_ModeAddVelOption(builder, velOption):
    builder.PrependInt32Slot(1, velOption, 0)

def AddVelOption(builder, velOption):
    Request_Set_Fixed_Speed_ModeAddVelOption(builder, velOption)

def Request_Set_Fixed_Speed_ModeAddVelParameter(builder, velParameter):
    builder.PrependFloat32Slot(2, velParameter, 0.0)

def AddVelParameter(builder, velParameter):
    Request_Set_Fixed_Speed_ModeAddVelParameter(builder, velParameter)

def Request_Set_Fixed_Speed_ModeAddAccOption(builder, accOption):
    builder.PrependInt32Slot(3, accOption, 0)

def AddAccOption(builder, accOption):
    Request_Set_Fixed_Speed_ModeAddAccOption(builder, accOption)

def Request_Set_Fixed_Speed_ModeAddAccParameter(builder, accParameter):
    builder.PrependFloat32Slot(4, accParameter, 0.0)

def AddAccParameter(builder, accParameter):
    Request_Set_Fixed_Speed_ModeAddAccParameter(builder, accParameter)

def Request_Set_Fixed_Speed_ModeEnd(builder):
    return builder.EndObject()

def End(builder):
    return Request_Set_Fixed_Speed_ModeEnd(builder)
