# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Request_Set_User_Frame_3Points(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Set_User_Frame_3Points()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Set_User_Frame_3Points(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Set_User_Frame_3Points
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Set_User_Frame_3Points
    def UserFrameNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_User_Frame_3Points
    def SettingOption(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_User_Frame_3Points
    def OrderOption(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_User_Frame_3Points
    def Point1X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_3Points
    def Point1Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_3Points
    def Point1Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_3Points
    def Point2X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_3Points
    def Point2Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_3Points
    def Point2Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_3Points
    def Point3X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_3Points
    def Point3Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Request_Set_User_Frame_3Points
    def Point3Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Request_Set_User_Frame_3PointsStart(builder):
    builder.StartObject(12)

def Start(builder):
    Request_Set_User_Frame_3PointsStart(builder)

def Request_Set_User_Frame_3PointsAddUserFrameNum(builder, userFrameNum):
    builder.PrependInt32Slot(0, userFrameNum, 0)

def AddUserFrameNum(builder, userFrameNum):
    Request_Set_User_Frame_3PointsAddUserFrameNum(builder, userFrameNum)

def Request_Set_User_Frame_3PointsAddSettingOption(builder, settingOption):
    builder.PrependInt32Slot(1, settingOption, 0)

def AddSettingOption(builder, settingOption):
    Request_Set_User_Frame_3PointsAddSettingOption(builder, settingOption)

def Request_Set_User_Frame_3PointsAddOrderOption(builder, orderOption):
    builder.PrependInt32Slot(2, orderOption, 0)

def AddOrderOption(builder, orderOption):
    Request_Set_User_Frame_3PointsAddOrderOption(builder, orderOption)

def Request_Set_User_Frame_3PointsAddPoint1X(builder, point1X):
    builder.PrependFloat32Slot(3, point1X, 0.0)

def AddPoint1X(builder, point1X):
    Request_Set_User_Frame_3PointsAddPoint1X(builder, point1X)

def Request_Set_User_Frame_3PointsAddPoint1Y(builder, point1Y):
    builder.PrependFloat32Slot(4, point1Y, 0.0)

def AddPoint1Y(builder, point1Y):
    Request_Set_User_Frame_3PointsAddPoint1Y(builder, point1Y)

def Request_Set_User_Frame_3PointsAddPoint1Z(builder, point1Z):
    builder.PrependFloat32Slot(5, point1Z, 0.0)

def AddPoint1Z(builder, point1Z):
    Request_Set_User_Frame_3PointsAddPoint1Z(builder, point1Z)

def Request_Set_User_Frame_3PointsAddPoint2X(builder, point2X):
    builder.PrependFloat32Slot(6, point2X, 0.0)

def AddPoint2X(builder, point2X):
    Request_Set_User_Frame_3PointsAddPoint2X(builder, point2X)

def Request_Set_User_Frame_3PointsAddPoint2Y(builder, point2Y):
    builder.PrependFloat32Slot(7, point2Y, 0.0)

def AddPoint2Y(builder, point2Y):
    Request_Set_User_Frame_3PointsAddPoint2Y(builder, point2Y)

def Request_Set_User_Frame_3PointsAddPoint2Z(builder, point2Z):
    builder.PrependFloat32Slot(8, point2Z, 0.0)

def AddPoint2Z(builder, point2Z):
    Request_Set_User_Frame_3PointsAddPoint2Z(builder, point2Z)

def Request_Set_User_Frame_3PointsAddPoint3X(builder, point3X):
    builder.PrependFloat32Slot(9, point3X, 0.0)

def AddPoint3X(builder, point3X):
    Request_Set_User_Frame_3PointsAddPoint3X(builder, point3X)

def Request_Set_User_Frame_3PointsAddPoint3Y(builder, point3Y):
    builder.PrependFloat32Slot(10, point3Y, 0.0)

def AddPoint3Y(builder, point3Y):
    Request_Set_User_Frame_3PointsAddPoint3Y(builder, point3Y)

def Request_Set_User_Frame_3PointsAddPoint3Z(builder, point3Z):
    builder.PrependFloat32Slot(11, point3Z, 0.0)

def AddPoint3Z(builder, point3Z):
    Request_Set_User_Frame_3PointsAddPoint3Z(builder, point3Z)

def Request_Set_User_Frame_3PointsEnd(builder):
    return builder.EndObject()

def End(builder):
    return Request_Set_User_Frame_3PointsEnd(builder)
