# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Request_Set_User_Frame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Set_User_Frame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Set_User_Frame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Set_User_Frame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Set_User_Frame
    def UserFrameNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Request_Set_User_FrameStart(builder):
    builder.StartObject(1)

def Start(builder):
    Request_Set_User_FrameStart(builder)

def Request_Set_User_FrameAddUserFrameNum(builder, userFrameNum):
    builder.PrependInt32Slot(0, userFrameNum, 0)

def AddUserFrameNum(builder, userFrameNum):
    Request_Set_User_FrameAddUserFrameNum(builder, userFrameNum)

def Request_Set_User_FrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return Request_Set_User_FrameEnd(builder)
