# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Request_Set_Free_Drive(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Set_Free_Drive()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Set_Free_Drive(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Set_Free_Drive
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Set_Free_Drive
    def Onoff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Request_Set_Free_Drive
    def Sensitivity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Request_Set_Free_DriveStart(builder):
    builder.StartObject(2)

def Start(builder):
    Request_Set_Free_DriveStart(builder)

def Request_Set_Free_DriveAddOnoff(builder, onoff):
    builder.PrependInt32Slot(0, onoff, 0)

def AddOnoff(builder, onoff):
    Request_Set_Free_DriveAddOnoff(builder, onoff)

def Request_Set_Free_DriveAddSensitivity(builder, sensitivity):
    builder.PrependFloat32Slot(1, sensitivity, 0.0)

def AddSensitivity(builder, sensitivity):
    Request_Set_Free_DriveAddSensitivity(builder, sensitivity)

def Request_Set_Free_DriveEnd(builder):
    return builder.EndObject()

def End(builder):
    return Request_Set_Free_DriveEnd(builder)
