# automatically generated by the FlatBuffers compiler, do not modify

# namespace: IPC

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Request_Set_Master_Mode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Request_Set_Master_Mode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequest_Set_Master_Mode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Request_Set_Master_Mode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Request_Set_Master_Mode
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Request_Set_Master_ModeStart(builder):
    builder.StartObject(1)

def Start(builder):
    Request_Set_Master_ModeStart(builder)

def Request_Set_Master_ModeAddMode(builder, mode):
    builder.PrependInt32Slot(0, mode, 0)

def AddMode(builder, mode):
    Request_Set_Master_ModeAddMode(builder, mode)

def Request_Set_Master_ModeEnd(builder):
    return builder.EndObject()

def End(builder):
    return Request_Set_Master_ModeEnd(builder)
