
from typing import(
    Any,
    Protocol,
    runtime_checkable,
)

from app.features.network.domain.network import NetworkModel

@runtime_checkable
class NetworkPort(Protocol):
    """
    [Network 포트]
    """
    async def get_network(self) -> dict: ...
    async def get_ethernet(self) -> dict: ...
    async def get_wifi(self) -> dict: ...
    async def get_bluetooth(self) -> dict: ...
    async def set_network(self, model: NetworkModel) -> dict: ...
    async def connect_wifi(self, model: NetworkModel) -> dict: ...
    async def scan_wifi(self) -> dict: ...
    async def get_wifi_list(self) -> dict: ...
