#ifndef MESSAGE_H
#define MESSAGE_H
enum MESSAGE_LEVEL{
    MSG_LEVEL_INFO = 0,
    MSG_LEVEL_WARN,
    MSG_LEVEL_ERRR,
};

enum MESSAGE_LIST_0000_GENERAL{
    MSG_OK = 0,
    MSG_FAIL,
    MSG_DESIRED_INDEX_IS_OVER_BOUND,
    MSG_DESIRED_PORT_IS_OVER_BOUND,
    MSG_DESIRED_VALUE_IS_OVER_BOUND,
    MSG_DESIRED_PORT_IS_NOT_AVAIL,
    MSG_NOT_VALID_COMMAND_FORMAT,
    MSG_SAVE_CONDITION_FAIL,
    MSG_SAVE_TO_DB_FAIL,
    MSG_COMMAND_TIME_OUT,
};

enum MESSAGE_LIST_0100_SYSTEM{
    MSG_SYSTEM_POWER_OFF = 100,
    MSG_SYSTEM_POWER_ON,
    
    MSG_SYSTEM_NOT_CONNECT_INTERFACE,
    MSG_SYSTEM_EATER_NOT_WORKING,

    MSG_SYSTEM_NOT_CONNECT_SAFETY_1,
    MSG_SYSTEM_NOT_CONNECT_SAFETY_2,
    MSG_SYSTEM_NOT_CONFIGURED_SAFETY_1,
    MSG_SYSTEM_NOT_CONFIGURED_SAFETY_2,
    
    MSG_SYSTEM_INPUT_LOW_48V,
    MSG_SYSTEM_INPUT_LOW_24V,
    MSG_SYSTEM_INPUT_LOW_19V,
    MSG_SYSTEM_INPUT_LOW_12V,
    MSG_SYSTEM_INPUT_LOW_05V,
    MSG_SYSTEM_INPUT_LOW_03V,

    MSG_SYSTEM_OUTPUT_LOW_48V,
    MSG_SYSTEM_OUTPUT_LOW_24V,
    MSG_SYSTEM_OUTPUT_LOW_19V,
    MSG_SYSTEM_OUTPUT_LOW_12V,
    MSG_SYSTEM_OUTPUT_LOW_05V,
    MSG_SYSTEM_OUTPUT_LOW_03V,

    MSG_SYSTEM_SWITCH_EMG_MAIN,
    MSG_SYSETM_SWITCH_EMG_USER,
    MSG_SYSTEM_SWITCH_PROTECTIVE,
    MSG_SYSTEM_SWITCH_CONFIG,
    MSG_SYSTEM_SWITCH_COMMUNICATION,

    MSG_SYSTEM_SCB_FET_CMD_IS_NOT_CHANGED,    
    MSG_SYSTEM_NO_CAN_MESSAGE_CHECK_CABLE,

    MSG_SYSTEM_THIS_FUNC_IS_AVAIL_WHEN_POWER_ENGAGED,
    MSG_SYSTEM_CANNOT_REF_ON_BEFORE_SERVO,
    MSG_SYSTEM_THIS_FUNC_IS_AVAIL_WHEN_REF_ON_STATE,

    MSG_SYSTEM_SELF_COLL_ARM_ARM_OCCUR,
    MSG_SYSTEM_SELF_COLL_ARM_TOOL_OCCUR,
    MSG_SYSTEM_SELF_COLL_AREA_ARM_OCCUR,
    MSG_SYSTEM_SELF_COLL_AREA_TOOL_OCCUR,
};

enum MESSAGE_LIST_0300_MOTION{
    MSG_MOVE_COMMAND_ERR = 300,
    MSG_MOVE_POINT_NUM_ERR,
    MSG_MOVE_SMALL_VEL_ERR,
    MSG_MOVE_SMALL_ACC_ERR,
    MSG_MOVE_RANGE_J_ERR,
    MSG_MOVE_RANGE_L_ERR,
    MSG_MOVE_INPUT_PARAMETER_BOUND_ERR,
    MSG_MOVE_PRE_IK_ERR,
    MSG_MOVE_PATH_IK_ERR,
    MSG_MOVE_PATH_ADDING_ERR,
    MSG_MOVE_PATH_GEN_ERR_SIZE_MATCH,
    MSG_MOVE_PATH_GEN_ERR_VEL_CHECK,
    MSG_MOVE_PATH_GEN_ERR_LAST_TIME_MATCH,
    MSG_MOVE_PATH_GEN_ERR_LAST_POINT_MATCH,
    MSG_MOVE_PATH_LINING_ERR,
    MSG_MOVE_PATH_CIRCLE_FIT_ERR,

    MSG_MOVE_RUNTIME_TERMINATE_OVER_SPD,
    MSG_MOVE_RUNTIME_TERMINATE_IK_ERR,
    MSG_MOVE_RUNTIME_TERMINATE_TRAJ_ERR,
};

enum MESSAGE_LIST_0500_TOOLFLAGE{
    MSG_TFB_NOT_DETECTED = 500,
    MSG_TFB_DISCONNECTED_DURING_RUN,
    MSG_TFB_ERR_FIRMWARE_IS_NOT_DETECTED,
    MSG_TFB_ERR_FIRMWARE_VER_IS_LOW,
};

enum MESSAGE_LIST_0600_SIDEIO{
    MSG_SIDE_NOT_DETECTED = 600,
    MSG_SIDE_ERR_FIRMWARE_IS_NOT_DETECTED,
    MSG_SIDE_ERR_FIRMWARE_VER_IS_LOW,
};

enum MESSAGE_LIST_1000_JOINTS{
    MSG_JOINT_NOT_DETECTED_0 = 1000,//
    MSG_JOINT_TYPE_NOT_MATCH_0 = 1050,//
    MSG_JOINT_ERR_COM_0 = 1100,
    MSG_JOINT_ERR_BIG_0 = 1150,//
    MSG_JOINT_ERR_INP_0 = 1200,//
    MSG_JOINT_ERR_JAM_0 = 1250,//
    MSG_JOINT_ERR_CUR_0 = 1300,//
    MSG_JOINT_ERR_OVR_0 = 1350,
    MSG_JOINT_ERR_TMP_0 = 1400,//
    MSG_JOINT_ERR_MAT_0 = 1450,//
    MSG_JOINT_ERR_ANG_LIMIT_UP_0 = 1500,//
    MSG_JOINT_ERR_ANG_LIMIT_DW_0 = 1550,//
    MSG_JOINT_ERR_IDLE_CUR_BIG_0 = 1600,
    MSG_JOINT_ERR_FIRMWARE_IS_NOT_DETECTED_0 = 1650,//
    MSG_JOINT_ERR_FIRMWARE_VER_IS_LOW_0 = 1700,//
    MSG_JOINT_ERR_SERVO_ON_FAIL_0 = 1750,//
    MSG_JOINT_ERR_DISCONNECTED_DURING_RUN = 1800,//
    MSG_JOINT_ERR_ESTI_TMP_OVR_0 = 1850,//
    MSG_JOINT_ERR_GEAR_OVER_TORQUE_0 = 1900,//
    MSG_JOINT_ERR_NO_MOVE_DURING_SERVOON_0 = 1950,//
    MSG_JOINT_ERR_NO_MOVE_DURING_SERVOON_PLUS_0 = 2000,//
    MSG_JOINT_ERR_NO_MOVE_DURING_SERVOON_MINUS_0 = 2050,//
    MSG_JOINT_ERR_DELTA_TORQUE_IS_TOO_BIG_0 = 2100,
    MSG_JOINT_ERR_CORE_PARAMETER_NOT_RECEIVED_0 = 2150,//
};

struct MessageMap {
    int code;
    std::string_view name;
};

// 모든 구간 enum 항목을 포함한 매핑 테이블
constexpr MessageMap MESSAGE_LIST_TABLE[] = {
    // 0 ~ 99 : General
    {MSG_OK, "MSG_OK"},
    {MSG_FAIL, "MSG_FAIL"},
    {MSG_DESIRED_INDEX_IS_OVER_BOUND, "MSG_DESIRED_INDEX_IS_OVER_BOUND"},
    {MSG_DESIRED_PORT_IS_OVER_BOUND, "MSG_DESIRED_PORT_IS_OVER_BOUND"},
    {MSG_DESIRED_VALUE_IS_OVER_BOUND, "MSG_DESIRED_VALUE_IS_OVER_BOUND"},
    {MSG_DESIRED_PORT_IS_NOT_AVAIL, "MSG_DESIRED_PORT_IS_NOT_AVAIL"},
    {MSG_NOT_VALID_COMMAND_FORMAT, "MSG_NOT_VALID_COMMAND_FORMAT"},
    {MSG_SAVE_CONDITION_FAIL, "MSG_SAVE_CONDITION_FAIL"},
    {MSG_SAVE_TO_DB_FAIL, "MSG_SAVE_TO_DB_FAIL"},
    {MSG_COMMAND_TIME_OUT, "MSG_COMMAND_TIME_OUT"},

    // 100 ~ 299 : System
    {MSG_SYSTEM_POWER_OFF, "MSG_SYSTEM_POWER_OFF"},
    {MSG_SYSTEM_POWER_ON, "MSG_SYSTEM_POWER_ON"},
    {MSG_SYSTEM_NOT_CONNECT_INTERFACE, "MSG_SYSTEM_NOT_CONNECT_INTERFACE"},
    {MSG_SYSTEM_EATER_NOT_WORKING, "MSG_SYSTEM_EATER_NOT_WORKING"},
    {MSG_SYSTEM_NOT_CONNECT_SAFETY_1, "MSG_SYSTEM_NOT_CONNECT_SAFETY_1"},
    {MSG_SYSTEM_NOT_CONNECT_SAFETY_2, "MSG_SYSTEM_NOT_CONNECT_SAFETY_2"},
    {MSG_SYSTEM_NOT_CONFIGURED_SAFETY_1, "MSG_SYSTEM_NOT_CONFIGURED_SAFETY_1"},
    {MSG_SYSTEM_NOT_CONFIGURED_SAFETY_2, "MSG_SYSTEM_NOT_CONFIGURED_SAFETY_2"},
    {MSG_SYSTEM_INPUT_LOW_48V, "MSG_SYSTEM_INPUT_LOW_48V"},
    {MSG_SYSTEM_INPUT_LOW_24V, "MSG_SYSTEM_INPUT_LOW_24V"},
    {MSG_SYSTEM_INPUT_LOW_19V, "MSG_SYSTEM_INPUT_LOW_19V"},
    {MSG_SYSTEM_INPUT_LOW_12V, "MSG_SYSTEM_INPUT_LOW_12V"},
    {MSG_SYSTEM_INPUT_LOW_05V, "MSG_SYSTEM_INPUT_LOW_05V"},
    {MSG_SYSTEM_INPUT_LOW_03V, "MSG_SYSTEM_INPUT_LOW_03V"},
    {MSG_SYSTEM_OUTPUT_LOW_48V, "MSG_SYSTEM_OUTPUT_LOW_48V"},
    {MSG_SYSTEM_OUTPUT_LOW_24V, "MSG_SYSTEM_OUTPUT_LOW_24V"},
    {MSG_SYSTEM_OUTPUT_LOW_19V, "MSG_SYSTEM_OUTPUT_LOW_19V"},
    {MSG_SYSTEM_OUTPUT_LOW_12V, "MSG_SYSTEM_OUTPUT_LOW_12V"},
    {MSG_SYSTEM_OUTPUT_LOW_05V, "MSG_SYSTEM_OUTPUT_LOW_05V"},
    {MSG_SYSTEM_OUTPUT_LOW_03V, "MSG_SYSTEM_OUTPUT_LOW_03V"},
    {MSG_SYSTEM_SWITCH_EMG_MAIN, "MSG_SYSTEM_SWITCH_EMG_MAIN"},
    {MSG_SYSETM_SWITCH_EMG_USER, "MSG_SYSETM_SWITCH_EMG_USER"},
    {MSG_SYSTEM_SWITCH_PROTECTIVE, "MSG_SYSTEM_SWITCH_PROTECTIVE"},
    {MSG_SYSTEM_SWITCH_CONFIG, "MSG_SYSTEM_SWITCH_CONFIG"},
    {MSG_SYSTEM_SWITCH_COMMUNICATION, "MSG_SYSTEM_SWITCH_COMMUNICATION"},
    {MSG_SYSTEM_SCB_FET_CMD_IS_NOT_CHANGED, "MSG_SYSTEM_SCB_FET_CMD_IS_NOT_CHANGED"},
    {MSG_SYSTEM_NO_CAN_MESSAGE_CHECK_CABLE, "MSG_SYSTEM_NO_CAN_MESSAGE_CHECK_CABLE"},
    {MSG_SYSTEM_THIS_FUNC_IS_AVAIL_WHEN_POWER_ENGAGED, "MSG_SYSTEM_THIS_FUNC_IS_AVAIL_WHEN_POWER_ENGAGED"},
    {MSG_SYSTEM_CANNOT_REF_ON_BEFORE_SERVO, "MSG_SYSTEM_CANNOT_REF_ON_BEFORE_SERVO"},
    {MSG_SYSTEM_THIS_FUNC_IS_AVAIL_WHEN_REF_ON_STATE, "MSG_SYSTEM_THIS_FUNC_IS_AVAIL_WHEN_REF_ON_STATE"},
    {MSG_SYSTEM_SELF_COLL_ARM_ARM_OCCUR, "MSG_SYSTEM_SELF_COLL_ARM_ARM_OCCUR"},
    {MSG_SYSTEM_SELF_COLL_ARM_TOOL_OCCUR, "MSG_SYSTEM_SELF_COLL_ARM_TOOL_OCCUR"},
    {MSG_SYSTEM_SELF_COLL_AREA_ARM_OCCUR, "MSG_SYSTEM_SELF_COLL_AREA_ARM_OCCUR"},
    {MSG_SYSTEM_SELF_COLL_AREA_TOOL_OCCUR, "MSG_SYSTEM_SELF_COLL_AREA_TOOL_OCCUR"},

    // 300 ~ 499 : Motion
    {MSG_MOVE_COMMAND_ERR, "MSG_MOVE_COMMAND_ERR"},
    {MSG_MOVE_POINT_NUM_ERR, "MSG_MOVE_POINT_NUM_ERR"},
    {MSG_MOVE_SMALL_VEL_ERR, "MSG_MOVE_SMALL_VEL_ERR"},
    {MSG_MOVE_SMALL_ACC_ERR, "MSG_MOVE_SMALL_ACC_ERR"},
    {MSG_MOVE_RANGE_J_ERR, "MSG_MOVE_RANGE_J_ERR"},
    {MSG_MOVE_RANGE_L_ERR, "MSG_MOVE_RANGE_L_ERR"},
    {MSG_MOVE_INPUT_PARAMETER_BOUND_ERR, "MSG_MOVE_INPUT_PARAMETER_BOUND_ERR"},
    {MSG_MOVE_PRE_IK_ERR, "MSG_MOVE_PRE_IK_ERR"},
    {MSG_MOVE_PATH_IK_ERR, "MSG_MOVE_PATH_IK_ERR"},
    {MSG_MOVE_PATH_ADDING_ERR, "MSG_MOVE_PATH_ADDING_ERR"},
    {MSG_MOVE_PATH_GEN_ERR_SIZE_MATCH, "MSG_MOVE_PATH_GEN_ERR_SIZE_MATCH"},
    {MSG_MOVE_PATH_GEN_ERR_VEL_CHECK, "MSG_MOVE_PATH_GEN_ERR_VEL_CHECK"},
    {MSG_MOVE_PATH_GEN_ERR_LAST_TIME_MATCH, "MSG_MOVE_PATH_GEN_ERR_LAST_TIME_MATCH"},
    {MSG_MOVE_PATH_GEN_ERR_LAST_POINT_MATCH, "MSG_MOVE_PATH_GEN_ERR_LAST_POINT_MATCH"},
    {MSG_MOVE_PATH_LINING_ERR, "MSG_MOVE_PATH_LINING_ERR"},
    {MSG_MOVE_PATH_CIRCLE_FIT_ERR, "MSG_MOVE_PATH_CIRCLE_FIT_ERR"},
    {MSG_MOVE_RUNTIME_TERMINATE_OVER_SPD, "MSG_MOVE_RUNTIME_TERMINATE_OVER_SPD"},
    {MSG_MOVE_RUNTIME_TERMINATE_IK_ERR, "MSG_MOVE_RUNTIME_TERMINATE_IK_ERR"},
    {MSG_MOVE_RUNTIME_TERMINATE_TRAJ_ERR, "MSG_MOVE_RUNTIME_TERMINATE_TRAJ_ERR"},

    // 500 ~ 599 : ToolFlange
    {MSG_TFB_NOT_DETECTED, "MSG_TFB_NOT_DETECTED"},
    {MSG_TFB_DISCONNECTED_DURING_RUN, "MSG_TFB_DISCONNECTED_DURING_RUN"},
    {MSG_TFB_ERR_FIRMWARE_IS_NOT_DETECTED, "MSG_TFB_ERR_FIRMWARE_IS_NOT_DETECTED"},
    {MSG_TFB_ERR_FIRMWARE_VER_IS_LOW, "MSG_TFB_ERR_FIRMWARE_VER_IS_LOW"},

    // 600 ~ 699 : SideIO
    {MSG_SIDE_NOT_DETECTED, "MSG_SIDE_NOT_DETECTED"},
    {MSG_SIDE_ERR_FIRMWARE_IS_NOT_DETECTED, "MSG_SIDE_ERR_FIRMWARE_IS_NOT_DETECTED"},
    {MSG_SIDE_ERR_FIRMWARE_VER_IS_LOW, "MSG_SIDE_ERR_FIRMWARE_VER_IS_LOW"},

    // 1000 ~ 2100 : Joints
    {MSG_JOINT_NOT_DETECTED_0, "MSG_JOINT_NOT_DETECTED_0"},
    {MSG_JOINT_TYPE_NOT_MATCH_0, "MSG_JOINT_TYPE_NOT_MATCH_0"},
    {MSG_JOINT_ERR_COM_0, "MSG_JOINT_ERR_COM_0"},
    {MSG_JOINT_ERR_BIG_0, "MSG_JOINT_ERR_BIG_0"},
    {MSG_JOINT_ERR_INP_0, "MSG_JOINT_ERR_INP_0"},
    {MSG_JOINT_ERR_JAM_0, "MSG_JOINT_ERR_JAM_0"},
    {MSG_JOINT_ERR_CUR_0, "MSG_JOINT_ERR_CUR_0"},
    {MSG_JOINT_ERR_OVR_0, "MSG_JOINT_ERR_OVR_0"},
    {MSG_JOINT_ERR_TMP_0, "MSG_JOINT_ERR_TMP_0"},
    {MSG_JOINT_ERR_MAT_0, "MSG_JOINT_ERR_MAT_0"},
    {MSG_JOINT_ERR_ANG_LIMIT_UP_0, "MSG_JOINT_ERR_ANG_LIMIT_UP_0"},
    {MSG_JOINT_ERR_ANG_LIMIT_DW_0, "MSG_JOINT_ERR_ANG_LIMIT_DW_0"},
    {MSG_JOINT_ERR_IDLE_CUR_BIG_0, "MSG_JOINT_ERR_IDLE_CUR_BIG_0"},
    {MSG_JOINT_ERR_FIRMWARE_IS_NOT_DETECTED_0, "MSG_JOINT_ERR_FIRMWARE_IS_NOT_DETECTED_0"},
    {MSG_JOINT_ERR_FIRMWARE_VER_IS_LOW_0, "MSG_JOINT_ERR_FIRMWARE_VER_IS_LOW_0"},
    {MSG_JOINT_ERR_SERVO_ON_FAIL_0, "MSG_JOINT_ERR_SERVO_ON_FAIL_0"},
    {MSG_JOINT_ERR_DISCONNECTED_DURING_RUN, "MSG_JOINT_ERR_DISCONNECTED_DURING_RUN"},
    {MSG_JOINT_ERR_ESTI_TMP_OVR_0, "MSG_JOINT_ERR_ESTI_TMP_OVR_0"},
    {MSG_JOINT_ERR_GEAR_OVER_TORQUE_0, "MSG_JOINT_ERR_GEAR_OVER_TORQUE_0"},
    {MSG_JOINT_ERR_NO_MOVE_DURING_SERVOON_0, "MSG_JOINT_ERR_NO_MOVE_DURING_SERVOON_0"},
    {MSG_JOINT_ERR_NO_MOVE_DURING_SERVOON_PLUS_0, "MSG_JOINT_ERR_NO_MOVE_DURING_SERVOON_PLUS_0"},
    {MSG_JOINT_ERR_NO_MOVE_DURING_SERVOON_MINUS_0, "MSG_JOINT_ERR_NO_MOVE_DURING_SERVOON_MINUS_0"},
    {MSG_JOINT_ERR_DELTA_TORQUE_IS_TOO_BIG_0, "MSG_JOINT_ERR_DELTA_TORQUE_IS_TOO_BIG_0"},
    {MSG_JOINT_ERR_CORE_PARAMETER_NOT_RECEIVED_0, "MSG_JOINT_ERR_CORE_PARAMETER_NOT_RECEIVED_0"}
};

#endif // MESSAGE_H
