from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from rb_flat_buffers.deploy.Response_Deploy_Upload import Response_Deploy_Upload

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class Response_Deploy_Upload(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> Response_Deploy_Upload: ...
  @classmethod
  def GetRootAsResponse_Deploy_Upload(cls, buf: bytes, offset: int) -> Response_Deploy_Upload: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Tag(self) -> str | None: ...
  def FileName(self) -> str | None: ...
  def Sha256(self) -> str | None: ...
  def Path(self) -> str | None: ...
class Response_Deploy_UploadT(object):
  tag: str | None
  fileName: str | None
  sha256: str | None
  path: str | None
  @classmethod
  def InitFromBuf(cls, buf: bytes, pos: int) -> Response_Deploy_UploadT: ...
  @classmethod
  def InitFromPackedBuf(cls, buf: bytes, pos: int = 0) -> Response_Deploy_UploadT: ...
  @classmethod
  def InitFromObj(cls, responseDeployUpload: Response_Deploy_Upload) -> Response_Deploy_UploadT: ...
  def _UnPack(self, responseDeployUpload: Response_Deploy_Upload) -> None: ...
  def Pack(self, builder: flatbuffers.Builder) -> None: ...
def Response_Deploy_UploadStart(builder: flatbuffers.Builder) -> None: ...
def Start(builder: flatbuffers.Builder) -> None: ...
def Response_Deploy_UploadAddTag(builder: flatbuffers.Builder, tag: uoffset) -> None: ...
def Response_Deploy_UploadAddFileName(builder: flatbuffers.Builder, fileName: uoffset) -> None: ...
def Response_Deploy_UploadAddSha256(builder: flatbuffers.Builder, sha256: uoffset) -> None: ...
def Response_Deploy_UploadAddPath(builder: flatbuffers.Builder, path: uoffset) -> None: ...
def Response_Deploy_UploadEnd(builder: flatbuffers.Builder) -> uoffset: ...
def End(builder: flatbuffers.Builder) -> uoffset: ...

