# AUTO-GENERATED by scripts/fbs_to_pydantic.py. DO NOT EDIT.
from __future__ import annotations

from enum import Enum
from pydantic import BaseModel, ConfigDict, Field

NAMESPACE = "IPC"

# union FilePayloadPD: FileMetaPD, FileChunkPD, FileAckPD, FileRequestPD
FilePayloadPD = dict

class FileMetaPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    session: str | None = Field(default=None)
    name: str | None = Field(default=None)
    size: int | None = Field(default=None)
    mime: str | None = Field(default=None)
    chunk_size: int | None = Field(alias="chunkSize", default=None)
    total_chunks: int | None = Field(alias="totalChunks", default=None)
    sha256: list[int] = Field(default_factory=list)

class FileChunkPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    session: str | None = Field(default=None)
    index: int | None = Field(default=None)
    offset: int | None = Field(default=None)
    data: list[int] = Field(default_factory=list)

class FileAckPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    session: str | None = Field(default=None)
    index: int | None = Field(default=None)
    ok: bool | None = Field(default=None)

class FileRequestPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    session: str | None = Field(default=None)
    want_index: int | None = Field(alias="wantIndex", default=None)

class FileMessagePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    payload: FilePayloadPD | None = Field(default=None)

__all__ = [
    "FilePayloadPD",
    "FileMetaPD",
    "FileChunkPD",
    "FileAckPD",
    "FileRequestPD",
    "FileMessagePD",
]
