# AUTO-GENERATED by scripts/backend/fbs_to_pydantic.py. Derek said 'DO NOT EDIT. ㅡㅡ#'
from __future__ import annotations

from enum import Enum
from typing import List
from pydantic import BaseModel, ConfigDict, Field

from .flow_manager_models import *  # noqa: F401,F403

NAMESPACE = "program"

class RB_Program_Sub_Task_TypePD(Enum):
    SUB_TASK_INSERT = 'SUB_TASK_INSERT'
    SUB_TASK_CHANGE = 'SUB_TASK_CHANGE'

class RB_Program_Log_TypePD(Enum):
    INFO = 'INFO'
    WARNING = 'WARNING'
    ERROR = 'ERROR'
    USER = 'USER'
    DEBUG = 'DEBUG'
    GENERAL = 'GENERAL'

class RB_Program_Task_StatusPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    task_id: str | None = Field(alias="taskId", default=None)
    program_id: str | None = Field(alias="programId", default=None)
    sync_task_ids: List[str] = Field(alias="syncTaskIds", default_factory=list)
    node_path: List[str] = Field(alias="nodePath", default_factory=list)
    status: str | None = Field(default=None)
    offset: int | None = Field(default=None)

class RB_Program_Task_CheckpointPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    task_id: str | None = Field(alias="taskId", default=None)
    program_id: str | None = Field(alias="programId", default=None)
    sync_task_ids: List[str] = Field(alias="syncTaskIds", default_factory=list)
    node_path: List[str] = Field(alias="nodePath", default_factory=list)
    offset: int | None = Field(default=None)
    status: str | None = Field(default=None)

class RB_Program_DialogPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    robot_model: str | None = Field(alias="robotModel", default=None)
    title: str | None = Field(default=None)
    content: str | None = Field(default=None)

class RB_Program_LogPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    content: str | None = Field(default=None)
    robot_model: str | None = Field(alias="robotModel", default=None)
    type: RB_Program_Log_TypePD | None = Field(default=None)

class Request_Program_At_StartPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    task_id: str | None = Field(alias="taskId", default=None)

class Request_Program_At_EndPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    task_id: str | None = Field(alias="taskId", default=None)

class Request_Update_Sub_Task_StatePD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    sub_task_id: str | None = Field(alias="subTaskId", default=None)
    sub_task_type: RB_Program_Sub_Task_TypePD | None = Field(alias="subTaskType", default=None)
    state: RB_Flow_Manager_ProgramStatePD | None = Field(default=None)

class Request_Exec_Control_ProgramPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    robot_model: str | None = Field(alias="robotModel", default=None)
    program_id: str | None = Field(alias="programId", default=None)

class Response_Exec_Control_ProgramPD(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    manipulate_return_value: int | None = Field(alias="manipulateReturnValue", default=None)

__all__ = [
    "RB_Program_Sub_Task_TypePD",
    "RB_Program_Log_TypePD",
    "RB_Program_Task_StatusPD",
    "RB_Program_Task_CheckpointPD",
    "RB_Program_DialogPD",
    "RB_Program_LogPD",
    "Request_Program_At_StartPD",
    "Request_Program_At_EndPD",
    "Request_Update_Sub_Task_StatePD",
    "Request_Exec_Control_ProgramPD",
    "Response_Exec_Control_ProgramPD",
]
