# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RequestMoveCircular(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestMoveCircular()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequestMoveCircular(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RequestMoveCircular
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestMoveCircular
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RequestMoveCircular
    def Target(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RequestMoveCircular
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RequestMoveCircular
    def Direction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RequestMoveCircularStart(builder):
    builder.StartObject(4)

def Start(builder):
    RequestMoveCircularStart(builder)

def RequestMoveCircularAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    RequestMoveCircularAddId(builder, id)

def RequestMoveCircularAddTarget(builder, target):
    builder.PrependFloat32Slot(1, target, 0.0)

def AddTarget(builder, target):
    RequestMoveCircularAddTarget(builder, target)

def RequestMoveCircularAddSpeed(builder, speed):
    builder.PrependFloat32Slot(2, speed, 0.0)

def AddSpeed(builder, speed):
    RequestMoveCircularAddSpeed(builder, speed)

def RequestMoveCircularAddDirection(builder, direction):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(direction), 0)

def AddDirection(builder, direction):
    RequestMoveCircularAddDirection(builder, direction)

def RequestMoveCircularEnd(builder):
    return builder.EndObject()

def End(builder):
    return RequestMoveCircularEnd(builder)
