# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RequestMoveXLinear(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestMoveXLinear()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequestMoveXLinear(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RequestMoveXLinear
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestMoveXLinear
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RequestMoveXLinear
    def Target(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RequestMoveXLinear
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def RequestMoveXLinearStart(builder):
    builder.StartObject(3)

def Start(builder):
    RequestMoveXLinearStart(builder)

def RequestMoveXLinearAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    RequestMoveXLinearAddId(builder, id)

def RequestMoveXLinearAddTarget(builder, target):
    builder.PrependFloat32Slot(1, target, 0.0)

def AddTarget(builder, target):
    RequestMoveXLinearAddTarget(builder, target)

def RequestMoveXLinearAddSpeed(builder, speed):
    builder.PrependFloat32Slot(2, speed, 0.0)

def AddSpeed(builder, speed):
    RequestMoveXLinearAddSpeed(builder, speed)

def RequestMoveXLinearEnd(builder):
    return builder.EndObject()

def End(builder):
    return RequestMoveXLinearEnd(builder)
