# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SLAMNAV

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ResponseMoveGoal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ResponseMoveGoal()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponseMoveGoal(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ResponseMoveGoal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ResponseMoveGoal
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ResponseMoveGoal
    def GoalId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ResponseMoveGoal
    def GoalName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ResponseMoveGoal
    def Method(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ResponseMoveGoal
    def Preset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ResponseMoveGoal
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ResponseMoveGoal
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ResponseMoveGoalStart(builder):
    builder.StartObject(7)

def Start(builder):
    ResponseMoveGoalStart(builder)

def ResponseMoveGoalAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    ResponseMoveGoalAddId(builder, id)

def ResponseMoveGoalAddGoalId(builder, goalId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(goalId), 0)

def AddGoalId(builder, goalId):
    ResponseMoveGoalAddGoalId(builder, goalId)

def ResponseMoveGoalAddGoalName(builder, goalName):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(goalName), 0)

def AddGoalName(builder, goalName):
    ResponseMoveGoalAddGoalName(builder, goalName)

def ResponseMoveGoalAddMethod(builder, method):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(method), 0)

def AddMethod(builder, method):
    ResponseMoveGoalAddMethod(builder, method)

def ResponseMoveGoalAddPreset(builder, preset):
    builder.PrependInt32Slot(4, preset, 0)

def AddPreset(builder, preset):
    ResponseMoveGoalAddPreset(builder, preset)

def ResponseMoveGoalAddResult(builder, result):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder, result):
    ResponseMoveGoalAddResult(builder, result)

def ResponseMoveGoalAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    ResponseMoveGoalAddMessage(builder, message)

def ResponseMoveGoalEnd(builder):
    return builder.EndObject()

def End(builder):
    return ResponseMoveGoalEnd(builder)
